### ISSUE TITLE
add historical validation ability to SmvDataset

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1000]
Need to be able to perform validation based on historical data and not just the current run (as in DQM).  See design doc: https://github.com/TresAmigosSD/SMV/blob/master/docs/dev/Validator/validator.md

**Comment by laneb** [comment]
I think the pattern of throwing an error to indicate a validation error and a meaningless return value is confusing. For both internal and client code readability's sake, I suggest the return value be a string describing the validation failure, and `None` in case of success. On the Scala side, this can be an Option[String] or a similar structure. This will also simplify extracting the error message for logging in the `DQMState`.

**Comment by laneb** [comment]
Is there any need to publish historical metadata?

**Comment by AliTajeldin** [comment]
Good question.  We currently distinguish the historical meta data from the current metadata due to use or lack of use of hash in name of generated file.  Since published data will not have the hash, I don't think we can have both current and historical meta in the published directory.
An alternative is to name the historical meta file with a "hist" extension to distinguish it from the current published metadata.
But back to the original question, I think we should publish the historical meta data.  The user will be able to preserve arbitrary data which they may need when they resolve a published module.

**Comment by AliTajeldin** [comment]
@laneb one feedback I got from the client is that they would prefer to have the metadata file reside in a different directory than the output directory.  This is because they routinely wipe out the output directory to force a re-run.  That would cause the meta files to be wiped out as well.  It might be best to store the metadata under the `dataDir/meta` or something like that.

**Comment by laneb** [comment]
Will do.

**Comment by laneb** [comment]
Not really within the scope of this ticket, but maybe we should make the output directory configuration more granular, e.g. letting the user identify the meta history dir.

**Comment by laneb** [comment]
We minify the metadata JSON and save it as a single row RDD. Should the metadata history be 'exported' to a single file? Does it need to be human-readable?

**Comment by laneb** [comment]
The core of this feature is implemented. Need to discuss a couple things regarding method names and publishing data to finish up.

**Comment by laneb** [comment]
@AliTajeldin Your example validation function was 
```
  def validate(self, cur_metadata, hist_metadata):
    # if we don't have history, nothing to compare
    if len(hist_metadata) == 0: return

    # compute average historical id count.
    avg_id_count = sum(hist_metadata.id_count) / len(hist_metadata)

    # if current id count is > %10 different than historical, fail validation.
    if abs(avg_id_count - cur_metadata.id_count)/avg_id_count > 0.1:
      raise "Large Difference in id_count.  avg = ?, cur = ?"
```

If we require the user to return the error message instead of throwing an error, it would look like:
```
  def validate(self, cur_metadata, hist_metadata):
    # compute average historical id count.
    if(hist_metadata == 0):
      return

    # compute average historical id count.      
    avg_id_count = sum(hist_metadata.id_count) / len(hist_metadata)

    # if current id count is > %10 different than historical, fail validation.
    if abs(avg_id_count - cur_metadata.id_count)/avg_id_count > 0.1:
       return "Large Difference in id_count.  avg = ?, cur = ?"
```

where `None` indicates success. It may be slightly confusing for users to return `None`, but putting an empty return statement as in your example would have the same effect. Alternatively, the user could simply omit a return statement.

**Comment by laneb** [comment]
Another disadvantage of raising an error to indicate validation failure is that it will be nontrivial to discern between validation failures and runtime errors in validation (e.g. a `KeyError` on the metadata object).

**Comment by AliTajeldin** [comment]
@laneb : makes sense.  Let's go with the return None option then.
