### ISSUE TITLE
Make module reusable in SMV

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#1007]
In some cases, user wants to reuse some transformation logics and apply to different inputs.

In Pingan, they will do missing imputation, cap floor, woe transformation to both training data and test data but current smv implementation is to copy and paste code, which is not concise.

Could we design a reusable module and for users, they just need to pass different inputs.

**Comment by ninjapapa** [comment]
For SMV, user could use Abstract Class to abstract out the common part, and let concrete class (the real modules) to derive from the ABC with override. 

It is not an issue for SMV. Could open in the other project.
