### ISSUE TITLE
smv should handle non-numeric spark versions

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1009]
When SMV is used with a spark version that is not completely numeric (such as hour hotdeploy version or the version on cloudera), it shows an error.  The error is ignored but we should be more graceful in handing such a case.
```
/Users/alitajeldin/Projects/SMV/tools/_env.sh: line 109: [: 152+hotdeploy: integer expression expected
```

**Comment by Kai-Chen** [comment]
A typical version comparison would place things like `1.5.2rc1` and `1.5.2+hotdeploy` before `1.5.2`.
But we actually want the '+hotdeploy' to be an acceptable version.
Will implement a version check function that would do that in this particular case.

Now I really regret having chosen that naming scheme.

**Comment by AliTajeldin** [comment]
@Kai-Chen no worries, the Cloudera cluster also had a version number with a trailing string 😄
