### ISSUE TITLE
extract "spark-submit" and "pyspark" to _env.sh

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1014]
Customer was using `spark2-submit` and `pyspark2` for version 2.2 of spark on cloudera.  We had to modify multiple scripts to use the new names.  Should extract these to a single place and even perhaps allow a config to be used to supply the executable names (so it only has to be configured once)

Affected files: `smv-pyshell`, `_env.sh`, `_pyenv.sh`

**Comment by laneb** [comment]
@AliTajeldin can we assign this to @kmannislands?
