### ISSUE TITLE
Do not set SPARK_HOME in smv scripts

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1015]
Setting `SPARK_HOME` env variable fails on Cloudera cluster.   Assign the `--spark-home` argument to an internal var.

**Comment by jacobdr** [comment]
Any chance you can expand on this? I use this pattern quite a bit and have
never had a problem on HDP

**Comment by AliTajeldin** [comment]
Cloudera doesn't work if `SPARK_HOME` is set to `/usr` which is what we set it to when we try to discover the path of `spark-submit`.

**Comment by laneb** [comment]
Makes sense. We want to know where `spark-submit` is located, not where Spark installed. Can you verify that `pyspark` is also located in `/usr/bin`?

**Comment by laneb** [comment]
@AliTajeldin can we assign this to @kmannislands?
