### ISSUE TITLE
Enable functionality to retrieve a dataset's schema in json format from the python side

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [TresAmigosSD/SMV#1016]
Currently, it is possible to retrieve/discover the schema by generating a schema file. The python interface should be able to get the schema of a dataset without having to create the file. Namely, there should be a function that when called, returns a json string representing the schema of a given dataset.

**Comment by AntonioRecaldeRusso** [comment]
The original plan was to return a json string from an entrypoint in smvapp. However, after some discussion with @laneb, it was decided that since there is no particular use inside `smv` for a schema in `json` format, it is more appropriate to only return the schema string from the `smvapp` `discoverSchemaReturnString` entrypoint

**Comment by AliTajeldin** [comment]
@AntonioRecaldeRusso So is the return the same format as what would be expected from `userSchema` method?

**Comment by AntonioRecaldeRusso** [comment]
@AliTajeldin Yes.

**Comment by AntonioRecaldeRusso** [comment]
@AliTajeldin this can be closed

**Comment by ninjapapa** [comment]
BTW: for a df, you can do
```
df.schema.jsonValue()
```
http://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=structtype#pyspark.sql.types.StructType.jsonValue
