### ISSUE TITLE
Throw clearer exception when link to non-SmvOutput module

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1018]
When trying to run an client application containing an `SmvModuleLink` to a module that is not `SmvOutput`, an error is thrown reporting 

```
java.lang.ClassCastException: org.tresamigos.smv.SmvExtModulePython cannot be cast to org.tresamigos.smv.SmvOutput
```

which doesn't clearly express the problem. We should detect this and throw a clearer exception. Note that this only arises for Python modules as a link to a non-output module will not compile in Scala.

**Comment by ninjapapa** [comment]
Not an issue any more.
