### ISSUE TITLE
Add smvapp entrypoint to get the defined schema for a module's csv file

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [TresAmigosSD/SMV#1019]
It should be possible for a user to get the schema of a module's input csv file as defined in its corresponding `.schema` file

**Comment by AliTajeldin** [comment]
As discussed, we should returned the defined schema which **may** be in a `.schema` file or it can also have been specified by the user as `userSchema` method.

**Comment by AntonioRecaldeRusso** [comment]
No need to add an entrypoint as that information is already available through the `schema` method in `SmvDataset.scala`, which can be obtained by calling `getRawScalaInputDS()` on a python SmvCsvInput module.
