### ISSUE TITLE
Bring 1.6 branch up to date with master

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1027]
The 1.6 branch has fallen far behind the master (1.5) branch and the 2.X branches. It would be helpful to a client project for this branch to be brought up to date and for a 1.6.2.2 release to be cut. This is not an urgent requirement; however, we should estimate how much effort this will entail.

**Comment by laneb** [comment]
Merging master into 1.6 thankfully turned out to be pretty trivial and 1.6 has been updated. However, need to verify a few things

1. The docker build works
2. References to 1.5.2 are updated to 1.6.2 where appropriate
3. smv-release and smv-install work
4. Python version independence (Python 3 support was added after the 1.6.2.1 release)

**Comment by laneb** [comment]
Confirmed everything except that `smv-release` works. @AliTajeldin objections if I cut a new 1.6 release tomorrow?

**Comment by AliTajeldin** [comment]
@laneb no objections but we need to fix `smv-release` before hand (it is required to do the release)
