### ISSUE TITLE
count overflow in reported rows after DF is persisted

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1037]
When a dataset is "run", SMV will display an approximate number of records persisted (which could be higher than actual records due to restarts).  However, this number seems to be limited to a 32bit counter as it overflows over 2B records and the reported number of records overflows to a much smaller number.  This could be quite confusing.

**Comment by Kai-Chen** [comment]
In the `SmvDataSet.persist()` function we are indeed using a `Accumulator[Long]` (`LongAccumulator` in spark 2).
But we are updating that accumulator in a dummy predicate function which is passed to `df.where()` -- in other words, not in an action (which would be equivalent to `df.count`.

One possible cause that the accumulator may not be updated correctly is that Spark may launch a speculative copy of a slow running task, which would increment the accumulator more than once.

Another trigger for multiple update is when Executors are lost, and Spark has to relaunch the task.
Similarly, if the RDD is too large to fit in memory, it will trigger re-updates.

All of the above scenario will cause the accumulator to over-count.

@ninjapapa Perhaps we can switch to `df.count` when the data set is very large?
Would that operation be quick or very slow?

**Comment by jacobdr** [comment]
Can we just use the countApproximate from the API?

**Comment by AliTajeldin** [comment]
This issue here is not the multiple updates.  We are ok with that.  It is the overflow issue which seems to overflow over 2B records.
We need to avoid doing any post processing count/countApproximate as that would add to the running times.  The user of the accumulator solution is to eliminate the extra run and just use a running count from the current run.

**Comment by jacobdr** [comment]
Makes sense.... Though if the failed or slow tasks do add to the count, then I would say the count is approximate and we might want to document it as such. 

On a side note, if we swapped out ORC or Parquet for CSV as an output type, the count would be a very quick operation (metadata based) and would be guaranteed to be accurate.

**Comment by laneb** [comment]
This issue will be moot once the current DQM implementation is phased out. @AliTajeldin Do we need to fix this in the near term?

**Comment by AliTajeldin** [comment]
I don't think so.  Not worth the effort.
