### ISSUE TITLE
Provide API to write to HDFS

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#1039]
Need to be usable by Python, so may involve conversion from Python stream to Java stream.

**Comment by jacobdr** [comment]
It would be great if this makes it easier to start writing ORC and Parquet

Jacob

**Comment by AliTajeldin** [comment]
ORC/Parquet are outside the scope of this ticket.

**Comment by jacobdr** [comment]
We’ll talk about this offline, but given how standard those formats are, I wanted to put flexibility on the mind of the ticket implementor. But I guess out of scope for this (vaguely written) ticket...

Jacob

**Comment by Kai-Chen** [comment]
@kmannislands After the PR is merged, see `testHdfsConn.py` for example of use.

The entry point from Python is `SmvApp.copyToHdfs`.

The only expectation is that the file object from the upload is opened in binary read mode.
Let me know if this is not the case, and we will work on that.

Cheers!

**Comment by Kai-Chen** [comment]
@jacobdr ... since my `mind` is mentioned :)

A stream of bytes is probably as flexible as you can get with any api, so you can certainly upload an ORC or a Parquet file.

But conversion is a different matter -- not the kind of matter that I'd mind, though :)

-- Sorry about the bad puns ... gotta get that out of my system ... it's holidays.
