### ISSUE TITLE
need to add version override to SmvFile

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#104]
We need to add a version override value to the SmvFile constructor so that when the data of a SmvFile changes, the version would be incremented.

**Comment by ninjapapa** [comment]
Should rather derive the SmvFile hash from file's attributes, e.g. Name, Create Time.

**Comment by ninjapapa** [comment]
with bb7909dce9d2bd0be6fbb8ef4eb420e2746d5ab3, either file name change or file modification time change will cause SmvFile CRC change so the downstream SmvModule will be re-calculated. No need to  implement version in SmvFile constructor.
