### ISSUE TITLE
smvDedupByKeyWithOrder performance is lower than using window function

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1045]
Current smvDedupByKeyWithOrder using rdd level operations. On a client dataset, using window function is much faster than our implementation. Should at least make the default behavior of smvDedupByKeyWithOrder using the window function as in 
https://stackoverflow.com/questions/33878370/how-to-select-the-first-row-of-each-group

The order structure approach is also interesting, although it only work for selected columns.

**Comment by ninjapapa** [comment]
Performance compare on the same client data with 112M records, relatively even distribution along 4 key columns and 1 order column:
* Current smvDedupByKeyWithOrder: >8 min
* Using rank over window: 41 sec

**Comment by AliTajeldin** [comment]
WOW!!!

**Comment by ninjapapa** [comment]
Implement this need to use `row_number` function, which was named `rowNumber` in 1.5.* and `row_number` in 1.6+.Since the last client using 1.5.* will upgrade to 1.6.* soon, we will implement this after dropping 1.5.* support.

**Comment by ninjapapa** [comment]
done.
