### ISSUE TITLE
Implement r_sum

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#105]
Client code:
```scala
val res = srdd.r_sum('k)('t, 'amt, ('r_t <= 't && 'r_t > 't - 3))
```

Possible implementation:
```scala
val with_rw = srdd.orderBy('k.asc, 't.asc).chunkByPlus('k)(r_Window('amt, 't, ('r_t <= 't && 'r_t > 't - 3)))
```
will add a column `'run_amt` as an array of `'amt` and one can do
```scala
val res = with_rw.selectPlus(ScalaUDF(s:Seq[Double]->s.sum, DoubleType, Seq('run_amt)))
```

**Comment by ninjapapa** [comment]
It could be simpler and more generic as
```scala
val res = srdd.chunkByPlus('k)(RunSum('t, 'amt, ('r_t <= 't && 'r_t > 't - 3)))
```

**Comment by AliTajeldin** [comment]
I like the second one much better (the chunkByPlus).  
Note: I'm still a bit confused by the join condition (r_t <= t && r_t > t -3).  What is the type of t?  that only works if t is a continuous value and not the current time value y*100 + m/q.  This might have just been a place holder syntax.  In that case, we need to come up with some helper join condition functions.
example:
```scala
val res = srdd.chunkByPlus('k)(RunSum('t, 'amt, inLastNMonths(3, 't, 't_r))
```
Some variation of the above may be the way to go even for the long term, with the rename of chunkBy :-)

**Comment by ninjapapa** [comment]
Agree. 

I tried to create temporary SRDD in each partition of the groupByKey, so that I can reuse all SchemaSQL expressions. However it sounds like I can't `makeRDD` within groupByKey. The following code will run into error
```scala
scala> val srdd=sqlContext.createSchemaRdd("k:String; v:Integer", "z,1;a,3;a,2;z,8;")
scala> srdd.map{r => (r(0), r)}.groupByKey.map{case (keys, l) => sc.makeRDD(Seq():Seq[Double])}.collect
```

Sounds like I have to work on scala collections instead of RDD for the implementation.

**Comment by ninjapapa** [comment]
How about this interface?
```scala
val res = srdd.chunkByPlus('k)(SmvChunk.runSum('amt, 'month, InLastN(3)))
```

Ideally, I should make `SmvChunk.runSum` simply as `RunSum`. Haven't figure out how to do that yet.

**Comment by AliTajeldin** [comment]
I like that better.  To make it work with just RunSum, you must make RunSum an object (not function) with an apply method.  The object should implement the base class that chunkByPlus accepts.
For example:
```scala
package smv.runagg

class RunningAggregate;

object RunSum extends RunningAggregate {
  def apply(...) {
     // the actual running sum implementation
   }
}
```
```scala
def chunkByPlus(agg: RunningAggregate) {
}
```
```scala
// user code
import smv.agg._ // this should bring in RunSum into scope
srdd.chunkByPlus(RunSum('a, 'b, ...))
```

**Comment by ninjapapa** [comment]
Latest version be62e10dd4206d6344e056c0c0f57ff76a5ec565 has
```scala
val res = srdd.orderBy('k.asc, 't.asc).chunkByPlus('k)(RunSum[Double]('v, 't, InLastN(3)))
```

The `[Double]` part is redundant information, since the schema of srdd knows that `'v` is a Double already. However RunSum doesn't know that fact. Need to figure out a way to get rid of it.

**Comment by ninjapapa** [comment]
Finally:
```scala
val srdd=sqlContext.createSchemaRdd("k:String; t:Integer; v:Double", "z,1,0.2;z,2,1.4;z,5,2.2;a,1,0.3;")
val res = srdd.orderBy('k.asc, 't.asc).chunkByPlus('k)(RunSum('v, 't, InLastN(3)))
```
