### ISSUE TITLE
Update the help() command in `smv-pyshell`

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#1051]
* [ ] Harmonize output of `help()` with the docs [here](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/run_shell.md#smv-utility-methods)
* [ ] Fix spelling mistakes (`lsDeadLead()` -> `lsDeadLeaf()`)

**Comment by laneb** [comment]
@jacobdr I think this is done. Can you confirm?

**Comment by ninjapapa** [comment]
Done.
