### ISSUE TITLE
metadata method is called twice per module

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1056]
To reproduce, use `smv-init` to create a simple app and add a `metadata` method to `EmploymentByState` that prints to standard output.  When the app is run, you will see that `metadata` method was called twice.
The `metadata` method can potentially be expensive to compute so we shouldn't be calling it multiple times.

**Comment by AliTajeldin** [comment]
The two call locations are:
* We add a `DQMMetadataPolicy` to all dataset dqm rules that eventually calls `SmvDataSet::createMetadata`.  The policy will fail if `validateMetadata` returns something other than `None`
* In addition, in `SmvDataSet::computeRDD` method, we call `SmvDataSet::createMetadata' directly to persist the history.

There are two possible solutions:
* Get rid of `DQMMetadataPolicy` all together and explicitly validate the results in `computeRDD`.  The bad part of this is we will not have a the policy result stored in the `DQMResult` then.
* make the instance of `DQMMeatadataPolicy` a member of `SmvDataSet` and stash away the result of the `metadata` call inside the policy.  `ComputeRDD` would the retrieve the metadata result from the policy rather than recompute it.
My preference is for the second option.

**Comment by AliTajeldin** [comment]
@Kai-Chen , @laneb what do you guys think?

**Comment by laneb** [comment]
Of your proposed solutions, I prefer the second as well. Alternatively, perhaps we can supply the metadata when building the SmvDQM with dqmWithTypeSpecificPolicy at the beginning of computeRDD.

**Comment by laneb** [comment]
I presume that caching the metadata in the SmvDataSet is not an option 😂

**Comment by Kai-Chen** [comment]
Johnny `Cache` would not have minded it at all :)

I'm quite behind on the design and implementation of metadata.
So the most I can offer would be the following question:

What would be the downside of having metadata, or some wrapper -- which would be DQMMetadataPolicy -- being a stateful member of `SmvDataSet`?
That's just another way of looking at option 2.

**Comment by Kai-Chen** [comment]
Inside the `SmvDataSet::publish` method, there is another call to `SmvDataSet::createMetaData`

**Comment by laneb** [comment]
Based on a previous discussion with @AliTajeldin, publish will accept the `DataFrame` to be published as an argument. `publish` should also accept the metadata.

**Comment by AliTajeldin** [comment]
I'm beginning to like the idea of just caching the metadata in the `SmvDataset` and keep all the current calls the same.  @laneb can you think of any issues with that wrt reload?  I'm assuming on reload we will get a brand new `SmvDataset` and that can recompute fine.

**Comment by laneb** [comment]
No, I don't foresee any problems.

**Comment by laneb** [comment]
The above commit looks to me like it should work. However, I think we should just access the cache directly in `runDqmAndMeta` instead of changing the behavior of `createMetadata`. We know that the metadata will be cached by then, because the metadata is always generated during DQM even if the user's metadata validation is a no-op.

**Comment by laneb** [comment]
Scratch that. We don't currently do metadata validation for `SmvDSWithParser`, because the metadata policy is added to the user's DQM in `dqmWithTypeSpecificPolicy`. That's a weird place to put this variance, and it means that `SmvHiveTable` is validating metadata every time, but none of the file types do. Not sure if that's intentional, but it rules out my suggestion above.

**Comment by laneb** [comment]
Scratch that again :see_no_evil:  We _do_ validate metadata for `SmvDSWithParser`, because it calls `super.dqmWithTypeSpecificPolicy`.

**Comment by AliTajeldin** [comment]
The amount of scratches above indicates we should just stick with the simple cache design 😄
