### ISSUE TITLE
create higher order historical dqm

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1057]
The current historical dqm interface is low level and forces users to define the `metadata` and `validateMetadata` for each module.  Client requested a higher order implementation where they can "mixi-in" a set of historical validators per module.

Proposed Interface Example:
```
@SmvHistoricalValidators(
  DistinctCountVariation(“id_count”, “id”, 0.1),
  AvgValueVariation(“amt_var”, “amount”, 0.2))
class MyModule(smv.SmvModule):
  def requiresDS(self): …
  def run(self, i): …
```

Users just add a decorator to an existing module to add historical validation checks.  In the above example, we added two validation rules.  Each rule takes a name parameter and validation specific parameters.  The first rule will check variation in distinct count of the “id” column.  The second rule checks for variation in average value of the “amount” column.  The third parameter (0.1 and 0.2) determine how much variation we allow.

It should be easy add additional validators.  It is similar to the low level metadata interface.  For example:
```
class NewValidator(smv.SmvHistoricalValidator):
  def __init__(self, name, arg1, arg2, arg3, …):
    pass
  def metadata(df):
    # compute value to track from current result df.
    val = ...
    return { name : val }
  def validateMetadata(cur_metadata, hist_metadata):
    # compare current metadata value to historical metadata values.
    return True/False
```

If the decorator interface does not work, an alternative is to mix-in a validation class:
```
class MyModule(smv.SmvModule, smv.SmvHistoricalValidators):
  def requiresDS(self): …
  def run(self, i): …
  def getValidators(self): return [
    DistinctCountVariation(“id_count”, “id”, 0.1),
    AvgValueVariation(“amt_var”, “amount”, 0.2)]
```

**Comment by AliTajeldin** [comment]
## Implementation Detail
The decorator will inject a `metadata` and `validateMetadata` methods into the module class.  These methods will in-turn call the `metadata` and `validateMetadata` of each validator in the list of validators.
Note: each validator must also additionally define a `key()` method that should return a unique key to define the **instance** of this validator based on the parameters.

**Comment by jacobdr** [comment]
Why the key instead of just overriding __hash__() to return a hash over the params + class name?

**Comment by AliTajeldin** [comment]
Because python hash is broken.  It returns different results on separate runs of app.  See implementation of `_smvHash` for details.
