### ISSUE TITLE
Publishing ephemeral modules should run related modules only once

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#1058]
### Background
Ephemeral modules, by design, do not persist their computation result dataframes.
Instead, the result is always re-computed each time it is asked for by dependent modules.
### Publishing Ephemeral Modules
As of b78598128b, we can still publish ephemeral modules in both Python and Scala.
However, upstream ephemeral modules could be run more than once due to dependency and non-persistent result, because ephemeral modules would result in dataframe actions as often as they are found on the dependency path.
### Feature Requirement
We need a way to allow ephemeral modules, especially dependent ephemeral modules, to have `sticky` results that are valid within a run.

**Comment by AliTajeldin** [comment]
not sure what "sticky" results mean but I think any persisted data for a module would have to either be published or module made non-ephemeral.  SMV shouldn't try to do anything tricky when an ephemeral module depends on another.

**Comment by jacobdr** [comment]
I would be slightly worried about the DQM and metadata results being harder
to decipher for an ephemeral upstream module that gets re-run multiple
times... I would imagine we would see many copies of nearly identical
entries.
