### ISSUE TITLE
SMV won't run if client environment has SPARK_PRINT_LAUNCH_COMMAND set

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1059]
SMV thinks the wrong version of Spark is installed when this variable is set. We are grepping the output of `spark-submit --version` for "version", which occurs first in the launch command. I think the solution is to use `env -u` to run the `spark-submit --version` command without SPARK_PRINT_LAUNCH_COMMAND set.

**Comment by laneb** [comment]
@AliTajeldin thoughts on that solution?

**Comment by Kai-Chen** [comment]
You can add another pipe `grep -v SparkSubmit` to filter out the launch command before passing to `head -1`.
Not sure if `-v` would work on Mac's grep, but should check.

**Comment by laneb** [comment]
I like that better!

**Comment by AliTajeldin** [comment]
Let's go with the "-v" option.  That is an old option from sys 5 days so should work on mac as well.
