### ISSUE TITLE
Python API docs for v2.1.1.3 and v1.6.2.2 releases are broken 

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1060]
See e.g. [1.6.2.2 docs](http://tresamigossd.github.io/SMV/pythondocs/1.6.2.2/smv.html). None of the packages have any info. It's possible that this is the case for other releases as well.

**Comment by laneb** [comment]
After regenerating the docs on the 1.6 branch, they aren't broken. It is not clear what the problem is/was. The last several 2.1 releases have been broken, but only 1.6.2.2 was broken (not 1.6.2.1).

**Comment by laneb** [comment]
The problem was that the wrong Docker image was being used when building the docs #1064. The incorrect py4j version was causing `ImportErrors`.

**Comment by laneb** [comment]
@AliTajeldin Should any of the existing documentation be fixed, or should we just wait for the next releases?

**Comment by AliTajeldin** [comment]
No worries about old docs.  Just fix future releases should be fine.

**Comment by laneb** [comment]
Will close this issue when we confirm that the next non-master release has correct docs.

**Comment by laneb** [comment]
Docs at http://tresamigossd.github.io/SMV/pythondocs/1.6.2.3/smv.html are correct.
