### ISSUE TITLE
Report DQM validation results from a module run

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#1062]
### Motivation
As SMV module developer, after a run is finished, I want to be able to examine DQM results, including DQMState snapshots, for all modules that ran.

#### `SmvApp::runModuleByName`
This is the current entry point to run a specified module by name.
```scala
def runModuleByName(modName: String,
                    forceRun: Boolean = false,
                    version: Option[String] = None): DataFrame
```
where `moduleName` can be partial or full FQN, and if `version` is specified, the published version is read from storage.
#### `SmvApp::runDS`
Internally, `runModuleByName` calls `runDS` after asking the `DataSetMgr` to infer the dataset.
`runDS` is also called by `SmvApp::runModule` which takes an `URN` instead of a `String`.
```scala
  def runDS(ds: SmvDataSet,
            forceRun: Boolean,
            version: Option[String],
            runConfig: Map[String, String] = Map.empty): DataFrame
```
#### `SmvDataSet::rdd` and `SmvDataSet::computeRDD`
`runDS` sets dynamic run config before invoking `SmvDataSET::rdd`
```scala
def rdd(forceRun: Boolean = false, genEdd: Boolean = app.genEdd)
```
which then invokes `SmvDataSet::computeRDD`
```scala
  private[smv] def computeRDD(genEdd: Boolean): DataFrame = {
    val dqmValidator  = new DQMValidator(...)
    ...
    val df = dqmValidator.attachTasks(doRun(dqmValidator))
    dqmValidator.validate(df, false, moduleValidPath()) // no action before this point
    ...
  }
```

### Anaylsis
The current API cannot support this feature without change, because all DQM-related validation and policy application is done inside `computeRDD` and, although the results are persisted along with other metadata for the dataset, it is neither returned nor collected.
In addition, the class `DqmValidationResult` contains insufficient information about the details of validation errors, in case when the user would like to access specific DQMState.

New API will be designed in the following comment section.

**Comment by Kai-Chen** [comment]
### New API Design

#### `class SmvRunInfoCollector`
Responsible for collecting and maintaining run information, including, but not limited to, `DQMValidationResult` on a per-`SmvDataSet` basis.
```scala
class SmvRunInfoCollector {
  // adds a validation result for a smv module
  def addDqmValidationResult(dsFqn: String, validation: DqmValidationResult): Unit

    // returns in the same order as the validation results are added
  def dsFqns: Seq[String]

   // throws exception if not found
  def getDqmValidationResult(dsFqn: String): DqmValidationResult
}
```

This type will be added to all methods invoked from calling `runModuleByName`, `runModule`, and `publish`.

#### Modify `DqmValidationResult` to hold `DQMState`

#### Persist `DQMState` (need to take snapshot first if not done so)

### Task List
- [ ] Add SmvRunInfoCollector
- [ ] Add DqmState in DqmValidationResult
- [ ] Persist DQMState when validation result is persisted

**Comment by AliTajeldin** [comment]
LGTM.  couple of suggestions.
* Remove requirement for `dsFqns` to return in same order as addition. 
* Add example use of above api.

**Comment by laneb** [comment]
LGTM, except I think `DQMState` should just be persisted in the validation result, not separately from it (if that's what you meant). The validation result will in turn be added to the metadata. Rought ETA?

**Comment by AliTajeldin** [comment]
@laneb correct.  `DQMState` will be part of `DqmValidationResult` and will be read/persisted along with it.

Rough ETA is by end of next week (1/19)

**Comment by laneb** [comment]
Cool. Will this ticket include changes to the Python API to make the metadata accessible?

**Comment by AliTajeldin** [comment]
correct

**Comment by Kai-Chen** [comment]
We have a little bit of a choice on the Python API, wrt the entry points `runModuleByName`and `runModule`.

1.  Keep the same signature as the Scala API, and pass an instance of `SmvRunInfoCollector`, which we would have to ask jvm to create for us.
2.  Return a tuple of `DataFrame` and `SmvRunInfoCollector`.  This is more pythonic in idiomatic usage, but the existing client would need to change.

@AliTajeldin which of the two do you like better?

**Comment by AliTajeldin** [comment]
I like option 2 as we don't have clients that use `runModule*` directly.

**Comment by Kai-Chen** [comment]
@ali Since @laneb mentioned about metadata being accessible through this issue implementation, should metadata be included in `SmvRunInfoCollector`? like `DqmValidationResult`?
or is metadata kept as a member in SmvDataSet?

**Comment by Kai-Chen** [comment]
Should `RunConfig` also be part of the parameter list for `runModuleByName`?

**Comment by AliTajeldin** [comment]
The metadata (and history) should be added to the collector and have a separate entry point for getting the metadata (eg. `getMetadata(Optionfqn)` and `getMetadataHistory(fqn)`).  If fqn is not specified, the metadata for the module we ran is returned.  This should be the same for all other getter methods.

**Comment by AliTajeldin** [comment]
For the immediate need, we don't need `RunConfig` in `runModuleByName` but should have for consistency sake (optional parameter).

**Comment by jacobdr** [comment]
@kai-chen can you post a screenshot when you can of the contents of the RunInfoCollector after one run with DQM and metadata? (Or just the former if the latter isn’t done yet). Just want to make sure it has enough information for our need. 

Also, just checking... Even though we have separate getters for DQM and metadata, if a dataset implements both, we have some way of tying those results to each other to present a unified view of the run, right? 

Thanks for the good work here

**Comment by Kai-Chen** [comment]
```shell
kchen@twine01:~/checkout/smv$ PYTHONPATH=src/main/python:src/test/python/testSmvFramework ./tools/smv-pyshell --smv-props smv.stages=stage
Using spark-submit to submit jobs
Using pyspark to start shells
APP_JAR = target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar
Spark Command: python2.7
========================================
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Spark Command: /home/kchen/local/jdk/bin/java -cp target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar:/home/kchen/local/spark/conf/:/home/kchen/local/spark/lib/spark-assembly-1.5.2-hadoop2.7.2.jar:/home/kchen/local/spark/lib/datanucleus-rdbms-3.2.9.jar:/home/kchen/local/spark/lib/datanucleus-core-3.2.10.jar:/home/kchen/local/spark/lib/datanucleus-api-jdo-3.2.6.jar -Xms1g -Xmx1g org.apache.spark.deploy.SparkSubmit --conf spark.driver.extraClassPath=target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar --name PySparkShell --jars target/scala-2.10/smv-1.5-SNAPSHOT-jar-with-dependencies.jar, pyspark-shell
========================================
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 1.5.2+hotdeploy
      /_/

Using Python version 2.7.6 (default, Jun 22 2015 17:58:13)
SparkContext available as sc, HiveContext available as sqlContext.
SMV starting Py4j callback server on port 41027
>>> res, coll = app.runModuleByName('modules.D1')
>>> res.show()
+---+---+
|  a|  b|
+---+---+
|  x| 10|
|  y|  1|
+---+---+

>>> showRunCollector(coll)
datasets: Set(stage.modules.D1)
first dataset: stage.modules.D1
dqm validation result is DqmValidationResult(true,DqmStateSnapshot(2,ErrorReport(0,List()),Map(),Map()),List((org.tresamigos.smv.SmvCsvStringData metadata validation,true), (FailParserCountPolicy(1),true), (stage.modules.D1 metadata validation,true)),List())
-- passed is True
-- dqm state is DqmStateSnapshot(2,ErrorReport(0,List()),Map(),Map())
---- dqmstate.totalrecords is 2
---- dqmstate.parsererror is ErrorReport(0,List())
---- dqmstate.fixcounts is Map()
---- dqmstate.ruleerrors is Map()
-- err msgs is List((org.tresamigos.smv.SmvCsvStringData metadata validation,true), (FailParserCountPolicy(1),true), (stage.modules.D1 metadata validation,true))
-- check log is List()
````

**Comment by Kai-Chen** [comment]
Above is a sample run from pyshell.

Inspecting the collector is much easier in Scala, but in Python, traversing DqmValidationResult is still a bit torturous because of the intermediate structure is not native python, so can't iterate, index, etc.

The metadata isn't there yet -- that's one of the checkbox items.

I think making a python-side DqmValidationResult would be a nice one to do.

**Comment by Kai-Chen** [comment]
WRT tying metadata with dqm validation result, there is no such api right now.
Their relationship is implicit in that you use the same dataset fqn to get the respective component from run info collector.

**Comment by Kai-Chen** [comment]
The pyshell function output is changed a bit.
It now looks like this

```shell
>>> show_run_info(coll)
datasets: [u'stage.modules.D1']
+ stage.modules.D1
`-- dqm validation:
    {   u'checkLog': [],
    u'dqmStateSnapshot': {   u'fixCounts': {   },
                             u'parseError': {   u'firstN': [], u'total': 0},
                             u'ruleErrors': {   },
                             u'totalRecords': 2},
    u'errorMessages': [   {   u'org.tresamigos.smv.SmvCsvStringData metadata validation': u'true'},
                          {   u'FailParserCountPolicy(1)': u'true'},
                          {   u'stage.modules.D1 metadata validation': u'true'}],
    u'passed': True}
>>>
```

**Comment by Kai-Chen** [comment]
Just noticed that if I call `runModule` twice, one right after another, the second time, the collector doesn't have any information in it, because the `rdd` skips the call to `computeRDD`.

@AliTajeldin is this an issue?

**Comment by laneb** [comment]
I think the metadata and validation results for the target and all upstream
modules should be included. If the module doesn't need to run, we can just
retrieve whatever is persisted.

@jacobdr Thoughts? My concern for our use case is that we will need the
upstream DQM.

**Comment by AliTajeldin** [comment]
Hmmm, I can see this from two perspectives:
1. We should always return the current state for a module run and everything upstream even if we didn't "run" anything.  Should use the persisted metadata.
2. The results in the collector should be only what actually ran.

One thing about option 1, this could get quite expensive for a large dependency graph.  Imagine a project with a 1000 nodes.
On the other hand, option 2 can be quite confusing for the user.

**Comment by Kai-Chen** [comment]
What about introducing a `forceCollectInfo` parameter in `runModule`?
If it's set, RunInfo will be read from persistence from previous run if there is one.
The default value is false, which means collect only from modules that got ran.

**Comment by AliTajeldin** [comment]
It's getting too complicated for my taste.  Let's think about this over the weekend.

**Comment by jacobdr** [comment]
@AliTajeldin 
Good point on option 1 -- we could include all parent information by default, but provide some option to turn that off. A large project is likely to have SMV expertise anyway, and so would be expected at scale to know about such parameters. As long as we have some facility to getting the last run RunCollector result for a given FQN (from persistence) and we have access to all of the upstream FQNs, can move the collection of all upstream metadata back into the user space. 

Perfect solution aside, what would be useful in the short-term is some helper to access the persisted RunCollector from an FQN

**Comment by jacobdr** [comment]
@laneb Agreed. If we have some easy way to get the "last" result and the downstream module knows about all of its parents, we can iterate ourselves back in user space to gather all the results I guess

**Comment by Kai-Chen** [comment]
I like having a second api to return the validation and metadata info tree of a module.
That leaves `runModule` to return information just for that run.

**Comment by laneb** [comment]
Agreed.

**Comment by laneb** [comment]
All subtickets are complete. Is there any more work to do here?

**Comment by Kai-Chen** [comment]
I think that's it ... closing.

**Comment by jacobdr** [comment]
@laneb will you create a tracking ticket for the validation historical metadata bit?

**Comment by laneb** [comment]
@jacobdr #1098
