### ISSUE TITLE
Runtime error when file in stage contains a Py4J JavaObject or PySpark Column

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1069]
Maybe an atypical usage pattern, but it's come up in a client project. When trying to run the project, got an error whose gist is
```
py4j.Py4JException: Method fqn([]) does not exist
```
During module discovery, we are filtering the objects discovered in files first by attempting to get their `IsSmvDataSet` properties and then by comparing their fqns to the stage name. An assumption is made that if an object is not an `SmvDataSet`, it will not have property named `IsSmvDataSet` and we will get an attribute error before `fqn` is called on the object. However, Py4J has overridden how `JavaObjects` get attributes, and `IsSmvDataset` is resolving to a truthy `JavaMember`. Then we try to call a nonexistent `fqn` method of the `JavaObject`.

**Comment by laneb** [comment]
Instead of just checking that objects in files have `IsSmvDataSet`, we could check that `obj.IsSmvDataSet is True`. That way, it's not sufficient that `obj.IsSmvDataSet` resolves to a truthy object. But maybe there is a more general solution?

**Comment by laneb** [comment]
Suffice to say PySpark and Py4J both have plenty of classes that override either `__getattr__` or `__getattribute__` in a way that attribute access will _always_ return something.

**Comment by laneb** [comment]
Using `hasattr` to check for `IsSmvDataSet` won't work for Python 2, because it thinks `JavaObject` has `IsSmvDataSet`. 

Using `issubclass` to check for inheritance from `SmvDataSet` won't work on its own, because applying `issubclass` to objects which are not types can cause a couple different types of error. We could first verify that that the object is a type. This would be more straightforward than the current approach, but is probably slower.

**Comment by AliTajeldin** [comment]
can we just do a `hasattr` and call the `IsSmvDataset` as suggested above?  Is there a downside to that?

**Comment by laneb** [comment]
Do you mean use `hasattr` to verify that the object has `IsSmvDataSet`, and then check that `IsSmvDataSet is True`?

**Comment by AliTajeldin** [comment]
correct

**Comment by laneb** [comment]
The solution of verifying that `IsSmvDataSet is True` works without checking `hasattr` first. I can't think of any downsides except that it makes code a tiny bit more confusing.
