### ISSUE TITLE
Smv version dependency is not working when a deep dependency is modified.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#107]
assume we have the following dependency:
 E -> D-> C -> B -> A

If B version is bumped up, then we expect C to be rerun (which then causes D and E to also rerun).  However, currently that doesn't occur.  And E version is the same as before B version was increased.  E version is only increased if D is increased.
The problem is with the implementation of `versionSum()` method, it should call `versionSum` on all children instead of just `version()`.  Need to watch out for **O(n!)** algorithm if we don't cache the value of versionSum!!!!!

**Comment by ninjapapa** [comment]
I assume this issue is fixed.
