### ISSUE TITLE
Add SmvSchema support for ByteType

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1072]
SMV doesn't know how to handle input data containing Bytes (or Hive tinyints).

**Comment by jacobdr** [comment]
@laneb I also saw some problem on a cluster with a Hive type of `smallint`.... Maybe a separate ticket, but can you see if you can reproduce in a test?

**Comment by laneb** [comment]
It appears that `smallint` corresponds with `ShortType`, which we do not yet support. I will add a fix in the PR for this issue.
