### ISSUE TITLE
Typo in name of requiresDS causes module not to be found

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1075]
I created a module MyMod with a valid run and requiresDS, except I misspelled requiresDS as requireDS. As a result MyMod was still "abstract" and the DataSetRepo filtered it out during module discovery. If possible, we should still get an error in this case. However, not sure how to distinguish between an intentionally abstract class and an accidentally abstract one.

**Comment by ninjapapa** [comment]
This should not be an issue anymore, since python module is loaded in pure python, so the error should be good enough to identify the problem.

@laneb please confirm.

**Comment by laneb** [comment]
The issue will still exist but it's a very small one. No need to fix.
