### ISSUE TITLE
Make all smv config dynamic

### ISSUE THREAD

**Issue by kmannislands** [TresAmigosSD/SMV#1084]
There is now a use case to have stages and dataDir at least dynamic.
Task is to extend the dynamic run config strategy previously employed to cover all smv config

**Comment by AliTajeldin** [comment]
Well, at least the stages and the data dirs (all variations).  Things like app id and app name can remain static.

**Comment by kmannislands** [comment]
Will update [relevant docs](https://github.com/TresAmigosSD/SMV/blob/master/docs/dev/SmvConfig/smvconfig.md) as well

What is the `class_dir` prop used for? Should it be dynamic in our new model?

**Comment by AliTajeldin** [comment]
that is only for scala.  No need to worry about that for now.
