### ISSUE TITLE
SmvExtModule description should be return value of Python module description

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [TresAmigosSD/SMV#1087]
Currently, in `SmvDataset.scala`, the `SmvExtModulePython` constructor sets the description to be a -partially- hardcoded string, instead of the actual description value returned by the python module's description method. E.g.:
```scala
override val description    = s"SmvModule ${fqn}"`
```
This causes the dependency graph to return nodes with inacurate description values.

The task is to make `SmvExtModulePython` to initialize the description with the correct value (as defined in the python module).

**Comment by ninjapapa** [comment]
@AntonioRecaldeRusso is this still been working on?

**Comment by AntonioRecaldeRusso** [comment]
@ninjapapa This task has been completed in #1095. Can close.
