### ISSUE TITLE
Create shell helper to show current app config

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#1091]
We set different sampling rates in through our `user-conf` and `app-conf` files, and want to reason from the shell what are my final [merged settings](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/app_config.md#name-conflict-resolution). 

Since I don't think that the app config is available on the Python `app` instance in a public way, was hoping we could add some other convenience to give a snapshot of the config

**Comment by AliTajeldin** [comment]
Actually, part of work @kmannislands is doing right now is to provide an api on `SmvConfig` to expose the merged properties.

**Comment by kmannislands** [comment]
@AliTajeldin the use case for that was when dynamic `appDir` wasn't working to discover stages but now providing a dynamic `appDir` as part of `dynamicRunConfig` works for everything without a stages arg, so I don't think there's a need anymore to add the 'inspect merged props' functionality for my purposes.
I think it's pretty useful however so I can go ahead and add this to the `smv-pyshell` as part of my branch or a new one?

**Comment by AliTajeldin** [comment]
Let's add that in the same ticket as we are modifying the config anyway.

**Comment by laneb** [comment]
@jacobdr Kieran's PR included a shell function `props` which returns a dict of config values like
```
{u'smv.stages': u'stage1, stage2', u'smv.appId': u'3eb242ed-59ab-4868-9094-8c973a7b0b04', u'smv.dataDir': u'file:///Users/laneb/twine/smv-projs/enterprise/data', u'smv.class_dir': u'./target/classes', u'smv.config.keys': u'', u'smv.config.alias': u'"PME"', u'smv.appName': u'Example App'}
```
