### ISSUE TITLE
User metadata can't contain None

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1123]
When user metadata contains `None`, it gets jsonified as `null`. In Scala, SMV reads back that json as an `SmvMetadata`, merges it with the default props, and eventually re-jsonifies it to send to `validateMetadata`. The problem occurs when re-jsonifying: we rely on Spark metadata under the hood, and (at least in Spark 1.6.2) Spark doesn't know how to jsonify `null`. The result is  a `NullPointerException`.

**Comment by ninjapapa** [comment]
Is this related SmvModule's metadata or Column's metadata?

**Comment by laneb** [comment]
SmvModule's metadata

**Comment by AliTajeldin** [comment]
@laneb your response didn't go through.

**Comment by laneb** [comment]
Weird, my comment displays correctly when I view it. I just said 

> SmvModule's metadata

I.e. that this issue pertains to `SmvModule` Metadata (i.e. `SmvMetadata`) and not `Column` metadata.

**Comment by AliTajeldin** [comment]
Oh, I just thought you actually had more to say and it got cut off 😄

**Comment by ninjapapa** [comment]
I got the answer :grinning:
Do we need to use Spark metadata to implement SmvModule's metadata?

**Comment by AliTajeldin** [comment]
Thats a scary clown symbol: 🤡

**Comment by ninjapapa** [comment]
No more an issue since smvmetadata is a pure python dict now.
