### ISSUE TITLE
smv-run should accept driver script as argument

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1132]
Use case: user wants to write a Python driver script that will decide contextually what module(s) to run with what configuration, etc. Needs SMV to create and configure SmvApp, then execute script.

**Comment by laneb** [comment]
@AliTajeldin I think `runapp.py` can just decide between calling `app.run` and `exec`ing the user's file. The arg list will be interpreted as `smv-run smv_args driver.py -- spark_args`. Do you foresee any issues?

**Comment by AliTajeldin** [comment]
@laneb Can you give an example of a driver app.  I'm trying to visualize how this would glue together.  How the `sqlContext`, `smvApp` are shared.

**Comment by laneb** [comment]
Conclusion of my discussion with @AliTajeldin, was to add a `--script` option for specifying the driver script.

**Comment by laneb** [comment]
Usage will now look like `smv-run [-h] <smv_app_args> [--script script_name script_args] [-- spark_args]`.

**Comment by laneb** [comment]
@AliTajeldin Thoughts on where this argument parsing should happen? I don't think we can do it with scallop, so I am inclined to add it to `_env.sh`.

**Comment by AliTajeldin** [comment]
I would have thought scallop would be able to handle this.  I thought they support array argument types by default.  But worse case scenario we can create a custom convertor (See https://github.com/scallop/scallop/wiki/Custom-converters)

**Comment by Kai-Chen** [comment]
The current `smv-run` script calls a function (sourced from `_pyenv.sh`) that takes a python script.

```shellscript
run_pyspark_with /path/to/runapp.py
```

To run a user-supplied script, this should be as simple as passing the user script to `run_pyspark_with`.

Supporting both SMV and user-script cmdline options, however, needs to be specified further so that the correct options are processed by the intended scripts.

How about
```shellscript
smv-run [--script <script-path> [--script-opt <option>]*] <smv_app_args> [-- spark_args]
```

**Comment by Kai-Chen** [comment]
Also, the user script would need to include the following snippet

```python
from smv import SmvApp
import sys

app = SmvApp.createInstance(sys.argv[1:])
# skip the first argument, which is this program
app.run()
```
