### ISSUE TITLE
Clean up getModulePackages in SmvApp

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#114]
Other than figure out the common string of all the modules in an dependency graph, ```getModulePackages``` is not necessary.  

The dependency graph itself doesn't depend on it. For figuring out the common string of all modules, it could be more natural to specify it in the concrete class directly.

packages should rather be a parameter to ```genJSON``` to define the scope of the graph. 

Client code should look like
```scala
class MyCoolApp(...){
  ...
  override def packagePrefix() = "org.tresamigos.mvd"
}
```

And the genJSON call from app should be 
```scala
app.genJSON(Seq["phase1", "phase2", "adhoc"])
```

**Comment by AliTajeldin** [comment]
The only reason getModulePackages was kept around was incase we wanted to create a module catalog.  That is, list all the available modules and their description and perhaps what data sets they depend on.  Perhaps even provide a query on these parameters.
