### ISSUE TITLE
Dynamic run config should be reset before SmvApp.runModule exits

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1140]
Methods like `runModule` which alter the `dynamicRunConfig` don't currently reset it afterward, which is problematic because other methods that don't override the `dynamicRunConfig` will pick up the old config. Also, the result of the shell helper `props` will be misleading if dynamic config values are included.
```
# runs with no dynamic run config
df1 = df("A")  
# runs with dynamic run config {"x": 1}
df2 = df("A", runConfig={"x": "1"})
# gets info for A with dynamic run config {"x": 1}
info = get_run_info("x")
```

**Comment by kmannislands** [comment]
I'd be happy to pick this one up if you don't want it.

**Comment by AliTajeldin** [comment]
@kmannislands @laneb one of you guys should pick this up.  It is really weird behavior without the fix.

**Comment by kmannislands** [comment]
@laneb indubitably

**Comment by laneb** [comment]
Chill :tophat:

**Comment by AliTajeldin** [comment]
What the heck did I just witness 😄

**Comment by ninjapapa** [comment]
@laneb since now the dynamic conf is sticky, should this issue be closed?

**Comment by laneb** [comment]
Yes
