### ISSUE TITLE
clear_sys_modules is broken for multipart stages

### ISSUE THREAD

**Issue by kmannislands** [TresAmigosSD/SMV#1144]
It appears that the `clear_sys_modules` method on python dataset repos doesn't actually successfully clear loaded modules for multi-part stages.

**Comment by AliTajeldin** [comment]
To elaborate further for future readers:
if an app has stages such as `airline.etl` and `airline.model` then when we clear the sys modules, we iterate over the stages and we clear the `sys.modules` cache of the stages and anything that starts with the stage name.  So we would clear `airline.etl`, `airline.model`, `airline.etl.f1`, `airline.etl.f1.c`, etc.  However, we do **not** currently clear `airline`.  That is an issue as we will get the old `airline` value on reload and not the new `airline` if project dir changed.
