### ISSUE TITLE
Preserve docstrings and other properties of helper methods

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1154]
Methods of `DataFrameHelper` have docstrings that are documented in the API docs as methods of `DataFrameHelper`, but if you run
```
from pyspark.sql import DataFrame
pydoc.help(DataFrame.peek)
```
you get 
```
Help on method peek in module smv.helpers:

peek(self, *args, **kwargs) unbound pyspark.sql.dataframe.DataFrame method
```
where you should get helpful documentation based on the docstring.
 
When we attach helper methods to `DataFrame`, `Column`, etc., we already preserve the name of the method by setting `__name__` on the attached attribute. If we use `functools.wraps` or maybe just `functools.partial` instead we should be able to preserve the name, docstring, and perhaps other things I haven't thought of.

**Comment by AliTajeldin** [comment]
Didn't even know `functools` had such helpers.

**Comment by laneb** [comment]
Yep! They're pretty neat. @jacobdr showed them to me.

**Comment by laneb** [comment]
Unfortunately, `functools.wraps` preserves docstrings but not method signatures. The resulting help messages look like 
```
peek(self, *args, **kwargs) unbound pyspark.sql.dataframe.DataFrame method
    Display a DataFrame row in transposed view

    Args:
        pos (integer): the n-th row to display, default as 1
        colRegex (string): show the columns with name matching the regex, default as ".*"

    Returns:
        (None)
```
According to [this SO post](https://stackoverflow.com/a/147878), we could use a package called [decorator](http://decorator.readthedocs.io/en/latest/) to create a decorator the preserves the signature.
