### ISSUE TITLE
Option to limit ascii graph to ancestors or descendants of a module

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1157]
The shell function `graph` tends to be too detailed/noisy to be useful. We allow the user to filter the graph for a particular stage, but sometimes I want to see the graph of all the data flowing into or out of a module, including upstream or downstream stages. @jacobdr any other filters you think would be helpful?

**Comment by jacobdr** [comment]
Bring back the export to dot option... maybe out of scope of this ticket.

Jacob Roberts

**Comment by laneb** [comment]
Can you open a separate ticket for that?

**Comment by ninjapapa** [comment]
The ascii-graphs library was not maintained, so might be hard to use it when we have to support scala 2.11.
