### ISSUE TITLE
Support getting the latest history metadata

### ISSUE THREAD

**Issue by cloudysail** [TresAmigosSD/SMV#1161]
Right now we are using `smvserver.py->getMetadataJson()` which eventually calls `SmvDataSet.scala->getMetadata()` to construct information such as 'lastRunTime' of a module. This won't work if a module has never been run before or the output dir has been wiped out.

To solve this issue, we can utilize `SmvMetadataHistory->toJson()` to eventually construct our `lastRunTime`. The history metadata persisted in history folder has all the information we need, and the history would be empty if a module has never been run before.

We can even do optimization to avoid retrieving the whole history since the history could be big. We just need the latest history(the first item in the history array). To implement this, we can create a new function `SmvMetadataHistory->latestHistorytoJson()` to serialize the latest history metadata as JSON string, and expose it in `smvapp` and `smvserver`

**Comment by AliTajeldin** [comment]
Let's keep this simple and not worry about the history size.  It shouldn't be very big.  If the user stores a million records in history we will have other problems anyway 😄

**Comment by cloudysail** [comment]
Cool. I changed to expose history metadata JSON function directly.
