### ISSUE TITLE
Add library dir to py path as well

### ISSUE THREAD

**Issue by kmannislands** [TresAmigosSD/SMV#1163]
Spoke with @AliTajeldin this morning, and it has been decided that we want to standardize on adding `$PROJECT_DIR/library/` to the $PYTHON_PATH for SMV projects as well.

**Comment by laneb** [comment]
This ticket seems incomplete. If SMV considers "library" code to be part of a user's application, I think it ought to be reloading that code along with "application" code in `src/main/python`.

**Comment by kmannislands** [comment]
@laneb good catch, thanks@

**Comment by AliTajeldin** [comment]
Oh, I thought this was the old ticket.
