### ISSUE TITLE
Raise an error if there is an smv.config key which is not included in smv.config.keys

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#1166]
Based on document, to pass a config parameter, we need to:
1. Enumerate the app config parameters in a config file
2. Get config within module
3. Change config parameter from command line

In my case, I forgot to add `smv.config.keys` to config file and passed different parameters through command line to run the job, module only got refreshed at first time. After adding `smv.config.keys`, module got refreshed each time with different values of parameter.

I suggest SMV should raise errors if user doesn't include `smv.config.keys` in conifg file in above case. How do you think @laneb ?

**Comment by ninjapapa** [comment]
Agreed.

**Comment by laneb** [comment]
This issue will be better resolved through the solutions discussed in #1186 and #1176.
