### ISSUE TITLE
Option to skip metadata when running a module with smvApp.runModule

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1169]
Sometimes I want to skip creating metadata e.g. when I run a module with `df` and just want a quick result. It would be convenient to be able to suppress the calculation of metadata when running a module.

**Comment by AliTajeldin** [comment]
Whatever flag/method we use should also make it clear we would be suppressing the metadata validation as well.

**Comment by laneb** [comment]
This should suppress all validation. We have some modules where DQM without metadata can take quite a long time as well.
