### ISSUE TITLE
need to remove "global" schemaWithMeta from SchemaRDDHelper

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#117]
There seems to be a "var" called `schemaWithMeta` in `SchemaRDDHelper` that is acting as a global (withing the enclosing class namespace).  This variable is affected by the `addMeta` function.  Both it and the function that modifies it should be removed.  Globals are evil and should be avoided as this is not MT safe and makes the code very hard to understand.  It would be better to allow the user to  pass in an optional schema to `saveAsCsvWithSchema()` instead of relying on this global.
We can add the equivalent of `addMeta` to the SMV `Schema` class  that creates a new immutable Schema with the added fields

**Comment by ninjapapa** [comment]
Fixed.
