### ISSUE TITLE
Switch master to 2.*

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1174]
Since the last client using 1.5.* was moved to 1.6. We should switch our master branch to 2.*.

**Comment by AliTajeldin** [comment]
Finally!!!! 🎉 🎈

**Comment by laneb** [comment]
I think the only thing outstanding on this is to get the 2.0 and 1.6 branches up to date with the 2 branch. Then the 2 branch can become master.

**Comment by laneb** [comment]
Given the issues we've been having with derby+spark 1, we're going to prioritize making 2 master over getting 2.0 or 1.6 in sync. Although I am still ironing out some bugs in the release process aren't any other critical issues that need to be addressed before that happens. Will make the switch this afternoon. Once this is done

1. 1.5 will point to the current head of master
2. master will point to the current head of 2

**Comment by ninjapapa** [comment]
done.
