### ISSUE TITLE
smvGetRunConfig should return None if config key undefined

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [TresAmigosSD/SMV#1176]
Currently, SMV throws an error if `smvGetRunConfig()` (from `SmvRunConfig class`) if a runConfig key is undefined. 
E.g.:

Suppose `myKey1` and `myKey2` are defined as a `dynamic run config` parameters
```json
{ "myKey1": "value1", "myKey2": "value2" }
```

And, suppose no additional keys are defined anywhere else (namely, `command line args`, `smv-app-conf.props`, `smv-user-conf.props`). The the following code will throw an error because the `runConfig` key `myKey3` is undefined
```python
class MyModule(SmvModule, SmvRunConfig):
    def run():
        m1 = smvGetRunConfig("myKey1")    # <--- returns "value1"
        m2 = smvGetRunConfig("myKey2")   # <--- returns "value2"
        m3 = smvGetRunConfig("myKey3")   # <--- will throw and error!
```

After some discussion with @AliTajeldin, it was determined that instead of throwing an error, getting the value of an undefined runConfig key should return `None`

**Comment by laneb** [comment]
Every key in the `runConfig` is supposed to be declared in config value `smv.config.keys`. Listing the key in the conf is how you inform SMV that the value for that key should be included in the hash. If you declare the key and try to run a module without giving a value for the key either in the dynamic run config or in the app conf, then you will get a key error when SMV tries to compute the hash for the module. It's only possible to get this key error in the `run` method if the key is not listed in the app conf, in which case its value is not considered in the hash. If we are going to endorse using keys which are not explicitly listed via `smv.config.keys`, we should go the distance to make sure that those keys will still be included in the hash. To accomplish this, we can get rid of `smv.config.keys` and just include every config value whose key starts with `smv.config.` in the hash. This will make the whole interface simpler anyway.

**Comment by laneb** [comment]
The above should also resolve #1166.

**Comment by AliTajeldin** [comment]
The tricky part is that it is not possible to find all keys of the form "smv.config.*" using current parser.  That looks for a specific property but doesn't enumerate all properties in the config file.  We can create a simple property parser to do that perhaps.
Note for dynamic config that is doable as we are sending the entire list of config parameters along with the run request.

**Comment by AliTajeldin** [comment]
Oh, nice.  For some reason, I really thought we only evaluate the props on a as needed basis hence no keys.  Then we can get rid of the "keys" all together.  That only existed because I didn't think we can enumerate the run config params.

**Comment by laneb** [comment]
Closing as this is duplicated by #1252, which already has work attached to it.
