### ISSUE TITLE
Add duration of long actions to metadata

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1178]
When performing an action on a `DataFrame` which may take a long time (e.g. persisting to CSV) the time elapsed should be added to the metadata. Will help track job performance.

**Comment by AliTajeldin** [comment]
* For ephemeral modules, this should be done if we force an action during DQM
* for non-ephemeral modules, this should be done around the persist **and** DQM so users get a better idea of whats actually taking a while.

**Comment by AliTajeldin** [comment]
@laneb Maybe we need a couple of definitions.  For DQM do you mean the traditional inline DQM calculation?  Not sure how that time can be isolated.  Or is it the DQM validation step (which would normally be very quick as it is shouldn't be doing any relational algebra)

**Comment by laneb** [comment]
I mean the validation step, specifically the expression that reads 
```
dqmValidator.validate(df, hasAction, moduleValidPath())
```
To be clear, validation includes forcing an action when appropriate, so validation is very quick _iff_ the module is _not_ ephemeral. This means for non-ephemeral modules the relational algebra of DQM will be included in time spent on persistence and for ephemeral modules it will be included in time spent on validation.

**Comment by AliTajeldin** [comment]
Does the `dqmValidator.validate()` include the metadata validation?  I thought that was how it was implemented (the metadata validation was just another validation step in dqm validator).  But my memory could be tricking me.

**Comment by laneb** [comment]
It does, which is why I'm forcing the user metadata to be cached before
running the validation step.

On Apr 5, 2018 12:39 PM, "Ali Tajeldin" <notifications@github.com> wrote:

Does the dqmValidator.validate() include the metadata validation? I thought
that was how it was implemented (the metadata validation was just another
validation step in dqm validator). But my memory could be tricking me.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TresAmigosSD/SMV/issues/1178#issuecomment-378803949>,
or mute the thread

**Comment by AliTajeldin** [comment]
So, I think I need a clearer explanation of " I've explicitly populate the metadata cache before validation".
How are you proposing to cache the metadata?  Just caching the json result?  Or the DF result from which the json is computed?

**Comment by laneb** [comment]
We already cache the user metadata to avoid computing it multiple times.
I've added a step in runDqmAndMeta to ensure that the user metadata is
cached before validation so the time spent on validation is isolated.

On Apr 5, 2018 12:46 PM, "Ali Tajeldin" <notifications@github.com> wrote:

So, I think I need a clearer explanation of " I've explicitly populate the
metadata cache before validation".
How are you proposing to cache the metadata? Just caching the json result?
Or the DF result from which the json is computed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TresAmigosSD/SMV/issues/1178#issuecomment-378804765>,
or mute the thread

**Comment by AliTajeldin** [comment]
Got it.  Ok, then the above plan sounds good.
