### ISSUE TITLE
 SmvRunConfig is too aggressive about changing the dataset hash

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1186]
Expected behavior:  hash changes when a key in use by the dataset changes

Observed behavior: hash changes when _any_ key changes

**Comment by laneb** [comment]
Proposed alternative interface:

Every `SmvDataSet` can access run config. The user gives a list of config keys that the module needs access to
```
def smv_config_keys(self):
  return ["k1", "k2", ...]
```
and when the module is constructed, we add those KVs as attributes.
```
def __init__(self, smvApp):
  self.smvApp = smvApp
  for k in self.smv_config_keys():
    v = smvApp.getConfigValue(k)
    self.k = v
```
so they can be accessed at runtime
```
def run(self):
  some_logic(self.k1, self.k2)
```
and since we know all the config values the module relies on, we can base the dataset hash on those values instead of the whole config.
@AliTajeldin @chengfei0913 @jacobdr thoughts?

**Comment by AliTajeldin** [comment]
This fits in well with the way we are using config keys in the UI as well. 
We may also use that as a way to derive the set of global "keys" based on a given run instead of requiring the use to enumerate the keys in config.  It is the union of all dataset keys for all modules we are about to run.

**Comment by laneb** [comment]
It may no longer be necessary to create a set of all config keys - the only use I'm aware of for that set is to influence the dataset hash.

**Comment by AliTajeldin** [comment]
The other reason was a way to find what keys/values to ship to each executor so that they can access the config values in udf.  But I think there are better ways to do that.

**Comment by laneb** [comment]
This approach makes the user responsible for coercion to non-string types - currently `SmvRunConfig` provides `smvGetRunConfigAsBool` and `smvGetRunConfigAsInt` for this. However, the logic for the coercion is pretty trivial.

**Comment by laneb** [comment]
We will maintain the existing interface (`smvGetRunConfig*`) in place of the new interface for kv access proposed in this ticket. Otherwise the existing implementation is ready for PR.
