### ISSUE TITLE
Create Python SmvApp method for accessing the smv config

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1187]
Sometimes I want to access the config outside of a dataset.

**Comment by ninjapapa** [comment]
Python SmvApp does have `config` method, which returns `smvConfig` from Scala side. Does this issue refer to the RunConfig?

**Comment by laneb** [comment]
Not sure what exactly is meant by RunConfig in context. I need a convenient and supported way to access all of the current config values through `SmvApp`. Today we can technically access through something like `smvApp.config().mergedProps().apply(key)`, but rather than having client applications depend on an implementation detail like `mergedProps` I think we ought to expose a method on `SmvApp`.

**Comment by ninjapapa** [comment]
I see.

**Comment by ninjapapa** [comment]
SmvConfig is pure python now.
