### ISSUE TITLE
SmvTeeOps

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#119]
Currently if we need to generate 2 things from the same SRDD source we do
``` scala
val cached = srdd.cache()
val res1 = cached.doSomethingHere
val res2 = cached.doOthers
```

In a lot use cases, actually one task could be very simple and can be done with a single data pass through. Some examples:

* Record count
* Basic statistics on key fields
* Sum on a column by a field with limited distinct values. Like total spend by gender

In those cases, we can use Accumulator to hold the intermediate values and pass the input data records directly to the output. 

The code will look like:
```scala
val tee = srdd.smvTee()
val res = tee.addCount(...).addSum(...).toSchemaRDD
res.saveAsCsvWithSchema(...)
tee.counter(...).report()
```

The only tricky thing of this is that the accumulators will only be available when the SRDD have actions on them. In that case may need to create a method equivalent to pipe the output to "/dev/null".

Implementation wise, a tricky thing is the scope of the accumulators. It is possible that a SmvModule will not trigger any action by itself, instead it will pass the SRDD down to next SmvModule. Also Accumulator is a concept at SparkContext level. Because of that we need to maintain the Accumulators in SmvApp, although the use of them are in SmvModule. Need to design it with care.

**Comment by AliTajeldin** [comment]
I'm not too keen on the api.  I don't really have an alternative but I think we need to have a whiteboard session before we go too far down this path.

**Comment by ninjapapa** [comment]
Agree. Tomorrow? 

I noticed the issue when i was writing it. Anyhow throuw the problem out first :-)

Currently SmvModule does not need to know what SmvApp is there. If we want to use Accumulator in SmvModule, it have to know which App it should ask for the Accumulator. Or the App may need to keep an eye on which SmvModule claimed it need an Accumulator and then assign to it when really do the persist. Anyhow not easy.

**Comment by ninjapapa** [comment]
As discussed the 3 use cases are actually in 2 groups. Use case 1 and 2 both happen when we persist SmvModule (either in dev mode or not) to either provide quick feedback or create persist meta data with SmvModule. In those 2 use cases, we can implement them in the framework as default (or simply allow user to switch on/off) without expose any user interface. 

The tricky one is the last use case. The real requirement is actually inform execution of a groupBy operation that the groupBy dimension is small, so some specific optimization could be apply. We will get deeper to the Logical Plan -> Physical Plan layer and figure out a way to perform the optimization there, so that the user interface to groupBy is still unique. 

Will drop the requirement for the last use case and implement to support the first 2 use cases without publish any user interface. Will open another issue to clarify.
