### ISSUE TITLE
Make SmvInput python class more user friendly so user can easily define their own inputs

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1195]
The use case is that other that the input connectors SMV is supporting, there might be all types of input sources which are not covered and can't be fully covered anyhow. The best way to address this could be providing an easier `SmvInput` ABC, so that user can easily extend for their own use cases.

As an example, we will use XML reader to test the design of the simpler `SmvInout` ABC.

This is a Type2 issue. Will design it within issue comments.

**Comment by ninjapapa** [comment]
# Requirement

For the use case that an end-user to use `SmvInout` directly, target client code for reading in an XML file:
```python
class MyXmlInput(SmvInput):
    def reader(self):
        return self.smvApp.sqlContext\
            .read.format('com.databricks.spark.xml')\
            .options(rowTag='MedlineCitation')\
            .load('path/to/xmlfile.xml')
```

For use case that a "library-creator" using `SmvInout` to create an `SmvXmlInput` class for end-user,
The end-user code will look like:
```python
class MyXmlInput(SmvXmlInput):
    def path(self):
        return "path/to/xmlfile.xml" # could be dir or xmlfiles.*.xml
    def rowTag(self):
        return "MedlineCitation"
    def userSchema(self):
        with open ("path/to/schema.json", "r") as sj:
            schema_st = sj.read()
        return schema_st
```

# Design

Current `SmvInput` assumes there is a Scala implementation of the concrete class. That assumption should be separated to another class, and can be mixed in when the concrete class does have a Scala backend.

The `instanceValHash` logic for `SmvFile` on Scala side should be made available out of the class definition so that the Python side can call it even in the case that there are no concrete class level Scala backend.

**Comment by AliTajeldin** [comment]
We should go a step further in and assume that there is **always** a python class for input.  We can create adaptors for the current scala only classes in python.  It should make our life easier in the future for other things as well.

**Comment by AliTajeldin** [comment]
Note: I'm assuming the above design is not complete yet.  Need to hash this out a bit more before we start the implementation.

**Comment by ninjapapa** [comment]
@AliTajeldin the design is pretty much complete. It is simpler than I originally thought.

**Comment by AliTajeldin** [comment]
So, what is the actual design?  What is the proposed interface?

**Comment by ninjapapa** [comment]
The `SmvInput` class will have 2 changes:
* Adding an abstract method `reader`
* Remove the `getRawScalaInputDS` stuff

Then need to create `SmvInputWithScalaDS` class to add back `getRawScalaInputDS`.

To handle the `instanceValHash` calculation, need to create `SmvInputFile` on python side to call the Scala side `instanceValHash` logic (last modified time plus name). 

Client side `SmvXmlInput` should derive from `SmvInputFile`.

**Comment by AliTajeldin** [comment]
LGTM

**Comment by ninjapapa** [comment]
Discussed with @AliTajeldin, on the python side, the top level structure of `SmvDataSet` will be
* `SmvInput` 
  - `SmvInputWithScalaDS`
  - user defined input class
  - future smv input class
* `SmvModule` 
* `SmvOutputBase`

For now all pre-defined existing input classes are under `SmvInputWithScalaDS`. In the future might define them under `SmvInput` on python side and remove their dependency to Scala side. 

Currently we have an `SmvOutput` mix-in to label whether some SmvDataSet are "output", and provides table name etc. to be used by "publish" or "publishhive" command line parameter.

In the future, although we will keep `SmvOutput` for backward compatibility, we will create another base class `SmvOutputBase` and create child classes such as `SmvHiveOutput` etc. So that run those modules is actually writing to Hive or or other output locations. Then SmvOutput/publish can be deprecated.

One thing need to discuss though is the name of `SmvInput` and `SmvOutputBase`. Several options:
* `SmvInput`, `SmvOutputBase`
* `SmvInputBase`, `SmvOutputBase`
* `SmvInput`, `SmvOutputWriter`
* `SmvInput`, `SmvWriter`
* `SmvReader`, `SmvWriter`

**Comment by AliTajeldin** [comment]
For symmetry sake, my vote is for either:
* `SmvInputBase`, `SmvOutputBase`
* `SmvReader`, `SmvWriter`

Maybe a slight preference for the first.

**Comment by ninjapapa** [comment]
OK. Go with `SmvInputBase` and `SmvOutputBase`.

**Comment by ninjapapa** [comment]
As pointed out in the review process, need to make `SmvInputWithScalaDS` fully derived from `SmvInputBase`, we need to pass the validator through. However, the natural parameter for `readAsDF` is the `ParserLogger` instead of the `DQMValidator`. 

Even for future input readers, we can use the `ParserLogger` interface to feed reader's log to DQM policy. So it makes sense to keep an `ParserLogger` parameter to the `readAsDF` function.

However user defined `readAsDF` should not know the details of `DQMValidator`. It makes implementing a general `SmvInputWithScalaDS` harder. 

The solution can be the following:
* Separating out Hive and JDBC input modules to use `SmvInputBase` directly, so that the only thing left in `SmvInputWithScalaDS` are the csv modules
* Call `readFromFile` function instead of the `doRun` function on the Scala side within the `readAsDF`
