### ISSUE TITLE
☂️Remove Python side built-in input modules' dependency to Scala implementation

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1201]
Basically the only functions left on Scala side are:
* File path logic (including schema file path)
* Get DF from file, dir, string using file handler
* Create schema from schema file or schema string

None of those are too hard to call the functions from python directly instead of rely on Scala implementation.

Make this an ☂️ issue:
* [x] Implement the path logic
* [x] convert `SmvCsvStringData` 
* [x] convert others

**Comment by laneb** [comment]
Should we then remove the Scala implementation altogether?

**Comment by ninjapapa** [comment]
# Path logic

Currently `SmvCsvFile` only support `path` method to pass in the path of the data file relative to `smvInputDir`. 

While we are migrating to pure python interface we should design the base class so it can support the following use cases:
* Use case1: same as before, path as relative to `smvInputDir`, and schema path derived from data file
* Use case2: specify fullpath for data path and schema path
* Use case3: data path as relative to `smvInputDir`, but schema path is somewhere else
* Use case4: data path as full path or relative, but schema is defined in code
* Use case5: no need for schema, full or relative data path specified

## Design

`SmvInputFromFile` base class provides the following methods:

* `fullPath` - as full path with protocol to data file(s)
* `schema` - the schema as StructType (could be None in case the reader does not need schema to be specified)
* `fullSchemaPath` - full path to schema file
* `path` - data path relative to `smvInputDir`.

For the 4 use cases above,
* Use case1: define `path`, all others derived from it
* Use case2: define `fullPath` and `fullSchemaPath`
* Use case3: define `path` and `fullSchemaPath`
* Use case4: define `path` and `schema`
* Use case5: define `path` and define `schema` as `None`

The base classes (`SmvCsvFile`, `SmvXmlFile`, etc.) have the default definition of the 4 methods:
* `fullPath` - derive from `path` and `smvInputDir`
* `schema` - read from `fullSchemaPath`
* `fullSchemaPath` - derive from `path`
* `path` - None

**Comment by ninjapapa** [comment]
Ready to remove Scala's interface functions for python to access SmvCSV stuff on scala side.
