### ISSUE TITLE
SmvDataSet should have an optional uniqueKeys method

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1210]
For most modules, user either knows or assumes some unique keys of the output dataframe. Need to create an interface method in the SmvDataSet so that users could specify the unique keys. At least it will give down-stream module a hint of how to use those DFs. Also we are able to create DQM rules to check against that uniqueness.

**Comment by AliTajeldin** [comment]
How about a simple interface such as:
```python
class MyMod(SmvModule):
  def primaryKey(self): return [ "x", "y", "z" ]
  def run(self, i): ...
```

The above implies that the combo key `["x","y","z"]' is a unique constraint on the result table (which can be checked in DQM).
The default `primaryKey()` method should just return an empty array or None which mean there is not primary constraint.

**Comment by laneb** [comment]
How would `primaryKeys` be used within SMV itself other than for DQM?

**Comment by jacobdr** [comment]
For one thing, I think they would serve a self-documenting function — and in that way could be combined with some module description to generate UI or reporting.

The primary key is also very likely in the set of candidate keys to other tables, so could be used for features to discover the likelihood two tables join together.

Finally, we still haven’t really put forward a framework way to do SCDs, so maybe we should design this feature with that in mind.

JR

**Comment by ninjapapa** [comment]
Will do it in the way describe in #1038
