### ISSUE TITLE
datasetsForStage sometimes fails due to incorrect result from walk_packages

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1216]
Need to debug this on the cluster where the problem occurs - it seems that `pkg_util.walk_packages` in some circumstances only returns packages at the shallowest depth. It only seems to occur in cluster mode, which suggests it could be tied to a particular version/installation of Python. The issue seems to be resolved by replacing the following line from `_iter_submodules_in_stage`
```
stagemod = __import__(stage)
```
with
```
stagemod = __import__(stage)
for name in stage.split('.')[1:]:
    stagemod = getattr(stagemod, name)
```

**Comment by laneb** [comment]
We have applied the change described above as a hotfix but I'd like to identify the true cause of the issue and fix it in SMV ASAP.

**Comment by AliTajeldin** [comment]
Also keep in mind that if python encounters any partial match of a path, it will use the cached value and not look for the full path even if it exists elsewhere.  For example, if you have two packages `com.foo.a` and `com.foo.b`.  If `com.foo.a` was in one zip and `com.foo.b` was in another, we will never find `com.foo.b`.  When you search for `com.foo.b`, it will find the cached `com.foo` it got when it found `a`.  It will not bother to keep looking for another `com.foo`.  This is why short, non dns package names is the norm in python.
I assume the above will also hold true for tree walk.

**Comment by laneb** [comment]
Having trouble replicating this issue recently. May be due to changes in the way we package our source.

**Comment by laneb** [comment]
Closing as we are still unable to replicate the issue.
