### ISSUE TITLE
Give SmvModule run method access to the app

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#122]
Although we didn't started that way, the SmvApp/SmvModule structure effectively provided a OO style wrapper to SqlContext/SchemaRDD with additional functions as we intended to do.

To complete that wrapper, we need to give SmvModule run method an access to the SmvApp which gonna to run it, just like Srdd have an access to sqlContext. 

The real need is that SmvApp may have sqlContext level resource which the SmvModule's may want to utilize at run time. In contrary to Srdd, a SmvModule is an Object, which only attach to an App at run time.

**Comment by AliTajeldin** [comment]
This will be implemented using setter injection as we must wait until AFTER the app is initialized to inject the current app object into all the known modules.

**Comment by AliTajeldin** [comment]
The injection part is done but clean up of old smvApp parameters will have to wait until after port to 1.3 of app (to make the port easier as I'm not porting the injection into old 1.1 smv).

**Comment by AliTajeldin** [comment]
Done.
