### ISSUE TITLE
Option to turn off hotloading of Python modules

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1221]
Reloading modules leads to annoying gotchas when writing custom runners.

**Comment by AliTajeldin** [comment]
@laneb can you elaborate on that a bit.  What was the gotcha?  Perhaps we should either resolve it or document it for folks who do depend on hot loading.

**Comment by laneb** [comment]
E.g. @guangningyu was writing a script that did something like

*module_def.py*
```
from proj_utils import CustomModuleType as CMT
CustomModuleImpl(CustomModuleType):
```

*script.py*
```
from proj_utils import CustomModuleType as CMT
dsrepo = smv.DataSetRepo(smvapp)
mod = dsrepo.load("CustomModuleImpl")
assert isinstance(mod, CMT)
...
```
and the assertion would always fail, because by the time that we were loading the module `DataSetRepo` had triggered reloading `proj_utils` - there were now two copies of `CMT` and he was comparing against the wrong one. I don't think there is anything to resolve. We can document it, but it would make things a lot easier for development if the hotloading could just be turned off.

**Comment by ninjapapa** [comment]
@laneb I agree with the first part of the statement of the need of documenting, but not convinced that the option of turn off hotloading in development solves any real problem.

**Comment by AliTajeldin** [comment]
The ultimate fix for the above would be to provide a safe "instance" check that is somehow based on the name of classes in the RMO rather than the actual class instance.  Something like:
```python
assert mod.isOfType("CustomModuleType") // or something along those lines.
```
And we would need to document that so users are aware of the gotchas.

**Comment by laneb** [comment]
@ninjapapa it wouldn't be just for development, I would like to be able to do this for custom runners in production. 

@AliTajeldin What makes that solution superior? There's only a need for hotloading code for long-running interactive applications like `smv-server`. Introducing custom typecheckers seems overcomplicated (and unpythonic :wink:). This isn't the only gotcha either. Here's another scenario
**file1**
```
import some_lib
class MyMod(smv.SmvModule):
  ...
  def getConfig(arg):
     ...
     # use some_lib.some_func
     ...
```
**file2**
```
mod = dsrepo.loadDataSet("MyMod")
for arg in args_to_run_with:
  config = mod.getConfig(arg)
  smvApp.publishModuleByName("MyMod", runConfig=config)
```
This will cause an error like `NoneType has no attribute some_func`. Understanding why or working around it would require understanding how SMV's transactions work. Rather than trying to patch problems like this, it seems natural just not not create the problem by messing with `sys.modules`.

**Comment by ninjapapa** [comment]
Agree that other than the interactive use cases (pyshell, notebook, or smv-server), there is no need of doing custom hotloading. 

But on  above example, let's say some future UI based user want to have the same flexibility of using the same module to process an array of data with and array of parameters, what he should do? Should he also use the DSrepo directly, or should SMV runner provides some function to support that use case?

Another thing for the example, this type of use cases may need the interactive environment too. 

* I support the idea of having a flag to turn off hotloading (might only for smv-run)
* I don't agree on allow user to using dsrepo.loadDataSet directly, we should abstract that requirement out and make SMV supporting it. Although for short term may just turn off hotload and implement like the example to deliver

**Comment by ninjapapa** [comment]
The root problem here is that originally we only allow user to run app through smv command line, when we start allowing custom driver, we opened up quite a lot internal stuff to users. 

To solve this fundamental problem, we need to separate the interactive mode and the running only mode. With this separation:
* Command line all should be considered "running only"
* `Smv-shell` and `Smv-server` are "interactive"
* Custom driver is "running only" and only need the `runModule` command (`publishModuleToHiveByName` function will be replaced by a `runModule` on a Hive output module)

Running only mode does NOT need to do hot loading. We can still keep the the transaction concept for catching management, no-hot-loading only means we will not clean up `sys.modules`.

**Comment by AliTajeldin** [comment]
@ninjapapa sounds good 👍

**Comment by laneb** [comment]
Sounds good to me.
