### ISSUE TITLE
Undefined functions in smvserver.py

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1227]
https://github.com/TresAmigosSD/SMV/blob/master/src/main/python/scripts/smvserver.py#L206

err_res and ok_res functions are not defined.

**Comment by ninjapapa** [comment]
Sounds like most of the code in `smvserver.py` is not used any more. 
@AntonioRecaldeRusso @kmannislands , could you take a look and confirm?

**Comment by AntonioRecaldeRusso** [comment]
Sure, I will

**Comment by AntonioRecaldeRusso** [comment]
I discussed with @AliTajeldin about this. I will see what it takes for this entry-point to work again, and fix it if not too onerous time-wise. Else, it will be removed.
