### ISSUE TITLE
SMV doesn't currently integrate with YARN cluster mode out of the box

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1242]
`SmvApp` now expects the environment variable `SMV_HOME` to be set at runtime. This works fine for local and yarn client mode, but not for cluster mode. This was added to support identifying the SMV version (reading it from `.smv_version`), which is needed by a SMV shell function. We should be able to just make `SmvApp.smvVersion` a lazy val.

**Comment by cloudysail** [comment]
This is the `smvVersion` for now
```
  val smvVersion  = {
    val smvHome = sys.env("SMV_HOME")
    val versionFile = Source.fromFile(f"${smvHome}/.smv_version")
    val nextLine = versionFile.getLines.next
    versionFile.close
  }
```
Other than adding `lazy` before `val`, shall we also add `nextLine` at the last line otherwise it seems not return any value.

**Comment by ninjapapa** [comment]
Just checked it is returning None on the python side.
