### ISSUE TITLE
SmvModel/SmvModelExec can be used in non-model use cases, may consider to create new alias of them

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1243]
With a client project, client want to use Hive tables to drive configurations. Although most of the confs are small tables, there are cases that the config table only have 1 value, for example, the cut-off date of a run.

In that case if we use regular SmvInput and SmvModule, in the dependent modules, we need to call
`df.select('cut_off').collect()[0][0]`, which is hard to read and have to be repeated. What we turn out to do in the project is actually using the SmvModel/SmvModelExec. 

We made the input table a SmvModel, which returns the cut_off as a Python string, and all dependents are SmvModelExec, which use the cut_off as a model output (Python string).

It solved the copy-paste problem, but the names SmvModel/SmvModelExec are quite misleading. Should we create other alias for them?

**Comment by ninjapapa** [comment]
The interesting thing is that this use pattern addressed the original reason of introducing the `SmvAncillary`, although later the `SmvAncillary` was used to implement Scala side `SmvHierarchy`.

Since `SmvHierarchy` python implementation has nothing to do with the Scala implementation, maybe it's time to remove the entire `SmvAncillary` and `SmvHierarchy` structure from Scala side. 

Then we can reclaim `SmvAncillary` as an alias to `SmvModel`.

**Comment by laneb** [comment]
`SmvModel` is already an alias for `SmvResultModule` :joy: Should probably come up with a name which is more expressive of what this type is for.

**Comment by ninjapapa** [comment]
Replaced by the generic module design.
