### ISSUE TITLE
Allow smv-init to create empty projects

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [TresAmigosSD/SMV#1250]
The current options for creating projects are:
- simple
- enterprise
- test

A new `"empty"` option should be added, which should do the following:
- create a project with no modules and no data
- require mandatory argument `datadir`, and set `smv.dataDir` in `user.conf.props` with this value

**Comment by AliTajeldin** [comment]
note that empty should be exactly the same as "simple" but without the two modules (so stages, config, etc stay the same).

**Comment by AntonioRecaldeRusso** [comment]
In addition to the ability to create an empty project, I plan on adding the following changes as well:

- create a `/library` and `/notebooks` directory in the project dir
- add option to initialize git repo: `-gi | gitinit`
