### ISSUE TITLE
Support for Spark 2.3.X

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1254]

**Comment by laneb** [comment]
Moving to 2.3.x from 2.2.1 won't be too bad. I've run into 2 issues:

1. The way that `LogicalPlan` manages broadcast hints has changed again, but instead of continuing to manage the propagation of broadcast hints we will add an option to `smvJoinByKey` to explicitly broadcast the target dataframe when joining. This will be a simpler solution to support `smvSkewJoin` and easier to support as Spark internals change.

2. There is a test of `DQMRule` that is failing. Debugging this now.

**Comment by laneb** [comment]
Once I have a branch working with Spark 2.3, I'll see if we can squash all of the Spark 2 branches into a single branch compatible with 2.0-2.3.

**Comment by laneb** [comment]
All tests now passing on branch 2.3, but before making a release to support Spark 2.3 we need to dig into the changes to catalyst expressions which caused the `DQMTest` to fail in the first place.

**Comment by laneb** [comment]
@AliTajeldin Have a look at [this commit](https://github.com/TresAmigosSD/SMV/commit/6feb33946dcf5fb7feb5b26a984d1ab5bd51021c) which fixes the problem I encountered where Spark 2.3.0 throws an exception when we try to collect the names of the columns involved in a DQM rule. 

Here's the rundown:

When a `DQMRule` is violated, we want to report the values of the columns which triggered the failure. However, to do this we have to identify the column names, and the user has only provided the pass/fail column which defines the rule itself. Crucially, *that expression may be unresolved*, as in the test that began failing.

We retrieve the column names by from  column expression's references, which are stored in a collection called an `AttributeSet`. We map over the `AttributeSet` by first using its `toSeq` method to get a `Seq[Attribute]`. It's `AttributeSet.toSeq` which changed problematically between 2.2.1 and 2.3.0. `toSeq` used to simply call `toSeq` on a `Set[Attribute]`. Now, it also tries to sort the resulting `Seq[Attribute] by `exprId`, which can only be accessed for references that have been resolved.

It is somewhat interesting that we had at least 2 tests using `DQMRules` based on unresolved `Columns`, but only 1 failed. The test that passed only had 1 column reference, while the test that failed had 2, and adding a second column reference to the former test caused it to fail. It appears that `Seq.sortBy` doesn't bother applying the transformation (i.e. does not access `exprId`) when sorting a `Seq` of length 1.

**Comment by laneb** [comment]
Trying to run with Spark 2.2.1 on the `2.3` branch ends in a lot of errors like 
```
py4j.protocol.Py4JJavaError: An error occurred while calling o3119.smvStrToTimestamp.
: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.ScalaUDF$.apply$default$6()Z
	at org.tresamigos.smv.ColumnHelper.smvStrToTimestamp(ColumnHelper.scala:81)
```
It's not clear to me why this error occurs - `smvStrToTimestamp` did not change between `2.2.1` and `2.3`.

**Comment by laneb** [comment]
@AliTajeldin I'll add a comment to describe the workaround in the above commit. Otherwise, I think this branch is ready for release.

**Comment by ninjapapa** [comment]
Did py4j library version changed from 2.2.1 to 2.3.0?

**Comment by laneb** [comment]
@AliTajeldin Should I cut a release, or should we wait on that?

**Comment by AliTajeldin** [comment]
@laneb if it is ready to go and working, let's cut an initial release.

**Comment by laneb** [comment]
Done. @AliTajeldin Anything else required on this ticket?

**Comment by AliTajeldin** [comment]
Done. Done. Done.
