### ISSUE TITLE
Can we git rid of *.valid?

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1259]
@AliTajeldin has suggested that the .valid files (which record DQM validation reports) are not used and can be discarded.

**Comment by ninjapapa** [comment]
There used to be a logic that if a DF validated (DQM action ran) it should not be validated again. Not sure whether that logic still needed.

**Comment by ninjapapa** [comment]
Since dqm results are in metadata already, and we are supporting quick run option, so no need to use `.valid` as a semaphore. Delete

**Comment by ninjapapa** [comment]
Will be solved in #1249.
