### ISSUE TITLE
Add "Stage" concept to SMV

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#126]
# Introduction
We currently only have 1 way to separate out large apps which is using scala packages.  However, the set of modules within each package can access all the other modules in other packages.  We need a higher level abstraction to group together packages and control access to modules.

The "Stage" layer can be injected between the package level and the app.  Each stage defines its own set of "inputs" and marks the modules that are the external interface of the stage.  A stage can have one or more packages:
App ---> Stage(s) --> Package(s) ---> Module(s)

# Proposed Changes

## Single SmvApp
In the current implementation, `SmvApp` is an abstract base class.  Each application must create its own concrete derived class (e.g. `FooApp`) and override the `getModulePackages` method and optionally provide some initialization code.  Today, developers would also have to create a companion "Main" object (e.g. `FooApp`) that defines the main method and enumerate the inputs to the app.

The alternative proposed here is to create a single `SmvApp` object with a main entry point (while still providing the base `SmvApp` as a base class incase the user wants to do something special and unusual).  The application configuration (e.g. stage definitions) would be moved to a property file instead of requiring a class override.

## Application Configuration
Rather than doing configuration by code, instead, SMV should provide a standard way to parse some user provided configuration file (default to "smv.conf").  The configuration file should be a simple property type configuration rather than complex hierarchical format such as yaml/json.  This would make it **very easy** to provide command line augmentation/override. 

Example:
```ini
smv.stages = stage1, stage2
smv.stage1.package = com.foo.stage1

# spark specific configuration (note smv.sql prefix!)
smv.sql.spark.sql.shuffle.partitions = 64
...
```

`SmvApp` should also accept a command line argument to override name/location of configuration file.

# Stage Interface
## Stage inputs
Each stage (which can have multiple scala packages), should define its own input set object.  The input set should define all the `SmvFile` objects used in this stage.  Note that this is a best practice and is not enforced by SMV.  Example:
```scala
package com.foo.stage1

object Stage1InputSet {
  val file1 = SmvFile("input/foo.csv", CsvAttributes.defaultTsv)
  ...
}
```
## Stage Outputs
Modules that should be exposed externally should be marked as so.  A new annotation will be created that can be applied to a module object to mark it as output.  Example:
```scala
@SmvModuleOutput
MyModule extends SmvModule("compute x over y") {
  override def requireDS = {...}
  override def run()
}
```

This will also allow us to add a command line option to "run" a stage.  Running a stage would mean to execute all "output" modules within a stage.  The same can also apply to the package and app level.  See execution section below.

Need to add a configuration option per stage the specifies the stage output directory.
```ini
stage1.outputDir = stage1out
```

## Stage Linking
Because we now can specify both the input and output of a stage, we can link the two programmatically to avoid typos in names and to keep up with changing version number of output files.  For example:
```scala
package com.foo.stage2

object Stage2InputSet {
  # this is an SmvFile and not a reference to a module
  val res1a = SmvModuleOutputFile(com.foo.stage1.mod1)
  # this will also work but user would then have to keep name up to date.
  # but can also be used to always use a frozen old version.
  val res1b = SmvFile("output/stage1/com.foo.stage1.mod1_v15.csv")
}
```

# Execution
The current `SmvApp` main entry point takes a list of modules to run.  Given the addition of the "output" annotation markers described above, we can now "run" at multiple levels.
* App : run all output modules in the given app
* Stage: run all output modules in the given stage
* package: run all output modules in a given package
* module: run the given single module (same as today)

# New Project Script
We should ensure that adding the stage concept does not make it too onerous for developers / scientists to start a new project. Smv should provide a script that will initialize a new project hierarchy based on some basic information.  The script should create an actual working project with all the build files and sample data files to test the functionality.
TBD: not sure if above script can also be used to add additional stages / packages similar to how Yoeman works for web projects.  example:

```bash
$ smv_init.sh --project my_project  --package_prefix com.mycompany
```

## Generated Project Hierarchy
```
project_dir
    smv.conf  // project configuration file
    pom.xml
    src/main/scala/com/mycompany
        core  // common code package
            util.scala
        stage1
            stage1InputSet.scala // define the stage input set
            etl // package within stage
                mod1.scale, mod2.scale, ... // modules in package
            mdm // another package within stage
        stage2
            stage2InputSet.scala
            ui // package in stage 2
    tools
        run_module.sh
        ...
```

**Comment by ninjapapa** [comment]
1. Should we name SmvModuleOutput annotation differently? It sounds like the output of a module, instead it's an output module
2. Should stage inputs be SmvFile or SmvDataSet? When we want to generate the overall App level module dependency graph, it's better to have everything linked. In that sense the stage input definition should have knowledge of the module. On the other hand, we may also potentially need the stage input as a data version older than the current version of the up stream stage output, in that sense we have to have a way to specify the file instead of the module. I don't have a solution to solve this yet. Please see issue #116

**Comment by AliTajeldin** [comment]
1. how about reverse: SmvOutputModule, or just SmvOutput
2. Hmm, I was Initially thinking the linking would be just an SmvFile.  That is `SmvModuleOutputFile` would just be a helper function.  But I see your point.  While I think #116 is a separate issue, I think it might be best to create a separate SmvDataSet concrete type for linking purposes.  We can that create different behaviours for dependency graphs in the future if need be.

btw, for #116, I think the best solution is to add versioning at the stage level.  We had discussed doing that at the App level in the past.  The stage version just becomes part of the output directory path of the stage.  Then we can add an optional version number to `SmvModuleOutputFile` dataset that specifies a specific version.

**Comment by AliTajeldin** [comment]
Summary of proposed changes to initial proposal:
1. Use a trait rather than an annotation to mark output modules.
2. The trait should be simply called SmvOutput.  A module just needs to extend `SmvOutput` (as well as `SmvModule`).  Perhaps create a helper `SmvOutputModule` concrete class that is essentially an `SmvModule` that has already been extended with `SmvOutput`.  We would keep `SmvOutput` trait incase user wants to mark an already derived module class.
3. Allow for multiple configuration files to be specified on the command line.  This will allow for creating an "app" config (static) and a "user" config (dynamic).  Perhaps provide defaults for each or just limit it to two (each with own command line config flag).  My preference is for the later (two config flags with defaults for each).
4. add versioning to the stage output.  Each stage can have a configuration driven current stage version.  The version number is a just a number that is controlled by the user and not by the code.  The stage version is optional and will default to 0.
5. Now that stage output is versioned, `SmvModuleOutputFile` should take an optional version number that binds the file to a specific version output of the file.  The default is just to use the current stage version as specified in the config file.
6. `SmvModuleOutputFile` will become a subclass of `SmvDataSet` rather than a helper function so that we can distinguish between a link and a real file.
7. Add a command line flag to run dependencies beyond the stage links.  That is, do not stop at `SmvModuleOutputFile`, but do run the upstream module as well.  This will make it easy to run everything from scratch.

**Comment by AliTajeldin** [comment]
After looking at the resulting code, SmvOutputModule was abandoned.  It was hard to  tell if a module as a regular module or an output module.  Requiring caller to add  the "with SmvOutput" to the module declaration made it more obvious.

**Comment by AliTajeldin** [comment]
closing this as it has been mostly implemented and all remaining tasks/issues have new SMV issue to track it.
