### ISSUE TITLE
SMV should distinguish between driver script args and SMV args

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1267]
All args following `--script <script name>` and preceding any `--` should be treated as arguments to the driver script. Arguments preceding `--script` should be treated as SMV args. It is prohibitive to expect the user to distinguish between the two at runtime.

**Comment by laneb** [comment]
Decision regarding #1268 will probably determine the details of this ticket.

**Comment by laneb** [comment]
We will create an `SmvDriver` class which allows the user to define a `main` method which is the logic of the driver, and also allows them to override how the `SmvApp` is created

**Comment by AliTajeldin** [comment]
So the script body would look something like:
```python
class MyDriver(SmvDriver):
  def main(self, smvApp, args):
    # main code goes here.  user will have access to already created
    # SMV app instance and all command line args following `--script`

MyDriver().run()
```

The above interface would allow us to add a hook in the future for creating the `SmvApp` instance if needed.  For example:
```python
class MyDriver(SmvDriver):
  def createApp(self, args):
    # should create SmvApp instance here.  Can depend on `args` command line args.
  def main(self, smvApp, args):
    # main code goes here.  user will have access to already created
    # SMV app instance and all command line args following `--script`

MyDriver().run()
```

**Comment by laneb** [comment]
Ready for merge once #1282 is merged.
