### ISSUE TITLE
Hour value will be changed to 0 when reading in a timestamp column with hour value is 12

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#1269]
Attached test csv file and schema: [time data.zip](https://github.com/TresAmigosSD/SMV/files/2068072/time.data.zip), smv version 1.6.2 and 2.1.1.3

When column type is `Timestamp` and hour value is `12`, e.g. `2018-02-28 12:31:25.0`, after reading in csv file using `openCsv`, hour value will be changed to 0, e.g. `2018-02-28 00:31:25.0`

See below 3rd and 4th columns:
<img width="1419" alt="screen shot 2018-06-04 at 7 55 15 pm" src="https://user-images.githubusercontent.com/31650576/40916215-87cbf8c6-6831-11e8-9803-f26fb8328970.png">

**Comment by AliTajeldin** [comment]
@cloudysail Should share you deck on Timestamps.  That should clear what is going on above.
Note: We might still have a bug in SMV though in either case if we are not handling TZ correctly.

**Comment by cloudysail** [comment]
Turns out to be a serious bug. If I modify the test case below, it will fail
```
SchemaTest.scala:
  test("Test Timestamp default format") {
    val df = dfFrom("a:Timestamp", "2011-09-03 12:13:58.0")
    assert(df.collect()(0)(0).toString === "2011-09-03 12:13:58.0")
    assert(SmvSchema.fromDataFrame(df).toString === "Schema: a: Timestamp[yyyy-MM-dd hh:mm:ss.S]")
  }
```

**Comment by AliTajeldin** [comment]
@cloudysail are you looking at this, or should I assign it to @laneb

**Comment by cloudysail** [comment]
Let me look at it first to see if it is easy to fix. If not, I will assign to Lane

**Comment by cloudysail** [comment]
- It is the 24h format/12h format issue:
https://stackoverflow.com/questions/13245944/java-simpledateformat-parses-121900-to-001900

- Workaround:
Use `H` rather than `h` to define the schema type format like `a:Timestamp[yyyy-MM-dd HH:mm:ss.S]`

- Change SMV?
Right now SMV uses default TimestampTypeFormat "yyyy-MM-dd hh:mm:ss.S":
```
private[smv] case class TimestampTypeFormat(override val format: String = "yyyy-MM-dd hh:mm:ss.S")
```
Maybe we should change it to "yyyy-MM-dd HH:mm:ss.S" which is more common

**Comment by yw-yang** [comment]
Thanks Xiaoshun. Looks like an interesting behavior - `hh` only converts 12 to 00 and for any hour greater than 12, it just remains the same.

**Comment by laneb** [comment]
Makes sense to me to change the default. I don't think the current default is really usable right now since we are using a 12h format without an AM/PM field. Correct?

**Comment by cloudysail** [comment]
Right, I think we were using `hh` and expected it to behave like `HH`. I will do the changes
