### ISSUE TITLE
Remove SmvGDO totally

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1271]
As part of Smv history, SmvGDO was designed to iterate through all the records in a group by some keys. This approach was introduced when there are no easy native Spark function to address the need.  `SmvGDO` used some Spark internal implementation details which were not supported anymore. 

We need to finally remove `SmvGDO` totally and use native Spark functions to support the used cases.

Currently, the following GDOs are in the code:
* `SmvQuantile` - dead code, can be removed already (since we used window function now)
* `SmvChunkUDF` and `SmvChunkUDFGDO` - never ported `chunkBy` method to Python, so can drop support, so can remove also
* `DedupWithOrderGDO` - issue #1045 will remove the need for this GDO
* `FillNullWithPrev` - is in use and has Python side api dependency 

For the `FillNullWithPrev`, we should figure out a Spark native approach to implement.

**Comment by laneb** [comment]
This will make it easier to unify Spark 2 support onto a single branch.

**Comment by laneb** [comment]
This is high priority, because it is required to proceed with unifying Spark 2 support.

**Comment by ninjapapa** [comment]
Will implement on the 2.3 branch.

**Comment by ninjapapa** [comment]
Turn out since Spark 2.0, `last` function takes an optional parameter to support **non-null last**. `FillNullWithPrev` can simply implement as `non-null last over a pre window`. 

Tested on Spark 2.3. Should also work on all 2.*.

So GDO will be totally removed in 2.* branch. Still need to keep in 1.6 branch.

**Comment by ninjapapa** [comment]
done
