### ISSUE TITLE
Remove Scala smv-shell

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1275]
@AliTajeldin In the spirit of transitioning to a Python-only API, I think it's time we remove support for the Scala shell. `smv-shell` should launch the Python shell, `smv-pyshell` should be depcrecated, and if we can't remove it over night then the Scala shell can be renamed `smv-shell-scala` and deprecated.

**Comment by AliTajeldin** [comment]
Yup.
* make `smv-shell` run the python shell.
* make `smv-pyshell` show a deprecation message and then launch `smv-shell`
* move current `smv-shell` to `smv-scala-shell`
