### ISSUE TITLE
hasHeader attribute of schema ignored

### ISSUE THREAD

**Issue by cloudysail** [TresAmigosSD/SMV#1276]
If I define an input CSV file tt.csv like:
```
a,b,1,2.0
c,,3,3.3
```
Then I define the module like below
```
class x1(smv.SmvCsvFile):
    def path(self):
        return "tt.csv"
    def failAtParsingError(self):
        return False
    def userSchema(self):
        return '@quotechar = "; @delimiter = ,; @hasHeader = False; f1: String; f2: String; f3: Integer; f4: Float'
    def isEphemeral(self):
        return True
    def run(self, df):
        return df
```

I suppose since we have `hasHeader = False` in the `userSchema()`, we should output 2 rows, but in fact it output the second row only. Seems SMV treats `hasHeader = True` so that the first row was skipped.

**Comment by laneb** [comment]
I'm not sure if this has anything to do with `hasHeader`, but it's not about `userSchema`. That line gets dropped even when the schema is given in a .schema file and the `userScema` is dropped.

**Comment by laneb** [comment]
The attribute name is `has-header`, not `hasHeader`. If you fix the name, SMV will stop dropping the first row. We should probably warn when an unrecognized attribute is given.

**Comment by laneb** [comment]
Same goes for `quoteChar`, btw. Should be `quote-char`.
