### ISSUE TITLE
Unify Spark 2 support on a single branch

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1283]
- [x] Create candidate branch which is compatible with all Spark 2.1+
- [x] Verify artifact compiled against Spark 2.1.0 compatible with all Spark 2.1+
- [ ] ~Simplify SMV version update process~
- [x] Prepare tooling to test against all Spark 2.1+
- [x] Set up CI to test against all 2.1+ daily
- [ ] ~Set up travis to ping slack when a daily build fails~
- [x] Update documentation
- [x] Rename `new_2` to `2`
- [x] Merge `master` into `2`
- [x] Cut new release for Spark 2 (really Spark 2.1+)

**Comment by laneb** [comment]
When compiled against Spark 2.2.0, the `2.3` branch appears to be compatible with Spark 2.2.0 through Spark 2.3.0. However, the 2.3 branch cannot currently be compiled against Spark 2.1 because of changes to the Spark internal `SortOrder` class between Spark 2.1 and 2.2. This issue will disappear if we remove `SmvGDO` as proposed in #1271. Also, the `2.1` branch cannot currently be compiled against Spark 2.0 due to its use of `DataFrame.crossJoin`, which was added in Spark 2.1. I need to do a little more reading about it, but it appears that Spark 2.0 disallowed implicit cross-joins without providing a method for explicit cross-joins, which were added in Spark 2.1.

**Comment by AliTajeldin** [comment]
WTF, how were people supposed to do cross joins in 2.0 then? 
From the above, does that mean we can at least get away with a single 2.x branch for 2.1-2.3 (assuming no GDO)?

**Comment by laneb** [comment]
I'm inferring from threads like [this](https://stackoverflow.com/questions/42158598/how-to-cross-join-2-dataframe) that 2.0 just didn't support cross joins, whether intentional or not. But not 100 on that.

**Comment by laneb** [comment]
The release script (at a minimum) will need verify that there are no regressions for any supported Spark 2 versions.

**Comment by laneb** [comment]
Fat jars compiled against Spark 2.1.0 aren't compatible with Spark 2.1.1. It looks like a linking issue. The signature of `ScalaUDF` changed between 2.1.0 and 2.1.1, but just to add a parameter with a default value.
```
======================================================================
ERROR: test_smvCountHist (testDataFrameHelper.ShellDfHelperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/laneb/twine/SMV/src/test/python/testDataFrameHelper.py", line 359, in test_smvCountHist
    res = dfhelper(df)._smvCountHist(["k"], 1)
  File "/Users/laneb/twine/SMV/src/main/python/smv/helpers.py", line 1239, in _smvCountHist
    res = self._jDfHelper._smvCountHist(_to_seq(keys), binSize)
  File "/Users/laneb/twine/libs/sparks/spark-2.1.1/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/laneb/twine/libs/sparks/spark-2.1.1/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/Users/laneb/twine/libs/sparks/spark-2.1.1/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o1102._smvCountHist.
: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.ScalaUDF.<init>(Ljava/lang/Object;Lorg/apache/spark/sql/types/DataType;Lscala/collection/Seq;Lscala/collection/Seq;)V
	at org.tresamigos.smv.ColumnHelper.smvCoarseGrain(ColumnHelper.scala:385)
	at org.tresamigos.smv.edd.BinNumericHistogram.<init>(EddTask.scala:173)
	at org.tresamigos.smv.edd.EddHistogram.org$tresamigos$smv$edd$EddHistogram$$createHist(EddTaskGroup.scala:198)
	at org.tresamigos.smv.edd.EddHistogram$$anonfun$11.apply(EddTaskGroup.scala:206)
	at org.tresamigos.smv.edd.EddHistogram$$anonfun$11.apply(EddTaskGroup.scala:204)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.tresamigos.smv.edd.EddHistogram.<init>(EddTaskGroup.scala:204)
	at org.tresamigos.smv.edd.Edd.histogram(Edd.scala:59)
	at org.tresamigos.smv.SmvDFHelper._smvCountHist(SmvDFHelper.scala:1504)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ninjapapa** [comment]
Need to modify the helpers to use 'udf', instead of the internal 'ScalaUDF'.

**Comment by laneb** [comment]
Yeah, that did it. `2.3` branch is now compatible with Spark 2.1+ when compiled against Spark 2.1.0!

**Comment by laneb** [comment]
@AliTajeldin We ought to be proactive in preventing regressions for our supported Spark 2 versions. What do you think is a good balance between coverage and test runtime?

**Comment by AliTajeldin** [comment]
One way we had something like that working in the past is to have multiple sets of test types.
1. Quick tests that are run per checkin or part of continuous  integration.
2. Slow stress tests that test everything. These maybe done on daily/weekly basis depending on how extensive they are.

**Comment by laneb** [comment]
We should be able to run an extensive compatibility test daily. If we're sticking with travis we can use they're "[cron jobs](https://docs.travis-ci.com/user/cron-jobs/)" and add the compatibility tests to a [condition stage](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Stages) which runs daily.

**Comment by laneb** [comment]
Is it acceptable to merge a compatibility-breaking PR if we catch the breakage later that day?

**Comment by laneb** [comment]
@AliTajeldin Any objections to using `make` to orchestrate tests? As it is, using `sbt` to run a shell command to trigger the python unit tests is...icky.

**Comment by AliTajeldin** [comment]
This comment has been there for over a minute.  I'm surprised @ninjapapa has not chimed in yet when you mentioned `make` 😄 
Let's discuss when you are here.  I think it should be fine but let's discuss the details.

And yes to ok to merge compatibility breaking PR.  We need to have a "current" blessed version that is never broken, but have the other versions always close to working (a day away).

**Comment by ninjapapa** [comment]
Somehow my keyword detector missed it!

**Comment by laneb** [comment]
@AliTajeldin What's a good way to label the unified 2 release? We can't just do `2.[smv-release]` because we'd end up with e.g. `2.0` for the first release - Spark 2.0 or Spark 2 SMV release 0? It would also be a little confusing to have a placeholders for the minor and path, like `2.x.y.0`. I think we should transition to naming releases like `[spark-version]r[smv-release]`. The next release for Spark 1.6 would be `1.6r7`. The first release for the unified 2 branch would be `2r0`.

**Comment by AliTajeldin** [comment]
@laneb I like that naming convention.

**Comment by laneb** [comment]
@AliTajeldin What is the problem with the current approach the updating the Spark/SMV version when a release is cut? We discussed replacing all of the references to the SMV version with a token which can be substituted on release, but this won't work e.g. for the `README.md`, which (at least on master) needs to have a valid link to the API docs.

**Comment by AliTajeldin** [comment]
The main issue is if you cut a new release from the branch then the next merge will have conflicts on **all** mentions of version.

**Comment by laneb** [comment]
Here are the places where we have hard references to the SMV release name:
* User doc links to API docs
Replacing these references with tokens would break the referential integrity of [these docs](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/0_user_toc.md) outside of the release. Is that acceptable? External links to our docs can be pointed to the release. The `README.md` currently points here for the user and API docs, but we could have it point to the latest docs or to the documentation index instead.

Tangentially, we weren't very good about keeping [the doc index](http://tresamigossd.github.io/SMV/) up to date.
 
* `smv-install `
There is one reference to the version here, so this would create just one merge conflict for each merge target after the release. However, if need be we could require the version as a parameter to the script.

* `.smv_version`
This file in turn informs `smv-release`, which finds and replaces this previous version with the new version. If we remove all the other hard references to the version, then we won't need this. It also informs the `SmvApp` itself of the SMV version in use. If this is the only place where we need a programatic reference to the SMV version, then we can just declare it directly in the `SmvApp` itself. This is common for ruby gems ;). This would also make it simple to inject the SMV version into the metadata regardless of Spark deploy mode. Regardless, this a reference I don't think we can get rid of. But as before it's just one merge conflict.

**Comment by laneb** [comment]
@AliTajeldin What do you think about breaking the links from the user docs to the API docs?

**Comment by AliTajeldin** [comment]
@laneb Let's discuss when you are here.

**Comment by laneb** [comment]
Ok. I'll create a separate issue for it since it isn't a direct requirement for creating the unified Spark 2 branch. Really a dependency of make the unified Spark 2 branch master.

**Comment by laneb** [comment]
See https://travis-ci.org/TresAmigosSD/SMV/builds/395724442 for a "quick" build. Basically equivalent to the old travis build, but now managed through make. The daily "thorough" build is red today and should be green tomorrow.

**Comment by laneb** [comment]
If you rerun the daily build, Travis checks out the repo at the same commit as the original run. Helpful if you want to confirm that a failures was spurious, but annoying if you want to rerun the thorough tests and confirm that they're fixed. I added an option on the .travis.yaml so you can trigger a build and specify `env: TEST_TYPE=thorough` to force travis to run the thorough tests.

**Comment by laneb** [comment]
I've had another look at that `crossJoin` issue in Spark 2.0. Contrary to what I saw in some threads, it appears you _can_ do implicit cross join in Spark 2.0. According to the [relevant Spark JIRA](https://issues.apache.org/jira/browse/SPARK-17298), the requirement for joins to be explicit was added at the same time as the `crossJoin` method and both were released with Spark 2.1.0. Also it appears you can perform an explicit cross join by using the `join` method with `joinType="cross join"`.

Rewinding, problem for us is that we have to use explicit cross join for the entity matcher and EDD on branches supporting Spark 2.1+, while the `crossJoin` method is not supported for Spark 2.0. We should be able to use the approach above for a cross-compatible explicit cross join. 

As a side note, we could configure Spark to never check for implicit cross, but that's not worth the cost of altering vanilla Spark's behavior for users.

**Comment by laneb** [comment]
I was trying to compare the `2.3` branch to the `2` branch but I can't find `2` in my local repo or on github...did we delete it at some point?

**Comment by AliTajeldin** [comment]
I don't think we ever had a "2" branch.  we had a "2.1" and "2.2"

**Comment by laneb** [comment]
I could've sworn we use to have a 2 branch. Which branch were the 2.0
releases cut from?

**Comment by cloudysail** [comment]
Before I did the initial 2.2 release on early Feb, I remembered we only had 2.1 for 2.x. And I asked why we did not build 2.0 and the answer was 2.0 has too many bugs and no one is using it.

**Comment by laneb** [comment]
Actually, I guess we never cut a release for 2.0. We don't have any tags for it.

**Comment by laneb** [comment]
In Spark 2.0.2:
```
>>> l = app.createDF("k:String;v:String", "1,a;2,b")
>>> r = app.createDF("k_:String;v_:String", "1,a;2,b")
>>> l.join(r)
DataFrame[k: string, v: string, k_: string, v_: string]
>>> l.join(r).show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/laneb/twine/libs/sparks/spark-2.0.2/python/pyspark/sql/dataframe.py", line 287, in show
    print(self._jdf.showString(n, truncate))
  File "/Users/laneb/twine/libs/sparks/spark-2.0.2/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/Users/laneb/twine/libs/sparks/spark-2.0.2/python/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: u'Cartesian joins could be prohibitively expensive and are disabled by default. To explicitly enable them, please set spark.sql.crossJoin.enabled = true;'
>>> l.registerTempTable("l")
>>> r.registerTempTable("r")
>>> sqlContext.sql("select * from l cross join r").show()
>>> sqlContext.sql("select * from l cross join r").show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/laneb/twine/libs/sparks/spark-2.0.2/python/pyspark/sql/dataframe.py", line 287, in show
    print(self._jdf.showString(n, truncate))
  File "/Users/laneb/twine/libs/sparks/spark-2.0.2/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/Users/laneb/twine/libs/sparks/spark-2.0.2/python/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: u'Cartesian joins could be prohibitively expensive and are disabled by default. To explicitly enable them, please set spark.sql.crossJoin.enabled = true;'
```
so `l cross join r` isn't explicit enough 🙄

**Comment by laneb** [comment]
The above also illustrates that implicit cross joins are illegal in Spark 2.0, so maybe I'm misunderstanding the details on the JIRA I posted earlier. Also the `joinType = "cross join"` idea was a red herring, it's not actually a supported join type. Since we only do a cross join in a couple of specific places, we may be able to temporarily turn off the cross join check specifically in those cases. Otherwise, we should create a 2.0 support branch which at least works when cross joins are enabled.

**Comment by laneb** [comment]
Since we may not need to support the 1.6 branch for much longer anyway, we will postpone any work on changing the SMV version update process.

**Comment by laneb** [comment]
We'll leave the notifications as is until we move to a more flexible CI.

**Comment by laneb** [comment]
I'll cut a Spark 2 release tomorrow :)

**Comment by laneb** [comment]
🎉 https://github.com/TresAmigosSD/SMV/releases/tag/v2r0
