### ISSUE TITLE
Remove SmvGit

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1284]

**Comment by tianruiwang** [comment]
Just want to make sure if I understand this correctly... Right now the `SmvGit` provides only one method called `addFile()`. And such method has an interface defined in `SmvPyClient`, which is then propagated to the `smvserver` as another interface.

So the content of this ticket is to remove the class `SmvGit` as well as the above two interfaces, am I correct?

**Comment by laneb** [comment]
Correct. SMV should not be aware of git.

**Comment by laneb** [comment]
It will be enough to remove it on master. All other branches are downstream from master.
