### ISSUE TITLE
Investigate future of support of ds ascii graph

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1291]
It's tests are currently disabled and @ninjapapa mentioned that the library that the feature depends may have been removed in Scala 2.11. Should restore support if the cost is low. Otherwise remove it entirely.

**Comment by AliTajeldin** [comment]
Let's just remove it.  There are better ways to see the dependency graph 😄

**Comment by laneb** [comment]
Okay ☹️I'll miss the ascii graph. I had fun with it on my last project.

**Comment by ninjapapa** [comment]
That was my biggest contribution to SMV :-)
