### ISSUE TITLE
Fix bad search and replace in `smv-release`

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1293]
When updating the SMV version, `smv-release` does
```
  # update version in user docs.
  find docs/user -name '*.md' \
    -exec perl -pi -e "s/${PREV_SMV_VERSION}/${SMV_VERSION}/g" \{\} +
```
neglecting the fact that `.` is a wildcard. The result is a lot of bad replacements, like
```
-    "java.lang.NumberFormatException: For input string: \"001x\" @RECORD: 123,001x  ,20130109130619,12102012"
+    "java.lang.NumberFormatException: For input string: \"001x\" @RECORD: 123,001x  ,2.2.0.09130619,12102012"
```
Need to fix all of the bad replacements (see #1272 for some examples) and as well as fix the bug.

**Comment by laneb** [comment]
@AliTajeldin this is a fun one 😆

**Comment by AliTajeldin** [comment]
@laneb your idea of fun and mine are apparently different 😄
