### ISSUE TITLE
support creating big tree structure project in smv-init

### ISSUE THREAD

**Issue by cloudysail** [TresAmigosSD/SMV#1297]
- improve the `smv-init` script to support `-bigTree ` option to create a typical big tree structure project for the stress test
- rename the current `-big` option to `-bigChain` option which still create a long chain list project
- allow parametrize the module number so that we can generate different size of trees/chains.

**Comment by laneb** [comment]
Do we have a profile of typical project structures? I'm curious what the average tree looks like.

**Comment by cloudysail** [comment]
This is just for the stress test. So something like a balanced binary tree should be fine.

**Comment by laneb** [comment]
Is a balanced binary tree a more representative example than the "big" project that exists today? They both have n-1 edges. IIRC, the performance of `ls` is influenced more directly by edge count than by node count.

**Comment by AliTajeldin** [comment]
We are not stress testing the algorithm complexity here but rather the user experience with large projects.  A more bushy/balanced tree is better representation.

**Comment by laneb** [comment]
Got it.

**Comment by cloudysail** [comment]
Looks good.

Some minor issues could be addressed here:
- we have `-b` for both `blank` and `big` mode in code. Maybe we should just allow `-bigChain` or `bigTree`.
```
    -b|--blank)
        PROJ_TYPE="blank"
        shift
        ;;
    -b|-big)
        PROJ_TYPE="big"
        shift
        ;;
```

- In the USAGE, we should add `-bigxxx` option. Also the `data directory` option show `-dd` and `-d` which is inconsistent.
```
USAGE: ./tools/smv-init [-q][-o] [-s|-e|-t|-b] [-dd] [-n]  project_path
project types:
  -s: simple (default)
  -e: enterprise
  -t: test (for developers only)
  -b: blank/empty project
  -d: data directory
  -n: project name
  -g: initializes git repo in project directory

```

**Comment by lidaqing** [comment]
use `-b` for `blank`, `-bc` for `bigChain`, `-bt` for `bigTree`?

**Comment by lidaqing** [comment]
Create a tree project like:
![screen shot 2018-06-21 at 9 45 43 am](https://user-images.githubusercontent.com/9389241/41694919-3b960e18-753f-11e8-97f0-6afee170e19a.png)

**Comment by lidaqing** [comment]
done
