### ISSUE TITLE
externalize the smv test framework

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#130]
Every app must create its own test framework at the moment (usually by copying SparkTestUtil function from SMV.  We should make that class external (and all support functions/classes).  This will add a dependency on ScalaTest in the generated SMV jar but that is far less harmful than copy-n-paste of the test util classes.

**Comment by Kai-Chen** [comment]
We've added `publishArtifact in Test := true` in build.sbt so that on publishing, the test jar is also published locally, and the dependent projects can declare that as a test dependency.  This seems to be the best option so far, except that it works only with SBT.

**Comment by AliTajeldin** [comment]
Done using `smv-pytest` for python and `test.jar` for scala projects (we only need to work with SBT)
