### ISSUE TITLE
SMV support for Spark 1.6.3

### ISSUE THREAD

**Issue by jagatsingh** [TresAmigosSD/SMV#1300]
@laneb  @jacobdr Can you please make a new release for SMV to support Spark 1.6.3.

**Comment by laneb** [comment]
Hi @jagatsingh! Release [v1.6.2.6](https://github.com/TresAmigosSD/SMV/releases/tag/v1.6.2.6) should be compatible with Spark 1.6.3. Have you run into issues with it?

**Comment by jagatsingh** [comment]
@laneb You are right it should work for other functions.

We are interested in this patch https://issues.apache.org/jira/browse/SPARK-16078

This is in 1.6.3 and not in 1.6.2

**Comment by cloudysail** [comment]
@jagatsingh The SMV [v1.6.2.6](https://github.com/TresAmigosSD/SMV/releases/tag/v1.6.2.6) can work on Spark 1.6.3.

By the way, regarding those timestamp issues, we have found Spark(even the latest version) lacks certain key functions to handle the timezone and timestamp. So we have recently added a new function [smvTimestampToStr](http://tresamigossd.github.io/SMV/pythondocs/1.5.2.20/smv.html?highlight=time#smv.helpers.ColumnHelper.smvTimestampToStr) in SMV.  Hope it could help.

**Comment by laneb** [comment]
@jagatsingh Did this answer your question?
