### ISSUE TITLE
Bring back SMV base Docker image for building release

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1308]
Currently we have a bit of a convoluted approach to using Docker to standardize the environment for the release build. The short of it is that we build a docker image based on the old release to use when building the new release. This leads to complications. Instead we should create a base image with all of SMV's dependencies to use when building the new release artifact. The SMV image which we publish will be based on this image and will install SMV by unpacking the release artifact which we've just published.

**Comment by laneb** [comment]
This should fix #1307 since the requirements installed will no longer be the requirements of the previous release. We should confirm and close this ticket.

**Comment by laneb** [comment]
We will use a multi-stage build to accomplish the base image / publishable image approach. The base image will build the release artifact, and the publishable image will unpack it. This will help ensure that

1. the published image is as skinny as possible
2. the contents of the published image are the same as the published artifact (this has been a recurring problem)

this will also simplify the surrounding tooling.

**Comment by AliTajeldin** [comment]
Sounds good 👍
