### ISSUE TITLE
Generated EDD output should go along with csv/schema

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#132]
We now accept an edd output dir (named "outdir"?) that will direct the edd output to the local dir.  The edd output should go along with the CSV/Schema files so that they would be properly versioned as well (both at module and stage version levels).

**Comment by Kai-Chen** [comment]
A small refactor proposal regarding data directory management:

Move SmvModule#fullPath into SmvApp and make it public or package private.

Currently a private method SmvModule#fullPath(SmvApp) returns the output path.  This method is probably better placed in SmvApp, which provides a central place for managing different output directories as well as naming output files.

When run_module.sh turns on the output-edd flag, SmvApp will add a step to write the EDD results to the same output directory, using Edd#saveReport.

**Comment by AliTajeldin** [comment]
sounds good.
