### ISSUE TITLE
Fix SMV API document

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#1322]
Currently SMV API document is not working at here: http://tresamigossd.github.io/SMV/pythondocs/2r1/smv.html#smv-functions-module

<img width="550" alt="screen shot 2018-08-09 at 16 21 50" src="https://user-images.githubusercontent.com/19701233/43887139-787b0cca-9bf0-11e8-8f25-38920a80e5af.png">

If I am using the wrong link, please also kindly help update the user guide link in the homepage.

**Comment by AliTajeldin** [comment]
That's the right link

**Comment by ninjapapa** [comment]
Fixed by rerun `./admin/publish_docs.sh 2r1 2r1`. Not sure what caused the original issue.
