### ISSUE TITLE
Support to discover timestamp type in smvDiscoverSchemaToFile function

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#1323]
Current `smvDiscoverSchemaToFile` does not support to discover timestamp type. If data value is `2018-01-01 10:22:14.0`, the discovered type is Date[yyyy-MM-dd] since 
`case null if canConvertToDate(valueStr, "yyyy-MM-dd")  => DateTypeFormat("yyyy-MM-dd")` can pass.

Need to figure out a way to discover timestamp type.

**Comment by ninjapapa** [comment]
@yw-yang are you working on this? Otherwise I'd like to take this.
