### ISSUE TITLE
Need a smvDupeCheck helper

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1325]
I keep doing the following code in Notebook for many times per day:
```
d3p = d3.limit(10000).cache()

d3p.groupBy('NPI').agg(F.count('NPI').alias('_N')).where(F.col('_N')>1).join(d3p, ['NPI']).orderBy('NPI').limit(20).toPandas()
```

Basically it print out some examples of records in the data where the "key", "NPI" is not unique.

**Comment by ninjapapa** [comment]
## Design

Client code:
```python
myDf.smvDupeCheck(['k1', 'k2']).limit(20).show()
```
or
```python
myDf.smvDupeCheck(['k1', 'k2'], 100000).limit(20).show()
```

Default check first 10k records. Output the records with keys, `_N`, and all other columns, order by keys.

**Comment by AliTajeldin** [comment]
@ninjapapa looks good.  Quite handy
