### ISSUE TITLE
Extend smvJoinByKey api to handle null-safe join

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1327]
Current `join` or `smvJoinByKey` will drop records with null value keys. See:
https://stackoverflow.com/questions/41728762/including-null-values-in-an-apache-spark-join

It is the correct SQL behavior. However it will be convenience if we can have a null-safe join helper, so user don't need to worry about how to handle potential null-value keys. 

## Design

Extend `smvJoinByKey` API with an optional parameter `isNullSafe` with default `false`. 

Client code
```python
df1.smvJoinByKey(df2, ['k1', 'k2'], 'inner', true)
```

**Comment by ninjapapa** [comment]
@laneb Do you remember have we ever used the `broadcastOther` parameter in the client project?
I know it is used internally by `smvSkewJoinByKey`.

Current `smvJoinByKey` Scala interface is the following:
```
  def smvJoinByKey(
      otherPlan: DataFrame,
      keys: Seq[String],
      joinType: String,
      postfix: String = null,
      dropRightKey: Boolean = true,
      broadcastOther: Boolean = false
  ): DataFrame
```

Since I python side only support the first 3 parameters, and I don't recall any client project is really using Scala interface. If so I will make current `smvJoinByKey` an private function, and make the Scala interface the same as the Python interface.

**Comment by laneb** [comment]
@ninjapapa No I'm pretty sure that `broadcastOther` was only used internally.
