### ISSUE TITLE
SequelizeEntity.get impl should raise a clearer error when entity not found in DB

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1336]
Currently, when the entity doesn't exist, a error is raised about `null` not having an attribute `toJSON`. This is because we don't check whether the sequelize actually found the entity before we try to jsonify it. When the RPC occurs over cable, the stacktrace is lost when the cable sends the error back to the UI, complicating debug.

**Comment by AliTajeldin** [comment]
Both issues should be resolved (bad error and sending the error back over RPC).
