### ISSUE TITLE
add command line option to discover dead modules.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#137]
Once stages are fully implemented (issue #126), we will be able to determine if any `SmvModule` in any of the packages of a stage is actually being used to affect one of the output modules of the same stage.  If a module is not in any of the dependency graph of any of the output modules, then it is a dead module.

Add a command line flag (e.g. "--dead") that will dump the list of all such dead modules.

**Comment by laneb** [comment]
Still needed?

**Comment by AliTajeldin** [comment]
yes

**Comment by laneb** [comment]
Done.
