### ISSUE TITLE
Make SmvModuleLink a pure pass through

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1377]
In PR #1369, read back versioned data through the SmvModuleLink mechanism we are removed. So other than links still show in the list or graph when print/plot the modules, they are just pass the target module down. 

Since all the client project I know use the SmvModuleLink in the following way:
```python
M2 = SmvModuleLink(M1)
```

We can just replay the `SmvModuleLink` class by an identity function. 

There will be no behavior change of any projects already delivered, except when use try to list out modules in shell. 

@jacobdr @yw-yang @laneb could you confirm the client-T code only use `SmvModuleLink` in above way?

**Comment by ninjapapa** [comment]
Did a search on client-T's project,

- Project delivered with the version of SMV source code as part of it, so no need to worry future version of SMV will break it
- All the `SmvModuleLink` used as `M2 = SmvModuleLink(M1`

So will move forward on this.

**Comment by laneb** [comment]
Yeah that's correct.
