### ISSUE TITLE
Fix _smvGetRunConfigHash in SmvDataSet

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1389]
Search `_smvGetRunConfigHash` in code will find that it was used in `SmvDataSet` without definition. Since it was in try-catch logic, the hash logic to handle `SmvRunConfig` mix-in case was simply ignored.

Instead of implementing that method, here is a better way to address it:
* Define a concrete `requiresConfig` with all the possible run conf keys in `SmvRunConfig` mix in
* Remove all the other methods in `SmvRunConfig`
* Remove `_smvGetRunConfigHash` part of the hash calculation totally, since `config_hash` part already covers all the possible run configs which could be used
* Document in user doc that `SmvRunConfig` mix-in will be deprecated, and it is simply added a requires-all `requiresConfig` method, which may cause unnecessary module recalculations

**Comment by laneb** [comment]
`SmvRunConfig` has been documented as deprecated for 4 months. I think it's fine to remove it now.

**Comment by ninjapapa** [comment]
Will remove from document. But still keep in the code for now, just in case client-G want us to upgrade their SMV.
