### ISSUE TITLE
dynamic config should stick when runModule without runConfig

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#1400]
Expected behavior:

```
smvApp.setDynamicRunConfig({"foo": True})
smvApp.runModule(fqn="bar")
```

modules run with `"foo": True` in the config.

Reality:

`runModule` resets the `runConfig` to empty.

**Comment by ninjapapa** [comment]
I'm almost about to create the same ticket!

**Comment by ninjapapa** [comment]
Will deprecate  `runModule` interface with dynamic run config as a parameter. Instead always call `setDynamicRunConfig` explicitly.
