### ISSUE TITLE
strange errors when running integration tests

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#1457]
When I run the integration tests through tox (via the makefile), I get the following error:

```
--------- BUILD INTEGRATION APP -------------
mkdir: cannot create directory ‘/.sbt’: Permission denied
rsync: mkdir "/.sbt/preloaded" failed: No such file or directory (2)
```

My hypothesis is that the call to `sbt clean assembly` (from inside tox) is being run without the $HOME variable being passed through (since tox seems to clean all env variables). 

Therefore SBTs default behavior of playing games in `$HOME/.sbt` is getting messed up...

**Comment by ninjapapa** [comment]
Actually we don't need to "build" when doing integration test any more. Should remove the step which call sbt.
