### ISSUE TITLE
Optimize runner visitor

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1466]
Current run method of `SmvModuleRunner` creates a linearized sub-tree from the roots it was given, then run `get_data` (used called `rdd`) methods of each module on in that queue as in depth first order. So in the following case:
```
A <- B <- C
```
The running order is A, B, and, C.

Assume A is input (so ephemeral), B and C are non-ephemeral, and the following events happened in sequence:
* `df("C")`
* removed B's persisted file
* `df("C")`

For the 2nd time of run C, B still need to be run within current implementation. Since C was persisted, the correct behavior should be just return the persisted C without even bothering checking A and B.

**Comment by ninjapapa** [comment]
Another issue of current runner:

Call `get_data` and `persist_meta` are two different visits (actually more then 2), it will happen much more often that when a long running job get killed, there will have modules which have valid persisted data, but no persisted metadata.

Need to fix is by bring the `persist_meta` call in the same visit to the `get_data` for all the non-ephemeral modules. For ephemeral modules, it is not a problem, since anyhow there are no data persisted.

**Comment by AliTajeldin** [comment]
Let's have a whiteboard discussion on this.  I don't want us to go back to the complex state machine we had before.  Let's see if we can still keep linear traversal with a single state.

**Comment by ninjapapa** [comment]
Since the first issue has less impact, will create PR to address it specifically and will create a separate issue for the 2nd.
