### ISSUE TITLE
Path does not exist after renaming hive table

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#1488]
I encountered an issue when reading hive input:
1. I create a hive table A
2. Rename hive table A to B in hive - "alter table A rename to B"
3. Create a smv hive input module and table name is B
4. Create a smv module and input is the hive input module in step3
5. Run this smv module and error "Path does not exist: hdfs:///user/hive/warehouse/db/A"

I checked create statement of table B and found SERDEPROPERTIES still points to A and LOCATION points to B.
```
CREATE TABLE `B`(
PARTITIONED BY (
  `partition_date` date)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
WITH SERDEPROPERTIES (
  'path'='hdfs:///user/hive/warehouse/db/A')
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  'hdfs:///user/hive/warehouse/db/B'
```

After I reset SERDEPROPERTIES path value, issue has been solved.
`ALTER TABLE table_name SET SERDEPROPERTIES ('path' = 'hdfs:///user/hive/warehouse/db/B');`

Any ideas why it happens? Hive version - 1.1.0-cdh5.12.2.

**Comment by guangningyu** [comment]
It seems like a Hive issue.

**Comment by jacobdr** [comment]
Definitely a bit confusing and Hive version dependent.

https://issues.apache.org/jira/plugins/servlet/mobile#issue/HIVE-14909

https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-RenameTable

**Comment by yw-yang** [comment]
Yes, it's a spark/hive issue. I did some tests again and found this issue only happens when hive table is created by spark. Close now as not related to smv.
1. Create a hive table in spark
``` 
df.write.saveAsTable("test")
```
2. Alter table name in hive
```
alter table test rename to test_2;
```
3. Query new table in spark, "path doesn't exist" error pops out.
```
spark.sql("select * from test_2")
```
