### ISSUE TITLE
use DataFrame reader/writer once we switch to 1.4

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#153]
We currently implement our own writeCSV/readFromCSV.  We should move to use the standard reader/writer introduced in 1.4.  It makes things like CSV Attributes much cleaner to implement.

**Comment by laneb** [comment]
Still needed?

**Comment by AliTajeldin** [comment]
We need to investigate use of the spark csv package (especially with respect to the speed as some csv parser are very slow.  Almost an order of magnitude slower).

**Comment by laneb** [comment]
Based on conversation with @AliTajeldin, we will not fix this unless the current CSV reader/writer becomes a problem.
