### ISSUE TITLE
Support config files in a folder

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1579]
Currently we supports 4 type of configurations other than the default values:

Priority: Low to High
 - default
 - conf/smv-app-conf.props
 - ${HOME}/.smv/smv-user-conf.props
 - conf/smv-user-conf.props
 - command-line

As adding the connection concept, to avoid making existing config files too complicated, we will support config files in folders. A structure this issue should support is:

- conf
   - smv-app-conf.props
   - smv-user-conf.props
   - connections
         - all_hdfs_conns.props
         - all_hive_conns.props

And all config files in folders are at the same priority level as `smv-app-conf.pros`.

**Comment by ninjapapa** [comment]
@AliTajeldin please review the plan.

**Comment by AliTajeldin** [comment]
Do we need a folder hierarchy?  How about hard code the file name such as `connections.props`.  A single project will probably not have too many connections.  We can read/write them all at once anytime once changes.
