### ISSUE TITLE
use the smv app/user conf files as spark config files

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#158]
We would like to set some spark configuration parameters at the app and user level.  However, spark only supports a single configuration file (default to SPARK_HOME/conf/spark-defaults.conf).
It is also a pain for the user to maintain two sets of configs (spark and smv).  This issue suggests that we combine the smv app/user config files into a temporary file and use that as the spark config file.  This needs to be done in both run_app and run_shell.

**Comment by AliTajeldin** [comment]
Note: we need to remove the code base setting of "spark.sql" config parameters in SmvApp

**Comment by laneb** [comment]
@AliTajeldin Is this still needed?
