### ISSUE TITLE
Shell resolve DS issue: Cycle Error

### ISSUE THREAD

**Issue by eagle123** [TresAmigosSD/SMV#161]
When running the shell and failing to resolve a given DS due to some exception, trying to resolve the same DS again lead to the following error: "cycle found while resolving DS".
According to Ali, this is due to the fact we did not pop DS name from the stack of the DSs to resolve when the exception happen during the first attempt to resolve the DS, trying the resolve the same DS again will lead to cycle found error. A potential fix is the add try/catch around the resolve implementation and pop the DS from the stack if an exception took place.

**Comment by ninjapapa** [comment]
fixed
