### ISSUE TITLE
verify that a module in RequireDS is a module in the same stage

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#167]
Need to add a verification step that ensures that a dependent module resides in the same stage or is either an SmvFile or SmvModuleOutputFile.

**Comment by AliTajeldin** [comment]
TBD: should we apply the same rule to SmvFile?

**Comment by ninjapapa** [comment]
Check this at run time is easy. Is there a way to check this on compile time?

**Comment by Kai-Chen** [comment]
I can look into how to do this with a macro.  Conceptually it should be pretty straight-forward.  But the macro implementation is different from Scala 2.10 to 2.11.  So we might want to switch to 2.11 first before tackling this to avoid unnecessary work.

**Comment by laneb** [comment]
This is now checked at runtime when modules are loaded, and I think the integration with Python won't allow for any sort of compile time check - plus we no longer compile pure Python projects.
