### ISSUE TITLE
Define SmvStageInputSet

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#168]
This is just a marker triat/ABC for now. It add no functionality other than to mark the object being utilized as the input set for a given stage.  Example:

```scala
object Stage1InputSet extends SmvStageInputSet {
  val f1 = SmvFile("input/f1.csv")
  ...
}
```

We can utilize the above in the future to do inter stage file dependency checks or discover of all input files in a stage, etc.

**Comment by ninjapapa** [comment]
Does this duplicate #148 ?

**Comment by AliTajeldin** [comment]
yes it is a duplicate.  Closing this.
