### ISSUE TITLE
allow user to specify spark home in run_app.sh and run_shell.sh

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#171]
By default the script use the spark-submit and spark-shell that is in the path.
Should allow user to override the spark home dir.  For example:

``` bash
$ run_app.sh --spark-home /tmp/spark-1.1 --output-dir output/1.1 -s stage1
```

**Comment by laneb** [comment]
Is something like this still needed?

**Comment by AliTajeldin** [comment]
The intent was for developers who might have multiple versions of spark around.  For example, I was just testing the 2.1 branch and I would have to run `smv-pyrun` from either the `master` or `2.1` branch (I cloned the 2.1 into another directory rather then `git checkout`).

I'm not sure if the explicit flag is still needed.  But we do need to confirm that if the user runs `smv-pyrun` from anther SMV directory other than the one in the path, it runs everything from that new directory (jar files, executables, etc).

**Comment by laneb** [comment]
Having the `--spark-home` option will be helpful when developing features across multiple Spark versions. Will add. Can confirm the second point described.

**Comment by laneb** [comment]
Done.
