### ISSUE TITLE
Add SmvFileHandler parameter to SmvFile.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#175]
# Problem
We need to associate some ETL/DQM rules with a given input file.  The current method is to create a module that depends on the raw `SmvFile` and do the ETL/checking in that module.  All other modules would then depend on the file ETL module rather than the raw `SmvFile`.  However, there is no way to enforce that at the moment.

# Proposed Solution
The proposal here is to create a `SmvFileHandler` base class that can be supplied as an optional argument to the SmvFile class.  The concrete `SmvFileHandler` instance would then be responsible for performing the ETL/DQM checks and reporting any errors using the soon to be provided reject logger interface.

# Example

```scala
// Note: input set is defined at the stage package level
package com.mycompany.stage1

object stage1InputSet extends SmvInputSet {
  // regular csv file as before without a special handler.
  val file_a = SmvCsvFile("/tmp/a.csv")
  // csv file with a special ETL/DQM handler.
  val file_b = SmvCsvFile("/tmp/b.csv", dqm.bHandler)
}
```

```scala
// Note: file handlers are defined at the stage/dqm package level
package com.mycompany.stage1.dqm

object bHandler extends SmvFileHandler {
  override def run(input: DataFrame) = {
    // add the age column as part of the file ETL process.
    input.selectPlus( today - $"birthday" as 'age)
  }

  override def dqmRules() = {
    SmvDQMRules().
      addRule($"age" < 150).
      addFix($"income > 100000, lit(100000) as 'income)
  }

  override def validate(dqmResult: SmvDQMResult, file: SmvFile) = {
    // if any records violated the rule, they would have been rejected already and we never get here. 
    // only need to check against the dqm results here.

    // fail validation of 
    if ( dqmResult.fixCount("age") > 0.20 * dqmResult.recordCount ) {
      file.rejectDataSet(file.name, "too many age fields needed to be fixed!")
    }
  }
}
```

# Implementation details
## Notes
* When a module downstream depends on an `SmvFile` that defines a handler, the rdd associated with the `SmvFile` would be the result of the `run()` method plus any DQM fixes defined in the `dqmRules()` method.
* We need to pass in the `SmvFile` parent class to the handler as that has the per file logger / state.
* The `rejectDataSet()` / `rejectRecord()` methods need to be on the `SmvDataSet` class so that we can have the context in the error message.
* The concrete `SmvFileHandler` instance can be shared by multiple SmvFile instances.  But for that to work, the concrete `SmvFileHandler` instances should not maintain any volatile state (no vars!!!)
* Best practice is to collect all the file ETL/DQM modules into a single dqm subpackage of the stage package.
* Applying the DQM rules will cause a forced action to be performed on the DAG up to this point (which should just be reading the file and applying the run method).
* all three methods of `SmvFileHandler` should have a reasonable default.
  * default `run()` should be just a passthrough.
  * default `dqmRules()` should just return an `EmptyDQMRules` which basically do a pass through when they are applied to a `DataFrame`
  * default `validate` should be a no-op.

## Persistence
Because the calculation of DQM and validation rules can be expensive, the result of the DQM can be persisted in the same manner as we currently do with `SmvModule` instances.  That is, the hash of the file (perhaps name and creation time) can be used to create a persisted instance of the file.  Once DQM and validation is performed once, subsequent runs will use the persisted instance of the file rather than recompute the ETL/DQM/validation.  If the file is modified (name or creating time), then the calculation is repeated.

Perhaps we can add the same idea of `isEphemeral` to the `SmvFileHandler` base with a TBD default (true if we don't persist by default, or false if we want to persist by default).

## Default Handler
Rather than create a special case inside `SmvFile` for with/with-out handler, we should just create a default handler that is a passthrough.  It is pretty much the base `SmvFileHandler` with the default methods described above (but no persist)

**Comment by ninjapapa** [comment]
As we making input files as `SmvFile` objects, #177, we can drop the `SmvFileHandler` concept and make most of the DQM functions as part of the `SmvDataSet`, so both `SmvFile` and `SmvModule` can share the same DQM structure.

**Comment by ninjapapa** [comment]
Based on the dqm design doc:
https://github.com/TresAmigosSD/SMV/tree/master/docs/design/SmvDQM

we dropped the `SmvFileHandler` concept.
