### ISSUE TITLE
update DQM interface

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#176]
The current DQM interface bind the DQM rules directly to the `DataFrame`.  This issue proposes that we separate out the creation of the DQM rules from applying the rules.

## Creating Rules

```scala
val rules = SmvDQM().
    add(Rule($"age" < 150), FailAny, "ageLT150").
    add(BoundRule($"age", 1, 150), FailCount(10)).
    add(Fix( $"age" > 150, lit(150) as 'age), "ageFix150").
    add(BoundFix($"age", 1, 150), "ageFix1-150").
    ...
```

The `SmvDQM` is a builder which takes `add` method with 3 signatures
* `add(rule: DQMRule, rulePolicy: DQMRulePolicy = FailNone, name: String = null)`
* `add(fix: DQMFix, name: String = null)`
* `add(policy: DQMPolicy, name: String = null)`

A `DQMRule` is applied on records. If any record violates the Rule, the entire record will be rejected. A `DQMFix` is applied to a cell of a record and fix the cell while keep the record. A `DQMPolicy` is applied on the entire DF with the DQMResult (see below).

A `DQMRulePolicy` is a `DQMPolicy` which only depends on the specific Rule's result. It has 4 case class/objects:
* `FailNone` - policy check never fails even if some records are rejected
* `FailAny` - policy check fails if any record get rejected by the CheckRule
* `FailCount(n)` - policy check fails if more than n records get rejected by the CheckRule
* `FailPercent(r)` - policy check fails is more than r percent records get rejected by the CheckRule. The percentage `r` is a float between 0 and 1. 

For now we only implement 2 case classes
* `TotalFailCountPolicy(n)`
* `TotalFailPercentPolicy(r)`

Which will combine all the rule rejected counts and check the policies. For example, if in total there are 2 rules defined, one for checking the `age` field and the other checking `amt` field, we can defined a `TotalFailCountPolicy(1000)`. The `DF` will fail the policy if add up together there are more than 1000 records get rejected by the 2 rules.

We can extend DQMRule and DQMFix for specific common cases to make the code clearer.  See example below. Note: only the rules are shown below, there would be an equivalent "Fix" method that takes a default value.
```scala
val rules = SmvDQM().
    add(FormatRule($"age", """^[A-Z]""".r)).
    add(SetRule($"gender", Seq("M", "F"))).
    ...
```

## User defined Rules, Fixes and Policies

A Rule can be defined with a `Column` which returns a BooleanType. So user can extends `DQMRule` to define new rules. For example,
```scala
case class DoubleOpenBoundRule(c: Column, upper: Double, lower: Double) 
  extends DQMRule(c < lit(upper) && c > lit(lower))
```

User defined `DQMFix` interface
```scala
case class SetFix(c: Column, validVals: Seq[String], default: String) 
  extends DQMFix(! c.in(validVals.map{s => lit(s)}: _*), lit(default))
```

User defined `DQMPolicy` interface
```scala
DQMPolicy((DataFrame, DQMLogger) => Boolean)
```

## Applying the DQM
Once the DQM (set of rules, fixes, policies) have been created, they can be applied to a `DataFrame`.  As a matter of fact, the same set of rules can be applied to multiple `DataFrame`s.

However, since we want to avoid introducing an extra *Action* to the `DataFrame` just for DQM, internally we will split the applying DQM to 2 steps:
* attachDQM, and
* checkDQMPolicy

where the first step will simply apply the Rules and Fixes to the DF as projections and filters (*Transformations*, instead of *Actions*).

After that user could trigger an *Action*, within SmvApp framework it will be the persist step of a SmvModule which depends on the DF. After the action, `checkDQMPolicy` should be called, which will collect the results from the Rules and Fixes and also potentially apply checks agains any operation on the output DF.

In between of the `attachDQM` and `checkDQMPolicy` methods, a `DQMLogger` objects will be used to pass the results.

### `DQMLogger`
The following counters and logger are needed to store the DQM results
* recordCounter
* fixCounter
* rejectCounter
* rejectLog

All of them are accumulators. Counters are accumulators on Map, and Loggers are accumulator on List[String].

### `attachDQM` (private[smv])
```scala
val resDf = df.applyDQM(dqm, dqmLogger)
```
Applying the DQM is a transformation on the df will not force an action.  The results of the DQM will be stored in the `dqmLogger`. 

### `checkDQMPolicie` (private[smv])
DQM rule and fix results, which stored in the `DQMLogger`, will be checked when action happened on a `DataFrame`.
```scala
val dqmRes = df.checkPolicy(dqm, dqmLogger)
```
Depending on the policies, a `checkPolicy` method could be a transformation or an action. 
By splitting `applyDQM` and `checkPolicy`, we don't need to force an action just for DQM check. Instead, we can wait for a downstream action and then call the `checkPolicy`. In case that policies in the DQM are all based on the results in the `dqmLogger` we can save an unnecessary action.

### `applyDQM`
We will provide a single method, `applyDQM`, to users with combining the `attachDQM` and `checkDQMPolicy` methods. In this method, we will force an action (could be a `count`) in between of those 2 methods. 

### DQMResult
The returned `DQMResult` object will have the following attributes:
* `passed: Boolean` - whether the DQM is passed
* `errorMessages: Seq[(String, String)]` - list of policy name - error message pair on failed policies

----
**Note:** this is similar to what was proposed in issue #48 but using the suffix instead of the bind/check prefix.

**Comment by AliTajeldin** [comment]
Looks real good.  I really like the new DQM Interface as it allows for easy addition of future rules/fixes.
A couple of comments / questions:
* Define the unit of FailPercent method.  Is it float 0<r<1 or a float in range 0<r<100?
* What is the purpose of the TotalX policy case classes (e.g. TotalFailPercent).  How are they different from the base policy class (e.g. FailPercent)?
* Add the word Policy to end of the Policy instances (e.g. FailPercentPolicy)
* What is the difference between checkPolicy and applyDQM?  Does checkPolicy apply DQM as well (seems redundant then)?  If not, shouldn't checkPolicy then take the DQMResult as a parameter?  Not sure when to use which.  Perhaps a quick whiteboard discussion is needed here.
* Need to define the DQMPolicy interface here.  We may not need to implement the generic policy but it might help us ensure that we have the correct end-to-end interface.
* I'm not sure about the errorMessages interface in DQMResult.  While it is great for reporting, it may not be very useful when used with a generic DQMPolicy.  May need to separate that out into an interface point for each named rule.
* Need to add a check that no two policies defined in a DQMRules are of the same name.

**Comment by ninjapapa** [comment]
Captured in the design doc
https://github.com/TresAmigosSD/SMV/tree/master/docs/design/SmvDQM

**Comment by ninjapapa** [comment]
implemented. Still need to do:
* Inline document
* Some build-in rules and fixes
* Simplify RejectLogger
* Report number of records from dqm instead of pipeCount

**Comment by ninjapapa** [comment]
done
