### ISSUE TITLE
add soundex and metaphone UDF.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#18]
The soundex and metaphone algorithms are available in apache commons library.  We just need to create a Spark UDF wrapper around them.
We should include the direct compuation function and the delta if available.

**Comment by ninjapapa** [comment]
Should this belongs to SMV? Or we simply provide examples to show how to add those 3rd party libraries?

**Comment by AliTajeldin** [comment]
I don't think these two options are mutually exclusive.  I think we do need to add a simple string soundex/metaphone matching along with one or two string distance algorithms to SMV.  AND we also need to document how to use a generic third party library (or is that part of spark documentation?).
Just having easy access to the above is a value add for SMV especially if we somehow integrate it with an easy join that finds closest match type thing.

**Comment by ninjapapa** [comment]
Soundex is added. Will add metaphone.

**Comment by ninjapapa** [comment]
Done. 7ce21b1e6082d13443e1e249bcf84a853ad54e3d
