### ISSUE TITLE
Mixin BeforeAndAfterAll in SparkTestUtil

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#180]
### Motivation

* When writing tests for a component, it often happens that there are several aspects of that component that one would like to test.  It is good practice to group these tests together in a test suite (or class).  It is also good practice to separately mark these aspects, within that suite (class), and provide a good description for each to summarize what the test is about.
* Very often in this test suite, one could very well reuse a test setup (or fixture).  If that fixture takes some time to build up and tear down, it would improve the overall time taken for tests if it is only set up once and shared among the tests within that test suite.  A SparkContext belongs to this type of test fixture.
* There is also other kind of test code that could be shared across tests within a suite.  For example, one often builds an in-memory DataFrame for testing, using the SparkContext.  Sharing this DataFrame is currently not quite easy to do, as the SparkContext is constructed within the sparkTest() function, and DataFrame built outside the test is not only unavailable, but the SparkContext itself is not available outside the sparkTest() function scope.

### Proposed Solution

Mixin BeforeAndAfterAll in SparkTestUtil and place SparkContext and SparkSQLContext in the beforeAll() and afterAll() methods.

### Additional Benefits

One added benefit is that, now that sparkTest() method will no longer be needed, the ScalaTest test() method can be used, which is integrated with IDEs like IntelliJ.  Thus it's possible to execute a single test block within the test suite.  (Emacs+Ensime can probably do that as well ;)

**Comment by ninjapapa** [comment]
In addition to SparkContext and SqlContext, we may want to add a default SmvApp there too.

**Comment by ninjapapa** [comment]
done
