### ISSUE TITLE
provide a way to source user level run_shell init

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#181]
`run_shell.sh` now sources a standard init (smv/tools/conf/smv_shell_init.scala) and a project level init (conf/shell_init.scala).  We should add the ability to `run_shell.sh` to source a user level shell init file (~/.smv/shell_init.sh) so that users can add their own custom functions.

**Comment by laneb** [comment]
Is this (or a Python equivalent) still needed?

**Comment by AliTajeldin** [comment]
I think this would be nice to have in the long run.  Users sometimes have their own aliases, helper methods, etc.  As an alternative, we can add `${HOME}/.smv/python` to the python path in the runner so that the user can simply `import` their helpful libraries.
Hmmm, need to think this over a bit.

**Comment by ninjapapa** [comment]
Should support project level user init. By convention, `project/conf` could have a file `shell_init.py`, and run_pyshell should try to `import` it.

It is needed since project could have it's own library.

**Comment by AliTajeldin** [comment]
So in summary, there are three init files:
* standard init `smv/tools/conf/smv_shell_init.py`.
* project conf `project/conf/smv_shell_init.py` or some other name.
* user level con `${HOME}/.smv/smv_shell_init,py` or some name.

The last two should be optional.

**Comment by laneb** [comment]
Seems like they should also be executed in the same order you've described
them. Correct?

**Comment by ninjapapa** [comment]
I think the order should be 
* Standard
* User
* Project

Also I'm not very sure about the support of the user one. The issue there is that the user config file typically will not check into any repo, so behavior introduced by that file can not be reproduced in someone else's environment. It will introduce another place to look into when debugging for some new users. On the other hand, I can't see big benefit of supporting user level config file, especially when most of the projects developed on SMV are heavily team projects.

**Comment by AliTajeldin** [comment]
The user scripts are not supposed to be project specific.  They are for common aliases / functions that the user would like to set.  It sort of mirrors how config works.  We have smv config (the defaults), app config (`tools/smv-app-config`) and user config (`tools/smv-user-config` and `~/.smv/smv-user-config`).

**Comment by AliTajeldin** [comment]
Closing as will not implement.
