### ISSUE TITLE
remove schema helper functionality from SmvSchema

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#186]
The `SmvSchema` class should just be a configuration holder and parser that corresponds to the schema files.  All helper methods that only depend on the name/type of the fields should be moved to a Spark Schema helper (StructType helper to be more precise).  The advantage of making these helpers on `StructType` instead of `SmvSchema` is that we can always access the `StructType` for any `DataFrame`  by calling its `df.schema()` method.  Whereas the `SmvSchema` instance has to be tracked separately.

Note: Type 1 issue

**Comment by ninjapapa** [comment]
`SmvSchema` will only handle marshal-de-marshal of data fields and converting between `StructType` and `.schema` file. The marshal-de-marshal is handled by `SmvSchemaEntry`. 

The `StructType` helper should actually be `StructField` helper, which provide access to `ordering` and `numeric` for some types of `DataType`. 

```scala
class SmvSchemaEntry {
  def strToValue
  def valueToStr
  def name
  val typeName
  def toString
}
```

```scala
class StructFieldHelper {
  def ordering
  def numeric
}
```

**Comment by AliTajeldin** [comment]
agree.

**Comment by ninjapapa** [comment]
done
