### ISSUE TITLE
SmvDataSet instrumentation facility

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#192]
We need to have a standard way to tell "how many times a SmvDataSet runs". 

Similar to the way Spark 1.5 implement DF level instrumentation, we can define accumulators to do this.

**Comment by Khorkhe** [comment]
would you please clarify the end goals for this issue?  Is it to get statistical idea of which modules are most commonly run?

**Comment by ninjapapa** [comment]
Yes. 
It could be part of the module level meta data.

**Comment by Khorkhe** [comment]
is the accumulation done for the lifetime of the smvshell command, or is it persisted to be used over multiple uses?

**Comment by ninjapapa** [comment]
I can't recall exactly what was the use case of this issue anymore. @AliTajeldin do you remember?

**Comment by AliTajeldin** [comment]
I think the intent was for collecting stats about the runs of modules.  E.g. how many times a module was run, max/min/avg run times, etc.  Not sure this is still needed though.  For the run times, I think that should be part of the generated meta data.
Closing.
