### ISSUE TITLE
Extract CSV functionality into a separate package.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#206]
CSV handling (file and schema) should probably go into a separate package.
- rename `SmvSchema` to `SmvCsvFileSchema` to make the distinction clear (it is only for parsing the schema file associated with a CSV file).
- Move `SmvCsvFileSchema` and `SmvCsvFile` into own package.

**Comment by Khorkhe** [comment]
is this still a valid issue?
