### ISSUE TITLE
rename moduleCRC and classCodeCRC functions in SmvDataSet

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#210]
There are too many similarly named methods in SmvDataSet that do different things.
* Rename classCodeCRC to datasetHash
* Rename moduleCRC to datasetCRC (and remove comment about cached CRC)

**Comment by AliTajeldin** [comment]
Should be done after #150 and folks had a chance to publish.

**Comment by ninjapapa** [comment]
done
