### ISSUE TITLE
Create EddResult equal method 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#222]
need to check whether 2 edd results are the same within some tolerance setting.

**Comment by AliTajeldin** [comment]
We should add a new `EddResult` class that contains all the results from the EDD execution.  This should not just be the text report but rather the scala object representation of each result.
This class could than provide methods such as:
* `compare(other: EddResult, epsilon: Double)` : returns True if the two EDD results are the same (within epsilon difference) or false if they are different.
* `toJSON()` : creates a JSON representation of the result.
* `fromJSON()` : extract an EddResult from the JSON representation.

The above would allow us to integrate the EDD results into the overall meta-data output file associated with each csv/schema file.  Also, we can compare EDD results from multiple runs of the file in multiple versions of SMV.

**Comment by AliTajeldin** [comment]
We should also add a command line option to compare two edd result files:
```shell
$ smv-run --edd-compare edd_file_1 edd_file_2
```

**Comment by ninjapapa** [comment]
basic methods are created. Need to add the command line parameter.

**Comment by AliTajeldin** [comment]
added command line option.
