### ISSUE TITLE
smv-run --purge-old-output is not working if some output files are missing

### ISSUE THREAD

**Issue by GeorgeLembersky** [TresAmigosSD/SMV#227]
The first step is to reproduce this problem, as I've only seen this once.

smv-run was killed half way through, creating the first few output files, but not the rest.   When I then ran the same command, but with --purge-old-output, it failed, complaining about the missing files.

Expected result: It should remove all expected output files, but silently ignore any that are missing.

**Comment by Khorkhe** [comment]
unable to reproduce today.  However, while trying to reproduce, ran into #807
