### ISSUE TITLE
Reproduce hashOfHash changing bug

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#229]
Two team members observed that in some cases when client code changes on Module A. which has no dependency relationship with Module B, will cause Module B re-calculated with a different hashOfHash. 

Need to reproduce the issue and identify where is the problem.

**Comment by Kai-Chen** [comment]
What would elucidate the cause is to obtain the bytecode of the affected SmvModule both before and after the change to code in another area.

**Comment by Kai-Chen** [comment]
We found that between 2015-10-27 and 2015-11-09, with changes in both SMV and CommonData repository, all SmvModules hashOfHash changed (and need to be re-persisted), including those without any code change, such as raw input files.  In the follow-up study, we used these specific commits

  | 2015-11-09 | 2015-10-27/29 |
--------|-----------------|--------------
smv | 847f206248cc071a8084b3041b1eba3af0bad84d | 544dc38053dc8527b9dab2185a453d202419ca5d
common | 300628aa | a2991c31
input.npi_2012 | hash == cbb45cb8 | hash == c4fd2cfb

We further examined the disassembled bytecode, as well as the bytecode themselves.  The results will be summarized separately in the documentation.

**Comment by ninjapapa** [comment]
done
