### ISSUE TITLE
signal dependency graph

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#23]
Not sure how this will look like at the end, but Ideally allow the user to generate dependency graphs at the signal level and the op level.  For example:

``` scala
val srdd = rdd.select('dob - 'today as 'age, ...).group(...).select(Avg('a) as 'aa, Sum('a) as 'sa, ...)
srdd.generateSignalDependencyAsDotFile("foo.dot")
// or for op dependency
srdd.generateOperationDependencyAsDotFile("bar.dot")
```

The operations will generate a dot file for all the signals / operations respectively.  If the signal generation gets too busy then perhaps add an option to only create dependency graph that contain a certain signal from the leaf nodes.  Perhaps we can allow users to select a certain signal in the middle of the dependency graph and include all sources and results from that signal (TBD)

**Comment by ninjapapa** [comment]
This is implemented half by the SmvApp. (Module level dependency). For variable level dependency, this issue actually depend on the issue of derive Schema before running the data.
