### ISSUE TITLE
SmvFile hashCode wrong

### ISSUE THREAD

**Issue by eagle123** [TresAmigosSD/SMV#232]
The SmvFile hashCode should take into consideration the modification time of the schema as well.
Here is the scenario that lead to the discovery of this issue:
  - First I run a module that depend on file x.csv
  - I discovery that the schema is wrong, so I corrected the schema but smv never read file x.csv file again because its date never changed but the associated schema file did change

**Comment by ninjapapa** [comment]
Duplicate with issue #223

**Comment by ninjapapa** [comment]
done
