### ISSUE TITLE
Refine moduleCRC method

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#236]
Just discovered that since the bytecode of a class has **line number** info in it, any change on the location of the class in a file will cause `moduleCRC` change. Such as adding comment lines will cause CRC change.

Because of that if there are multiple SmvModule's in a Scala file, any changes on one module will highly likely cause CRC changes on any other modules after the changed module within the file. 

A best practice for now is to make sure each Scala file only contain highly related modules. However ideally `moduleCRC` method need to be enhanced to depend only on the disassembled code.

**Comment by ninjapapa** [comment]
fixed

**Comment by Kai-Chen** [comment]
Added a unit test that compiles scala code before comparing the moduleCRC calculated from the bytecode before and after source code change.

The first commit was amended to remove the leading '\' without any change in code.
