### ISSUE TITLE
Need a histogram based percentile aggregate function

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#246]
The accurate percentile function, either implemented using `runagg`  or `window`, is more like of full table operation on each individual columns. For example, if we want to calculate the 5-50-95 percentiles of 100 columns, within each group, the data have to be sorted 100 times, one for each column. 

If we can trade off some accuracy, we can implement the percentile calculation as a histogram calculation and a sort on the result histogram. This will make the job more scalable across number of columns.

**Comment by eagle123** [comment]
Suggested syntax/usage
df.groupBy($”id”).agg( Percentile(90)($”v”) as v90 )
where 90 is the 90th percentile and v is the column name.
v should be of type  numerical.

**Comment by eagle123** [comment]
Do we ever want to specify some min/max values and the number of bins?

**Comment by ninjapapa** [comment]
Should allow user to specify max, min, and num_bin, or num_bin only. In most of the case user may have some sense of how may bins (or how accurate) he want to have. However it will be pretty rare for him to know the max and min.

**Comment by eagle123** [comment]
The user code will look like:
 
 df.smvDoubleBinHistogram("id", "v", 2) where v is the value to bin and 2 is the number of bins. This will create a double bin histogram column called "v_bin". To compute the percentile of column v, the user have to do df.selectPlus('v_bin.smvBinPercentile(10.0)) where 10 is the percentile value
multiple flavor of smvDoubleBinHistogram will be added to allow bining multiple values using multiples keys. The default bin value will be 1000

**Comment by eagle123** [comment]
Done
