### ISSUE TITLE
Split Parser Validation counter

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#253]
Csv parsing could have 2 types of errors
- Parsing error: happens when Row[String] => Row[Seq[String]] 
- Demarshalling error: happens when Row[Seq[String]] => DataFrame

Current DQM has both logged in the same counter. Need to split the two cases.

**Comment by AliTajeldin** [comment]
@ninjapapa do we still need this?    Is this more confusion than help for the user who is not familiar with SMV internals (the two step parsing)?

**Comment by ninjapapa** [comment]
@AliTajeldin agreed. No need for this. Close.
