### ISSUE TITLE
use SMV_MASTER env variable as default --master in smv run/shell

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#258]
both `smv-run` and `smv-shell` both accept a `--master` parameter.  If the user always want to override the `--master`, then they have to either specify it every time or create an alias.  For cluster installs, it would be nice to have the user be able to specify an environment variable to override the default (e.g. on an edge box, specify the SMV_MASTER parameter in their `.bash_profile` file).

**Comment by ninjapapa** [comment]
done
