### ISSUE TITLE
enable column labeling to categorize columns in a wide table

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#263]
Use case:
In a wide table, there are generally multiple categories of variables. Labeling them help later processing, such as only extract one category of columns as deliverables.

Additional request:
Labeling with work as other functions to simplify labeling process, such as SMVpivot (when generating variables), select(when selecting multiple variables to give the same name).

**Comment by Kai-Chen** [comment]
Implemented add and remove methods in SmvDFHelper.  Also provided a query method that returns all labels on a given column.
