### ISSUE TITLE
Enable better reading for US dollar amount columns

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#266]
Many dollar amount variables, in the input data, have "$" and "," in them, which caused them to be read as "String" variables 
For example:
Column A:
$15,336
$13,234
$367
Currently will be read as schema = "string"
There should be a way to detect this type of use cases, so they can be read in as numeric variables.

**Comment by laneb** [comment]
This would be for `discoverSchema`, correct?

**Comment by laneb** [comment]
We don't have support for reading currency values, so we have to read this as a string.

**Comment by ninjapapa** [comment]
This one is interesting, is it possible to use the format idea in schema to address?

**Comment by laneb** [comment]
@AliTajeldin ^

**Comment by AliTajeldin** [comment]
The format will just enforce a pattern.  The type will probably still be string.  So a schema entry such as "`money: String[$nnn,nnn.nn]`" will just force the value to be 11 characters with a leading dollar and 8 numeric digits.  It will be very hard to make that automatically be treated as a numeric value.   If the user uses the format string above, their conversion to numeric routine can assume the format is correct.
