### ISSUE TITLE
Need inline filter for aggregation functions

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#27]
Client code:
```scala
val res = srdd.groupBy('zip)(Sum('amt) where 'tranType === "c" as 'Camt, 
                         Sum('amt) where 'tranType === "d" as 'Damt)
```

**Comment by ninjapapa** [comment]
The exact example now is handled by "pivot_sum". In general, CDS and pivoting cover this issue. Closed.

**Comment by AliTajeldin** [comment]
While pivot sum handles the example above, this ticket is for the more generic example of creating a conditional on an aggregate function.  I think this will be addressed by the CDS changes we discussed earlier
