### ISSUE TITLE
create a helper function to generate bitmap from a group of boolean columns

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#274]
To investigate the joint distribution on multiple boolean columns, the easiest way is to plot the histogram on the bitmap of those columns. 
* True => 1
* False & Null => 0

User code should look like
```scala
df.select(smvBitmap($"c1", $"c2", ...) as "c_bitmap")
```

Like other functions on columns, need 2 signatures:
* ```smvBitmap(Column*)```
* ```smvBitmap(String, String*)```

**Comment by GeorgeLembersky** [comment]
In order to allow other bitmap conversion functions in the future we will call this smvBoolsToBitmap instead.   Thus the signatures are:

- smvBoolsToBitmap(Column*)
- smvBoolsToBitmap(String, String*)
