### ISSUE TITLE
Implement joinAllByKey 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#275]
A group of DFs could be joined all together on some join key. Need a helper function for this. 
One possible choice of the user code should look like
```scala
df1.joinAllByKey(Seq(df2, df3, df4, ...), Seq("k1", "k2"), Inner)
```

**Comment by XiaosenChen** [comment]
After discussion with Bo and Ali, we decide on implementing following interface:

df1.joinMultipleByKey( Seq("key1", "key2"), SmvJoinType.Inner)
     .with(df2, "_df2")
     .with(df3, "_df3")
     ...
     .doJoin()

**Comment by XiaosenChen** [comment]
Shall we enable following interface?

df1.joinMultipleByKey( Seq("key1", "key2"), DefaultJoinType)
.with(df2, "_df2", OptionalOverrideJoinType)
.with(df3, "_df3", OptionalOverrideJoinType)
...
.doJoin()

In this way, join commands with different join type can be chained together.

**Comment by ninjapapa** [comment]
Since `with` is a reserved key word of Scala, we have to use `joinWith` instead of just `with`.
