### ISSUE TITLE
smvPivotCoalesce need an optional cutoff

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#279]
Currently the number of output columns of `smvPivotCoalesce` method is purely driven by data. It is very dangerous. For example if the "pivotCol" has some default value, say an ID field has a default value "000000" which captures all the records without an identifiable ID, in that case there will be very many potential "valueCol"s from this ID, although all normal IDs have limited number of values.

Need to add a cutoff parameter, and set it to a relatively large number such as 100 as default.

**Comment by ninjapapa** [comment]
Sounds like we need to re-design the `smvPivotCoalesce` interface. 
Current interface's signature is
```scala
  def smvPivotCoalesce(pivotCol: String)(
    valueCol: String,
    rankCol: Option[String] = None,
    maxResCols: Int = 100
  ): DataFrame
```
It works but it's inconsistent with the naming convention of other `smvPivot` method. The `pivotCol` here are actually `keptCols` in `smvPivot` (smvGroupBy version), and `rankCol` is `pivotCol` in `smvPivot`. 

Also it only support one use case. Ideally it should support the following 2 use cases:
* Unknown number of potential values, but have a upper limit as "common sense" 
* Desire `N` output columns. If more than that, just ignore; if less than that all fill with null

Other requirement
* Should support user specified prefix for the result columns
* Rank start from 0 instead of 1, or allow user to specify?

No so sure about whether we need user-defined-rankCol. What use case this one supports?

Potential new interface:
Instead of defined as an `SmvDFHelper` method, define `smvPivotCoalesce` as an `SmvGroupedData` method. Signature:
```scala
def smvPivotCoalesce(
  valueCol: String,
  maxResCols: Int = 100,
  prefix: String = valueCol,
  keepNullCols: Boolean = false
)
```

Client code:
```
df.smvGroupBy("key1", "key2").smvPivotCoalesce("value", 10, "v", true)
```

**Comment by XiaosenChen** [comment]
Reopened the ticket in Jira on this function.

**Comment by ninjapapa** [comment]
There is an use case that `smvPivotCoalesce` need to behave exactly like `smvPivotSum` except it's not sum all the values but coalesce (first non-null). Example: the same ID has records on day1, day4, and day7, and we want to pivot it and create columns as "v_day1", "v_day4" and "v_day7" from column "v". 

In this case we'd rather make the `smvPivotCoalesce` interface fully consistent with `smvPivotSum` interface as
```scala
def smvPivotCoalesce(pivotCols: Seq[String]*)(valueCols: String*)(baseOutput: String*)
```

In case the `pivotCols` are empty, in group rank will be used as pivot column. In case `baseOutput` is empty, it will be derived from the `pivotCols` from the data in the same way as `smvPivotSum` did. 

Examples:
```scala
df.smvGroupBy("k1").smvPivotCoalesce()("v")()
```
will group by "k1" and create output columns "v_0", "v_1", ..., "v_n", where `n` is the max number of possible `v` values in a `k1` group. It has the same danger as describe on the first comment above. 

```scala
df.smvGroupBy("k1").smvPivotCoalesce()("v")("0", "1", "2", "3")
```
Same as above, but limit the output to `v_0` to `v_3`. If there are more values in a `k1` group, they are simply ignored. If the max number of `v` values in a `k1` group is less than 3, say is 2, `v_3` will still be part of the output and be all `null`s.

```scala
df.smvGroupBy("k1").smvPivotCoalesce(Seq("days"))("v")()
```
use the `days` column as the `pivot` column, for the case described on the top of this comment.

**Note**, as same as `smvPivotSum`, if the `baseOutput` parameter is omitted, an additional data action need to be performed to derive the `baseOutput`. User should always be encouraged to specify `baseOutput`.

**Comment by ninjapapa** [comment]
Should the default rank start from 0 or 1?

**Comment by ninjapapa** [comment]
Done
