### ISSUE TITLE
Remove smvWithKey and SmvDFWithKeys class

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#280]
Current `smvGroupBy` play 2 roles:
- Similar to Spark's "groupBy" but provides "runAgg" type of methods
- Simply let further methods know that some columns on the input DF are keys

The second role should be replaced by `smvWithKeys`.

**Comment by laneb** [comment]
Still needed?

**Comment by ninjapapa** [comment]
I need to think about this... 
This issue will most likely change to "Remove smvWithKey, and just user smvGroupBy". Before make the change I need to think a little more.

**Comment by ninjapapa** [comment]
It is unnecessary and confusing to have both `smvGroupBy` (and `SmvGroupedData`) and `smvWithKeys`. Let's just keep `smvGroupBy`, and make `smvWithKey` an alias on Scala side to `smvGroupBy`.

**Comment by laneb** [comment]
Just noticed you already assigned yourself @ninjapapa. Sorry!

**Comment by ninjapapa** [comment]
My bad. Assigned myself but forgot.

**Comment by laneb** [comment]
Done.
