### ISSUE TITLE
Allow for running of test cases from shell

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#293]
With the new hive context, it is really expensive to start a new shell.
Allow user to dynamically load and run a test case from the shell.  This should reduce the cost of running/updating testcases.

**Comment by AliTajeldin** [comment]
This depends on #298 to be able to run SMV without an app and build an SMV fat jar.

**Comment by laneb** [comment]
In order for this to be useful we will need to reload _ALL_ relevant code - this includes the test itself and all SMV code.

**Comment by laneb** [comment]
Now working i293_tests_in_shell. Needs documentation.

**Comment by laneb** [comment]
Done.
