### ISSUE TITLE
Need the second SmvAncillary

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#294]
We have the `SmvHierarchy` concept to handle things like `zip`->`county`->`state`->`country` type of structure and methods related to that structure. There is a similar but different structure we need to handle.

Let's say our data is about some products, and those products are not structured as hierarchies (`sku`->`category`->`department`) instead they are all modeled as product attributes (or tags). For example, a specific "bag" could have attributes "red", "fiber", "travel", "outdoor", "large", etc. From data aggregation angle, we want to know 
- How many units of each product (sku) sold in last month, and
- How many units sold for each attribute (for example, how many "ourdoor" items) in last month

The rollup function is pretty similar to `SmvHierarchy`, however the input data are represented differently and required to be more flexible (for example adding another tag to that bag should not cause too much change on the code).

Another decisions should be around how the final result (output data) should be organized. For `SmvHierarchy` we has this concept of 
- `prefix_type`,
- `prefix_value`

Should we use the same structure for attribute based structure?

**Comment by laneb** [comment]
Is this still needed?

**Comment by ninjapapa** [comment]
No.
