### ISSUE TITLE
Run smv-shell without an app

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#298]
Need a way to be able to run smv shell without an application build.
We currently need to rebuild SMV and build an app when we want to experiment with a new SMV functionality.  We are effectively utilizing the app build process to get the SMV fat jar and we wouldn't need the rest of the app classes in this particular case.

Basically, we somehow need to build an SMV fat jar (perhaps with the test cases as well). This is dependent on #297 because presumably this should be easier to accomplish with SBT than maven.

**Comment by Kai-Chen** [comment]
In SBT shell, one could run
```shell
set test in assembly := {}
assembly
```
to build the fat jar for smv only, and then run `./tools/smv-shell`.

**Comment by laneb** [comment]
We can now do this from `smv-pyshell`. Is it still needed for the Scala shell?

**Comment by AliTajeldin** [comment]
The ability to do that with `smv-pyshell` is sufficient.  Closing this.
