### ISSUE TITLE
Need an easy to use SMV install script.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#299]
The current SMV installation process is error prone and too difficult.  Ideally, the installation instructions for SMV should be a single like such as "`$ curl http://foo.com/bar.sh; ./bar.sh`".   
The above command would take care of:
* Download latest SMV
* Download / install SBT/Maven or whatever build tool is required.
* Download required JDK.  May need to use OpenJDK so user doesn't have to click on EULA.
* Download whatever other tools are required to run SMV (e.g. graphvis, etc.)

The above should **NOT** install in the standard system directories.  Therefore, no sudo should be required nor should we mess up the current user environment.  All packages should go into an SMV sandbox and all the SMV tools need to be modified to recognize when they are run in the sand box and utilize the downloaded utilities.

Uninstalling SMV would then just be removing the directory.

**Comment by xuxiaoshun** [comment]
I like the idea that make SMV a "green" software.

1.  Should we consider the option of re-build binary SMV in which case we don't need the build tool such as Scala SDK and sbt/maven?
2.  Should Spark also be included in the download list?
3.  Maybe one script to verify if the SMV installation is correct can be useful.

**Comment by xuxiaoshun** [comment]
1.JDK is NOT available as a portable zip in Mac OS. 
So how about let users install JDK by themselves as a system requirement? 
For example, we can document the steps as 1&2 below:
http://www.tutorialspoint.com/maven/maven_environment_setup.htm

2. Should the environment settings(such as adding mvn/spark bin to $PATH, etc.) be permanent? If so, then we need to make a script to remove them from environment when uninstall SMV.

**Comment by ninjapapa** [comment]
Sounds harder than it looks :-)

* Anyhow the Oracle JDK need to be installed by end user (since the agreement thing). If we use OpenJDK, the official site does not provide tar.gz way to install. If we can't find an easy way to install OpenJDK without SUDO, we need to run a JDK check, and suggest user to install Oracle JDK if no JDK detected.  
* How about provide an "init" script to setup the environment for the current shell?

**Comment by ninjapapa** [comment]
Should we create a test case for this? Not gonna be easy though.

**Comment by xuxiaoshun** [comment]
I don't think it is necessary because this is installation tool and only needs to run once. Not all script under tools have test case, do they?

**Comment by ninjapapa** [comment]
smv itself may need to have some integration test or QA process. This script may be tested there.  Anyhow it should be a separate issue.
