### ISSUE TITLE
Add DataFrame function to Generate a Unique Identifier (Primary Key) Column

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#301]
## Motivation
Sometimes we will run into a data set that has no observable natural key (even after combining multiple columns).  But we will need to reference to the rows in this data set from another.  Combining all columns is not quite wieldy.  It would help if we have a function that would generate a unique key for each row in the data frame.

## Requirements
* The function must guarantee uniqueness.  Spark already provides several column functions, such as md5 and sha2, that may be used for this purpose,  The collision rate is extremely low.  However, it's probably a good idea to check against hash collision after the keys are generated, e.g. by comparing the distinct row counts with the distinct key counts.
* The generated key should not be too long.  A hex rep of md5 or sha results is reasonable, being of 32 and 64 (for the 256-bit version) characters in length, respectively.
* User may optionally include a prefix to the key to have a readable portion of the row content.

**Comment by ninjapapa** [comment]
Client code
```scala
df.selectPlus(smvHashKey("prefix_", $"col1", $"col2") as "id")
df.selectPlus(smvHashKey($"col1", $"col2") as "id")
```

Since checking for collision is expansive, we will use sha2 (64 char size key) and not check for collision. Theoretically we should not run into collision issue within reasonable statistical sense.

**Comment by ninjapapa** [comment]
With some research we decided to use MD5 (size 32) instead of sha2 (size 64) because the collision rate on MD5 can be ignored for all of our problems. The reason and relevant links are in the scala doc.
