### ISSUE TITLE
exportCSV result in different DF

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#312]
exportCSV on a SMV module result in a df that is different from the original df, with more records and key value changed.

**Comment by XiaosenChen** [comment]
This is due to spark unable to correctly handle multiple partitions, when repartition to 1, the issue resolved itself

**Comment by ninjapapa** [comment]
Really weird. Do you mean that do a repartition before exportCsv solved the problem? Since exportCsv is simply a 'collect', it means Spark's collect has issues.

**Comment by XiaosenChen** [comment]
yes, looks like collect has issues when partitions are many. Kai was looking into this yesterday, he may have more details.

**Comment by Kai-Chen** [comment]
Don't have the bandwidth to hunt the bug in Spark.  But the work-around should suffice for now.

**Comment by Kai-Chen** [comment]
Please ignore commit fcd790d, the comment section was supposed to reference another ticket, not this one.

**Comment by ninjapapa** [comment]
done
