### ISSUE TITLE
Need to create a smvr package to be the single entry point to smv-r methods 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#314]
Currently, the smv-r only support module resolving methods. Will need to port more smv methods to smv-r environment. To have the interface managed, we need to create a package "smvr" as the single interface between smv and sparkR.

**Comment by laneb** [comment]
R does not appeared to be actively supported these days. Can we close this?

**Comment by AliTajeldin** [comment]
closing for now.  We can reopen if we pick up R support once again.
