### ISSUE TITLE
add --gen-sql option to SMV publish command

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#317]
We currently generate a csv/schema file when a module is published.  We should add an option of generating the sql DDL + loader commands to bullk load the table.  We can assume mysql syntax for now.
The generated output should not know anything about indexes or primary key.  That will be provided by the UI backend authors when the data is loaded.

After discussion, this should be part of a command line "export" command that also specifies the destination directory.  Publish should continue to output to HDFS (csv files are actually directories) for consumption by downstream Spark modules.

The export will generate a single csv/schema/sql file for each output module.

**Comment by laneb** [comment]
Is this still needed? Is it addressed by the new JDBC features?

**Comment by AliTajeldin** [comment]
Agree. jdbc table can now handle that in a better way.
