### ISSUE TITLE
Failing tests prevent building user guide example app

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#321]
**Issue**
When trying to get up and running with the user guide [installation instructions](https://github.com/TresAmigosSD/SMV/blob/ef2e8f1180622600ea21573dc384299dc046a19c/docs/user/smv_install.md#install-smv) at the current master [HEAD](https://github.com/TresAmigosSD/SMV/tree/ef2e8f1180622600ea21573dc384299dc046a19c) (2e081d0), I was unable to successfully build the library. 

**Steps To Reproduce**

1. Create a Dockerfile with the following contents:

        FROM ubuntu:15.10
        WORKDIR /home/app
        ENV SCALA_HOME=/home/app/scala-2.10.4 \
            SPARK_HOME=/home/app/spark-1.5.1-bin-hadoop2.6 \
            MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=128m" \
            _SMV_HOME_=/home/app/SMV
        ENV PATH=$PATH:${SPARK_HOME}/bin:${_SMV_HOME_}/tools
        RUN apt-get update
        RUN apt-get install -y openjdk-7-jdk maven git wget unzip scala
        RUN wget http://d3kbcqa49mib13.cloudfront.net/spark-1.5.1-bin-hadoop2.6.tgz && tar -zxvf spark-1.5.1-bin-hadoop2.6.tgz
        RUN wget http://www.scala-lang.org/files/archive/scala-2.10.4.tgz && tar -zxvf scala-2.10.4.tgz
        RUN git clone https://github.com/TresAmigosSD/SMV.git && cd SMV && mvn clean install
        RUN $_SMV_HOME_/tools/smv-init MyApp com.mycompany.myapp

3. Run: `docker build -t failing_build -f PATH_TO_DOCKERFILE .` (**NB**: This might take a few minutes to run since it must download all image dependencies)

In my runs the second to last line (`RUN git clone https://github.com/TresAmigosSD/SMV.git && cd SMV && mvn clean install`) will exit with a non-zero exit code, which then prevents `smv-init` from executing

**Failing Test Output**
```
ModuleCrcConsistencyTest:
- test moduleCrc changed or not *** FAILED ***
  1980550930 did not equal 3972922531 (ModuleCrcConsistencyTest.scala:38)
- test moduleCrc on SmvFile *** FAILED ***
  3221229757 did not equal 471507208 (ModuleCrcConsistencyTest.scala:42)
```

**Comment by ninjapapa** [comment]
fixed.

**Comment by jacobdr** [comment]
Confirm the fix. Build passes. 
```
git checkout cc185a6
mvn test
```
💯
