### ISSUE TITLE
Building SMV aborted: output directory ./target/scala2.10/classes does not exist

### ISSUE THREAD

**Issue by Khorkhe** [TresAmigosSD/SMV#322]
Following the SMV setup instructions, the command:
`mvn clean install`
causes error:
`  Cause: java.lang.RuntimeException: output directory /Users/georges/Desktop/twine/SMV-dup/target/scala-2.10/classes does not exist.`

![screen shot 2016-06-20 at 5 00 06 pm](https://cloud.githubusercontent.com/assets/4688418/16214045/1011cec4-3709-11e6-9cd7-7e2f6b1512f9.png)

Short term workaround was to manually create the directories scala-2.10/classes inside target, as soon as the latter was generated by mvn install: I was able to successfully build it like that.

**Comment by Kai-Chen** [comment]
Delay initializing of in-test-compiling-related value, as it doesn't work with maven build.
