### ISSUE TITLE
helper function to add description from a DF

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#324]
In some cases, data sets comes with descriptions in a DF format (column1: var names; column2: descriptions). In such cases, we need functionality to add descriptions using the supplied DF.

**Comment by ninjapapa** [comment]
Are there 2 DFs in this case?
* DF1 is the real data
* DF2 is the meta data of DF1, in other words the 2 columns described in the issue are the only 2 columns on DF2, and the number of rows are the same as the number of columns of DF1.

**Comment by XiaosenChen** [comment]
Yes, that is the case.

**Comment by XiaosenChen** [comment]
closed
