### ISSUE TITLE
Allow smv-init to create a new project from an existing git skeleton 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#325]
When starting a new SMV project, one could create the github repo first. In that case, a git skeleton (with or without README.md) is the starting point. In that case we'd like the `smv-init` command be able to init a project on that existing directory. Current `smv-init` creates a new dir, when try it on existing dir, it errors out.

**Comment by laneb** [comment]
Is this still needed?

**Comment by AliTajeldin** [comment]
Yes.  However, I think it needs to be an explicit flag.  That is something like:
```
$ smv-init -s -o foo
```
This tells `smv-init` to explicitly override the contents of the `foo` directory and add the sample stages, data, etc.  Note, we should make sure we are not actually overriding anything (do not erase anything in the existing directory).

**Comment by Khorkhe** [comment]
We now allow the user to specify an existing directory.  This is done so without the -o flag.

 - if the specified dir already exists, the user is notified with a printed message, and the scripts executes normally.
 - if the specified dir already exists, and contains the file `conf/smv-app-conf.props`, the script exits with error message, as that indicates the dir is already an SMV project.
