### ISSUE TITLE
Update documentation + link to developer resources (API) -- for example, joinByKey

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#327]
Did a search of Github for `joinByKey` and didn't come up with anything in the user docs. Might exist in the API documentation, but a more visible link to that documentation might also be helpful to developers.

@AliTajeldin 

https://github.com/TresAmigosSD/SMV/blob/09b2aa424d5f9e4f8873a8b9a4f6fe0f5d9c60b3/src/main/scala/org/tresamigos/smv/SmvDFHelper.scala#L300

**Comment by AliTajeldin** [comment]
There is already a link to the API docs from the main SMV page but I think that is not sufficient. I don't think the solution is to document all SMV functions in the user guide as that would be a large duplication of effort.  We need a chapter in the user doc that helps the user navigate the API docs.  Perhaps an appendix that walks the user through the major parts of the API documentation (the DF helper, the column helper, join keys, etc).

**Comment by AliTajeldin** [comment]
Turns out, the above already exists in the doc file.  Totally forgot I created that: https://github.com/TresAmigosSD/SMV/blob/master/docs/user/functions.md
