### ISSUE TITLE
create warning message for ddf

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#329]
when ddf a module that depends on many upstream modules, ddf will load everything from disk, which may result in a long loading time without any message in shell. A warning message will be helpful when user attempt use ddf in such cases.

**Comment by Khorkhe** [comment]
Commit #329 caused issue when building SMV on my and Shaoying's laptops with the following test failures:
```
ModuleCrcConsistencyTest:
- test moduleCrc changed or not *** FAILED ***
  2743763818 did not equal 1980550930 (ModuleCrcConsistencyTest.scala:38)
- test moduleCrc on SmvFile *** FAILED ***
  108332644 did not equal 3221229757 (ModuleCrcConsistencyTest.scala:42)
```

Commented the two asserts on local to get her SMV up and running but the execution of Spark scripts caused additional errors.
For now, ended up rolling back Shaoying's local SMV so she can proceed.

**Comment by Kai-Chen** [comment]
Can you paste the errors you get from spark-shell?

**Comment by Khorkhe** [comment]
```
res1: org.tresamigos.smv.SmvApp = org.tresamigos.smv.SmvApp@7e3e1b7b
<console>:60: error: value dependencies is not a member of org.tresamigos.smv.SmvDataSet
             ds.dependencies foreach (x => println(x.getClass.getName))
                ^
<console>:70: error: value dsForName is not a member of org.tresamigos.smv.SmvApp
           val ds = app.dsForName(fqn, cl)
                        ^
<console>:31: error: not found: value i
       import i._
              ^
```

Though by looking in the code, I did find "dependencies" in SmvDataSet.

**Comment by Kai-Chen** [comment]
I just checked in the update to the test code.  Try pulling again, it should pass now.

**Comment by Kai-Chen** [comment]
Also remember to run `sbt publish-local` or `mvn install` from the SMV project first.

**Comment by Khorkhe** [comment]
SMV now building on my local.  Will test on Shaoying's shortly, as NeoDM project is not configured on mine. Thanks!

**Comment by Khorkhe** [comment]
SMV build succeeded. Thanks!
