### ISSUE TITLE
Histogram over column

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#330]
In some use cases, we want to plot histogram over a column(mostly categorical columns). For example we may wan to know the distribution on age by gender, something like this:

df.edd.histogram("age", "education")("gender").eddShow

Assume gender has 2 levels, 4 histogram should be dumped on the screen for above command

**Comment by Kai-Chen** [comment]
Bo proposed a new API for running ad-hoc histogram analyses.  The method will be added to the DataFrame as follows
```scala
def showHist(groupBy1: Column, rest: Column*)(colA: String, more: String*): Unit = ???
```
where the `groupBy` parameters are in the first list, corresponding with the signature of `smvGroupBy`.

An additional change is made to the meaning of the `String` parameter list.  Currently, when you run `df.edd.histogram(colA, colB, ...)` it will generate one histogram for each of the named columns.  This is not as frequently used as anticipated.  And as the same result can be achieved by running the sequence of histograms each individually, the variable argument list can implement another use case, namely, generating 1 histogram for the concatenated values of all the columns.

**Comment by Kai-Chen** [comment]
This feature was implemented with the aforementioned commit.  A more congruent approach will be written in issue #348.
