### ISSUE TITLE
Precedence of command line flag for --executor-memory in smv-run

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#333]
If I want to modify the value from 6G, do I simply add that flag to my `smv-run` invocation? Will a second flag provided overwrite the default value hard coded here?

https://github.com/TresAmigosSD/SMV/blob/3843049319bb419f1fa5e2feb05c0af201e65e64/tools/smv-run#L31

**Comment by Kai-Chen** [comment]
See #347
