### ISSUE TITLE
License for this code?

### ISSUE THREAD

**Issue by jagatsingh** [TresAmigosSD/SMV#334]
Hi,

I wanted to use and may be contribute back the code in this project for my work. I was just wondering what is the license associated with this.

Thanks in advance for reply.

**Comment by ninjapapa** [comment]
Welcome! 

https://github.com/TresAmigosSD/SMV/blob/master/LICENSE

**Comment by jagatsingh** [comment]
Thank you. Few classes did not had header so thought to confirm. 

Any mailing list / group to discuss about questions about library ?

**Comment by AliTajeldin** [comment]
No specific mailing lists / groups.  For now, just utilize the SMV github issues for discussion topics.  Just open a new issue for a topic.

**Comment by jacobdr** [comment]
@AliTajeldin propose to close

**Comment by jagatsingh** [comment]
Thanks
