### ISSUE TITLE
user should be able to specify FQN of stage when specifying version. (Type 1)

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#336]
The current way a user provides the stage version is through the `smv.stages` property as follows:
```
smv.stages.etl.version = V1
```

Note that only the *basename* of the stage is specified. If the project has multiple stages with the same basename, the above declaration is ambiguous (it will actually apply to both, possibly unintentionally).

SMV should allow user to specify the FQN of the stage:
```
smv.stages.com.mycompany.project2.etl.version = V1
```

For backward compatibility, the old use of basename should be maintained but only the FQN version documented.

**Comment by ninjapapa** [comment]
done.
