### ISSUE TITLE
Allow user to define SMV modules in python (Type 3)

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#337]
This is a place holder ticket for allowing users to define SmvModules in python.  Design doc to follow shortly.

**Comment by Kai-Chen** [comment]
Just added ability to instantiate SmvApp and resolve SmvModule in Python (#335).  It should be straightforward to add the ability to persist the resulting dataframe as well.  It might be instructional to port one of the smaller existing modules to Python using these facilities to get a feel for how it would work.

**Comment by AliTajeldin** [comment]
@Kai-Chen, after discussion with @ninjapapa , we think the best approach for integrating SMV with pyspark is to allow user to create arbitrary `SmvModule` objects in python directly.  This will require some porting/duplication of the scala `SmvModule` functionality but will provide us with the greatest flexibility overall.  Users will then be able to link scala/python smv modules seamlessly.  This will be built on top of the work done in #335.
We should have a discussion some time next week to figure out best plan of attack and start the design doc.

**Comment by Kai-Chen** [comment]
Sounds good!  The only part that I think might be a bit tricky is how to calculate hash-of-hash of SmvModules written in python.  We could start with the original 'version' by hand.  Python does have a bytecode dumper that we can look into.  Another choice would be to see if we can get a comment-stripped AST from jython.

One question that might come up, in case I forget later, is do we need to support both Python 2 and Python 3.  If we do end up having to support both, it'd be good to know which one is a higher priority (depending on the users' preference).

**Comment by AliTajeldin** [comment]
We can either use the bytecode or the hash of the class object itself (they are just dictionaries).  The actual hash_of_hash would always be computed in scala (as it needs to follow the dependency graph).  Only the hash of the module code would be required in python.

What does spark support right now as far as python versions.  My preference is for python 3 if possible as that is the future and we already have some code from client the depends on v3.

**Comment by Kai-Chen** [comment]
Spark currently supports both Python 2 and 3; there is an environment variable(s) to set the python binary to use.  In spark python modules, there're quite a few places where they shim for 2.x the missing or changed API in 3.x.
