### ISSUE TITLE
extract SparkTestUtil into main code

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#34]
Projects (Lucentis and MVD) need to create their own copy of SparkTestUtil.  Copy-n-paste is evil.  so we need to move SparkTestUtil out of test and into main src. May need to provide some helpfull test schema rdd creation tools as well.
We may want to create another sub-package under org.tresamigos.smv for the above.  needs some further thinking.

**Comment by ninjapapa** [comment]
duplicated with #130
