### ISSUE TITLE
Need to figure out how to handle nulls in the ordering coulmns of dedupByKeyWithOrder 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#340]
Current `dedupByKeyWithOrder` will generate a run time error if the ordering columns have nulls. Should it be the correct behavior? How Sparks "orderBy" handle null values in columns?

**Comment by xuxiaoshun** [comment]
Spark "orderBy" puts null value records before any non-null value record. The sequence of null value records is the same as their reading sequence.

**Comment by ninjapapa** [comment]
Does it mean regardless whether `asc` or `desc`, `orderBy` will put `null` in front? Or just for `asc`?

**Comment by xuxiaoshun** [comment]
Good catch! `null` in front for `asc`, while at the end for `desc`. 
For example,
scala> df2.orderBy("age").show()
+----+-------+
| age|   name|
+----+-------+
|null|Michael|
|null|      a|
|   3|      b|
|  19| Justin|
|  30|   Andy|
+----+-------+


scala> df2.orderBy(desc("age")).show()
+----+-------+
| age|   name|
+----+-------+
|  30|   Andy|
|  19| Justin|
|   3|      b|
|null|      a|
|null|Michael|
+----+-------+

**Comment by Kai-Chen** [comment]
I think the user should have an option to specify whether `null` should come first or last in either ordering flavor (ascending and descending).  In the SQL standard, there is a `NULLS FIRST` and `NULLS LAST` clause in the `ORDER BY` list.  The default order in Oracle treats NULL is the largest (so it comes first in descending, last in ascending), and MS SQL default order is the reverse.

**Comment by Kai-Chen** [comment]
Sorry for missing the `dedupByKey` context.  Should records with `null` in the key be kept around?  If so, how should one detect a duplicate? If all `null`s are treated as equal, then there would be just one record left after the `dedup` operation.  Or maybe the result should simply discard all the rows with `null` in the key column?

**Comment by ninjapapa** [comment]
Fixed by PR #1287. Since suing window function now, the ordering behaves the same as standard Spark should be.
