### ISSUE TITLE
Docker image to accommodate SMV developers rather than just users.

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#342]
I have been trying to keep a few SMV Docker image [snapshots](https://hub.docker.com/r/jacobdr/smv/tags/) in my personal Docker Hub account. 

Today I went to rebuild an image based on a more recent [commit](https://github.com/TresAmigosSD/SMV/commit/1a60edc898b2d62e7b677b29248d99473955502f), and the image built really fast. Too fast.

Pretty much every layer hit the image layer cache (generally a very good thing), but in our case this meant that an older version of SMV was assumed -- that is, the `master` at a previous point in time. I think this was caused by [line 46](https://github.com/TresAmigosSD/SMV/commit/1a60edc898b2d62e7b677b29248d99473955502f) int the Dockerfile.

```
Step 9 : RUN mkdir $SMV_USER_LIB &&    wget http://www-us.apache.org/dist/maven/maven-3/$MVN_VERSION/binaries/apache-maven-$MVN_VERSION-bin.tar.gz &&    tar xzvf apache-maven-$MVN_VERSION-bin.tar.gz &&    rm apache-maven-$MVN_VERSION-bin.tar.gz &&    mv apache-maven-$MVN_VERSION $M2_HOME/ &&    wget http://d3kbcqa49mib13.cloudfront.net/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz &&    tar xzvf spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz &&    rm spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz &&    mv spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION $SPARK_HOME/ &&    wget https://dl.bintray.com/sbt/native-packages/sbt/$SBT_VERSION/sbt-$SBT_VERSION.tgz &&    tar -xzvf sbt-$SBT_VERSION.tgz &&    mv sbt /home/smv/lib &&    rm sbt-$SBT_VERSION.tgz &&    wget http://github.com/TresAmigosSD/SMV/archive/master.zip &&    unzip master.zip &&    rm master.zip &&    mv SMV-master $SMV_HOME/ &&    cd $SMV_HOME &&    mvn clean install -DskipTests &&    sbt publish-local
 ---> Using cache
 ---> 95e034f50dad
```

Building with the `--no-cache` flag was the obvious workaround, but we have an expensive build and it took quite a while. The ideal build solution would use the cache for spark, maven, and sbt, but not SMV. 

After reading more into [cache busting](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/build-cache) I am still a little bit confused, so I don't necessarily have a clear solution to offer here. However, I think something along these lines -- and then splitting that RUN command on the `wget` SMV master is likely a step in that direction.

@laneb

**Comment by laneb** [comment]
@jacobdr Sorry for the accidentally closing of this issue. 

The desired behavior is to build the most recent SMV without downloading/building SMV's dependencies over again, correct?  This should be resolved when we put SMV on docker hub, so you can download the prebuilt image with the most recent version of SMV instead of building it yourself. That should be coming soon.

**Comment by jacobdr** [comment]
Makes sense, but it still might be a good idea to investigate best practices in the space. I would agree this is not high priority.

One thing about official versioning is that it is unlikely to closely track master since it will likely be done at snapshot intervals. So while it solves the production use case, it doesn't really help a user who wants to use Docker for SMV development -- like me. 

When/if SMV moves to using a CI tool/platform it might also help with us getting faster build times. (Though some CI tools have caching for dependencies like mvn, etc., in which case adding the `--no-cache` flag to `docker build` wont be as expensive)

**Comment by AliTajeldin** [comment]
There are three use cases for the SMV docker image:
1. Users following the tutorial.  For these users, ease of setup is essential.  They should be able to just run the docker image and not worry about mounts, project dirs, etc.
2. Normal users of SMV.  For these users, the docker image is really just a black box app that they can use.  They will most likely use an image from docker hub.  They don't care about tracking latest and greatest.
3. SMV developers.  They will use the docker image as a starting point. They will need to constantly pull/push to the repo and rebuild SMV.  We have not spent too much time designing for this use case and need to take a step back and figure out how to accommodate this particular use case.

Lets keep this ticket open to track the third use case above specifically.  I will change the title of this ticket as well.

**Comment by laneb** [comment]
The official SMV image will be a Docker Hub automated build, so it should track pretty closely to the most recent commits checked in to this repo. For development purposes, we will make available a Dockerfile which only installs dependencies and lets the user build SMV themselves with mvn or sbt in the container.

**Comment by jacobdr** [comment]
I like the progress on this so far -- just saw the recent commits associated with it at 2fa2f77390bd30ddc8c8ebecf4facd4b8cd39e78 and d19ece029f7bf00a0a6b8d20fbacae88e6ce55c8. 

I can confirm that I am not successfully running `sbt '~ compile'` inside of my container, and pairing it with `ddf` inside of the `smv-shell` to reduce my iteration time during application development. 

I think one of the few things remaining is building out the documentation side. Please let me know if I can be of help in any way. 

Strong work @laneb 👍

**Comment by laneb** [comment]
Returning to this issue, what would you like to see from the documentation?

**Comment by jacobdr** [comment]
Closing this issue. Too much has changed. The world turns.
