### ISSUE TITLE
Create a new method to remove description from selected columns

### ISSUE THREAD

**Issue by ShaoyingZhang** [TresAmigosSD/SMV#343]
In certain cases, we want to remove descriptions from columns before operations, such as smvUnpivot,

when we add descriptions to a dataset and then apply smvUnpivot to some of its columns, if these columns do not have the same descriptions,  there will be an error when we resolve this module. 

df.removeDesc("column1", "column2")

@Kai-Chen

**Comment by XiaosenChen** [comment]
we already have this function -_-||||, called smvGetDesc

**Comment by XiaosenChen** [comment]
sorry, called "smvRemoveDesc"
