### ISSUE TITLE
smv-run executor memory hard-coded?

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#347]
I'm not sure that the configuration I have in `spark-defaults.conf` on the cluster is getting respected when I use `smv-run`.

It's possible I am not looking at the correct fields in the SparkUI. But could it be  because of the way that we call out to `spark-submit` from `smv-run`? 

I'm thinking the command-line flags (in this case for executor memory) will always take precedence over the configuration in `spark-defaults.conf` or through environment variables. 

[This is the relevant line](https://github.com/TresAmigosSD/SMV/blob/master/tools/smv-run#L31)

**Comment by Kai-Chen** [comment]
The cmdline does take precedence over `spark-defaults.conf`.  I think it's fair for `smv-run` and `smv-shell` to accept executor memory sizes as an argument.  Should be a quick one.

**Comment by Kai-Chen** [comment]
Examples:
```shellscript
smv-run --executor-memory 6G --driver-memory 2G ...
smv-shell --executor-memory 6G --driver-memory 2G ...
```
Both commands above explicitly set executor and driver memory to their respective default values.

Note that if you run spark in `local` mode, setting executor-memory won't have any effect, as there will be only one executor -- the driver.  In `local` mode, only `driver-memory` will be effective.

**Comment by jacobdr** [comment]
Looks good to me. You may want to double check your softtabs/expandtabs settings in your editor (see the weird spacing [here](https://github.com/TresAmigosSD/SMV/commit/4d6e3cddeb1982f9e0eacba757dbe68269c08623#diff-5147c1ca6ec2cc6cacad7d779bc05647R65)), but that small comment aside, the commit looks good.

👍

**Comment by Kai-Chen** [comment]
You're right ... my home-made IDE is doing things that I told it to, not the things that I meant again.
![both-tab-and-space](http://www.emacswiki.org/pics/static/TabsSpacesBoth.png)
