### ISSUE TITLE
Support Histogram for Groups

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#348]
Enhance current `Edd` functionality so it could be applied to groups in a `DataFrame`.

See also #330.

**Comment by ninjapapa** [comment]
Since we will prefix all the SMV DF helper method with "smv", the interface as implemented in #330 will be changes to #388 for the groupBy case. #388 implemented all other cases without groupBy.

**Comment by ninjapapa** [comment]
The most consistent way for histogram to support grouped data is to make EDD to support grouped data. Will make EDD support grouped data in general.

**Comment by ninjapapa** [comment]
done
