### ISSUE TITLE
[docker] Adding the patched Spark 1.5.2 as part of the image

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#350]
Since the hot-deploy (for fully functional dynamic load) need to use a patched version of Spark 1.5.2, to make our docker image fully support dynamic load, we need to incorporate the patched version of Spark 1.5.2.

**Comment by laneb** [comment]
I will replace the step from the smv-core Dockerfile which downloads a Spark prebuild with a step which downloads and builds the patched version.

**Comment by laneb** [comment]
[done](https://github.com/TresAmigosSD/SMV/commit/1d69c8c2cedf51448750360278d8845108c1247b)

**Comment by laneb** [comment]
Both the smv-core image and the smv image which depends on smv-core now support hotloading.
