### ISSUE TITLE
counting functions in levelRollup result incorrect values 

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#352]
When rolling up a dataframe using levelRollup (from SmvHierarchies), count and countDistinct do not produce the expected result.  

When rolling a table up from NPI to CCN, I expect that, for example

``` count("NPI") as "NPI_cnt```

should count the number of NPIs belonging to each NPI (1) and each CCN (>= 1). Currently this aggregation results in NPI_cnt of 0 for all CCNs. 

My code:
```
object PhysEventHier extends SmvModule("Aggregate NPI payment data to account level") {

    // ...

    override def run(i: runParams) = {
        val df = i(input.NPIPhysEvent).
            smvGroupBy(
                "NPI", "Brand"
            ).agg(
                count("Event_Id") as "Payment_Cnt",
                sum("Payment_Amount") as "Payment_Total"
            ).smvGroupBy(
                "NPI"
            ).smvPivotSum(
                Seq("Brand")
            )(
                "Payment_Total", "Payment_Cnt"
            )(
                "AVASTIN", "STIVARGA",
                //...
                "GILOTRIF", "ERBITUX"
            )

        import df.sqlContext.implicits._

        NpiHier.levelRollup(
            df,
            "NPI", "CCN"
        )(
            sum($"Payment_Total_AVASTIN") as "Payment_Total_AVASTIN",
            // ...
            sum($"Payment_Cnt_ERBITUX") as "Payment_Cnt_ERBITUX",

            count($"NPI") as "Distinct_NPIs_Paid"
        )()
    }
}
```

When running the following in smv-shell

```
df(lung2.PhysEventHier).where("geo_type = 'CCN'").select("Distinct_NPIs_Paid").distinct.show
```

I get the result

```
+------------------+
|Distinct_NPIs_Paid|
+------------------+
|                 0|
+------------------+

```
However, when substituting 

``` count( lit(1) ) as "Distinct_NPIs_Paid" ```

I get the result

```
+------------------+
|Distinct_NPIs_Paid|
+------------------+
|                 1|
|                 2|
|                 3|
|                 4|
...
```

**Comment by laneb** [comment]
Hierarchy:

```
object NpiHier extends SmvHierarchies(
  "geo",
  SmvHierarchy("npi", PhysCcnMap, Seq("NPI", "CCN"))
) {
}
```

PhysCcnMap:

object PhysCcnMap extends
  SmvModule("Map MDM and NPI to CCN according to Gene affiliation map and HCOS-CCN name matching") with SmvOutput {

  override def requiresDS() = Seq(
    input.PhysGeneMaster,
    HcosCcnMatch
  )

```
  override def run(i: runParams) = {
    val df = i(input.PhysGeneMaster)
    import df.sqlContext.implicits._

    val hcosCcn = i(HcosCcnMatch).select(
      $"id" as "ORGANIZATION_ID",
      $"_id" as "CCN"
    )

    df.select(
      "MDM_ID",
      "NPI",
      "ZIP",
      "ORGANIZATION_ID"
    ).joinByKey(hcosCcn, Seq("ORGANIZATION_ID"), LeftOuter)
  }
}
```

**Comment by Kai-Chen** [comment]
Can you reproduce the bug with a small, manufactured test data set?  You can add that to `SmvHierarchyTest`, which has examples for other tests.  I don't think there is any tests for the `levelRollup` function currently.

**Comment by laneb** [comment]
Yes, I have added the requested test to my local of SMV. Should I check it in? Will that break the build until the problem is solved?

**Comment by laneb** [comment]
One note which may help with the debug:

When I was writing the test, I found that this problem only arises when multiple levels are requested in the rollup. For example, the rollup above will count the correct number of NPIs in each CCN if instead of 

```
        NpiHier.levelRollup(
            df,
            "NPI", "CCN"
        )(
            //....
```

we put

```
        NpiHier.levelRollup(
            df,
            "CCN"
        )(
            //....
```

**Comment by Kai-Chen** [comment]
You can check in the test, but use `ignore` in place of `test`.  That won't break the build since the test won't be run (you'd get a message saying that the test is skipped).

**Comment by laneb** [comment]
Test is checked in. Thanks for the guidance!

**Comment by ninjapapa** [comment]
It's either a bug or feature of Spark's "rollup" DF method. The following 
```scala
val df=app.createDF("a:String;b:String", "1,a;1,b;2,b")
df.rollup("a","b").agg(count("b") as "n").show
```

results
```
+----+----+---+
|   a|   b|  n|
+----+----+---+
|   1|   a|  1|
|null|null|  0|
|   1|   b|  1|
|   1|null|  0|
|   2|   b|  1|
|   2|null|  0|
+----+----+---+
```

**Comment by ninjapapa** [comment]
To avoid that, one may need to assign the key column which he want to count on to a new column and then rollup,
```scala
df.selectPlus($"b" as "newb").rollup("a", "b").agg(count("newb") as "n")
```

Need to document this in our API doc.

**Comment by laneb** [comment]
The above was completed by @ninjapapa.
