### ISSUE TITLE
Misleading error for joinByKey when receiver df doesn't contain key

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#357]
No issue with the behavior, but

```
df1.joinByKey(df2, Seq(key), joinType)
```

causes

```
java.lang.IllegalArgumentException: Rename to existing fields
```

if df2 has a column named key but df1 does not. It would be helpful for debugging if a more explanatory error was thrown in this case.

This seems to happen because the keys are only made unique against the columns of df1 (why not also df2?) and no check is made that the keys exist in df1. Seems related to #354.

**Comment by ninjapapa** [comment]
@lanes please feel free to create test case and fix the issue.

**Comment by laneb** [comment]
Will do.

**Comment by laneb** [comment]
Finally done 😉
