### ISSUE TITLE
Add Docker tags other than `:latest` for consumers to pin to 

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#361]
Our project requires extending the SMV base image, but we only have `tresamigos/smv:latest` to extend on. Given the fluid nature of development on the SMV Githhub master branch, it would seem like a better idea for our project's Dockerfile to extend on a fixed image tag.

Currently, the Docker Hub automated build process for the SMV image only creates a single tag for "latest" -- which tracks HEAD on the SMV Github master branch. 

I propose adding additional Docker tags through the automated build process, though not one for every commit, which I think would lead to unnecessary tag clutter. 

Given that we don't yet use semantic versioning, I think a compromise might be to occasionally create Git tags that correspond to the short-hash of commits at certain intervals -- maybe once every two weeks. The Docker Hub automated build process will then create corresponding tags for us in the docker registry. 

Once the project is more mature and we get to semver this will no longer be necessary.

Downstream consumers of the image would then start their Dockerfiles with something like:

```
FROM tresamigos/smv:8c592a9
RUN apt-get update && apt-get install python3 MY_OTHER_PROJECT_DEPENDENCY ...etc
RUN curl -O https://myexternaldata.com/data.csv
......
```

**Comment by laneb** [comment]
@AliTajeldin any thoughts on this?

**Comment by AliTajeldin** [comment]
Some ideas for potential solution:
https://github.com/TresAmigosSD/SMV/blob/master/docs/design/Docker/docker_versions.md

**Comment by jacobdr** [comment]
I disagree with this:

"""
smv-core version should not be tied to the SMV release number. Instead, its
tag should be based on the tool versions it has
"""

While SMV has great testing, I think that once one SMV version has been
vetted a client site we would seek to pin on that.

I have worked with a few different container orchestration platforms and I
have seen they have different behaviors around pulling the "latest version"
of an image.

If I pull, for example, `node:7.7.4`, I would expect that no never change
underfoot. That image will be the same no matter how much time passes.

I would say we should seek the same with SMV. If I
pull `smv:core_jdk8_py35` on one host machine in Month 1, I should get the
same image Month 2. If we don't version on the SMV release tag we would not
get that behavior. What I fear is the situation where Month 1 I pull
`smv:core_jdk8_py35` and get SMV version 1.5.3, and then Month 2 spin up
another host and pull the same image and somehow have a different SMV
version underfoot.

**Comment by AliTajeldin** [comment]
@jacobdr : There is a difference between the `smv-core` and `smv` image versions.   The `smv-core` is essentially a tools image.  It has no code from SMV itself.  As a matter of fact, it should probably be moved into its own repo in the future.  Users will not normally pull the `smv-core` image.  They will use the tagged `smv` image which will have the same tag as the smv version (e.g. "v1.5.2.3").
From the doc:
"""
For the main `smv` docker image, we would tag the release the same as the SMV release.  Docker hub will then trigger the build off of the `v1.2.3.4` tag format.
"""

**Comment by jacobdr** [comment]
Sorry for the misunderstanding. You are completely right. Glad we are aligned.

**Comment by AliTajeldin** [comment]
Done.
