### ISSUE TITLE
Docker build for smv-core times out on docker hub

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#363]
Starting last night at about 8, our automated build on Docker Hub began failing with the message "The build has timed out." The log from one of the failed builds can be found [here](https://hub.docker.com/r/tresamigos/smv-core/builds/bycfpfhkxncfwcyybrvmbke/) (the page contains the full log of the build so it may take a bit to load). A little googling has turned out that this probably results from exceeding the [time limit](https://github.com/docker/hub-feedback/issues/519#issuecomment-168652934) on automated builds - our [build history](https://hub.docker.com/r/tresamigos/smv-core/builds/) on Docker hub suggests that the failed builds each took over 2 hours

I'm not certain of the precise cause. It may be a side-effect to my [recent commit](https://github.com/TresAmigosSD/SMV/commit/1d69c8c2cedf51448750360278d8845108c1247b) switching docker to our patched version of Spark. On its own, the Spark build step of the docker build usually takes over 30 min on AWS with 4g memory and 2 CPUs - Docker Hub provides 2g memory and 1 CPU for the build, and there is no accounting for network latency. However, the build including this commit worked as of yesterday morning, so it may be that there is some variability in the build time on Docker Hub or that something else has changed.

**Comment by jacobdr** [comment]
In looking at the builds -- both successful and failing -- there is just SO
MUCH console output.

This is pretty out there, and I'm not sure how the Docker Registry log
output is implemented, but is it possible that the writing to/ flushing of
STDOUT is contributing to a slower build? Maven seems to be trying to
update on its progress a few hundred times per second -- every couple of KB
downloaded.

Now, even if that is preposterous, modifying the Maven output (reduce some
verbosity, maybe include timestamps?) could help us in debugging failed
builds.

**Comment by laneb** [comment]
I can't wholly discount this theory, but we determined the problem arose after a [recent commit](https://github.com/TresAmigosSD/SMV/commit/19c5663e221a38f512665958ba8f62ac28d8673d) which siwtched from mvn package to mvn install in the Dockerfile. Reverting this commit fixed this problem for now. Moving forward, we plan download a prebuild (which we will host) of this patched version of Spark instead of building it in the Dockerfile, which should help us thin down the image substantially.
