### ISSUE TITLE
Docker images are too big

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#366]
Currently the smv-core image takes about 1.7g and the smv images takes about 2.3g (including the space taken by smv-core as its base). Clearing apt-cache and the maven repo doesn't free up much space. A lot of the space is consumed by the patched Spark build. If we build a binary distribution of Spark the size is much smaller, but Docker Hub has too little memory to run the make-distribution script distributed with the Spark source (fails during the mvn package). We may work around this by building and hosting our own prebuild of Spark, at least until the Spark maintainers pull our (@Kai-Chen's?) patch.

**Comment by Kai-Chen** [comment]
I think for the 1.5 series, it's unlikely that Spark will take our PR.  Miracles could happen, but I don't think Spark has a good track record of back-porting features.  So for 1.5.2, at least, we're on our own.

**Comment by laneb** [comment]
We should be able to make this work for 1.5.2 by attaching the prebuild to a release on github.

**Comment by laneb** [comment]
[Done](https://github.com/TresAmigosSD/SMV/commit/4e0beeaf2b935a64fa3808f2e2bc7a89e025a7f8). The resulting image for smv-core is down to about 1.2g.
