### ISSUE TITLE
Docker image for Jupyter with SMV

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#369]
The current smv-jupyter Dockerfile supports only smv-pyshell (no R or Scala support), and in Jupyter smv-pyshell is identified simply as Python 2 because of the slightly hackish way in which pyspark is enabled. Ideally, an smv-jupyter environment would include a 'kernel' to support each language supported by SMV, and the name would indicate the language supported. Kernels can be configured through a json file, and should require no additional code. I am currently working on one for smv-pyshell.

**Comment by jacobdr** [comment]
I actually got SMV working inside of a Scala Jupyter notebook the other day

I used [this project](https://github.com/andypetrella/spark-notebook) as a starting point, added a local Maven SMV artifact as a dependency, and then shimmied the code from [smv-shell-init.scala](https://github.com/TresAmigosSD/SMV/blob/master/tools/conf/smv_shell_init.scala) into the first cell. 

I will try to dig up my code tomorrow if that would be of any help.

**Comment by jacobdr** [comment]
Actually, here it is:

Dockerfile
```dockerfile
FROM andypetrella/spark-notebook:0.6.3-scala-2.10.4-spark-1.5.2-hadoop-2.6.0
RUN apt-get install -y apt-transport-https
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823

RUN apt-get update && apt-get install -y wget unzip maven sbt

ENV SMV_HOME=/usr/lib/SMV \
    PATH=$PATH:/usr/lib/SMV/tools

RUN wget http://github.com/TresAmigosSD/SMV/archive/master.zip &&\
    unzip master.zip &&\
    rm master.zip &&\
    mv SMV-master $SMV_HOME/ &&\
    cd $SMV_HOME &&\
    mvn install -DskipTests &&\
    sbt publish-local
```

Docker build command
`sudo docker build -t smv-notebook-test .`

Docker run command
`sudo docker run -it -p 9000:9000 -v ~/projects:/projects smv-notebook-test`

Command used to debug
`sudo docker run -it --entrypoint bash -v ~/projects:/projects smv-notebook-test`

And then since the notebook was hosted on a VM, I used ssh local port forwarding so that I could access the notebook at `localhost:9000`

**Comment by laneb** [comment]
When you say that you shimmied the code from smv-shell-init.scala into the first cell, do you mean you copy/paste the code after launching the notebook?

**Comment by jacobdr** [comment]
>
> When you say that you shimmied the code from smv-shell-init.scala into the
> first cell, do you mean you copy/paste the code after launching the
> notebook?


I copied and pasted the code after launching the notebook, and then ran the
cell manually. Creating a cell programmatically did not even cross my mind
could might be interesting.

I should say that I did spent some time looking for a good entrypoint that
would allow me to NOT have to do the copy/paste. For example, consolidating
all the code from that file into a single string which would run in
the 'Default
Import Statement
<https://github.com/andypetrella/spark-notebook/blob/master/docs/metadata.md#default-import-statements>'
config. But that wasn't very clean nor did my implementation work -- though
I need to confess I am new to Scala and so there may have been errors in my
implementation.

Let me know if you have any other questions.

**Comment by laneb** [comment]
Ideally, the startup script would be executed automatically to prepare the environment for the user, but so far I haven't found any clean solutions to accomplish this either. I had hoped that [Toree](https://github.com/apache/incubator-toree) would provide a simple solution for running a startup script like spark-shell does with -i, but at this time Toree does not.
