### ISSUE TITLE
add a zeroFillNumeric to schemaRDD (via implicit)

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#37]
When doing outer joins with some missing data, we often end up with null values that must be individually `NullSub` on the final projection.  For example:
```scala
s1.join(s2, LeftOuter, Option('k1 === 'k2)).
   select(
     's1a,
     's1b,
     NullSub('s2a, 0) as 's2a,
     NullSub('s2b, 0) as 's2ab,
     ...
   )
```

If we add another `s2` field upstream, we must remember to add it to the final projection.
Instead of that, we should provide a method that substitutes all missing numeric values with 0 or 0.0 depending on type.
```scala
s1.join(s2, LeftOuter, Option('k1 === 'k2)).zeroFillNumeric
```

TBD: should we do something similar with strings and date types?  what about maps, lists, etc.

**Comment by ninjapapa** [comment]
May not be a good idea. Since people may over use this function and forget to check whether zero-filling is a right thing or not.

**Comment by ninjapapa** [comment]
Spark 1.3 has `DataFrameNaFunctions` class, which support client code like
```scala
df.na.drop()
df.na.fill(0.0)
```
