### ISSUE TITLE
Support SmvHiveTable in Python

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#373]
Need to support SmvHiveTable in Python.

**Comment by Kai-Chen** [comment]
The main-class `SmvApp`, and the driver scripts `smv-run` and `smv-pyrun`, will accept another option **temporarily**: `--export-as-hive <hive-table-name>`.  When activating this option, the application must have exactly 1 module to run, usually passed to the `-m` option.
