### ISSUE TITLE
Need to provide an option to publish as Hive table

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#374]
In a client project,  we need to make the app output data available to them as Hive table instead of SMV. At least we need to support publish as Hive option, or we could also make all the persists in Hive instead as CSV.

**Comment by Kai-Chen** [comment]
The main-class `SmvApp`, and the driver scripts `smv-run` and `smv-pyrun`, will accept another option **temporarily**: `--export-hive <hive-table-name>`. When activating this option, the application must have exactly 1 module to run, usually passed to the `-m` option.

See Commit df13c78 for issue #373

**Comment by ninjapapa** [comment]
done
