### ISSUE TITLE
Create smv_pyshell_init.py Python init file

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#375]
The proposed solution is to use the PYTHONSTARTUP environment variable to allow pyspark shell to execute the SMV init file before dropping into interactive Python shell.  However, Spark 1.5.2 and 1.6.0 uses `execfile` in pyspark and consequently breaks Python3 compatibility (see [SPARK-12268](https://issues.apache.org/jira/browse/SPARK-12268)).  This would then require us to include the patched content of pyspark directly in smv-pyshell in order to support Python 3 and Spark 1.5.x.

**Comment by ninjapapa** [comment]
may also add this piece of code 
http://stackoverflow.com/questions/12334316/give-the-python-terminal-a-persistent-history
for history persistence. 
So restarting pyspark will still be able to use up-arrow to get to history.

**Comment by ninjapapa** [comment]
done
