### ISSUE TITLE
Check whether the module(s) to run and all the dependencies have parent stages

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#381]
Current SMV will still run even if the specified stage list in the config file does not cover all the modules. 

A common case is that when one create a new stage as adding directory and packages, he forgot to add a new stage in smv-app-conf.profs. 

When that happens, smv should error out when resolving modules in that newly added package, and remind user to add the stage in conf file.

**Comment by AliTajeldin** [comment]
@laneb : As part of the major refactor, I think this is no longer a problem as a module not in a configured stage will not be found.  If confirmed, then let's close this.

**Comment by laneb** [comment]
Right now `S1.X` depends on `S2.Y` and `S1` is a configured stage but `S2` is not, we will not find discover `S2.Y` users will not be able to run `S2.Y` directly. However, I think if one were to run `S1.X`, `S2.Y` would be found and run as a dependency of `S2.Y`.

**Comment by AliTajeldin** [comment]
@laneb Just to clarify, so users will not be able to run `S2.Y` directly but will be able to run `S1.X` directly (which would find and run `S2.Y` as a dependency).

**Comment by laneb** [comment]
Correct.

**Comment by AliTajeldin** [comment]
@Khorkhe please discuss with @laneb

**Comment by Khorkhe** [comment]
fixed
