### ISSUE TITLE
Use config to control whether persist EDD when run in pyspark

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#391]
Currently on python side when a DS get persisted, the EDD will be calculated. It was hard coded like in smv.py. Since EDD calculation is relatively expensive, this feature should be configurable either through command line or config files.

**Comment by AliTajeldin** [comment]
@Khorkhe : confirm this is still the case after the great python refactor.
If not generated, confirm that we can still generate EDD for python code.

**Comment by AliTajeldin** [comment]
Looks like edd is no longer generated as part of the great refactor.  User must specify `--edd` flag to generate edd.
