### ISSUE TITLE
Need a easy way to read persisted EDD (both Scala and Python sides)

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#392]
When `genEdd` flag in the SmvApp is turned on, the Edd is calculated and persisted. However there is not easy method to read in the Edd result into shell and let user to browse through. Need to create a DS level method to support that, and also implement shell command to call that method.

**Comment by laneb** [comment]
Is this still needed?

**Comment by AliTajeldin** [comment]
Yes. I actually think this could be quite handy
