### ISSUE TITLE
Pyshell command `pdf` and `ddf` should use the new runModule interface

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#405]
Current `pdf` is still using `run_python_module`. Should change to `runModule`.

**Comment by ninjapapa** [comment]
Now both `pdf` and `ddf` are calling `runModule`, and we are ready to unify those 2.

**Comment by ninjapapa** [comment]
To utilize dynamic load, actually `ddf` should call `runDynamicModule`. `pdf` should print a message to inform user to use the `ddf` command.

**Comment by Kai-Chen** [comment]
This is already done.
