### ISSUE TITLE
Support oneAgg, runAgg / runAggPlus and smvQuantile of SmvGroupedDataFunc in Python

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#409]
Hope to have below frequently used SmvGroupdData functions supported in python
- [ ] oneAgg
- [ ] runAgg
- [ ] runAggPlus
- [ ] smvQuantile

**Comment by ninjapapa** [comment]
Let's put this on lower priority, (except `smvQuantile`)

Most use cases of oneAgg, runAgg and runAggPlus could also be implemented using Spark native Window function. We need to review extensions on Window functions made by Spark 2.0.x, and then review whether we will keep supporting those 3 methods. Let's hold on porting them.

`smvQuantile` is pretty specific and already implement using Window function, so let port it.

**Comment by sarahnguvt** [comment]
Thanks for the comments. Will use Spark native Window functions for use cases of runAgg alike in python for now.

**Comment by ninjapapa** [comment]
Since all the `runAgg`, `oneAgg` methods are no longer supported and `smvQuantile` interface need to be reviewed, we will close this issue, and open a new one to capture the need for `smvQuantile`.
