### ISSUE TITLE
Maven install fails with UnsupportedOperationException

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#410]
I pulled the most recent version of SMV and tried to build with mvn install. Maven compiles the jar and passes tests but hits this exception when running the sample application:

> Exception in thread "main" java.lang.UnsupportedOperationException: Should not call method on SmvExtDataSet(com.mycompany.MyApp.stage1.inputdata.PythonEmployment) from Scala
> 	at org.tresamigos.smv.SmvExtDataSet.err(SmvDataSet.scala:561)
> 	at org.tresamigos.smv.SmvExtDataSet.requiresDS(SmvDataSet.scala:562)
> 	at org.tresamigos.smv.SmvExtDataSet.requiresDS(SmvDataSet.scala:557)
> 	at org.tresamigos.smv.SmvDataSet.dependencies(SmvDataSet.scala:50)
> 	at org.tresamigos.smv.SmvDataSet$$anonfun$dependencies$1.apply(SmvDataSet.scala:50)
> 	at org.tresamigos.smv.SmvDataSet$$anonfun$dependencies$1.apply(SmvDataSet.scala:50)
> 	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
> 	at scala.collection.immutable.List.foldLeft(List.scala:84)
> 	at org.tresamigos.smv.SmvDataSet.dependencies(SmvDataSet.scala:50)
> 	at org.tresamigos.smv.SmvApp$$anonfun$12.apply(SmvApp.scala:454)
> 	at org.tresamigos.smv.SmvApp$$anonfun$12.apply(SmvApp.scala:454)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
> 	at scala.collection.immutable.List.foreach(List.scala:318)
> 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
> 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
> 	at org.tresamigos.smv.SmvApp.run(SmvApp.scala:454)
> 	at org.tresamigos.smv.SmvApp$.main(SmvApp.scala:499)
> 	at org.tresamigos.smv.SmvApp.main(SmvApp.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> 16/11/04 14:50:39 INFO SparkContext: Invoking stop() from shutdown hook
> 16/11/04 14:50:39 INFO SparkUI: Stopped Spark web UI at http://192.168.0.16:4040
> 16/11/04 14:50:39 INFO DAGScheduler: Stopping DAGScheduler
> 16/11/04 14:50:39 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
> 16/11/04 14:50:39 INFO MemoryStore: MemoryStore cleared
> 16/11/04 14:50:39 INFO BlockManager: BlockManager stopped
> 16/11/04 14:50:39 INFO BlockManagerMaster: BlockManagerMaster stopped
> 16/11/04 14:50:39 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
> 16/11/04 14:50:39 INFO SparkContext: Successfully stopped SparkContext
> 16/11/04 14:50:39 INFO ShutdownHookManager: Shutdown hook called
> 16/11/04 14:50:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-53e56e80-11cb-4ab1-b2ab-8cdcbef3ba06
> 16/11/04 14:50:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-80a15312-b532-4e75-b526-60595786a7de
> 16/11/04 14:50:39 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
> 16/11/04 14:50:39 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 04:22 min
> [INFO] Finished at: 2016-11-04T14:50:39-07:00
> [INFO] Final Memory: 39M/479M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (run-sample-app) on project smv: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
>

**Comment by laneb** [comment]
sbt publish-local is successful, however.

**Comment by Kai-Chen** [comment]
Is this urgent to fix?

We're in the middle of rewiring the internals of SMV to support polyglot application development, where developers can write SMV modules in either Python and Scala.  And we're using the example application as a test before switching officially to the new implementation.

If we need to keep the example project pristine, I will need to create a separate area for testing the new code.

**Comment by laneb** [comment]
As long as this is nothing to be concerned about I can just skip the tests
for my purposes.

**Comment by ninjapapa** [comment]
Or we can temporarily modify the pom.xml to skip the app-test part.

**Comment by Kai-Chen** [comment]
The above-mentioned commit should fix the build error.  Please confirm and close.

**Comment by laneb** [comment]
Confirmed.
