### ISSUE TITLE
Implement reload-on-change for Python SmvModules in smv-pyshell

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#411]
Inside smv-pyshell, we should be able to provide reload-on-change for SmvModules written in Python.  There are probably quite a few mature frameworks that do this already.  But make sure we understand the ins-and-outs of Python module loading and import before we add this feature.  The ideal would be something small and simple, and it only needs to work when the pyshell is started.

There might be some changes we have to make wrt how we're instantiating SmvPyDataSet's, as a result of this feature.  So it's best done after the higher-priority features are complete.

**Comment by AliTajeldin** [comment]
@Kai-Chen need some clarification on what it means to have "reload on change"?  The name implies that there is a daemon or monitor that will reload classes as needed when the underlying FS file changes.  I think that is an overkill for what we need for SMV.  We want a "reload if changed when user says to reload the module" not at any arbitrary time.  If we are to mimic the behavior of the scala class loader then we can just reload the module code and all its parents classes and recursively reload all its dependent modules.  We can use the timestamp of the enclosing file to reduce the amount of modules we reload but that is just an optimization.

**Comment by Kai-Chen** [comment]
We do have that 'reload if changed' capability for Python.  But I think for Python users, having a different `df` operation and a `ddf` operation is a bit foreign, in a similar way that one must *compile* a program before one can run it.  So the aim of 'reload on change' is to provide a Python-friendly feature.

I think the first question would be is this what we want to do, or is the current `df` and `ddf` dichotomy sufficient.  As for implementation, my first instinct is that there should be plenty code that already does this in a number of mature frameworks, so it shouldn't be too involved -- at least not difficult enough that how to do it would influence the choice of whether to do it at all.

**Comment by jacobdr** [comment]
To be clear : what is the current prescribed method for reloading a module in the PySpark shell when there is a code change?

Maybe you could explain the case of a mixed-code repo (so either a Python module change or a Scala module code change).

Thanks.

Jacob

**Comment by Kai-Chen** [comment]
The current method is `ddf` in smv-pyshell.  It reloads the named module and recursively all its dependencies in Python.

Reloading of mixed code dependencies is currently not handled, as it's a corner case: the same developer would usually choose to write in one or the other language, not both.  In the rare scenario where this happens, restarting the shell should do the job.

**Comment by laneb** [comment]
One interesting example of 'reload on change' behavior is supplied by the [autoreload](http://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html) extension that ships with iPython. This might be more than we need, but autoreloading is not enabled until the user explicitly enables it and specifies whether they want to reload all modules or only specific modules marked for autoreload.

**Comment by AliTajeldin** [comment]
Closing as solution proposed in #469 would do the reload on demand.
