### ISSUE TITLE
Run Sample App fails when compiling SMV

### ISSUE THREAD

**Issue by ktlu4** [TresAmigosSD/SMV#413]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (run-sample-app) on project smv: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by ninjapapa** [comment]
duplicated as #410

**Comment by Kai-Chen** [comment]
The above commit should fix the error.  Please confirm and close.
