### ISSUE TITLE
Add option for number of executors/cores

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#415]
SMV spark runners (scala/python, shell/run) should be able to accept a config parameter for the max number of executors.  Should be able to override with environment variable as well.

```
--conf spark.dynamicAllocation.maxExecutors=4 \
 --conf spark.executor.cores=6 \
```

**Comment by AliTajeldin** [comment]
A couple of notes on the environment variables.  The environment variables should somehow map to the option name and should start with `SMV`.  For example:
* `--smv-max-executors` --> `SMV_MAX_EXECUTORS`
* `--smv-executor-cores` --> `SMV_EXECUTOR_CORES`

**Comment by ninjapapa** [comment]
Ideally `smv-run` or `smv-pyrun` should accept a parameter list with mix of spark parameters and smv parameters. Either the shell side need to separate the 2 lists or the SmvApp need to separate them. Here are the 2 options,

## Implement In Shell
Shell need to 
* Parse the parameter list itself
* Maintain a list of SMV acceptable parameter list
* Separate parameters which SMV can't handle 
* Re-construct the 2 list, send to Spark and SMV app separatly

## Implement in SmvApp 
The major issue this way is that not all the Spark parameters can be converted to SparkContext configuration. Therefore the only Spark parameter this method can support is `--conf`, or the aliases to some `--conf`. 
Smv need to
* Maintain a list of acceptable Spark parameters
* Handle them by constructing the SparkConf 

## Pros and Cons
Shell approach should be able to handle all Spark parameters, but it's a little too much for shell to do all this. 
SmvApp approach can only handle `--conf` and equivalent

## Alternatives
Neither of the above 2 is ideal. Should we re-consider the smv running idea? Dose it really belong to SMV or actually the app? Can SMV provide a shell "api" for app to easily create its own runner?

**Comment by AliTajeldin** [comment]
The other options is to use environment variables only and not support command line options.  If user wants to override on command line, then just set the environment variable first:
```bash
$ SMV_MAX_EXECUTORS=5 smv-pyrun ...
```
or
```bash
$ SMV_YARN_QUEUE=myqueue SMV_MAX_EXECUTORS=100 smv-pyrun ...
```

That should work for both shell/run and in scala/python.

**Comment by AliTajeldin** [comment]
A good compromise is to use env variables and command line options for specific/common spark parameters.  These will be looked-up by the `smv-run`/`smv-shell` scripts only.
To avoid having to redefine every spark configuration parameter, we would add a catch-all environment variable for a pass-through to the `spark-submit`/`spark-shell` commands.
The above will also apply to python run/shell as well.
**Note:** every config env variable should have a corresponding flag.  The flag should always start with `smv-` prefix.  The flag has higher precedence 

For example:
```bash
$ export SMV_DRIVER_MEMORY 20G
$ export SMV_EXECUTOR_MEMORY 10G
$ smv-run --smv-executor-memory 16G --master yarn-client
```
In the above, `--smv-executor-memory` command line would override the `SMV_EXECUTOR_MEMORY` environment variable.

## Default Values
In the current `_env.sh`, we extract the spark arguments (e.g. `--executor-memory`) and we **ALWAYS** specify the value (with a default specified in `_env.sh`) on the `spark-submit`/`spark-shell` execution line.  This would override any value specified in the default spark configuration.
Instead, we should only specify the value on the submit/shell command line iff the config was specified as an environment variable or command line flag.

**Comment by AliTajeldin** [comment]
After discussion with @ninjapapa , it was decided that rather than duplicate all the config parameters we actually remove all knowledge of spark configuration parameters from `smv-run`/`smv-shell`.  Instead, we just allow the user to pass through spark parameters to `spark-submit`/`spark-shell` untouched.  For example:
```bash
$ smv-run -m a.b.c -- --master yarn-client --executor-memory 16G ...
```
Everything after `--` is considered a spark parameter and is passed through to `spark-submit`/`spark-shell`

**Comment by AliTajeldin** [comment]
@Kai-Chen : Can you take a look at the above thread of discussion incase we missed something.

**Comment by AliTajeldin** [comment]
This ticket will now convert to modifying `smv-run`/`smv-shell` to use above suggested syntax (along with all the documentation changes).

**Comment by Kai-Chen** [comment]
Old runner scripts used to have a tradition of passing JVM option (in addition to application-specific options) in the form of `-J'<one jvm option per -J>'`.

Eclipse started using the form `-vmargs <all the jvm options together>`, where the `-vmargs` options must come last.

I think either one is fine.  Since generally people tend to group options together, the eclipse style is probably better.  Even if Scallop doesn't support it, should be easy to add on.

Maybe instead of `--` (git uses that), we can have `-sparkargs` or `-spark` to terminate option processing for SMV and pass the remaining to spark-submit or pyspark.

**Comment by AliTajeldin** [comment]
I looked at some of the options above.   Comparing both a pass through flag for each arg and a separator flag:
```bash
$ smv-run -m a.b.c -sarg "--executor-memory=6G" -sarg "--driver-memory=2G"
$ smv-run -m a.b.c -sparkargs --executor-memory=6G  --driver-memory=2G
$ smv-run -m a.b.c -spark --executor-memory=6G  --driver-memory=2G
$ smv-run -m a.b.c -- --executor-memory=6G  --driver-memory=2G
```

I still like the `--` the best.  It is concise and easy to type.  The closest to it is the `-spark` separator.  We can make it an option for the user to specify either `--` or `-spark`.  It is quite easy to implement.

Really don't like the `-sarg` option of having to specify the arg for every spark option.
