### ISSUE TITLE
SmvOutput and SmvPyOutput need to allow specify table name 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#416]
In case that the client application need to save the output to Hive or other database, all the `SmvOutput` modules should know where to store the published (or exported) result. 

This issue is related to #414 .

As both #414 and this implemented, we should be able to create a command to "publish stage to Hive" or "export stage to Hive".

**Comment by ninjapapa** [comment]
Since a client project is depend on this, we will first simply allow `SmvPyOutput` to specify table name without implement anything else.

**Comment by AliTajeldin** [comment]
Should the output table name have the schema name as well?  We decided to have the input table names be the full table name (including schema).  And if the schema needs to be configurable, user should specify a config parameter themselves and pre-pend it to the table name.  How about on the output?  We have two options:
* Be consistent with the input format.  That is, the table name is the full name (including schema) and the onus is on the user to create a pre-pended prefix if it needs to be configurable.
* Create an explicit config parameter for the schema name.

While we will probably always have the same schema for the output and the second option will be perhaps easier for the user.  I'm leaning toward the first option as it is more consistent.

side note: We may need to add a way for SMV to provide config parameters to the user that are available on both the driver and executers.

**Comment by ninjapapa** [comment]
Without many real use cases from multiple clients, it's hard to tell whether it's a common use case that all the output tables should be in the same schema or not. Therefore it's better to leave whether the make the schema name configurable or not to project developer. 

Ideally, as the side note mentioned, if we allow custom config parameters in the conf file, projects can have their own conf, and can specify input schema and output schema.

**Comment by AliTajeldin** [comment]
Opened issue #422 for the user config parameters.
