### ISSUE TITLE
Dynamic load in pyshell does not recalculate module when up stream module changed 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#417]
As in the sample App, 
* Start smv-pyshell
* Do `ddf` on `PythonEmploymentByStateCategory`
* Then modify `PythonEmploymentByState`
* Do `ddf` again on `PythonEmploymentByStateCategory`

The 2nd `ddf` does not re-calculate `PythonEmploymentByStateCategory`.

**Comment by Kai-Chen** [comment]
The `reloadDs` function needs to reload all upstream modules as well ... with the current implementation of force-reloading without detecting change, it's quite inefficient.  A better solution would be to have some form of reload-on-change (see #411)

Another use case that has not yet been taken care of is to re-run if dependencies include an _external module_, and that *external module* has been updated.  This requirement applies to the Scala-side as well.

**Comment by Kai-Chen** [comment]
Will implement upstream propagation for reload for now.
