### ISSUE TITLE
consistent var names in python interface.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#420]
The current python code uses `app`, `smv` interchangeably and often in inconstant ways which leads to confusion.  Sometimes the same object is imported as `app` and other times as `smv`.  Also `app` sometimes refers to the python `SmvApp` instance and other times to the proxy object (which leads to lovely `app.app` references). 
* Need to be consistent with what we import as.  `smv` and/or `app` should refer to the same thing always.
* Need to come up with a naming convention for the proxy objects to distinguish them from the wrapping objects (e.g. add a `j_` prefix or postfix to the name)

**Comment by Kai-Chen** [comment]
What do you think of the following naming convention:
- The name `smv` on the Python side should always refer to the `smv` module defined in the file `smv.py`
- The name `SmvApp` would refer to an instance of Smv, the Python class, this would be become available with `from smv import SmvApp`
- The name `j_smv` would refer to the `SmvPythonApp`, an instance of the facade class in Scala
- And the name `j_smvapp` would refer to the `SmvApp` value in the `SmvPythonApp`.

Example code:

```python
from smv import SmvApp
j_smv = SmvApp._jsmv  # get a reference to the Scala facade instance

mod_names = j_smv.moduleNames(SmvApp.repo)

should_publish = j_smv.publishVersion().isDefined()
```

**Comment by AliTajeldin** [comment]
I like it.  Consistent and clear.

**Comment by Kai-Chen** [comment]
Inside SmvPyDataSet and PythonDataSetRepository, the SmvApp instance is referred to as `smvapp`.

**Comment by AliTajeldin** [comment]
Just did a quick code review.  It is much better, but I think it is still a bit confusing.
* Class `Smv` in `smv.py` is actually a proxy to `SmvPythonApp`.  I think this was the one thing that was most confusing for me.  I kept thinking this is a proxy to smv.  It is not.  There are two level of indirection here.  So lets rename this to `SmvPythonAppProxy` and in turn rename the singleton instance of this to `smvPythonAppProxy` (for any class `FooBar`, instance should be of form `fooBar` so we can find what is it an instance of quickly)
* The above means that the internal member `self._jsmv` is actually **not** smv at all but rather is an instance of `SmvPythonApp`.  Ideally, this would be called `j_smvPythonApp` but that might get too annoying, too fast.  Perhaps something shorter like `j_smvPyApp` (we could even shorten the scala proxy and class to match too if we are very pedantic).

Lets discuss briefly before we implement the changes above.

**Comment by AliTajeldin** [comment]
@Kai-Chen : please add the result of naming discussion here.  I forgot to take a picture of the final mapping.

**Comment by Kai-Chen** [comment]
|Name |Context | Purpose
---------|---------|-------------
`SmvApp` | :red_circle: Scala class | The original SmvApp class and instance
`SmvPyClient`| :red_circle: Scala class | Python entry point, instantiated by SmvPyClientFactory
`SmvPy` | :large_blue_circle: Python class | The Python class connecting to SMV in JVM
`smvPy` | :blue_car: Python instance | The singleton instance of the class `SmvPy`
`j_smvPyClient` | :small_blue_diamond: Python property | References `SmvPyClient` in `smvPy`
`j_smvApp` | :small_blue_diamond: Python property | Shortcut to `j_smvPyClient.j_smvApp()`, references `SmvApp` singleton
`smvPy` | :small_blue_diamond:  Python property | References `smvPy` in `SmvPyDataSet`
