### ISSUE TITLE
SMV docker image requires user id of 1000

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#427]
Users with uid other than 1000 get permission errors when using the docker image:
```
xingyu@ip-172-31-37-13:~$ docker run --rm -ti -v /home/xingyu/apps:/projects tresamigos/smv
mkdir: cannot create directory ‘/projects/.ivy2’: Permission denied
mkdir: cannot create directory ‘/projects/.m2’: Permission denied
rsync: mkdir "/projects/.ivy2" failed: Permission denied (13)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]
rsync: recv_generator: mkdir "/projects/.m2" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) ...
```

This is due to the fact that the mounted `/projects` directory has a uid of 1002 and the docker user (smv) has uid of 1000.  Unless the directory permission is changed to 777 (it really shouldn't), the docker user (smv) will not be able to write to the projects directory.

**Comment by guangningyu** [comment]
There is a discussion about this issue. It seems there's not a Docker way to do it yet.
https://github.com/docker/docker/issues/7198#issuecomment-191990887

**Comment by guangningyu** [comment]
Below is a promising workaround. 
While building the image, we create the user using current user's UID, instead of using UID 1000. In this way, the user in the container and host will be the same, so that the permission problem is avoided. One problem is that it requires each user to build his/her own image. 

------------------------

Managed to solve this using the new dockerfile args. It doesn't require doing anything special after the container is built, so I thought I'd share. (Requires Docker 1.9)

In the Dockerfile:
```
# Setup User to match Host User, and give superuser permissions
ARG USER_ID=0
RUN useradd code_executor -u ${USER_ID} -g sudo
RUN echo 'code_executor ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ${USER_ID} 
```
Then to build:
```
docker build --build-arg USER_ID=$(id -u)
```
Everything else is as normal :)

**Comment by AliTajeldin** [comment]
We tried a similar hack.  In that we tried to change the SMV user id to the user id of the person running the container (then you dont need to do that at build time and can just pass the host user id via env variables or command line options).
One potential issue with the above solutions is if the user id already exists in the image (e.g. id 60, i think, on the aws test system already exists and that was the test user id).  And it just happened that this id was critical and mapping SMV user id to that id caused other things to break.

**Comment by guangningyu** [comment]
Another issue of switching user id when creating the container is that if the user id exists in the host, but it is not created in the image, an error will be thrown in the container that no such user exists.
That's why I think we need to do that at the build time.

**Comment by AliTajeldin** [comment]
We really can't do this at build time.  We need to make SMV a pullable package from dockerhub.  Which means it has to be built in dockerhub.
May need to explore the option of using the root user inside the container as that seems to map to the host user (at least on macs.  need to further test on unix).

**Comment by AliTajeldin** [comment]
Increased priority as it was impossible to build release on AWS with current docker user different than host user id. :-(

**Comment by AliTajeldin** [comment]
The solution is to make sure the docker image is run as root only.  We should not create or switch to smv user inside the docker image as we do not know what the user id of the smv user should be.  Instead, we should wait until `entrypoint.sh` is called when the image is run and we should accept an optional user id from the user.  That user id is then used to create the smv user at that point.  Did some quick timing tests and `useradd` on image entry does not add noticeable overhead.  Because the smv user id will match the user id of the calling user, we should be able to access host files without worry.
For example:
```bash
$ docker run --rm -it smv -u $(id -u) bash
``` 
Note that `$(id -u)` will map to the user id on the host.

**Comment by AliTajeldin** [comment]
Done
