### ISSUE TITLE
Create a SMV server that exposes a REST api for third party apps to submit SMV operations

### ISSUE THREAD

**Issue by guangningyu** [TresAmigosSD/SMV#428]
We should create a SMV server that exposes a REST api for doing SMV operations (e.g. project discovery, code for module, run module, get module output sample, etc) for third party applications.

**Comment by AliTajeldin** [comment]
This still needs a design document under `docs/design/SmvServer` directory.  Sorry for not catching that earlier.  Just a high level view of what we are trying to do and at least a high level class diagram of the components of the server.  Some explanation as to how this will tie with the current python implementation, etc.

**Comment by Kai-Chen** [comment]
Please ignore message in commit 287bb03: wrong ticket number
