### ISSUE TITLE
Support discoverSchema in python

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#438]

**Comment by ninjapapa** [comment]
The key question is how to pass in `CsvAttributes` on the Python side. Need to review is there a Spark "native" way to specify CSV attributes. If so, need to make sure our function interface is consistent with it.

**Comment by Kai-Chen** [comment]
In `SmvPyCsvFile` there are currently helper methods to create different `CsvAttributes`.  These can be pulled into `SmvPy`.

On another note, the factory methods for DQM-related classes, which are currently in `SmvPyDataSet`, probably should also be pulled into `SmvPy`. and made available there.

**Comment by Kai-Chen** [comment]
Please close the ticket after verifying that `discoverSchema` works in `smv-pyshell`

**Comment by sarahnguvt** [comment]
Many thanks it works in `smv-pyshell`.

**Comment by Kai-Chen** [comment]
You're very welcome.
