### ISSUE TITLE
port smvNullSub to python

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#440]

**Comment by ninjapapa** [comment]
This one is questionable. Since Spark has a native `coalesce` function which is exactly equivalent to `smvNullSub`. I actually prefer to deprecate `smvNullSub` on both Scala and Python side.

**Comment by sarahnguvt** [comment]
makes sense. will remove from python side first.

**Comment by sarahnguvt** [comment]
close this and any change at scala side will be another issue.
