### ISSUE TITLE
Make SmvApp Thread-Safe

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#443]
Originally, the `SmvApp` singleton was designed to run a single SMV Application.  With the requirement of #428 to expose its functionality through a REST server, the various mutable states (`resolveStack`, `dataframes` etc) in `SmvApp` should be made thread-safe.

**Comment by AliTajeldin** [comment]
@Kai-Chen : I think we can go ahead and close this as will-not-fix.  We can put the onus on the caller (e.g. rest api) to make sure calls to a single SMV application are serialized.  Not that hard to do with the python PIL.

**Comment by Kai-Chen** [comment]
A note before closing: `SparkContext` itself **is** threadsafe; multiple threads can submit jobs to the same shared `SparkContext`.

There is only 1 `SparkContext` per JVM (see [Spark Issue 2243](https://issues.apache.org/jira/browse/SPARK-2243))  There are other middleware projects that manage multiple SparkContext mentioned in discussions around that ticket.
