### ISSUE TITLE
Provide dependency graphing in smv-pyshell

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#445]
Rendering of the graph in ascii art can be simply forwarded to the implementation in Scala.  The Python side needs to build the dependency graph.

Need a data structure to represent the graph in Python; it needs to be easy to convert to the data structure in Scala.

**Comment by AliTajeldin** [comment]
We shouldn't duplicate functionality on the python side.  The python side should not be building the dependency graph. The python side should just request the ascii dependency graph from the scala side and echo it out to screen.

**Comment by Kai-Chen** [comment]
This is correct and the implementation should be done in accordance with the above comment after issue #450 is implemented.
