### ISSUE TITLE
Merge smv image and smv-jupyter image

### ISSUE THREAD

**Issue by guangningyu** [TresAmigosSD/SMV#452]
The size difference of the two images is small (1.412GB vs 1.488GB) and does not worth splitting.
One thing is that the entrypoint of the `smv-jupyter` image will start the jupyter notebook automatically. Need to confirm that nobody is using this feature.

**Comment by laneb** [comment]
@ninjapapa Is `smv-model` (which depends on `smv-jupyter`) used right now? If not I will delete both.

**Comment by laneb** [comment]
Done.
