### ISSUE TITLE
Broken links to documentation re: supporting spark command line parameters

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#453]
The bottom two links on the page are broken:

https://github.com/TresAmigosSD/SMV/blob/master/docs/announcement.md

**Comment by laneb** [comment]
We may be able to delete this announcement at this point. Thoughts, @ninjapapa?

**Comment by AliTajeldin** [comment]
Yah, let's go ahead and delete this.  It is quite dated.  Close this ticket once the announcement is deleted.

**Comment by laneb** [comment]
Done.
