### ISSUE TITLE
smv-Jupyter looking for project jar under Notebooks dir

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#461]
17/01/23 14:34:55 ERROR SparkContext: Jar not found at file:/Users/xiaosenchen/NeoDM/notebooks/target/scala-2.10/neodm-1.5-SNAPSHOT-jar-with-dependencies.jar

**Comment by AliTajeldin** [comment]
This could be related to #462

**Comment by ninjapapa** [comment]
smv-jupyter should run on the project root. User doc should have a session to address how to use smv-jupyter.
