### ISSUE TITLE
Need to develop a quick start guide

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#463]
Need an overall quick start guide for SMV that doesn't delve into details.  Just follow a recipe to get going.  Should standardize on docker rather than the full install + build or the binary release.  This is essentially an abridged version of the `getting_started` + `install` docs that already exist under the user doc.
This should be at the top level README so visitors to the main page can have a quick way to get going with SMV.

**Comment by AliTajeldin** [comment]
**Note**: This depends on the work done in #470 to generate a very simple minimal app.

The quick start guide should just focus on creating the simple app, running a module, modifying the module and rerunning to see the new result.  It should skip all the philosophical introduction to SMV and the whole DataSet hierarchy.

**Comment by cloudysail** [comment]
Some feedback of using Quick Start:
1.Installation
I think giving some general description of using Docker could make users feel more comfortable. Such as: The docker run command would download the published SMV image from docker hub. It contains(I guess) all the softwares needed to run SMV such as Scala, Spark, Python, etc. The total size to download is about xxx MB.

2. Create Example App
There is already a defualt project called 'MyApp' created like below
user@smv:/projects$ ls
MyApp 
So I suppose there is no need to run `smv-init -s MyApp`.  If users need to create new projects, they should use `smv-init -s MyProject com.mycompany.myproj` and build it using `sbt assembly`?

3. Run Example App
The output data path is too old. It is now `data/output/org.tresamigos.myapp.stage1.employment.EmploymentByState_...`.
Also, it's really not user friendly to access/modify the project files in command line. I guess this file system is built-in VM file system within Docker, but still it would be nice if we can do this in external tools like IDE.

**Comment by AliTajeldin** [comment]
@cloudysail 
1. A blurb about potential data size with docker use will be included.
2. The MyApp project under /projects is a prebuilt project directory used by SMV server.  It is a bit confusing naming it `MyApp`.  A new ticket (#501) has been created to fix the name issue. You should still create your own project directory with something like `smv-init -s SampleApp` (note only a single arg is now required)
3. paths fixed.
3.5. Using docker with IDE.  The example app uses the projects directory in the docker VM.  In real world scenario, the user would mount the `/projects` directory from the local host so that the changes are persisted across VM restarts and allows the user to use favorite editors/IDE on the host to modify the files.  A new issue (#502) has been created to document this use case in the user guide.
