### ISSUE TITLE
standardize on sbt

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#464]
Rather than maintain both a maven and sbt build configurations.  Just pick `sbt` and go with it.  Should probably include the sbt primer script as part of SMV so users don't have to download sbt explicitly.

**Comment by AliTajeldin** [comment]
Need to make sure all tasks that are being performed in `pom.xml` are duplicated in `sbt` before we abandon maven.
* site deployment
* doc generation
* integration test running
* install smv R packages during compile phase.

**Comment by laneb** [comment]
Integration test can now be run with `sbt itest`. Before running the sample app, sbt will perform a `publish-local`. Unit tests and integration test can be run together with `sbt alltest`. Additionally, the integration test itself now uses sbt instead of mvn to build the sample app.

**Comment by AliTajeldin** [comment]
Done
