### ISSUE TITLE
Upgrade to Spark 2.1

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#466]

**Comment by Kai-Chen** [comment]
The library `asciigraph` has currently no build for scala-2.11.  New commits are being checked in, and there is a PR for 2.11 build, but it didn't get merged and is now failing.

**Comment by Kai-Chen** [comment]
@ninjapapa

Just noting that a `stddev` function is introduced in the `o.a.s.sql.functions` namespace, which collides with the `stddev` object in the `o.t.smv` namespace, defined in `AggFuncs.scala` as a `UserDefinedAggregateFunction`.

The port will continue to use the `stddev` in the `smv` namespace.  But may need to see if the Spark implementation is stable enough (meaning without the quirks found in earlier `first` etc) to switch to.

**Comment by Kai-Chen** [comment]
All smv-related functions are ported after this commit, except for asciigraph, which doesn't have a build for scala 2.11.  Also maven's pom.xml is not yet checked in.

This port is waiting to be merged into the main after a final release of the 1.5 line.

**Comment by AliTajeldin** [comment]
@Kai-Chen : let's also check-in a working `pom.xml` file as well.  Until we make a complete move to sbt (#464) and find a way to either install or have an sbt stub(#507), most people will probably continue to use maven.

**Comment by hubertp-lshift** [comment]
Re: asciigraph - you might be better off forking the project and pulling it into your own repo. Given a recent change (https://github.com/mdr/ascii-graphs/commit/61fb705456983f9410ac14818472c1ae94ea3fb8) it looks to me that the maintainer is more likely to release 2.12.x, rather than 2.11.x. And the PR for 2.11.x has been there for 2 years.

**Comment by Kai-Chen** [comment]
Yes, we've considered that option and have decided to find a better way to visualize module dependency trees.

**Comment by hubertp-lshift** [comment]
@Kai-Chen Do you have a list of tasks that still need to be completed for this to move on? I've been playing around with 2.1 branch and would be happy to pick up sth if needed.

**Comment by ninjapapa** [comment]
We will highly likely to have a full review of the 2.1 branch this week, and tag a version, then move forward with full speed. 

The key decision need to make is actually on what to do with the earlier versions.

**Comment by ninjapapa** [comment]
A new tag was created on the 2.1 branch: v2.1.0-prerelease-2.
It passed all the tests and functions are in-sync with the v1.5.2.5 release, except the ascii graph. 

For the next a couple of weeks, the master branch will still be on 1.5.2 and have some cleanups. Those cleanups will also get merged to the 2.1 branch. After about 2 weeks, we will shift the master to 2.1.

**Comment by hubertp-lshift** [comment]
I would be happy to fix all those warnings related to the upgrade. It looks pretty ugly when you do a clean compile.

**Comment by jacobdr** [comment]
👍

Jacob

**Comment by ninjapapa** [comment]
@hubertp-lshift Thanks for taking this! Please go ahead and do so. 
May need to do a pull request when done.

**Comment by hubertp-lshift** [comment]
@ninjapapa Sure. I will send one soon'ish.
Also I noticed that this (or maybe the 1.x version as well?) branch has some memory leaks. Running 'test' in the sbt console will quickly build up used Metaspace. I will see if the profiler can point me to something quickly.
