### ISSUE TITLE
Pass through options to `smv-jupyter`

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#467]
Can we pass through the arguments to the `smv-jupyter` command after the double-dash?

I want to to be able to do something like this: `smv-jupyter -- --master=yarn-client`

[`smv-jupyter` code](https://github.com/TresAmigosSD/SMV/blob/master/tools/smv-jupyter#L10)

Reference:
https://github.com/TresAmigosSD/SMV/blob/master/tools/smv-pyshell#L24

**Comment by AliTajeldin** [comment]
I like this idea.  It is consistent with how `smv-pyrun` works today.

**Comment by AliTajeldin** [comment]
@jacobdr : this looks like it is fixed now.  Can you confirm and close if so.

**Comment by ninjapapa** [comment]
done
