### ISSUE TITLE
ls inside smv-pyshell does not work

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#468]
`ls` inside the SMV python shell does not report the correct list of available modules.

**Comment by jacobdr** [comment]
Reproduce:
1. `smv-init`
2. Alongside "src/.../python/.../stage{1,2}", create a new stage called "mystage" (adding an \_\_init__.py)
3. Create a file (e.g. inputdata.py) with a module inside of of it that does not link to the other stages. (I have not tried this with linking, not sure if that affects reproductino)
4. Open the `smv-pyshell` and run `ls()`. 

Stage 1 and Stage 2, and their constituent modules, are present in the output. The stage name "mystage" is present in the output, but not the module that we created within that stage.

**Comment by laneb** [comment]
This should be resolved through #469.

**Comment by ninjapapa** [comment]
`graph()` and `graph("stagename")` works now.

**Comment by ninjapapa** [comment]
done
