### ISSUE TITLE
python code refactor part deux (DataSetMgr)

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#469]
From a very high level, we need to return to having all our code variance captured by creating different SMV module types rather conditionals throughout the code.  Part of this refactor must do the following:
* isolate dependence on Repo to new DataSetMgr class.
* Create a base Repo interface (which means we need a scala repo to make the code language agnostic)
* Design must allow for Scala <-> Python module integration (including in/out stage links)
* Reduce number of caches in the code to make dynamic loading easier.
* Ideally, use a single interface for normal module load, dynamic module load, R interface module load.
* Remove any duplicate functionality from the python side (e.g. current publish code).

See current design docs in https://github.com/TresAmigosSD/SMV/tree/master/docs/design/DataSetMgr

**Comment by laneb** [comment]
The design for this refactor is documented in docs/design/DataSetMgr. It will be carried out in the loaduni branch.

**Comment by laneb** [comment]
Because module discovery is somewhat slow, the refactor should ensure that an invocation of `smv-pyrun` does not carry out the discovery of output modules twice. Particularly, it should only query the Python repository for the output modules of a stage, or for all output modules in the case of `--run-app`, once.

**Comment by laneb** [comment]
Refactor is complete and merged with master. The docs should be updated to reflect design decisions made along the way.
