### ISSUE TITLE
split smv-init into three different types of initial apps

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#470]
The current app generated by `smv-init` is serving two purposes:
* Initial project application template for a large project.
* A sanity check integration test.

With the growing complexity of the app, it is not serving either purpose very well.  This ticket is to split the current functionality into three different apps:
1. integration test: full integration with following types of modules:
    * python -> scala -> python dependency
    * scala -> python -> scala dependency
    * scala -> scala (in same and different stages)
    * python -> python (in same and different stages)
    * scala - > python (in different stages)
    * python -> scala (in different stages)
2. Simple app: Most minimal app possible.  This should only have a single python module with a single csv file input.  Both should reside in a single python file for ease of understanding.  The `run` method of the module should also be very simple.  Perhaps just a simple where clause.  This app would be used in the quick start guide to get the user going.
3. Enterprise app: This app is used for creating best practice initial app for large projects.  It should provide a multi-stage python application (no scala modules).  Just a single module in each stage should suffice with the module in the second stage linking to the module in the first stage.  Best practice dictates that each stage should have the `input.py` file that lists all the files/links.

Rather than create 3 different `smv-init` scripts.  We should probably just parameterize the current `smv-init` app.  Perhaps:
* `-test` : generate the integration test app
* `-simple` : create the simple app (should be the default if no flag is specified)
* `-enterprise`: create the full best practice enterprise app.

**Note:** The `-test` and `-simple` apps do not really need to take a parameter for the project package names.  We can hardcode the project names to make the tests and quick start easy to write without the need to make them parameterized.   The `-enterprise` app template should take the base package name though.

**Comment by Khorkhe** [comment]
@laneb as previously discussed, when using the -s (simple) flag, we overwrite the user-specified "com.company.xyz" with "org.tresamigos.myapp"

command to run the simple project:
`smv-pyrun -m org.tresamigos.myapp.stage1.employment.EmploymentByState`

**Comment by laneb** [comment]
Most of this issue has been completed as described. What is left is for me to complete the integration test cases.

**Comment by Khorkhe** [comment]
it was eventually decided to remove the base package name parameter for all project types:
 - the simple and enterprise projects are pure python and do not need a base package name
 - the test projects have the package name hardcoded in the template files

**Comment by Khorkhe** [comment]
Fixed
