### ISSUE TITLE
Remove extraneous print statement (or move it to logging)

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#475]
Came across this in my logs:
```
starting callback server on port 25334
```

Looks like it comes from [here](https://github.com/TresAmigosSD/SMV/blob/24cf68719ffe48fe78b5b2ad827847697cc5485a/python/smv.py#L187)

Looks like in general there might need to be a more structured logging push in general (notably at the debug levels), but in the meantime wanted to create a ticket for this one orphan instance that prints to the screen without any context.

**Comment by ninjapapa** [comment]
I don't think this one should go to logs. 
This message is part of the "temporary" solution of #401. 
It will be removed if we have a better way to address #401. Otherwise it's part of the starting message of smv-shell. Message itself should be enhanced though.

**Comment by laneb** [comment]
@ninjapapa how should the message be enhanced?

**Comment by ninjapapa** [comment]
@laneb since at the starting point there are info from Spark itself and SMV, at least the message should indicate it is an SMV message. Also may need to indicate it is a Py4j callback server, which at least provides a hint of what this thing is about. I don't know what else should be there.

**Comment by laneb** [comment]
Done.
