### ISSUE TITLE
smv-pyrun --run-app does not run all Python output modules 

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#478]
smv-pyrun --run-app should run all output modules in a project. This command currently appears to run all the Scala output modules but only those Python modules on which the Scala modules depend.

A quick way to replicate:

* Generate the integration test sample project with
```smv-init -s MyApp com.mycompany.myapp```

* Compile, then run with
```smv-pyrun --run-app```

`stage1.PythonEmploymentByState` will run, ostensibly because `stage2.StateEmpCategory2` depends on it. `PythonEmploymentByStateCategory` will not run - no Scala module depends on it. Both Python modules are SmvPyOutput.

**Comment by AliTajeldin** [comment]
Even though this will change considerably once we implement #469, we should do this ASAP as multiple clients are affected by this.

**Comment by laneb** [comment]
Fixed.
