### ISSUE TITLE
Add smv flag to ignore persisted intermediary files.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#481]
Need a `--force-run` or `--ignore-cache` flag to SMV that will tell SMV to ignore the persisted cache files and force the run of all modules even if a persisted file exists.

The current workaround is to delete the output data directory.

This should be implemented after #469

**Comment by laneb** [comment]
Done.

**Comment by AliTajeldin** [comment]
Need to add the command line flags to the user docs.

**Comment by laneb** [comment]
Done.
