### ISSUE TITLE
discover modules without using pkgutil.walk_packages

### ISSUE THREAD

**Issue by Khorkhe** [TresAmigosSD/SMV#482]
in smv.py, we iterate over pkgutil.walk_packages searching for packages that contain a given stageName.

This iterating is causing Python to crash and exit unexpectedly, after smvapp.py finishes executing.  The behavior so far can be reproduced only on my system, and it occurs only upon iteration of walk_packages (even if the loop content just passes).

**Comment by AliTajeldin** [comment]
@Khorkhe : please document the alternative we discussed here in more detail (using `import` and `dir()`).

**Comment by Khorkhe** [comment]
```
import com.a.b
```

allows us to see the modules inside of `com` and `a` as follows:

```
dir(com)  # lists 'a'
dir(com.a)  # lists 'b'
```

We want to explore the contents of module `b` which were not imported yet.  The command below would not list that:

```
dir(com.a.b)  # nothing useful
```

An alternative backup plan solution would be converting `com.a.b` to a path, and explore the subdirectories of the dirs using the `os` module, to find the module names to be imported

**Comment by Khorkhe** [comment]
The initial issue with walk_packages is that it has to import all the modules it iterates over, and some modules would cause a python crash on my system.

A cleaner alternative was to specify the given stage's path and name as parameters to walk_packages, hence restricting the search to only the stage's path.

This implementation also fixed the python crash on my system.
