### ISSUE TITLE
Redesign `SmvEntityMatcher` interface

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#483]
Current document is not clear. Need an overhaul.

**Comment by ninjapapa** [comment]
Actually need to redesign the `SmvEntityMatcher` interface. Current interface has the following issues:
* Names of `ExactMatchFilter`, `CommonLevelMatcherExpression`, `ExactLevelMatcher`, `FuzzyLevelMatcher` are too long and confusing
* Has assumptions on input data's ID column names
* Add `_` on right tables (user need to know the right table columns were renamed when write expressions)

**Comment by ninjapapa** [comment]
Client code of new interface
```scala
val mchr = SmvEntityMatcher("id1", "id2",
    ExactMatchFilter("Full_match", ($"fullName1" === $"fullName2") && ($"aID1" === $"aID2")),
    GroupCondition(soundex($"lastName1") === soundex($"lastName2")),
    List(
        ExactLogic("Level1_full_name", $"fullName1" === $"fullName2"),
        FuzzyLogic("Level2_levenshtien_first_name", null, levenshtien($"firstName1", $"firstName2"), 0.9)
    )
)

val res = mchr.doMatch(df1, df2)   //By default output all columns
```

**Comment by ninjapapa** [comment]
Python client code
```python
mchr = SmvEntityMatcher("id1", "id2",
    ExactMatchFilter("Full_match", (col("fullName1") == col("fullName2")) & (col("aID1") == col("aID2"))),
    GroupCondition(soundex(col("lastName1")) == soundex(col("lastName2"))),
    [
        ExactLogic("Level1_full_name", col("firstName1") == col("firstName2")),
        FuzzyLogic("Level2_levenshtien_first_name", None, levenshtien(col("firstName1"), col("firstName2")))
    ]
)

res = mchr.doMatch(df1, df2)
```

**Comment by ninjapapa** [comment]
Since new client code will be mainly on Python side, and we don't have `SmvEntityMatcher` ported to Python yet, to make the transition backward compatible, will do the following:
* Create a new `SmvEntityMatcher2` Class on Scala side
* Build Python interface to `SmvEntityMatcher2`

When all project code migrated, we will retire current interface and rename `SmvEntityMatcher2` to `SmvEntityMatcher`.

**Comment by ninjapapa** [comment]
Created branch `matcher2` for issue.

**Comment by AliTajeldin** [comment]
We should have a quick whiteboard session to discuss the new interface.

**Comment by ninjapapa** [comment]
After review, there are 2 more changes:
* Rename `ExactMatchFilter` to `ExactMatchPreFilter`
* Rename `matcher` package to `matcher_old` and `matcher2` to `matcher`

**Comment by ninjapapa** [comment]
done
