### ISSUE TITLE
Dependency checking with `smv-pyrun -m` takes very long

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#487]
When use `smv-pyrun` with `-m` and 5 output modules, the process stoped at
```
..checking dependency rules for all modules
```
for minutes.

**Comment by ninjapapa** [comment]
9 minutes on client powerful gateway machine. Checks are all passed eventually. Must be something wrong.

**Comment by ninjapapa** [comment]
Behave the same as in tagged version v1.5.2-pre-uniloader.

**Comment by laneb** [comment]
When the dependencies are checked it's for all of the modules that will be run, not just the output modules. If the dependencies consist of a great deal of Python modules then Py4J latency might be contributing to the slowdown.

**Comment by laneb** [comment]
Also, it appears that it is no longer necessary to for SmvApp's run() to check module dependencies (which is what is happens when that message is printed), because they are also checked in resolveRDD(). Per @Kai-Chen, we previously checked them in run() because run() did not delegate through resolveRDD() for DataFrames. I have removed this redundancy on the loaduni branch, which should be ready for merge fairly soon.

**Comment by Kai-Chen** [comment]
Odd that I didn't get notified with the mention.  That's happened quite a few times and I heard with other people, too.  So using the `@` is definitely not reliable enough a way to contact.

Encapsulating all python modules with a Scala module does have its cost.  And here is one of the manifestations.  I think we can improve quite a bit by collecting the dependencies in Python and ship it all over to the Scala side, as we (Lane and I) discussed briefly.

On the other hand, it might be better to actually profile the app first, to make sure that the socket communication really *is* the bottleneck, not the check algorithm itself.

**Comment by ninjapapa** [comment]
Tried the same client code on loaduni branch. There is no significant delay (comparing with 9 min before) on that branch.

**Comment by ninjapapa** [comment]
Will close this when we merge loaduni into master.

**Comment by laneb** [comment]
Merged.
