### ISSUE TITLE
Delete smv-jupyter docker image if it not used.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#492]
It appears we combined `smv-jupyter` and `smv` docker images into one.  We should probably delete the old jupyter image/Dockerfile (https://github.com/TresAmigosSD/SMV/tree/master/docker/smv-jupyter)

**Comment by AliTajeldin** [comment]
same goes for `smv-model`.  Is this being used anywhere?  Can it be combined with `smv` image.

**Comment by jacobdr** [comment]
AXE FIGHT! Off with their heads.

**Comment by laneb** [comment]
There's no docker-hub repo for `smv-model`, so anyone that could be using `smv-model` must be using it themselves. I would suggest that if they want all of those dependencies they should just take the `smv-model` Dockerfile and create their own build. `smv-model` is just `smv` with a bunch of pip packages added for a specific use case.

**Comment by laneb** [comment]
Closing this issue as duplicate of #452. Waiting for confirmation from @ninjapapa that we can delete `smv-merge` and then I will delete both.
