### ISSUE TITLE
Create prebuild SMV package

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#495]
Since we are under a quick developing phase. For outside people who may want to try out SMV, there is a risk that they just run into a commit which cause some issues. We can build some pre-build version like spark and make the "trying" process as simple as possible.

**Comment by AliTajeldin** [comment]
We used to do this as part of the `site-deploy` phase in the `pom.xml`.  We need to do the same using the sbt build.  May need to revive this for the short term due to large changes happening in the short term on master.

**Comment by AliTajeldin** [comment]
I stand corrected.  Just tried the `site-deploy` and the generated github site only has the docs and **not** the prebuilt binary.

**Comment by laneb** [comment]
Instead of (or at least in addition to) creating a pre-build package, would could tag a :stable version of the docker image so that docker users aren't stuck with the bleeding edge. We could push it to docker hub manually, or we could create an automated build that downloads a stable github tag.

**Comment by AliTajeldin** [comment]
@laneb : agree on the stable docker version.  We should create a release naming standard for SMV and have the binary release and docker release for each stable SMV release.

**Comment by AliTajeldin** [comment]
Done
