### ISSUE TITLE
Unbalanced Join Management

### ISSUE THREAD

**Issue by daStrauss** [TresAmigosSD/SMV#496]
Feature request for handling joins with uneven numbers of items per join key. 

For example. If I'm joining dataset A against dataset B where dataset B has one item per key while in dataset A, we may have:

key1: 2million records
key2: 200 records
key3: 2 records
....

It is often better to filter the dataset into two components:
- the `heavy_hitters` with more than a ~million items per-key and do a map-local join
- the rest where a distributed join is fast and adequate.

Once both joins have completed, taking a union of the resulting datasets provides the fully joined dataset.

Naively doing a distributed join typically results in OOM errors on the worker that ends up with one of the very large keys.

**Comment by AliTajeldin** [comment]
@daStrauss : I'm assuming that the caller knows ahead of time which keys are the "heavy hitters" and we don't need to do discovery.

**Comment by AliTajeldin** [comment]
Because it is often known what the list of heavy hitters are ahead of time (e.g. null values or some sentinel account number), we shouldn't create a helper function that always tries to discover the top-N values.  But we still need to handle the case where the user does not know the heavy hitters ahead of time.  Therefore, it might be best to implement this as two separate interfaces.
1. One api call to discover the heavy hitters.  Either find top-N or all keys with > some threshold values.
2. Second api to do the broadcast join on the heavy hitters and merge with the normal join on the rest of the data.

Note that the api must be designed to make it easy for the user to chain the above two calls.  That is the rest of the first api should be able to be used directly as input to the second api.

**Comment by laneb** [comment]
The design described sounds good to me. @AliTajeldin I see that DataFrame helper methods are mostly implemented in Scala and ported to Python across the proxy. Is that preferred over implementation in Python?

**Comment by AliTajeldin** [comment]
@laneb Correct.  Looks like scala is not completely dead yet.  Let's create the functionality on the scala side and add DF helpers on the python side.
Note:
* need to create a branch and a PR for this.
* need to document the proposed API below before starting.

**Comment by laneb** [comment]
Python API would look like
1. get "heavy hitters" with `df.topNKeysByFreq(n)`
2. perform join with `df.skewJoin(other, on, how, skewKeys)`
which could be combined like
```scala
scala> df1.skewJoin(df1, df1.myKey == df2.myKey, "inner", df1.topNKeysByFreq(5))
```
We could also allow
```scala
scala> df1.skewJoin(df1, df1.myKey == df2.myKey, "inner", 5)
```

**Comment by AliTajeldin** [comment]
* Wouldn't `topNKeysByFreq()` need to know which column to count?
* What is the return of `topNKeysByFreq()`?
* For the case where we know who the top hitters are, how do you specify that to `skewJoin`
* I think we shouldn't allow the implicit `5` in the second usage of `skewJoin`.  I prefer explicit call to `topNKeysByFreq`

**Comment by laneb** [comment]
- Yes, and `skewJoin` needs to know which of `other's` columns is skewed for which keys. Edited.
- Array of keys (whatever type the keys are)
- `df1.skewJoin(df1, df1.myKey == df2.myKey, "inner", "myKey", ["mySentinel"], "myKey", ["mySentinel"])`

**Comment by laneb** [comment]
For simplicity in the case that the keys match, we could also provide `df.smvSkewJoinByKey(other, col, skewKeys, how)` so that the previous example becomes 
```
scala> df1.smvSkewJoinByKey(df2, "myKey", ["mySentinel"], "inner")
```

**Comment by AliTajeldin** [comment]
Slight reorder of arguments to make the right key an optional parameter.  I think for the short term, we could assume an equality join condition (that is `df1.left_key == df2.right_key`).  We can always add a condition in the future but I think for this case, it is almost always equality. @jacobdr  . can you confirm if the client case would be using an equality join condition.
```scala
df1.smvSkewJoinByKey(df2, join_type, skewed_values, left_key, right_key=left_key)
```

Side note, let's avoid using the term key for the skew values.  The key is usually the column name (i.e. join key).

**Comment by laneb** [comment]
Done.

**Comment by laneb** [comment]
Need to add a section about this to the user doc.

**Comment by laneb** [comment]
Actually, none of the `DataFrameHelper` methods are currently documented in the user docs - there is just a link to the API doc. I will leave this as is until such time as we decide the user docs need more detail on the `DataFrameHelper methods.
