### ISSUE TITLE
Add info about using docker with SMV

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#502]
Need a section at the beginning of the user doc on how to use SMV docker in real world scenario (not just tutorial).
* how to mount `/projects` directory
* how to use IDE with SMV docker development.
* how is the data cached (e.g. maven/ivy caches)

**Comment by laneb** [comment]
I added a Docker doc a few days back but it needs more detail. 
https://github.com/TresAmigosSD/SMV/blob/master/docs/user/docker.md
