### ISSUE TITLE
Provide user defined SQL query for SmvPyHiveTable interface 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#504]
Sometimes user may want to specify the Hive SQL query instead of using `select * from`. For example, since Spark 1.5.* can't handle `CHAR[*]` type, user may want to do the casting in the sql query.

**Comment by ninjapapa** [comment]
This issue is getting higher priority now since a client project need this, otherwise the work-around will get pretty ugly.

**Comment by laneb** [comment]
I propose that `SmvHiveTable` should represent a Hive table, as described. Users will have the option to perform intermediate operations on the contents of the table through the `run` method. Allowing users to override the query used to access the data would be confusing, and also would betray concept of `SmvHiveTable` as a case class.

For users that specifically want an input that represents a Hive query, we can provide a `SmvHiveQuery` case class whose constructor expects a full query instead of a `tableName`.

**Comment by AliTajeldin** [comment]
The query is actually an optimization, it will be passed down to hive to pre-process.  The interface should be something like:
```python
class X(SmvHiveTable):
  def tableName(self): return "schema.table"
  def tableQuery(self): return "select a,b,c from blah where year  > 2016"
  def run(self, df): return post_filter(df)
```
the `tableQuery` should default to the current `select * from tablename`.  You can think of `tableQuery` as the pre-process step and `run` and the post-process step.

**Comment by laneb** [comment]
Keeping with the design pattern for Python `SmvInputs`, this design will look something like

```
class SmvHiveTable(SmvPyInput):
    def __init__(self, smvPy):
        super(SmvHiveTable, self).__init__(smvPy)
        self._smvHiveTable = self.smvPy._jvm.org.tresamigos.smv.SmvHiveTable(self.tableName(), self.tableQuery())

    @abc.abstractproperty
    def tableName(self):
        """The qualified Hive table name"""

    def tableQuery(self):
        return None
...
```

```
case class SmvHiveTable(override val tableName: String, override val userTableQuery = null) extends SmvInputDataSet {
  override def description() = s"Hive Table: @${tableName}"

  val realQuery = {
    if(userTableQuery == null)
      "select * from " + tableName
    else
      userTableQuery
  }

  override private[smv] def doRun(dsDqm: DQMValidator): DataFrame = {
    val df = app.sqlContext.sql(realQuery)
    run(df)
  }
}
```

**Comment by laneb** [comment]
The alternative would be to leave `SmvHiveTable` alone and differentiate `SmvHiveQuery`, like

```
class SmvHiveQuery(SmvPyInput):
    def __init__(self, smvPy):
        super(SmvHiveTable, self).__init__(smvPy)
        self._smvHiveTable = self.smvPy._jvm.org.tresamigos.smv.SmvHiveQuery(self.tableQuery())

    @abc.abstractproperty
    def query(self):
        """The Hive table query"""
...
```

```
case class SmvHiveQuery(val query = null) extends SmvInputDataSet {
  override def description() = s"Hive Query: @${query}"

  override private[smv] def doRun(dsDqm: DQMValidator): DataFrame = {
    val df = app.sqlContext.sql(query)
    run(df)
  }
}
```

**Comment by laneb** [comment]
In the first design, I would be concerned about abuse of the fact that the `tableName` and the `tableQuery` don't have to be related, and that this would encourage use of `SmvHiveTable` to encapsulate more complex queries. We may at least want to take away Scala `SmvHiveTable's` case class status. A potential problem is that a user is forced to attribute a `tableName` to an `SmvHiveTable` which already has custom query (perhaps a query that involves multiple tables), they will give it a garbage `tableName` like "query". Then every table with that name will be equivalent internally, and which will cause silent problems e.g. for maps with `SmvDataSet` keys (like RunParams).

**Comment by AliTajeldin** [comment]
My preference is for `SmvHiveTable`.

**Comment by laneb** [comment]
I checked in an implementation of the first example. I also added a couple unit tests for `SmvHiveTable`.

**Comment by ninjapapa** [comment]
Also need to added examples to the user doc.

**Comment by laneb** [comment]
Anything else needed on this?
