### ISSUE TITLE
SmvPyFile should have correct marker when graphed (or ls'd)

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#514]
When graphing modules, we mark each one with a character indicating what kind of dataset it is. The logic for this is the block

```
  private def baseNameWithFlag(ds: SmvDataSet) = ds match {
    case d: SmvOutput     => "(O) " + baseName(d)
    case d: SmvModuleLink => "(L) " + baseName(d)
    case d: SmvFile       => "(F) " + baseName(d)
    case d: SmvModule     => "(M) " + baseName(d)
    case d: SmvHiveTable  => "(H) " + baseName(d)
    case d => "(*) " + baseName(d)
  }
```

in `SmvStageGraph.scala`. Because `SmvApp` sees every Python dataset (including files and Hive tables) as an `SmvExtModulePython`, they are graphed with M instead of F or H

**Comment by ninjapapa** [comment]
I think we only need the following 4 types:
* Input
* Output
* Link
* Regular Module

**Comment by ninjapapa** [comment]
Might create a "DSType" attribute in `SmvDataSet` and let each type override it themselves.

**Comment by ninjapapa** [comment]
done
