### ISSUE TITLE
Add test of hashDataSet to the integration test.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#521]
In addition to any unit tests we have for the `datasetHash` function, we should add an explicit test for the end result hash value which can be done in the integration test.  This is due to the critical nature of the dataset hash values and the difficulty in creating good unit tests that do no produce false positives.
The above can be accomplished as follows:
* run the integration to produce output for module X. (this is already done today in the integration test)
* re-run the integration test without any modifications.  This should **NOT** produce a new X output (X should have the same hash value).
* Add a small modification to X and re-run the test.  This should create a new X output file as the hash value should have changed.

**Comment by laneb** [comment]
I have implemented this in the integration test, but it could probably be refactored, particularly to generalize it for #527.

**Comment by AliTajeldin** [comment]
Done
