### ISSUE TITLE
Update SMV user guide to use python examples

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#522]
The current user documentation uses scala examples.  Given the emphasis on python, we should use python examples instead.

**Comment by AliTajeldin** [comment]
We should also update the site docs #497

**Comment by ninjapapa** [comment]
For the user doc, I suggest to have both Python and Scala example code in the document. 

Also need to consider to reorganized the user doc. Split the entire user doc to multiple sessions,
* Quick Start
* Installation and Setup
  * Installation
  * Install with Docker
* SmvDataSet Framework
  * SmvDataSet Framework Basic: combine smv_file, smv_module, smv_module_python
  * SmvDataSet for Big Team: smv_stage
  * Work with Hive
  * Data Quality
* Smv Run and Interactive Use
  * app_config
  * run_app
  * run_shell
  * smv_jupyter
  * edd 
  * schema_discovery
* Smv Helper Functions and Libraries 
  * functions + python functions
  * matcher
  * hierarchy
  * label
* Best Practice 
  * Atom
  * Working on server
  * PlantUml

**Comment by AliTajeldin** [comment]
I like the user doc hierarchy.
@ninjapapa : I would rather we get rid of the scala examples rather than complicate the docs with multiple examples.  I would also suggest we make the user doc more of a reference doc rather than a walk.  Instead, use the basic tutorial notebook as the walk through guide (a more extensive getting started guide).  We would need to bring the basic tutorial notebook as part of SMV instead of a separate project.

**Comment by ninjapapa** [comment]
@AliTajeldin: Sounds like you emotionally moved to Python already :-)
Agreed that the User Doc should not be a walk though. For functions, helpers, configs, etc. the user doc should be purely a reference. For `SmvDataSet` structure, there is a need to briefly discuss the concept so that all the functions of the framework can be meaningful to readers.
