### ISSUE TITLE
smv-run/smv-pyrun -m Module should not re-calculate Module if a correct persisted version exists

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#526]
Currently if we specify a list of modules to run in command line, the target module will be recalculated even if a correct version of persisted file exists. It is unnecessary since if we trust all the persisted up-stream modules, there are no reason that the last module should have different content and need to rerun.

**Comment by AliTajeldin** [comment]
Agree.  This is a carry over of when we didn't have versions at all.  We actually **delete** the modules to run before we start.  With #481, there is absolutely no need to do that.

**Comment by laneb** [comment]
Fixed.
