### ISSUE TITLE
SmvPyHiveTable document or examples need to have a version method 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#528]
Since we can't make the `datasetHash` depend on the Hive table content, we need to provide a simple way for users to force a `hashOfHash` change. The simplest way is to change the version of a `SmvPyHiveTable`. 
Currently our document does not have `SmvPyHiveTable` examples with version method. Need to add it into the document. 

Also when later when we introduced user runtime options, we can make `SmvPyHiveTable`'s version specified through runtime config so that forcing a `hashOfHash` change does not need to change the code.

**Comment by laneb** [comment]
Wouldn't changing the runtime config force all modules to rerun?

**Comment by ninjapapa** [comment]
Please ignore the "Also" part, since it was before the implementation of runtime conf.
