### ISSUE TITLE
Issue with SmvPyMultiCsvFiles

### ISSUE THREAD

**Issue by ktlu4** [TresAmigosSD/SMV#533]
Multiple csv files are in directory 'Beneficiary' with schema in 'Beneficiary.schema' file at same level as Beneficiary directory.

The following error message shows up when trying to resolve using `SmvPyMultiCsvFiles`:
`Input path does not exist: file:/Users/katiel/Data/input/14_cms_synthetic/Beneficiary/.schema`

**Comment by ktlu4** [comment]
```
class Beneficiary(SmvPyMultiCsvFiles):
    def dir(self):
        return "input/14_cms_synthetic/Beneficiary/"
```

**Comment by jacobdr** [comment]
Try to follow the example here
<https://github.com/TresAmigosSD/SMV/blob/8cf175e764caa8664b6c589d99e92d9b9c35388b/src/test/python/testSmvFramework.py#L60>
.

Does "/Users/katiel/Data/input/14_cms_synthetic/Beneficiary.schema" exist
as a file? (`ls -l
/Users/katiel/Data/input/14_cms_synthetic/Beneficiary.schema`

Is "/Users/katiel/Data/input/14_cms_synthetic/Beneficiary" a directory?

Maybe you could copy the output of `ls -l
/Users/katiel/Data/input/14_cms_synthetic/`

**Comment by ninjapapa** [comment]
Here is the issue:
```python
return "input/14_cms_synthetic/Beneficiary/"
```
The last backslash should not be there. 

Either SMV code should handle that case or the document need to be very clear that the last backslash is not allowed.

**Comment by laneb** [comment]
I believe the problem is that dir should have no trailing '/'. Try it with "input/14_cms_synthetic/Beneficiary/" instead.

**Comment by laneb** [comment]
For now it's documented.
