### ISSUE TITLE
Dynamic load in Python does not have traceback

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#534]
Current `_reload` method in SmvPy does not print traceback as `_load` method, so when we resolve a `SmvPyModule` the first time with some syntax error, it will print the error message, after we "fix" it, and run `df` again in the same smv-pyshell, there will be no syntax error message. Need to make `_reload` to print out traceback too.

**Comment by laneb** [comment]
I need to do a review to make sure we are printing stack traces at of all of the callback entrypoints.

**Comment by laneb** [comment]
Fixed. It should also print the same stack trace if there is an error importing a module in urnsForStage (e.g. when trying to infer a DS name).
