### ISSUE TITLE
smv-pytest does not have the sys.path reordering

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#535]
Since `smv-pytest` does not use `smvapp` as the entry point, the `sys.path` fix in `smvapp` does not fixing `smv-pytest`. Need to make the same fix in the `smv-pytest`'s process. Ideally, we should have the same entry point for `smv-pyrun` and `smv-pytest` if possible.

**Comment by laneb** [comment]
For `smv-pytest`, we probably already need to empower the test fixture to configure the sys.path for the `datasetHash` tests. We could generalize the solution to address this problem as well.

**Comment by laneb** [comment]
The `datasetHash` tests now have a context manager that sets up and tears down the `sys.path` and loads the necessary module. We can generalize this solution to account for resources needed in all of the other tests.

**Comment by laneb** [comment]
This should be fixed by [this commit](https://github.com/TresAmigosSD/SMV/commit/bb6caf4bea1082ff5855de78dc90f9d4a0902c18), although in retrospect the name wasn't very descriptive.

**Comment by ninjapapa** [comment]
Confirmed on project server.

**Comment by laneb** [comment]
Is any further work needed on this issue?
