### ISSUE TITLE
The input-dir config parameter is being ignored

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#536]
We are currently using data dir as the basis for file input.  We should use input-dir instead and make input-dir be "input" by default.  This could break most existing code as we often hardcode the "input/" at the beginning of the file path.  My need to create a heuristic to remove the leading "input/" from name for existing projects.

**Comment by ninjapapa** [comment]
smv.inputDir in smv-user-conf.props works well. Is this issue about the --input-dir command line parameter?

**Comment by AliTajeldin** [comment]
@Khorkhe : please verify that this is still an issue and not that the code had "input" hardcoded in the paths.

**Comment by Khorkhe** [comment]
confirming that both smv.inputDir (in smv-user-conf.props) and --input-dir (command line param) are both working, and SMV reads data correctly from the specified path.

Closing.
