### ISSUE TITLE
Port discoverSchema to Python

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#540]

**Comment by laneb** [comment]
There is already an apparent port of `discoverSchema` defined in `smv_pyshell_init.py.template`, but when I tried to use it last night I didn't get the results that I was expecting. It may be that I was using it wrong, in which case we should just update the documentation to illustrate how it should be used.

**Comment by ninjapapa** [comment]
Should move it to smvshell.py. 
May also need to enhance the document and/or the function itself.

**Comment by ninjapapa** [comment]
done.
