### ISSUE TITLE
Add documentation about moving Python class names from SmvPy* -> Smv* (e.g. SmvPyModule -> SmvModule) to v.1.5.2.2 release notes

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#542]
[This commit](https://github.com/TresAmigosSD/SMV/commit/b3929d2891b8a14b1ee94201d1b38c1b257926b4) marked a pretty big stylistic change in the python API. 

I know that backward compatibility was fully maintained, but nonetheless important enough to warrant mention in the [release notes](https://github.com/TresAmigosSD/SMV/releases/tag/v1.5.2.2)...

cc @AliTajeldin @ninjapapa

**Comment by laneb** [comment]
done
