### ISSUE TITLE
SmvPyMultiCsvFiles tries to read .DS_Store files

### ISSUE THREAD

**Issue by ktlu4** [TresAmigosSD/SMV#545]
Error message:
```
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/Users/katiel/Data/14_cms_synthetic/Beneficiary/.DS_Store

```
Deleting the .DS_Store file temporarily resolves this issue

**Comment by laneb** [comment]
At a glance it appears that this is because SmvHDFS collects all the files in the specified directory without discrininating. I will hazard a guess that .swp files pose a similar problem.

**Comment by ninjapapa** [comment]
Is there a concept of hidden file on HDFS too? Maybe we should use that as an way to reject files. It is unlikely to happen on HDFS, but could be quite possible on local file systems. May also put something into the doc to make sure user aware that hidden files will not be included.

**Comment by Khorkhe** [comment]
Done.
The current solution was to ignore all hidden files (starting with ".").

Alternatives that were mentioned throughout the discussion are selecting files based on a whitelist / blacklist config.
