### ISSUE TITLE
Add support to Windows

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#548]
With a quick try, it sounds no very hard to run SMV on Windows. I followed [Install Spark](https://hernandezpaul.wordpress.com/2016/01/24/apache-spark-installation-on-windows-10/) (no need to install scala though), with replacing the Spark binary to our release. Also manually run SMV pyshell after set some environment variables. The only thing I still have some issue is the permission of "/tmp/hive" when I run CMD as a normal user. When run CMD as admin, everything is fine. 

Here is what we need to do:
* Create a Windows install document 
  * Install Java 
  * Install winutils.exe (Hadoop binary for windows) 
  * Install Spark and SMV prebuild packages 
  * Install Python 2.7 and Jupyter
  * Setup environment 
*  Create scripts for windows
  * smv-pyshell.cmd
  * smv-pyrun.cmd
  * smv-jupyter.cmd

**Comment by AliTajeldin** [comment]
This should probably be an unofficial supported platform.  Supporting windows is a whole can of worms.

**Comment by ninjapapa** [comment]
Will not fix for now.
