### ISSUE TITLE
isEphemeral does not have traceback message

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#550]
Currently isEphemeral is called from the java interface directly, no traceback messages.

**Comment by laneb** [comment]
`isEphemeral` is both user-defined and also an `ISmvModule` entrypoint. We will need to create a different entrypoint that delegates to the the user-defined `isEphemeral` and prints the traceback if necessary.

**Comment by laneb** [comment]
This should be resolved by #479.

**Comment by Khorkhe** [comment]
fixed by #479
