### ISSUE TITLE
Remove unnecessary content from templates

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#551]
The integration test now runs the test, enterprise, and simple template applications. There are modules and data shared between all 3 of these applications which should be deduplicated. There are 2 tasks here:

1) Remove stage1 and stage2 from test template (there is nothing here not accounted for elsewhere in the integration test or in the enterprise app)
2) Move the CSV file shared by the apps into a shared template data directory from which it can be copied into the the template. Deduplicating the CSVs should reduce the size of SMV by 8-9mb.

**Comment by laneb** [comment]
done

**Comment by AliTajeldin** [comment]
The CSV file is still duplicated in `tools/template` directory:

```
./big/data/input/employment/CB1200CZ11.csv
./data/input/employment/CB1200CZ11.csv
```

**Comment by laneb** [comment]
Forgot the big template was using this CSV in the first place. It's fixed now.

**Comment by jacobdr** [comment]
@laneb close?
