### ISSUE TITLE
Add validation check that SmvOutput is not ephemeral

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#552]
A module should not simultaneously be `SmvOutput` and have `isEphemeral == True`.

**Comment by Kai-Chen** [comment]
@AliTajeldin Found this ticket still open.

Was any work done on this or should it be closed, since we will allow this via another requirement?

**Comment by Kai-Chen** [comment]
As of b78598128b we can still publish Ephemeral modules, works in both Python and Scala.

**Comment by AliTajeldin** [comment]
closing this as "will not fix" because we actually want to publish ephemeral modules now.
