### ISSUE TITLE
port SmvUnpivot with all params to Python

### ISSUE THREAD

**Issue by Khorkhe** [TresAmigosSD/SMV#553]
currently, only the simple SmvUnpivot function is ported to Python, taking a list of columns.  

The more advanced SmvUnpivot Scala function also takes a function and an indexColName, and is called by the simple one with default params:

```
def smvUnpivot(valueCols: String*): DataFrame =
    smvUnpivot(valueCols, s => ("value", s), Some("column"))

def smvUnpivot(valueCols: Seq[String], colNameFn: String => (String, String), indexColName: Option[String] = Some("Index"))
```

**Comment by Khorkhe** [comment]
In helper.py, there are already helper functions available to convert Python lists (of cols etc) to Scala sequences. 

Is there a way to convert a Python function to a Scala function so it is passed as parameter?

**Comment by ninjapapa** [comment]
An arbitrary map from Python function to Scala function may not be possible, but the use case this function is really supporting could be replaced by a regex pattern. 
A real use case could be the original column names are:
* A_1
* A_2
* ...
* B_1
* B_2
* ...

And we want to split them to 2 parts, (A, B) X (1, 2 ...), where the (A, B) parts still are columns and the (1, 2, ...) parts fill in a new column with with column name "Index". 
For this specific use case, we could make the second parameter of the function a regex with 2 groups: `(.*)_(.*)`.

**Comment by Khorkhe** [comment]
the `smvUnpivotRegex` function needs to have its own name, because in Python, the order of parameters was modified because the valueCols have undetermined size, and hence has to be the last parameter.

**Comment by ninjapapa** [comment]
After agree on the python side signature, also need to update the User Doc.

**Comment by Khorkhe** [comment]
as of now, `smvUnpivot` and `smvUnpivotRegex` respectively take a varargs and a list for the columns.  It would be possible to let them have the same name by changing the initial python implementation to use a list of strings instead of varargs, along with a default regex param to represent the default function on the Scala side: `s => ("value", s)`.

However, this would require the users to update their usage of `smvUnpivot` in existing projects.

Any preference on how to proceed?

**Comment by ninjapapa** [comment]
Keeping them in different names is fine.

**Comment by Khorkhe** [comment]
Still have to do the docs
