### ISSUE TITLE
Need away to identify dead-in-the-middle persisted DS

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#554]
It's quite often someone killed the job in the middle, and after some fix, he want to restart. A danger there is that some DS is in the middle of persisting when the process got killed, so second job will consider the data is there already by read in the persisted part of the data. 

Need a way to tell when a DS is successfully persisted instead of dead-in-the-middle, so that the second run can ignore the part data and recalculate the DS.

**Comment by AliTajeldin** [comment]
This might be hard to accomplish using native hadoop.  Doesn't look like there is a way to tell if a file was closed in the middle.  We may have to add a "done" marker when we are done writing the file.  If the data is there but the "done" marker missing, then we can assume it was a partial write.

@laneb yes.  We should only re-run the datasets that did not complete.

**Comment by laneb** [comment]
Doesn't the _SUCCESS file only get written if the data was persisted successfully?

**Comment by AliTajeldin** [comment]
For some reason, I think the _SUCCESS is still written on close (for local filesystem).  My memory could be playing tricks on me.  Having a deja-vu moment here.  Need to verify with a very large file on local fs so that it starts writing but killed in middle.

**Comment by jacobdr** [comment]
This is a necessary feature to add -- I have had this issue come up a few times already in my current project

**Comment by laneb** [comment]
On my system, a module cancelled halfway through persisting does not leave a _SUCCESS file. I suggest that the `isPersisted` method described in #560 also checks that a _SUCCESS file has been written.

**Comment by laneb** [comment]
Because we may be unable to rely on a _SUCCESS file being created in all situations (users can configure Hadoop not to create this file), it will be better for us to create our own success marker. By creating the schema file only once the csv has been persisted, we can treat the schema as a success marker

**Comment by laneb** [comment]
Assuming we still need `isPersisted` for other purposes, it can check for the schema instead of _SUCCESS.

**Comment by laneb** [comment]
Done.
