### ISSUE TITLE
SmvInputDataSets with different run methods treated as equal

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#555]
Most or all of the Scala `SmvInputDataSet` implementations are case classes, so instances are treated as equal as long as the arguments they were constructed with are equal. E.g.

```
object F1 extends SmvCsvFile("file.csv") {
  def run(i: DataFrame) = i.select("c1")
}

object F1 extends SmvCsvFile("file.csv") {
  def run(i: DataFrame) = i.select("c2")
}

// This evaluates to true
F1 == F2
```

Currently, this causes a bug where runParams will map the inputs defined above to the same `DataFrame` because it thinks they are equal. E.g.

```
object M extends SmvMoudle(""){
  def requiresDS = Seq(F1, F2)
  def run(i: runParams) = i(F2)
}

// These are the same
df(M)
df(F1)
//These are not
df(M)
df(F2)
```
More generally, it is misleading for two instances of the same case class with the same arguments to not be conceptually equal. For ease of use we can define a factory object explicitly.

**Comment by ninjapapa** [comment]
We should probably remove the case class interface in Scala and always use the `object ... extends ...` interface.
