### ISSUE TITLE
SMV docker image is ignoring sbtopts file

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#556]
The `/home/smv/lib/sbt/conf/sbtopts` does not seem to be read by sbt so the ivy cache directory is always `/home/smv/.ivy2` which will be wiped out when the image is terminated.
The `sbtopts` file doesn't seem to be officially documented anywhere.
The current workaround is to specify the `-ivy` flag explicitly when building with sbt:
```
$ sbt -ivy /projects/.ivy2 clean assembly
```

**Comment by laneb** [comment]
The sbt startup script on my system reads
```
#!/bin/sh
if [ -f "$HOME/.sbtconfig" ]; then
  echo "Use of ~/.sbtconfig is deprecated, please migrate global settings to /usr/local/etc/sbtopts" >&2
  . "$HOME/.sbtconfig"
fi
exec "/usr/local/Cellar/sbt/0.13.13/libexec/sbt" "$@"
```
and sbt picks up the sbtopts I have added at /usr/local/etc/sbtopts.

**Comment by laneb** [comment]
However, from a usage message in the sbt startup script in the Dockerfile:
```
  # jvm options and output control
  JAVA_OPTS          environment variable, if unset uses "$java_opts"
  SBT_OPTS           environment variable, if unset uses "$default_sbt_opts"
  .sbtopts           if this file exists in the current directory, it is
                     prepended to the runner args
  /etc/sbt/sbtopts   if this file exists, it is prepended to the runner args
  -Dkey=val          pass -Dkey=val directly to the java runtime
  -J-X               pass option -X directly to the java runtime
                     (-J is stripped)
  -S-X               add -X to sbt's scalacOptions (-S is stripped)
```
(to find this, use `vim $(which sbt)` in an smv container and search for "sbtopts")

**Comment by AliTajeldin** [comment]
Done

**Comment by AliTajeldin** [comment]
sbt still writing to `~smv/.ivy2/cache`.  Even added an ivy setting file as suggested here: http://stackoverflow.com/questions/1293113/how-to-override-the-location-of-ivys-cache but to no avail.
In desperation, just made `~/smv/.ivy2` a symlink to `/projects/.ivy2`.  That seems to do the trick.  Will add to docker file shortly.

**Comment by AliTajeldin** [comment]
done
