### ISSUE TITLE
class files under resources need to be built with jdk 7

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#558]
There are a couple of class files under the `resources/data/ClassLoaderTest` that were built with java 8.  Users who have java 7 will get a class exception error if they run the tests.  Need to rebuild these classes using jdk 7.

**Comment by laneb** [comment]
Should we create a script for this?

**Comment by AliTajeldin** [comment]
agree.  Perhaps something that uses the `smv-core` or `smv` docker image to build the class files so that we always get the right version regardless of who rebuilds it.

**Comment by AliTajeldin** [comment]
Fixed.
There now a script to rebuild classes using smv docker image:
```
src/test/resources/data/ClassLoaderTest/updateClassFiles.sh
```
