### ISSUE TITLE
Need a "dry-run" option in command line and in shell

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#559]
The use case is that user have a project with modules take relative long time to run, and before do `df` or `-m`, need to tell what modules will need to re-run (instead of read from the persisted data).

**Comment by AliTajeldin** [comment]
To clarify for the implementer, this is different than the current list of "Modules to run/publish".  We need to find the list of all ancestors to the "Modules to run/publish" and then find which ones of these do not have a persisted file (for non-ephemeral modules).

**Comment by laneb** [comment]
If we empower modules to determine whether or not they are persisted, this will look something like
```
modulesToRun flatMap (_.ancestors) filter (m => m.isPersisted) distinct
```
Should it report ephemeral modules, inputs, and links? Perhaps the types report could be a user-specified option.

**Comment by AliTajeldin** [comment]
Depends on #560

**Comment by laneb** [comment]
It has occurred to me before that when we print the modules to be run during a real run, e.g. 
```
Modules to run/publish
----------------------
stage1.employment.EmploymentByState
----------------------
```
it seems intuitive that we would list all of the datasets that will actually run and none of the ones that won't - the same as we want from the dry-run option. The behavior today is to print the modules that were specified explicitly via cli options. If we change the behavior as described then all the dry-run would have to do is skip actually running the modules.

**Comment by AliTajeldin** [comment]
This could be a bit confusing for publish.  As we may have to run some modules but not publish them if they are not output modules.  Perhaps create a list of all modules that will be run but add flags to indicate if the module will just be computed (ephemeral), persisted (internal modules), or published (output modules with publish flag).

**Comment by laneb** [comment]
That makes sense to me. Then the dry-run would inform you of all the same details.

**Comment by AliTajeldin** [comment]
Exactly, the dry-run is just a suppression of the actual run.  The output would be exactly the same.

**Comment by AliTajeldin** [comment]
This depends on #560.  Need to wait until #560 is implemented.
