### ISSUE TITLE
smv-pyrun port in use error on the second job on the same server 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#561]
`smv-pyrun` used to generate a large random number for the call back server's port. In most of the cases it solved the problem of "port in use" error for the second run. 

Current version has that part removed, although the `smv-pyshell` still has that. 

It is the case that user can specify the call back port number on command line, but user should not worry about it.

**Comment by laneb** [comment]
A quick patch would be to c/p the code used to set the port to `runapp.py`.

**Comment by laneb** [comment]
We might consider making `SmvPy` responsible for setting the port, or at least delegating it to the Python `SmvApp`.

**Comment by ninjapapa** [comment]
To check whether a port is open,
http://stackoverflow.com/questions/19196105/python-how-to-check-if-a-network-port-is-open-on-linux

I like this one:
```python
import socket
from contextlib import closing

def check_socket(host, port):
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as sock:
        if sock.connect_ex((host, port)) == 0:
            print "Port is open"
        else:
            print "Port is not open"
```

**Comment by ninjapapa** [comment]
done
