### ISSUE TITLE
smv-pyrun should check for invalid stage names

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#562]
`smv-pyrun -s stage1` currently does not check if `stage` is indeed a valid stage name.  And if it is not, the run will silently not find the modules in `stage1` to run/publish.

**Comment by laneb** [comment]
What constitutes a valid stage name in this context? Where should this check occur?

**Comment by AliTajeldin** [comment]
A valid stage name is one that is specified in the config.  We should also accept unique partial stage names for `-s` just like we do for modules.

**Comment by laneb** [comment]
Ah I see. So we would not be checking that the stage name specified in the config is valid in any sense? I thought this might be connected to enforcing that a stage cannot be the path of a Python file.

**Comment by AliTajeldin** [comment]
nah, this was for the case where they have a typo in the specified stage name.  Right now we just silently do nothing.

**Comment by laneb** [comment]
Ok. When the user gives an invalid stage name, should we throw an exception?

**Comment by AliTajeldin** [comment]
correct

**Comment by laneb** [comment]
It appears that the behavior described was implemented in [this commit ](https://github.com/TresAmigosSD/SMV/commit/0a16f33fbfb45fba3b830f81852b440db343ea15).

**Comment by AliTajeldin** [comment]
Cool.  Let's just implement #569 to be consistent with module names.  Closing this.
