### ISSUE TITLE
Make inferStageFullName behave the same as inferDS

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#569]
currently `inferDS` take part of the DS fqn and try to infer it as long as a unique DS identified, while `inferStageFullName` only allow the partial name a either the full fqn or the basename of the fqn. Should make `inferStageFullName` behave the same as `inferDS`.

**Comment by laneb** [comment]
I added some test cases too.

**Comment by AliTajeldin** [comment]
Looks good.
