### ISSUE TITLE
self.should_be_same in python unit test passing on unequal DFs

### ISSUE THREAD

**Issue by Khorkhe** [TresAmigosSD/SMV#571]
Had a typo in the expected DF while writing a unit test, test still passed.  See inline comments:
```
def test_smvUnpivotRegex(self):
        df = self.createDF("id:Integer; A_1:String; A_2:String; B_1:String; B_2:String",
                """1,1_a_1, 1_a_2, 1_b_1, 1_b_2;
                   2,2_a_1, 2_a_2, 2_b_1, 2_b_2
                """)
        res = df.smvUnpivotRegex( ["A_1", "A_2", "B_1", "B_2"], "(.*)_(.*)", "index" )
        expect = self.createDF("id: Integer; index:String; A:String; B:String",
                """1,1,1_a_1,1_b_1;
                   1,2,1_a_2,a_b_2;  // typo here: a_b_2 instead of 1_b_2
                   2,1,2_a_1,2_b_1;
                   2,2,2_a_2,2_b_2
                """)
        self.should_be_same(expect, res)  // still passed even though typo
```

**Comment by laneb** [comment]
Those are C++ comments ;]

**Comment by Khorkhe** [comment]
whoops!

**Comment by laneb** [comment]
It appears that `should_be_same` actually only compares the column names, not the computed results (i.e. not the table you've defined). It also appears that you're not the first to use `should_be_same` with the expectation that it will compare the computed results. We will need to come up with a reliable means of testings the results.

**Comment by Khorkhe** [comment]
as per the description of `should_be_same`: 

"Returns true if the two dataframes contain the same data, regardless of order", it did give me the impression that it compares the entire DFs.  

Particularly that it asserts the following:
```
self.assertEqual(expected.collect().sort(), result.collect().sort())
```

**Comment by laneb** [comment]
Wow don't know how I missed that line. All the same, test has only been testing that the columns are the same. The `sort` method of `List` only sorts the list in place and _does not_ return the sorted list. The first assertion was comparing the columns and the second assertion was comparing `None` with `None`. 

The solution was to use the `sorted` built-in instead of the `sort` method of `List`.

**Comment by laneb** [comment]
I also fixed several tests which were failing because their results weren't actually the same (due to the test, not a bug in what they were testing).

**Comment by laneb** [comment]
It's also not true that `should_be_same` returns `True` in any scenario. It has no return statement.

**Comment by laneb** [comment]
Fixed.
