### ISSUE TITLE
Simplify SmvClassLoader

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#575]
It is not necessary to support loading classes from a remote server. We can simplify `SmvClassLoader` by removing all of the abstraction supporting the remote class server.

**Comment by AliTajeldin** [comment]
@laneb may be able to remove dependency on `httpclient`, `jetty-server`, and `jetty-client` from `pom.xml`/`build.sbt` now that the server has been removed.  Some of these may be used elsewhere in the app, but the `jetty-server` will probably go at a minimum.

**Comment by laneb** [comment]
I'll check those out.

**Comment by laneb** [comment]
Done.
