### ISSUE TITLE
Python API docs 

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#576]
We can use sphinx to generate Python API docs for us automatically if the modules, classes, and functions we want documented have docstrings. There are many that currently don't.

**Comment by laneb** [comment]
Using google style docstrings. sphinx can use [napoleon](http://www.sphinx-doc.org/en/stable/ext/napoleon.html#module-sphinx.ext.napoleon) to parse these.

**Comment by laneb** [comment]
Documenting DataFrame helper methods may be complicated. By default won't be documented in a sphinx project initialized with sphinx-apidoc. It may be possible to add a page documenting methods we've added to `DataFrame`, but we would probably have to create and maintain that manually. Alternatively, we could create a dummy Python DataFrameHelper class to house the docstrings.

**Comment by laneb** [comment]
Another option to try may be to add attribute docstrings to the module, something like
```
DataFrame.fooMethod = lambda: smvPy._jvm.fooMethod
"""function: summary of fooMethod

     longer description of fooMethod
"""
```
But I'm not certain this would and the resulting documentation might be a little confusing.

**Comment by laneb** [comment]
After discussing with @ninjapapa, it seems the best option may be to create a DataFrameHelper Python module, define and document the helper methods there, and then add them to DataFrame in `helpers.py` or `smvpy.py`.

**Comment by laneb** [comment]
DataFrameHelper should be a class because it will simplify iterating over methods and adding them to DataFrame. Also need a ColumnHelper.

Depends on #582.

**Comment by laneb** [comment]
This issue also depends on #581.

**Comment by laneb** [comment]
#581 and #582 are complete.

**Comment by laneb** [comment]
So many commits 😮

**Comment by Khorkhe** [comment]
each is small, minimizing chances of accidental mess-up
