### ISSUE TITLE
Make python SmvApp an instance rather than just a static class.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#580]
* Make SmvApp an instance.
* Constructor should automatically add the `src/main/python` instead of every caller having to call `add_source` now.  Violates DRY.
* Decouple the "init" from the "run".   The `run` method now does the init and run.  The init should happen in the constructor and the run method should only run.
* `smv-server` should then use SmvApp instead of calling `SmvPy.Init()` directly.  `smv-server` will NOT call the run method.

**Comment by laneb** [comment]
The reason I didn't make implement adding `src/main/python` this way by default is that it seemed problematic for `SmvApp's` constructor to modify the `sys.path`.  I think a slightly cleaner approach is for the constructor to initialize a list of sources `src/main/python` at minimum, then for `init` to actually add them to the `sys.path`. I don't foresee a scenario in which we instantiate an `SmvApp` without calling `init`, but I think that is a more transparent design.

**Comment by laneb** [comment]
The last bullet point was addressed as part of #586.
