### ISSUE TITLE
Explicitly add SMV's src/main/python to PYTHONPATH in _pyenv.sh

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#584]
Currently, the user application's `src/main/python`  is added explicitly (e.g. in runapp.py), whereas SMV's `src/main/python` is added implicitly when running the application with `smv-pyrun` . This happens because `runapp.py` is located in SMV's `src/main/python`. We should add SMV's `src/main/python` explicitly in `_pyenv.sh` instead.

**Comment by jacobdr** [comment]
This is a little bit of a confusing description. If I am reading it properly, want to add both SMV's `src/main/python` to the path, and also the user's project `src/main/python`. Is that right?

To that end, using the `__file__` variable in `runapp.py` but better express intention.

**Comment by laneb** [comment]
That is correct. I edited the description for clarity. I disagree with using the `__file__` variable, because we may eventually move `runapp.py` elsewhere. We would also then have to duplicate this logic across to other Python SMV entrypoints like `smvserver.py`. We already set the PYTHONPATH for `smv-pyshell` and can simply push that export statement up to `_pyenv.sh`.
