### ISSUE TITLE
Add `dot` executable into the Docker image

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#585]
Current workflow:
1. Run container from the `smv` image, mounting in my project using `-v $(pwd):/projects/my_project`
2. `smv-pyrun -g` to generate the ".dot" file
3. In another shell, use the `dot` executable on my local system to convert to PNG

Would be nice to be able to do it from inside the container and save the context switch.

**Comment by laneb** [comment]
@AliTajeldin does this belong in `smv-env` or just `smv`?

**Comment by AliTajeldin** [comment]
Since it is a tool.  `smv-env` is probably a better option.

**Comment by laneb** [comment]
Added dot to the Dockerfile for `smv-env`. Waiting on the docker-hub build.

**Comment by laneb** [comment]
Nevermind, `smv-env` doesn't have an automated build. Pushed it and manually triggered a build of the `smv` image. It would be helpful if we could coordinate triggering the `smv` build automatically when push `smv-env`, whether restfully or via automated builds.

**Comment by jacobdr** [comment]
Docker Hub does not support that at all. #594 is looking better and better
all the time....

**Comment by laneb** [comment]
Confirmed that `smv:latest` has dot.

**Comment by AliTajeldin** [comment]
We need to tag the `smv-env` image (with a new tag to force docker hub to rebuild it) and then change the FROM tag in the `smv` docker image to point to the new tag (after the `smv-env` image was built).

**Comment by AliTajeldin** [comment]
Done
