### ISSUE TITLE
use new location of sbtopts in SMV docker image

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#590]
The current location of the sbt config file `/home/smv/lib/sbt/conf/sbtopts` seems to be ignored and the ivy directory is still being created in `${HOME}/.ivy` which means each instance of the docker image will have to download all the dependent jars everytime.
The proper location of the sbtopts seems to be: `/usr/local/etc/sbtopts` (See https://medium.com/@jan______/sbtconfig-is-deprecated-650d6ff10236)

**Comment by laneb** [comment]
Seems duplicate of #556.

**Comment by AliTajeldin** [comment]
@laneb :  oops, yup.  closing this a duplicate of #556
