### ISSUE TITLE
Provide CI for every PR

### ISSUE THREAD

**Issue by hubertp-lshift** [TresAmigosSD/SMV#594]
Should be fairly easy to set up with https://github.com/travis-ci/travis-ci since it is a public repo.
It should be possible (at least) to identify PRs that introduce errors to the test sutie and that do not conform to the Scala code formatting.

**Comment by AliTajeldin** [comment]
This can potentially make #578 easier (to push to docker rather than rely on docker auto build).

**Comment by AliTajeldin** [comment]
oops accidental close.

**Comment by AliTajeldin** [comment]
Initial builds are below. 
https://travis-ci.org/TresAmigosSD/SMV
