### ISSUE TITLE
Need style guide for Python code

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#597]
For example, we are not consistent on whether to use camelCase or snake_case for method names. See for example L128 of `smvapp.py`

```
    def appName(self):
        ...

    def create_smv_pyclient(self, arglist):
        ...
```

Standard Python style is to use snake_case, but it seems like we favor camelCase on average, so it is not clear to me which we should use. Once we standardize, we should also fix existing style inconsistencies.

**Comment by jacobdr** [comment]
I like to use [flake8](http://flake8.pycqa.org/en/latest/) in my projects. Combines PEP8 checks and additional PyFlakes rules, and has really nice IDE support

**Comment by AliTajeldin** [comment]
@jacobdr `flake8` looks very promising.  And it looks like it does support project level config files so that we can set the ignore for module names being CamelCase (if that is indeed an error in `flake8`).

**Comment by hubertp-lshift** [comment]
Note that this and Scala style checking will have little impact unless a proper CI is setup on every PR that checks for style errors. And you also would have to agree that commits aren't pushed straight into master but only through PRs. It might seem like an overhead but with sbt build now on 2.1 it should be straightforward.

**Comment by jacobdr** [comment]
+1 on moving to PRs -- given the development velocity as of late, I have found it a little bit harder to keep track of which commits relate to which features/issues. I think this would help make that cleaner. 

Also, the GH PR viewer inlines the source changes so much better than inside of an issue, simplifying the life of a casual reviewer.

**Comment by laneb** [comment]
`flake8` is now covered by #634. Style guide is now covered by #667. Closing as duplicate.
