### ISSUE TITLE
add compile option to smv server.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#598]
Need to compile the new code when user submits a new code snippet to make sure it doesn't brake the build.  Just a simple syntax checker should suffice.  This is because any global syntax errors will break module discovery, graphs, etc.

**Comment by AntonioRecaldeRusso** [comment]
previous commits that belong to this issue:
2471d0b
a745b1e
269af28

**Comment by AntonioRecaldeRusso** [comment]
can be closed
