### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#599]
When building SMV (with sbt, at least) you get a big chunk of warnings about using deprecated SMV methods like
```
[warn] /Users/laneb/twine/SMV/src/main/scala/org/tresamigos/smv/SmvGroupedData.scala:245: method smvFirst in package smv is deprecated: use the one in smvfuncs package instead
[warn]     val cols = pivot.outCols map (n => smvFirst($"$n", true) as n)
[warn]                                        ^
[warn] /Users/laneb/twine/SMV/src/main/scala/org/tresamigos/smv/SmvGroupedData.scala:404: class RollupCubeOp in package smv is deprecated: Use Spark rollup/cube
[warn]     new RollupCubeOp(df, keys, (col +: others)).cube()
[warn]         ^
[warn] /Users/laneb/twine/SMV/src/main/scala/org/tresamigos/smv/SmvGroupedData.scala:410: class RollupCubeOp in package smv is deprecated: Use Spark rollup/cube
[warn]     new RollupCubeOp(df, keys, names).cube()
[warn]         ^
```
It appears that we are still using our own deprecated methods.

**Comment by Khorkhe** [comment]
the warnings above no longer appear on latest compilations.  However, it does look like some of our `@deprecated` annotations were put within the docstring instead of above the function definition, which did mask some of those deprecation warnings.  Will fix those.

**Comment by Khorkhe** [comment]
Investigating why the RollupCubeOp warnings shown above are no longer showing up even though the class still has a deprecation warning

**Comment by Khorkhe** [comment]
doing a comparison with another similar private case class, it seems a deprecation warning is thrown only when the case class is used as parameter or return type of a function, and not when instantiating objects from that class.

e.g.:

```
// locally deprecated SmvGroupedData for testing comparison

// no warning thrown
val x = new SmvGroupedData(newdf, keys ++ gdo.inGroupKeys)

// deprecation warning thrown
def smvMapGroup(gdo: SmvGDO, needConvert: Boolean = true): SmvGroupedData = {
```

@AliTajeldin 
Could it be that warnings were disabled for some use cases?

**Comment by AliTajeldin** [comment]
I don't believe we have any warnings disabled.  If the deprecation warnings are no longer there, we can go ahead and close this ticket.

**Comment by Khorkhe** [comment]
Okay will keep an eye on compilation output in the meantime
