### ISSUE TITLE
error enhancement, when smv.stages mismatch project code

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#601]
Currently, if smv.stages in config miss a stage or has a typo, following error is shown. Is it possible to have a message that give more hints to the source of the issue?
```
Traceback (most recent call last):
  File "/home/cchen/SMV/src/main/python/smv/smvapp.py", line 252, in dataSetsForStage
    return self._moduleUrnsForStage(stageName, lambda obj: obj.IsSmvPyDataSet)
  File "/home/cchen/SMV/src/main/python/smv/smvapp.py", line 277, in _moduleUrnsForStage
    for loader, name, is_pkg in pkgutil.walk_packages(stagemod.__path__, stagemod.__name__ + '.' , onerror=err):
AttributeError: 'module' object has no attribute '__path__'
```

**Comment by laneb** [comment]
Interesting. Can you share the config and the directory structure that led to this problem? According to the current design, what _should_ happen if you have a missing stage is that the `SmvDataSets` aren't discovered, and if you are doing a `df` then you should get an 'SmvDataSet not found' message.

**Comment by XiaosenChen** [comment]
ah ha, I found out what happened, it happens only when smv.stages points to the sub directory of the stage:
directory structure:
-python
 --dir1
  ---dir2
In config:
smv.stages = dir2 (wrong, should be dir1)

**Comment by laneb** [comment]
That still shouldn't cause the error that it did. I'll try to reproduce this later.

**Comment by XiaosenChen** [comment]
I still have this error in my specific case, but I cannot reproduce it generally...I may have missed something. No need to work on this. Let me show you next week.

**Comment by AliTajeldin** [comment]
@XiaosenChen Is this still an issue?  If not, we should close.

**Comment by XiaosenChen** [comment]
No longer an issue
