### ISSUE TITLE
smv docker image should use jdk 8 instead of jdk 7

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#604]
Switch to jdk 8 image of `smv-env` base.

**Comment by laneb** [comment]
Should probably include the appropriate memory option in sbtopts. See #473.

**Comment by AliTajeldin** [comment]
should only do this on the 2.1 branch as it is too late to move to jdk 8 for 1.5.x clients.

**Comment by Kai-Chen** [comment]
I think this was already done in commit 0da0283c
