### ISSUE TITLE
Merge master to 2.1

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#605]
Since scalafmt has been applied to both master and 2.1 branch separately, it is pretty hard to merge master to 2.1. Need to pay the effort and fix this before they move too far.

**Comment by Kai-Chen** [comment]
Apparently it's not just the use of scalafmt.
There are quite a few other undesirable changes that crept into the 2.1 branch, at least from a merging perspective.

Below is a list of the tasks to perform:
- [ ] Revert test-related changes first so we can run tests.
- [ ] Revert commits that introduced file renaming and repackaging, both of which unnecessarily complicates merge.
- [ ] Double check to make sure that we did not leave out the intended changes.

**Comment by hubertp-lshift** [comment]
Since I committed most of those changes, I can have a look at it and make a PR.

**Comment by hubertp-lshift** [comment]
Also, I don't think reverting is a way to go. You will be stuck with some pretty obvious file structure problems that should be fixed. I think the main question is where those changes should be applied. I assumed that the main dev will gradually shift towards 2.1 so merging will be unnecessary, but maybe I'm wrong?

**Comment by hubertp-lshift** [comment]
FYI, instead of reverting some of the changes, I would probably just cherry-pick them, apply to master, merge again into 2.1, which will be painless. It's a longer, but probably a safer route which I can volunteer to do. I will apply the non-2.1 specific changes to master from now on, until there is a decision to switch dev to it.

**Comment by AliTajeldin** [comment]
@hubertp-lshift correct.  master is our dev branch.  We will merge the 2.1 branch into master and create a 1.5.2.x maintenance branch in next couple of days.

**Comment by Kai-Chen** [comment]
The file renaming and repackaging definitely does not belong in this branch.
In fact, doing that task on a devoted branch by itself is probably a good idea.
It would keep simple isomorphic changes separate from functional changes, the stuff that really is different.

So I would say at least revert these changes on the 2.1 branch, and if you feel really strong about the names, send a separate PR for that only, to the master branch, and then we can discuss there.

Ultimately, though, I think these things and stylistic stuff is a time and energy sink.
It's necessary process to deal with the unfortunate fact that, when we read code, we let what the code **looks like** distract us from understanding what the code **means**.

**Comment by AliTajeldin** [comment]
Ok guys, to put an end to the back-and-forth, here is the plan:
* For future code refactors, they need to be on a branch with a separate PR against master and a github issue.
* If we can get 2.1 stabilized quickly, let's do that without the revert.  If it is not possible to get it resolved in a day, then lets roll back the refactor and do that on a separate branch (I'm trying to avoid having people redo work if not necessary).

**Comment by hubertp-lshift** [comment]
Cool. I can work with that.

I will revert my changes on 2.1 and send a PR on master. 

> Ultimately, though, I think these things and stylistic stuff is a time and energy sink.
Yes, that's why you have me :) I can understand that if you wrote most of the codebase the code is clear but for someone new, like me, I'm having troubles connecting the dots when a lot of the stuff is distracting me from reading the code. 

I will revert the changes and re-apply them on master. No biggie.

**Comment by Kai-Chen** [comment]
PR #636 was merged into 2.1.
Travis file was updated to specify using openjdk8 on trusty.
Travis also didn't like `fork`ing tests; the line was commented out to allow travis to pass the build.

**Comment by hubertp-lshift** [comment]
@Kai-Chen Thanks for merging but it seems it was complaining about a dependency rather than something else?

**Comment by AliTajeldin** [comment]
The "com.eed3si9n#sbt-assembly" dependency was a spurious error that was not related to SMV.
