### ISSUE TITLE
port input helpers to Python

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#610]
There are a few methods enumerated in the [SMV Input Docs](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_input.md) as ["Scala" only](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_input.md#python-6). Creating this ticket to track feature parity. 

- [saveAsCsvWithSchema](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_input.md#saving-files-in-shell)
- [discoverSchema](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_input.md#schema-discovery)

**Comment by ninjapapa** [comment]
discoverSchema was ported already. Need to update doc though.

**Comment by laneb** [comment]
`discoverShema` is now included in the Python API doc. Will port `saveAsCsvWithSchema`.

**Comment by laneb** [comment]
Actually, is `saveAsCsvWithSchema` needed in `smv-pyshell` @jacobdr? Or is the use-case covered by `smvExportCsv`.

**Comment by laneb** [comment]
@jacobdr bump

**Comment by ninjapapa** [comment]
Done.
