### ISSUE TITLE
Docker image needs Python graphviz package

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#615]
graphviz added as a Python dependency and can be installed with pip, but hasn't been added to the Dockerfile.

**Comment by AliTajeldin** [comment]
depends on #616.  not really, but easier to do this once than twice :-)

**Comment by AliTajeldin** [comment]
lowered priority since we no longer fail if graphviz is not installed (only the graphvis() will fail).

**Comment by AliTajeldin** [comment]
Done
