### ISSUE TITLE
Pass through smv args to `smv-pytest`

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#620]
Right now the following code fails:
`smv-pytest --smv-props smv.config.sample=full`

I get this error message:
`ImportError: No module named --smv-props`

**Comment by laneb** [comment]
Should the title of this issue be about `smv-pytest` instead of `smv-pyrun`?

**Comment by laneb** [comment]
In SMV's Python tests, smv args are supplied for each test in its setup - we don't even create an `SmvApp` until the setup step for the first test. If the desired behavior is to combine smv args supplied at the command line with smv args specified in test setup, one option is to give `SmvBaseTest` access to the command line smv args so that they are combined with the test-specific arguments when `SmvBaseTest` initializes `SmvApp`.

**Comment by jacobdr** [comment]
To provide some more context around the motivation...

In our normal development, our project users tend to have a run-time config set in `smv-user-conf.props` that drops them into a <1%  sampled universe. They work on a module, write some tests, and tend to invoke `smv-pytest` with an argument specifying just the test module / suite that is relevant to their immediate work.

Occasionally we want to run `smv-pytest` and enforce that the run-time config be set to "full data" -- especially when operating on our CI box. The easiest way to force this behavior is a simple bash script that wraps `smv-pytest` and provides the `--smv-props` flag with the value that we want. 

Does that make sense @laneb?

**Comment by laneb** [comment]
Yes, that makes sense. Currently, how are you getting an instance of `SmvApp` (we need to make sure your args make it to `SmvApp`)? Are you instantiating it yourself, or are you using `SmvBaseTest`, which instantiates it for you?

**Comment by laneb** [comment]
This appears to be more or less a direct c/p of the SMV's `SmvBaseTest`, though probably a month or two old (`smvPy` is now `smvApp`). If you want to continue using this `SmvBaseTest`, you will have to supply the args to `smvPy` yourself.

I will make the following changes:

- Individual tests will be run with `-t`
- `runtest.py` will only eat `-t` and the argument immediately following it.
- The remaining options will be available in `TestConfig.commandlineArgs`

You will just have to add `TestConfig.commandlineArgs` to the args that are passed to `smvPy.init`.

**Comment by laneb** [comment]
I will also move our `SmvBaseTest` into `src/main/python` so that it is easier for you to import it instead of rolling your own.

**Comment by laneb** [comment]
done.
