### ISSUE TITLE
Update SmvEntityMatcher document

### ISSUE THREAD

**Issue by sarahnguvt** [TresAmigosSD/SMV#625]
Based on test on the latest release (1.5.2.5), the document for [SmvEntityMatcher](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_entity_matcher.md) needs some small updates. 1) python example code; 2) the import of smv.functions for String Distance Measures.

**Comment by ninjapapa** [comment]
I assume it is done. Please reopen if not.
