### ISSUE TITLE
Add data traceability back to source code / input files that produced the output. 

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#630]
# The Problem
After running an SMV app in production for a while, there will be multiple output files for a given module in the output directory (with differing hash values).  We need to be able to trace each output file version to the code that generated it and possibly the input file version that was used.

# Code trace
The code trace can be as simple as noting the git hash of the repo at the time of the run.  It is not supper ideal as the user may have made multiple runs of the modules with modifications using the same git hash (uncommitted code).

For production, there is a good chance that git will not be available.  Therefore, we must store the git hash value in the generated production bundle (See #629).

# Input trace
In a production environment, input files are often updated (or new deltas applied).  In the ideal situation, each generated output file would have a trace to the input file used to generate it.  However, that would be too expensive as that would require a copy of the input data per run.

Neither CSV nor hive tables have a standard "version" that we can trace and document.

# Time trace
While each output file does have a timestamp, it would be nice to have a "time-of-run" timestamp that links together all the output files that were generated on a given run.

# Upstream trace
Each output file should also indicate which upstream module files (the actual hashed files) were used to generate this output.

# Log trace
For input files (both CSV and hive tables), the log output during the run is silent about what file is being used.  For projects that utilize run time configuration, it would be nice to see the output of the actual file being used.

# command line interface
We should add a command line interface for tracing the upstream data rather than have the user chase the links.  For example:
```bash
$ smv-pyrun --trace "hdfs:///app/blah/stage1/modX_a1847e32.csv" --run-app
```

# Metadata
All the above info about a given dataset version should probably live in a separate metadata file.  This will require #121 and #332.

**Comment by laneb** [comment]
Will start by including the inputs, their hashes, and the timestamp for running the application in the metadata.

**Comment by laneb** [comment]
Per discussion with @AliTajeldin, inputs will be listed by the path of their `.meta` files. This will simplify tracing the data and allow us to list all inputs (including ephemeral modules and published data) in a unified format. It will entail publishing metadata when a module is published.

**Comment by AliTajeldin** [comment]
And for links, the `.meta` file of the target will be shown (regardless if it is a normal module or a published module).

**Comment by laneb** [comment]
Done. We can add other metadata fields as needed.
