### ISSUE TITLE
df() on newly created module cause runtime error

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#641]
create a new module named foo.
without exiting out jupyter, encounter following error:
`org.tresamigos.smv.SmvRuntimeException: Cannot find module named [foo]`

**Comment by laneb** [comment]
Is the new `SmvModule` put in a pre-existing file or did you create a new file for it? I suspect this would occur because the package containing the `SmvModule` has already been imported, and during discovery we don't reload it to find out if the `SmvModule` inside have changed.

**Comment by XiaosenChen** [comment]
It is in a pre-existing file.

**Comment by laneb** [comment]
The solution is to make sure when doing discovery that we reload modules if we've already imported them in a previous transaction - _not in this one_.  This is closely tied to #646.

**Comment by laneb** [comment]
Fixed.
