### ISSUE TITLE
manually deleting output data does not trigger re-run but results in exception

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#643]
In the scala interface, if user manually delete a specific output data (both the .csv dir and .schema dir) of a module, df() on the module will trigger a re-run. However, with python interface, without exiting out of the jupyter, user gets this error.
```
An error occurred while calling z:org.tresamigos.smv.python.SmvPythonHelper.peekStr.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 22.0 failed 1 times, most recent failure: Lost task 0.0 in stage 22.0 (TID 33, localhost): java.io.FileNotFoundException: File file:outputdir/outputdata.csv/part-00000 does not exist
```

**Comment by laneb** [comment]
Does this happen every time? If not, can you consistently reproduce it?

**Comment by laneb** [comment]
This can be replicated in `smv-pyshell`. It appears that we are reusing the cached `DataFrame`, which wants to read from the persisted results even after they have been deleted. It is not clear to me how this would have worked before in the Scala shell _or_ the python shell without `ddf`, as we have always cached the `DataFrame`. In any case, to support this behavior `SmvDataSet` will need to skip the cache if there is no persisted output.

**Comment by laneb** [comment]
However, I'm not sure that this is a usage pattern we should encourage. Perhaps it would be better to provide an optional flag in `df` that forces the module to be run again by skipping the cache and ignoring the persisted data.

**Comment by AliTajeldin** [comment]
@laneb 👍 on the `df` flag.  This is related to #481 to ignore persisted files and force a rerun.

**Comment by laneb** [comment]
I will add the flag. What should the behavior be when the user runs a module again in the same shell after deleting its output?

**Comment by laneb** [comment]
Actually, the interface might get a little messy if we also want the flag described in #651. How would we combine the two?

**Comment by AliTajeldin** [comment]
Make both flags optional:
```python
def df(fqn, forceRun=false, version=None):
  ...
```
Then user can provide either positional or keyword mapping during call:
```python
> df("a.b.c", version="v15")
> df("a.b.c", true)
> df("a.b.c", forceRun=true)
```

Another option is to **only** accept keyword args.
```python
def df(fqn, **kw):
  # check here for "forceRun" and "version" args.
```
so the user will have to specify the `forceRun` and `version`

**Comment by laneb** [comment]
Will `df` be documented with `sphinx`? If so I think think the first option is preferable because it provides a more helpful signature.

**Comment by laneb** [comment]
I will add the flag for `df`. The process for forcing a module to rerun will be

1. Delete its output (if any) which has the current hash
2. Skip the `DataFrame` cache

The jump to the `--force-run` option will just be to add the flag to the `SmvConfig` and delete the output at the top of `generateOutputModules` if the flag is set.

**Comment by laneb** [comment]
To summarize, we do not support the usage pattern of deleting output files to force a module to rerun. In the shell, if you want to force a module to rerun, use the `force_run` flag.
