### ISSUE TITLE
prevent reload of python modules when multiple SMV modules are in same file.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#646]
## Problem
Assume we have the following hierarchy:
* SMV Module A which is in file f1.py
* SMV Modules B,C which exist in file f2.py
* Base class D which exists in file f3.py
* A depends on B and C (i.e. requires)
* B and C derive from D (base class)
* Inside a method of B, we call `super(B,self).blah()` to call the super method `blah()`.

When user runs `df("B")` from shell, everything works fine.  However, if user does `df("A")` then we get a type error with the super call because the `self` instance is not of the type `B`.  However, if we print the classname of `self`, it is indeed `B`.

## Root Cause
The root cause is the reload of python module `f2.py`.  When `A` is loaded, it will try to load `B` and `C`.  We will call `_reload("B")` which will import the `f2.py` file which has an instance of the `B` class object (not an instance object, but a class object).  When `C` is loaded, `_reload` will re-import the `f2.py` file which will create another instance of the `B` class.  When the `B` run method is called, the `self.__class__` will be different than the global `B` class (which is from when `C` is loaded)

## Proposed Solution
Because we create a new python repo for each load context, we should cache the reload of the python modules.  So the second time we try to reload `f2.py`, we should get the same module instance.

**Comment by laneb** [comment]
This is somewhat complicated by the fact that the reload of `f2` is implicit in the reload of `f1`-
 there is actually no `_reload("B")`. When we call the Python builtin `reload` on `f1` it causes a `reload` on the modules imported in `f1`, including `f2`. I'm not certain how to prevent reloading the same module twice in a transaction we have a scenario like the above with the addition of an `SmvDataSet` `E` which depends on `B` - in this scenario, we should expect `smv-pyrun -m E A` to fail, because we will reload both `E` and `A`, causing the reload of `B` twice.

**Comment by laneb** [comment]
Actually, this will cause an issue even without `E`. In the original scenario we could just run `smv-pyrun -m E C`.

**Comment by laneb** [comment]
What the solution needs to accomplish is to prevent `f2's` code from being executed twice, creating 2 distinct `Bs`, in a single transaction. If we have never imported the module `M` containing an `SmvDataSet` `X` before (`_load`), loading `X` will import `M`, executing its code and also the code of any module imported for the first time as a result of `M's` code.  Loading `M` again for any reason (`_reload`) will execute just this module's code and the code of any modules imported for the first time as a result of executing `X's` code - e.g. we decide after running `X` that `X` should also use data from `Y` in module `N`, which has not been imported before). In the first case, we can identify all newly executed modules by diffing `sys.modules`. In the second case, we can identify all newly executed modules by diffing `sys.modules` and adding `M`.

**Comment by AliTajeldin** [comment]
Current proposed solution is to remove the modules from `sys.modules` dictionary upon start of a transaction.  This will force a reload of relevant modules when they are normally imported (no need for reload then).  @laneb will provide full details in a design doc shortly.

**Comment by laneb** [comment]
Fixed. @ninjapapa can you confirm that this resolves the issue for you?
