### ISSUE TITLE
SmvModuleLink should be able to be resolved in shell

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#651]
Here is the use case:
* Published module A in stage1 with version 123
* In stage2 we have a link `ALink` defined as `ALink = SmvModuleLink(stage1.A)`, and
* The config file specified the version of stage1 is `123`
With above setup, we want to check/profile on the published `A`. 

Ideally in the pyshell or jupyter we should be able to:
```
a = df("ALink") 
a.smvEdd()
```

Currently to do above, we need to create a dummy SmvModule to pass down the link.

**Comment by AliTajeldin** [comment]
How about adding an optional version string to `df()`.  That is something like:
```
a = df("A", "123")
b = df("A", "124")
c = df("A")
```
That would also allow you to compare different published versions against the current code version.

**Comment by jacobdr** [comment]
Really like this feature idea. I imagine we could then even use DQM to raise issue if the diff is unexpectedly large.

**Comment by Khorkhe** [comment]
fixed, as per Ali's suggestion above

**Comment by ninjapapa** [comment]
Need to update docstr and user doc for the new parameter of "df".

**Comment by Khorkhe** [comment]
fixed
