### ISSUE TITLE
Make core bash scripts "strict mode" compatible

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#664]
[Bash unofficial strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/) is fairly popular. So are some other [bash script linters](https://github.com/koalaman/shellcheck). 

We should make an effort to try to make sure our scripts (mostly in [tools](https://github.com/TresAmigosSD/SMV/tree/master/tools)) oblige.

**Comment by laneb** [comment]
Per @AliTajeldin, we will do this for future scripts but will not change current scripts.

**Comment by jacobdr** [comment]
Can we keep this open as a tracking ticket? I'm happy to make the PR at some point in the future.

Jacob

**Comment by AliTajeldin** [comment]
We shouldn't add the flags to existing working scripts.  We have higher priority work.
