### ISSUE TITLE
smvEdd() fail on ArrayType Column

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#671]

**Comment by Khorkhe** [comment]
is this occurring in a Scala or Python project?

**Comment by AliTajeldin** [comment]
@Khorkhe I don't think the actual language matters here.  Just create a df with a column of type array and see if you can run edd on it.

**Comment by ninjapapa** [comment]
The problem is what should be the behavior when smvEdd encountered an ArrayType. I actually think fail on ArrayType is the correct behavior.

**Comment by XiaosenChen** [comment]
I think smvEdd on a df with an array type column should still work for the
rest of columns. For the array type column, results in a message saying
this is an array type.

**Comment by AliTajeldin** [comment]
@XiaosenChen 👍

**Comment by ninjapapa** [comment]
👆

**Comment by Khorkhe** [comment]
fixed
