### ISSUE TITLE
Include smvshell in the API docs

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#676]
We could automatically document changes to shell commands by including `smvshell` in the API docs. Currently `smvshell` has no docstrings and `smvshell.py`. Once this is included in the API docs we can limit the "Running Spark shell" section of the SMV guide to examples.

**Comment by laneb** [comment]
Hey @ninjapapa don't work on this! I should've assigned myself to this earlier, but I'm nearly done with it now.

**Comment by AliTajeldin** [comment]
Done
