### ISSUE TITLE
No Python test for `smvPivotSum`

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#678]
Doesn't seem like we have a test for the function on the Python side. Additionally, the [docstring](https://github.com/TresAmigosSD/SMV/blob/10d816257c2b7f35d2eb0d04817c9c5450209299/src/main/python/smv/helpers.py#L111) might need some updating

**Comment by Kai-Chen** [comment]
Note that when you write this test, you won't need to test the correctness of the function, as that is already covered by the relevant tests in Scala.
All you need is a one-liner that touches (covers) the code.
What you are looking to assert is just that there is no mistake in the glue code.

**Comment by ninjapapa** [comment]
Current smvPivot related functions on Python side is not comprehensive, and the docstring of `smvPivotSum` was copied from a wrong place. Need to fix.

**Comment by AliTajeldin** [comment]
Fixed
