### ISSUE TITLE
smv profile isn't sourced after install

### ISSUE THREAD

**Issue by chengfei0913** [TresAmigosSD/SMV#685]
the function "source_profile_file()" in smv-install.sh only writes the file name which need to be sourced into the profile file, but does not really source it. Maybe we can add a source command at the end of the function. Otherwise, we should log out and log back in to make SMV works.

**Comment by AliTajeldin** [comment]
We can not source the profile file inside the script.  Actually, we could, it just will not have any effect.  We can change the environment variables of the parent shell.  The user doesn't really have to logout, they can just run "source ~/.bash_profile".

I think we could just add the actual required source command for the user to run so that they can just copy and paste it.

**Comment by jacobdr** [comment]
With #623 we have a consistent directory from which to source the requisite environment variables from, irrespective of the `bash_profile` who user who actually does the installation

**Comment by jacobdr** [comment]
We do something like this in our project, where DEPENDENCY_INSTALLATION_DIRECTORY is an environment variable set by the user doing the installation. We also use a symbolic link of `smv-latest` so that we can keep multiple versions on disk and stage/test our upgrades.
```bash
mkdir -p "${DEPENDENCY_INSTALLATION_DIRECTORY}"
chmod 775 "${DEPENDENCY_INSTALLATION_DIRECTORY}"
pushd "${DEPENDENCY_INSTALLATION_DIRECTORY}"

SMV_DIR_NAME="SMV_${SMV_VERSION}"
SMV_PROJ_ROOT_DIRECTORY="${DEPENDENCY_INSTALLATION_DIRECTORY}/${SMV_DIR_NAME}"
SMV_PROJ_LINK_DIRECTORY="${DEPENDENCY_INSTALLATION_DIRECTORY}/smv-latest"
SMV_PROJ_TOOLS_DIRECTORY="${SMV_PROJ_LINK_DIRECTORY}/tools"
SMV_ENVIRONMENT_VARIABLES_PATH="${SMV_PROJ_TOOLS_DIRECTORY}/smv-profile.sh"

echo "About to start installing smv to: ${SMV_PROJ_ROOT_DIRECTORY}"
curl https://raw.githubusercontent.com/TresAmigosSD/SMV/master/tools/smv-install | bash -s -- -spark "${SMV_VERSION}"
popd
chmod -R 755 "${DEPENDENCY_INSTALLATION_DIRECTORY}"
ln -sfn "${SMV_PROJ_ROOT_DIRECTORY}" "${SMV_PROJ_LINK_DIRECTORY}"
echo "Successfully linked SMV from ${SMV_PROJ_ROOT_DIRECTORY} to ${SMV_PROJ_LINK_DIRECTORY}"


cat <<EOF
The SMV environment variable file at ${SMV_ENVIRONMENT_VARIABLES_PATH}
needs to be sourced.

This can be done through "source ${SMV_ENVIRONMENT_VARIABLES_PATH}"
EOF
```

**Comment by AliTajeldin** [comment]
To summarize above, we just need to add a message to smv install to say "source smvhome/tools/smv_profile.sh" at completion of install.

**Comment by laneb** [comment]
Done.
