### ISSUE TITLE
Handle Race Condition when Persisting SMV DataSet Result

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#687]
## The Problem

If two developers write SMV modules that depend (including transitively) on the same upstream module A and submit their jobs simultaneously, there can occur a rare race condition in which both jobs determine that A needs to be run (because the result of A does not exist when both processes are testing).
Though this would not necessarily generate an *incorrect* result, it carries at least the penalty of doing the work twice, which sometimes can be quite expensive.

## Solution

Turn `FileIOHandler.saveAsCsvWithSchema` into an atomic operation so that if it detects that the same dataset is in the process of being written to disk, it will block and poll (preferably with a configurable timeout) till writing is complete.

The `SmvDataSet.computeRDD` method may also need to be modified to check before compute.

**Comment by Kai-Chen** [comment]
One way with less impact to the existing code in FileIOHandler is to encapsulate the *Job* concept in a separate class with all the file checking and polling logic.

**Comment by AliTajeldin** [comment]
@Kai-Chen Can you add a quick design doc under `docs/design/persist` dir to show the class diagram and sequence diagram to show the relationship and flow.

**Comment by Kai-Chen** [comment]
For now the code deciding whether to initiate the persistence *job* will still be kept in `SmvDataSet.computeRDD`.

We will create an `SmvLock` class to simulate a mutex for SMV module persistence.
This class will be responsible for atomically creating a file, blocking if the file already exists, with the standard `lock`, `unlock`, and `tryLock(timeout)` methods.
Class diagram will be provided along with pseudocode.

**Comment by AliTajeldin** [comment]
Done
