### ISSUE TITLE
Rename YAER, MONTH, DAYOFMONTH and other date related non-aggregate

### ISSUE THREAD

**Issue by eagle123** [TresAmigosSD/SMV#70]
Need to rename the following non-aggregate to be pre-fixed by "Smv" and post-fixed by "Str"

- Rename YEAR to SmvYearStr
- Rename MONTH to SmvMonthStr
- Rename DAYOFMONTH to SmvDayOfMonthStr
...

**Comment by ninjapapa** [comment]
done.
