### ISSUE TITLE
Need a python conf/smv_shell_init.py 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#700]
Currently on scala side, when run `smv-shell`, a project level script `conf/shell_init.scala` will be loaded at the beginning of the SparkShell. We need an equivalent on the python side. Basically each project could have a `conf/smv_shell_init.py` file, and `smv-pyshell` and `smv-jupyter` should import it if exist.

**Comment by laneb** [comment]
Should it be imported or executed?

**Comment by ninjapapa** [comment]
python `import` is executing, right?

**Comment by laneb** [comment]
Importing `smv_shell_init` will execute the code, but in the context of the module `smv_shell_init`, so the user will have to call their function `foo` like `smv_shell_init.foo`. To execute client startup code, pyspark uses the builtin function `execfile`, with an effect equivalent to pasting the file into the shell when it starts up. Actually, we might be able to do `from smv_shell_init import *`, but I'm not sure all of the differences in behavior there might be. It _would_ make it easy for users to ignore some of the attributes defined in the module, like helper functions. It _wouldn't_ allow users to use any of the SMV shell methods like `df`

**Comment by laneb** [comment]
Notably, `pyspark` uses `execfile` to run the user's `PYTHON_STARTUP`. However, based on [this](http://stackoverflow.com/questions/11703327/python-import-vs-execfile) and [this](http://stackoverflow.com/questions/27517003/difference-between-import-and-execfile) SO posts, it sounds like `import` is probably better and also preferred even for this kind of use case.
