### ISSUE TITLE
scala test smvHiveTableTest failing

### ISSUE THREAD

**Issue by Khorkhe** [TresAmigosSD/SMV#715]
Latest changes for stage validation is causing a scala test to fail locally but not on Travis.

Reason for failure is "stage not defined".

**Comment by Khorkhe** [comment]
looks like Travis build is actually failing

**Comment by Khorkhe** [comment]
running sbt test on the following systems for commit 12aa7f93777eae92917e353bfe53dbb66f855383 (test should fail):

 - Travis: fail
 - @khorkhe (OSX): pass
 - @khorkhe (Linux): fail
 - @laneb (OSX): fail

Don't think it has to do with Scala versions as the version in build.sbt should be in use.  
Lane and my systems all have Java 8

**Comment by laneb** [comment]
@Khorkhe since we were unable to reproduce this last week, can we close the issue?

**Comment by Khorkhe** [comment]
I was going to keep it assigned to me just as a reminder for when it appears again. But if you prefer, we can close it for the time being
