### ISSUE TITLE
Support in SmvCsvFile interface to allow specify schema through code

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#726]
Use case:

A client wants to change input file paths to CSVs through config file, but is not familiar enough with SMV to follow the current requirement of creating a well-specified `.schema` file at the necessary locations 

Ideally would be able to provide schema through the Python code, and have some form of early run-time enforcement of that schema conversion (in addition to the DQM checks)

**Comment by laneb** [comment]
When you say 

> provide schema through the Python code 

do I follow correctly that the module would include a string describing the schema? Something like

```
class MyModule(SmvModule):
  def mySchema(self): return "col1:String;col2:Integer"
  ...
```

**Comment by ninjapapa** [comment]
@laneb it is accurate, except we may want to name the method differently.

**Comment by laneb** [comment]
Names are negotiable ;]

**Comment by laneb** [comment]
It should be simple to skip reading the schema from file if the user overrides the `userSchema`. `SmvSchema` already provides a tool for reading schemas from string. When you say 

> early run-time enforcement of that schema conversion

do you mean that the errors in the specification of the `userSchema` would be detected early?

**Comment by laneb** [comment]
Done.
