### ISSUE TITLE
Python vs Scala run-time checking of keys specified in `smv.config.keys`

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#727]
Not sure if this is a bug, but after looking at the source was a little bit unsure of what the behavior was when a user specifies a key in `smv.config.keys`, but then never provides the associated value downstream. 

For example, what the behavior is when a user specifies `smv.config.keys=mykey1`, but then fails to set `smv.config.mykey1` through smv-app-conf, smv-user-conf, or the command line properties. 

I think my reading is that because we look for the key in the [`mergedProps`](https://github.com/TresAmigosSD/SMV/blob/master/src/main/scala/org/tresamigos/smv/SmvConfig.scala#L174) Map using the apply method, we will get a runtime error when the [`getRunConfigHash`](https://github.com/TresAmigosSD/SMV/blob/master/src/main/scala/org/tresamigos/smv/SmvConfig.scala#L213) method is called. 

And because on the Python side will call this method [relatively early](https://github.com/TresAmigosSD/SMV/blob/10425c9b519c6ba3136061543feec887d31abf77/src/main/python/smv/smvpydataset.py#L173) when the first datasethash is computed, we do not have to worry about a super-late stage module failing for this reason.

However, I did not see `getRunConfigHash` invoked anywhere on the Scala side, so was not sure if we would get different behaviors.

Would someone mind helping me through this section of the code?

**Comment by AliTajeldin** [comment]
@jacobdr : did you try it out?  What was the result?

**Comment by laneb** [comment]
I think you are reading this correctly, and yes, I would anticipate a different behavior for a pure Scala project. For Scala modules, I anticipate the error will come wherever the user asks for the config value in their code.

**Comment by jacobdr** [comment]
Interestingly, on the Python side, it seems like if a key is provided in the body but not listed in the `smv.config.keys` section, the value is still accessible and no error is thrown

**Comment by laneb** [comment]
Does anything need to be changed or fixed?

**Comment by laneb** [comment]
@jacobdr is there anything you need fixed WRT this issue?

**Comment by jacobdr** [comment]
Not sure. The fact that a runtime exception was expected but not thrown is a little bit of a smell. On the other hand, not sure if we really do want the behavior of throwing a runtime exception when a key is specified, but its value is not provided.

In general, it would be nice if the framework provided a cleaner way to enforce runtime configuration required keys vs optional keys (potentially with default values). But that might be out of scope for this ticket and probably needs to be discussed internally. Also, It seems like Scala side runConfig hasn't gotten love in a little while. 

Am curious to hear @AliTajeldin's opinion given his recent work on a project that used the Python runtime config quite heavily

**Comment by AliTajeldin** [comment]
We are actually not using the `keys` in any way at this point.  They are there for future when we need the values on the executor side.  On the driver side, we just read the values from the config directly.  On the executor, we may need to "ship" all the values to each executor.  Since we are creating a giant map as part of parsing the config, we can probably deprecate the `keys` property all together.  Need to investigate further (See #881)

**Comment by AliTajeldin** [comment]
Closing this for now.
