### ISSUE TITLE
Provide Git Integration

### ISSUE THREAD

**Issue by Kai-Chen** [TresAmigosSD/SMV#729]
Because pygit2 introduces native dependency through libgit2, which complicates development environment, we will look further into GitPython as the library to use, despite its known limitation of leaking system resources.

**Comment by jacobdr** [comment]
What is the general use case here? I might have missed a previous conversation....

**Comment by AliTajeldin** [comment]
@jacobdr it is for an external project.

**Comment by Kai-Chen** [comment]
The most current `jgit` library is compiled with JDK8.
So work using this library can't be merged into master till either master is updated to Java 8 or branch 2.1 is merged (which uses Java 8).

**Comment by Kai-Chen** [comment]
This topic branch has been grafted from `master` to the `2.1` branch.

**Comment by Kai-Chen** [comment]
Only things missing  are:
* flask configuration for the location of a local repository (where `.git` directory is)
* flask test
