### ISSUE TITLE
Style the Python API docs

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#735]
The default style for SMV's Python API docs is hard to read and also hard on the eyes (ugly + bright white everywhere). Other Sphinx docs (like the [official Python docs](https://docs.python.org/2/)) have custom style. We roll our own style, but first we should see how others do their styling. There may be Sphinx plugins or other tools that make this easy.

**Comment by laneb** [comment]
Sphinx has several easily pluggable themes which we could use for layout and coloring. The list can be seen [here](http://www.sphinx-doc.org/en/stable/theming.html#builtin-themes). Notably, "classic" resembles the Python 2 official docs and "agogo" resembles pyspark docs. As a first step we can adopt one of these. Then we will need to work on styling the text. @AliTajeldin any opinions on these themes?

**Comment by laneb** [comment]
Also notably, we are currently using the "alabaster" theme. I guess that's the default.

**Comment by AliTajeldin** [comment]
Let's just go with classic as agogo seems to have the TOC on the right hand side.  We need to confirm that it will use the entire screen (minus nav-menu on left) instead of jumbotron style.

**Comment by laneb** [comment]
Got confused on the names, it's actually the "nature" theme that's used for the [pyspark docs](http://spark.apache.org/docs/2.0.0/api/python/index.html). But classic sounds good to me.
