### ISSUE TITLE
Finalize removing py from Python names

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#744]
A while back we dropped 'py' from the names of all of the user-facing `SmvDataSet` classes (e.g. `SmvPyModule` -> `SmvModule`) but added deprecated aliases for the old names. We need to finish the transition by removing the deprecated names, which are still used in some tests, fixing the internal names (`SmvPyDataSet` was never changed) and renaming the `smvpydataset` module.

**Comment by AliTajeldin** [comment]
Done
