### ISSUE TITLE
Two files in the project named `gen_docs.XYZ` without documentation

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#745]
[admin/gen_docs.sh](https://github.com/TresAmigosSD/SMV/blob/273f8728626f7d2179281c629643b0ffcafe7ec2/admin/gen_docs.sh) looks like it can replace [tools/gen_docs.py](https://github.com/TresAmigosSD/SMV/blob/f0e0c9f44b104c6592b7ed440448319d0d813b6a/pom.xml#L184), given that we allow it to handle additional command line arguments? Kind of confusing to have both files around

**Comment by laneb** [comment]
Yeah I think we can remove `gen_docs.py`. I don't think there is a lot of additional documentation necessary for `gen_docs.sh`, but it deserves a sentence in the dev docs.

**Comment by AliTajeldin** [comment]
`tools/gen_docs.py` is for generating the old site docs.  It can be removed (and the reference to it in `pom.xml`).
