### ISSUE TITLE
A dataset's run method should automatically create/define var mapped to a required dataset

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [TresAmigosSD/SMV#769]
When adding a required dataset `a.b.c.d` to the return value of the requiresDS function, the run method of a dataset should automatically map a variable name to the required dataset.

E.g.:

```
def requiresDS():
    return [a.b.c.d]   # let's say on /api/update_dataset_info, we aded a.b.c.d

def run(i):
    ###---requiresDS_mapping_start---###
    d = i[a.b.c.d]
    ###---requiresDS_mapping_end---###

   return  d 
```

Therefore, the end user should be able to automatically consume `a.b.c.d` by simple using the variable `d`

**Comment by laneb** [comment]
Handled by client (as per @AliTajeldin).
