### ISSUE TITLE
Issues of following the SMV installation guide (See #1)

### ISSUE THREAD

**Issue by tianruiwang** [TresAmigosSD/SMV#775]
1. In the installation guide, after SMV is installed, it turns out that the file .bashrc isn't updated properly. The lines "#---SMV PROFILE----" and "source ${SMV_PROFILE}" is not appended at the end of this file as desired.

2. In the SMV quick start "run example app" section, the command "smv-pyrun --run-app" should be run in the project directory, which is not mentioned in the tutorial.

3. In the SMV quick start "run example app" section, one may encounter the error "Could not find or load main class org.apache.spark.launcher.Main" if the java version is lower than 1.7. Can add some trouble shootings regarding to this error, let them check their java versions by the command "javac --version".

**Comment by laneb** [comment]
1. Did it end up in a different profile file (like .bash_profile)?
2. Will fix
3. Addressed in #778

**Comment by laneb** [comment]
@tianruiwang For 1, can you expand on what happened? Did the SMV_PROFILE lines end up in a different profile file? Was there an error message?

**Comment by tianruiwang** [comment]
@laneb I'm sorry that I might not be able to reproduce that error since I don't know how to rewind back to the same enviroment as I installed it 3 weeks ago. I checked through the root directory and find two files end up with the lines `#---SMV PROFILE----` and `source ${SMV_PROFILE}`, which are `.bashrc` and `.profile`. If I remembered correctly, one of them is manually added by Bo after the installation.

**Comment by ninjapapa** [comment]
The problem was,
* smv install script modified `.profile` file, as it was the first on the list
* but Ubuntu 14.* somehow ignored `.profile` when logout and log back in the graphical desktop management system

**Comment by AliTajeldin** [comment]
@laneb we just need to reverse the order of priority between `.profile` and `.bashrc` in the `smv-install` script.

**Comment by laneb** [comment]
Done.
