### ISSUE TITLE
Stop dynamically creating class for SmvModuleLink

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#776]
Currently, the `SmvModuleLink` and also `SmvExtDataSet` classes are created on the fly so that we can the result is a class with the correct `fqn` class method. However, it is not truly necessary that the `SmvModuleLink` helper method returns a proper class - it will be sufficient that it is an object with an `fqn` method. This will simplify the code.

**Comment by AliTajeldin** [comment]
I love duck typing. quack quack :-)

**Comment by laneb** [comment]
🦆

**Comment by laneb** [comment]
Done.
