### ISSUE TITLE
Slight Modification on the SMV Quick Start guide #2

### ISSUE THREAD

**Issue by tianruiwang** [TresAmigosSD/SMV#778]
In the SMV quick start "run example app" section, one may encounter the error "Could not find or load main class org.apache.spark.launcher.Main" if the java version is lower than 1.7. Can add some trouble shootings regarding to this error, e.g. check their java versions by the command "java -version".

**Comment by laneb** [comment]
The quick start guide already points users to the installation guide which includes the Java requirements. We could add instructions for checking Java version there. Perhaps we could also add a page about what common errors like this might mean.

**Comment by laneb** [comment]
For common errors page, #844. Will add a note about how to check java version.
