### ISSUE TITLE
Links on current master (v1.5.2.9 -- 381b2c3e00) README to python and scala api docs are broken

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#781]
http://tresamigossd.github.io/SMV/pythondocs/1.5.2.9/index.html

http://tresamigossd.github.io/SMV/scaladocs/1.5.2.9/index.html#package

**Comment by AliTajeldin** [comment]
@laneb Please generate the docs for 1.5.2.9 manually for now until #657 is implemented.

**Comment by laneb** [comment]
Done.
