### ISSUE TITLE
publish-docs.sh should fail and exit if sphinx is not installed

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#782]
Should be able to just use `set -e`.

**Comment by AliTajeldin** [comment]
publish-docs and gen-docs are being embedded inside `smv-install` #657 .
Closing this ticket as will not fix.

**Comment by laneb** [comment]
Will `publish-docs` be invoked from within `release_smv` or will `release_smv` run sphinx itself?  It appears that `-e` does not get passed through to child processes, so we would still have this problem if it is the former.

**Comment by AliTajeldin** [comment]
`smv-release` will run sphinx itself (using docker image, not directly).  I'm basically moving the code from the two above scripts into `smv-release` and using docker images to do the actual work to remove the need for user to have sphinx installed.

**Comment by jacobdr** [comment]
Hacker News turned me on to the "bash strict mode" a few years ago, and I'll mention it here as potential solution:

http://redsymbol.net/articles/unofficial-bash-strict-mode/
https://github.com/tests-always-included/wick/blob/master/doc/bash-strict-mode.md
