### ISSUE TITLE
adding an smvExportCSV method to SmvDataset

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#783]
Current `smvExportCsv` is a  DF helper, so it has no knowledge if a data set is persisted or not. Should provide `SmvDataset` a methods to export to csv, in that case we don't need to create an addition hdfs copy of the data. 

There should be potentially 2 places can trigger that method, we can provide a shell function similar to "df" function, and provide some command line parameter to trigger it through command line.

**Comment by AliTajeldin** [comment]
Agree.  There should be two interfaces:
* shell `smvExportCsv(fqn)` method.
* command line `--publish-local` that publishes all output modules in current run to a local csv file.

**Comment by laneb** [comment]
Done.
