### ISSUE TITLE
Add short option for --run-app

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#816]
Maybe -a.

**Comment by laneb** [comment]
@AliTajeldin what do you think of `-a` as short for `--run-app`?

**Comment by AliTajeldin** [comment]
@laneb `-a` sounds good to me.

**Comment by laneb** [comment]
Actually, it is easy to get the default short name for `--run-app` (`-r`) working, but Scallop seems to fail when toggle options are given custom short names. I've snooped on this one for about a half hour and haven't turned up any clues, and it's not worth the time just to change the letter. Will go with `-r`.
