### ISSUE TITLE
Add a selfjoin helper method on RDD

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#82]
self joins are a pain in spark SchemaRDD because of the name conflict.  Add a self join helper function that automatically joins an SRDD against itself and apply a prefix to the right hand side to avoid name conflict.
Example:
```scala
srdd.selfjoin(Inner, 'key === 'r_key)
```
instead of:
```scala
srdd.join(srdd.add_prefix("r_"), Inner, 'key === 'r_key)
```
While it doesn't save on much typing, it makes the code more self documenting.

**Comment by ninjapapa** [comment]
Name conflict is resolved by the ```joinByKey``` method. Self join by itself is more a "solution" than a problem we trying to solve. CDS basically is a generalize version of the self join requirement here. This issue is half solved and half should be moved to the CDS issue. Closed.
