### ISSUE TITLE
Updated Install user doc is not consistent with the released install script

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#824]
`smv-install` script of 1.5.2.9 taking a version parameter, which is different from the current user doc.

**Comment by ninjapapa** [comment]
Sounds like the User doc updated while the package is no released yet. There is an inconsistency between master branch's user doc and last release version's install script. How should we handle this? May need to publish the user doc with the release also.

**Comment by AliTajeldin** [comment]
This is because the `smv-install` script will no longer take a parameter for the version to install.  Once 1.5.2.10 is released shortly, everything will be in sync.

**Comment by ninjapapa** [comment]
Fixed as 1.5.2.10 released.
