### ISSUE TITLE
smv-server getFqnOfRequire failed

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#827]
Since SmvModuleLink now is a class, and "target" is an attribute instead of a method, `getFqnOfRequire` of smv-server stoped working.

This issue can be easily addressed when making the SmvModuleLink, if smv-server has some test case. This issue is a good example of why we need #826

**Comment by laneb** [comment]
Is this issue complete?

**Comment by AntonioRecaldeRusso** [comment]
completed. Can be closed
