### ISSUE TITLE
Allow smvserver to be extended by another server script

### ISSUE THREAD

**Issue by AntonioRecaldeRusso** [TresAmigosSD/SMV#828]
When running the container in --start-server mode, the user should be able to provide a -e flag followed by the full local path of a python script that extends the smvserver.
By doing this, the user can continue to consume the available smvserver entrypoints, but also define  additional entrypoints in a file from a different project.

**Comment by AliTajeldin** [comment]
Let's hold off on this for a bit.

**Comment by AliTajeldin** [comment]
oops, just noticed that the work was already done.

**Comment by AntonioRecaldeRusso** [comment]
completed. Can be closed
