### ISSUE TITLE
Link to the 1.6.2.1 version release notes is dead

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#847]
The [v1.6.2.1 release notes](https://github.com/TresAmigosSD/SMV/blob/master/releases/v1.6.2.1.md) is a dead link. 

[Releases page link](https://github.com/TresAmigosSD/SMV/releases)

**Comment by AliTajeldin** [comment]
Manually fixed the 1.6.2.1 release link.  Keeping this open to apply the fix to the `smv-release` script.
The issue is that we are releasing from a branch so the release notes are only available on the branch and not on master.  The release script should use the branch name in the url.

**Comment by laneb** [comment]
Closed as fix will be part of #882.
