### ISSUE TITLE
Remove special handling of SmvCsvFile with path starts with "input" 

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#855]
Due to historical reason, for a SmvCsvFile with the path starts with "input", we actually prepend "smv.dataDir" instead of "smv.inputDir". It is really confusing.

**We should not do it any more.** For any existing project which is using that "feature", one can simply adjust the "smv-user-conf.props" to make "smv.inputDir" the same value of "smv.dataDir".

**Comment by laneb** [comment]
Done.
