### ISSUE TITLE
SMV should handle utf-8 encoded files

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#858]
This should include:
 
- [x] reading csv files encoded in utf-8
- [x] persisting files using utf-8
- [x] publish local should publish using utf-8
- [x] publish-jdbc should allow to publish data to a JDBC database that understands unicode.
- [x] publish-hive should maintain the unicode characters.

**Comment by laneb** [comment]
Publishing UTF-8 text to JDBC will require the correct DB configuration and may in some cases require special parameters in the URL.

**Comment by laneb** [comment]
Confirmed that SMV preserves UTF-8 encoding in all of these cases.

**Comment by AliTajeldin** [comment]
Need to figure out the root cause of issue at client side. Reopening for tracking purposes.

**Comment by laneb** [comment]
@AliTajeldin We identified the root cause of this one. I believe the issue was with their database configuration. Is that accurate?

**Comment by AliTajeldin** [comment]
Correct.  The issue was with their Hive table setup.  Closing this.
