### ISSUE TITLE
stage level dependency

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#861]
This is to start the discussion of the functionality of stage. What should stage really do?
Here is a use case:
Stage1 (M1, M2, M3, ...Mn)
Stage2(Mfinal)
M4 depends on M1, M2...Mn, and is pined to a published version of Stage1 as V1. However, as development moves forward, there is an update of M2, whereas all other Modules in Stage 1 stays the same. To republish the entire Stage1 is not very efficient.
In this case, the stage level dependency restricts the development.

**Comment by laneb** [comment]
For the situation you describe, you should be able to republish V1 of M2 by itself without republishing the whole stage.

**Comment by XiaosenChen** [comment]
yes, the issue is not on publishing, but on the stage that depend on the
published output.

**Comment by AliTajeldin** [comment]
@XiaosenChen I think we will need a whiteboard session to understand the requirement and explore some possible solutions.

**Comment by laneb** [comment]
@AliTajeldin Did you and @XiaosenChen hash this out?

**Comment by AliTajeldin** [comment]
We are effectively deprecating stages.  Closing.
