### ISSUE TITLE
New SmvModule for modelling

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#862]
When modeling it would be helpful if a module could return a model as a result rather than a `DataFrame`. Need to create special module `SmvTraining` that returns a model as a result and`SmvModel` that receives a model as input.

**Comment by AliTajeldin** [comment]
The classes should be `SmvModel` and `SmvModelExec`.  `SmvModel` is where the training takes place.

**Comment by laneb** [comment]
Done.
