### ISSUE TITLE
schema csv attributes update is not reflected

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#868]
Module A (a SmvCsvFile) points to a csv file whose schema CSV attributes has been updated. Running Module A again after the update does not reflect the change.
currently, user can manually purge this data in the ouput dir to solve this problem.

**Comment by Khorkhe** [comment]
Hi @XiaosenChen 
I've attempted to reproduce this issue, as follows:

 - SmvCsvFile points to some csv file. The data dir also contains a .schema file for this csv
 - Run the first time, it persists: `16:48:17 PERSISTING: file:///Users/khorkhe/Desktop/temp/enter/data/output/stage1.employment.EmploymentByState_f68542ef.csv`
 - Edit the .schema file (say, change a coltype from String to Integer)
 - Run the second time again. It persisted under a different hash: `16:49:44 PERSISTING: file:///Users/khorkhe/Desktop/temp/enter/data/output/stage1.employment.EmploymentByState_b4d9346e.csv`

Am i missing something?

**Comment by XiaosenChen** [comment]
try changing the csv attributes such as quote_char

**Comment by Khorkhe** [comment]
done
