### ISSUE TITLE
Broken documentation links on the GH landing page for Scala + Python docs

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#880]
[Entry README](https://github.com/TresAmigosSD/SMV) contains broken links to the [Python API](http://tresamigossd.github.io/SMV/pythondocs/1.5.2.11/index.html) and the [Scaladocs](http://tresamigossd.github.io/SMV/scaladocs/1.5.2.11/index.html#package)

**Comment by AliTajeldin** [comment]
Fixed.  It was an issue with the automation script.
