### ISSUE TITLE
investigate removing smv.config.keys property

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#881]
`keys` as added as a way to determine which key/values need to be shipped to the executors to allow users to access config values in UDF code.  However, since we are building a merged map of all properties, it might be easier to just broadcast the entire map to all executors.
Need to make sure the above will work before we remove `keys`.

**Comment by laneb** [comment]
The executor no longer requires access to the config. We can remove `smv.config.keys` once `SmvRunConfig` is removed (currently it is deprecated).

**Comment by ninjapapa** [comment]
done.
