### ISSUE TITLE
smvExportCsv unable to acquire memory issue

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#883]
SMV tagged at 1.5.2.9
I have a DF size 38mb (UTF-8 Unicode text, with very long lines)
It has DF.rdd.partitions.length = 64
If I smvExportCsv this DF, I get this error: java.io.IOException: Unable to acquire 16777216 bytes of memory. There is still a csv file and schema file being exported, but of a fraction of the DF records.
If I repartition it to say 16 or 8, the smvExportCsv works fine.
Is this already solved in current master?

**Comment by ninjapapa** [comment]
There are changes made after 1.5.2.9. This issue should at least behave differently on master.

**Comment by AliTajeldin** [comment]
The fact that reducing the partitions made it work is interesting.

**Comment by ninjapapa** [comment]
Somehow the error message reminds me some error I ran into in client server environment.  It was caused by a spark bug in 1.5.x, it was fixed in 1.6 and above.

**Comment by ninjapapa** [comment]
@XiaosenChen Is this issue still exist in master branch?

**Comment by XiaosenChen** [comment]
no
