### ISSUE TITLE
Command line --publish-local behaves differently when the module is persisted

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#884]
--publish-local will "publish" the csv without header when the resolved module already got persisted. However the "published" csv will have a header when the module was not persisted.

**Comment by laneb** [comment]
Reviewing the code for` --publish-local`:

- for a non-ephemeral module that has been persisted, we just do a copy-merge

- for a non-ephemeral module that has not been persisted, persist it and then do a copy-merge, omitting the header

- for ephemeral modules we use `SmvDFHelper.smvExportCsv`, which writes the header 

Is the desired behavior to always write the schema in the header?

**Comment by ninjapapa** [comment]
The `smvExportCsv(module_name, path)` method in shell also has this inconsistency. At least the `smvExprortCsv` function should behave the same as `df.smvExportCsv(file)` method, which is to write **with** header.

If we consider `--publish-local` is the same as `smvExportCsv`, it should also write with header. The only concern there is that `--publish-local` is not `--publish` on local.

**Comment by AliTajeldin** [comment]
yes. `publish-local` should always have the headers.  Not sure what you mean by "The only concern there is that --publish-local is not --publish on local"

**Comment by laneb** [comment]
@ninjapapa mentioned to me that there may be a use case for publishing a headerless csv and schema file locally. It seems that it may be appropriate to distinguish an `export-csv` whose result is a CSV with header, and a `publish-local` whose result is a headerless CSV and schema file.

**Comment by AliTajeldin** [comment]
I think by default, if we are creating a single file, it should have a header.  The only reason we remove the header from the intermediate files is because there is was no way to guarantee that the header line would be the first line when generating a multi-partition file.  It should be possible to guarantee header when creating a single file.
If we need header-less output files, we should add an option in the future.

**Comment by laneb** [comment]
For now, I will change `SmvDataSet.smvExportCsv` to include the header, which will fix both exporting from the shell and `publish-local`. The appropriate name for the option currently called `publish-local` is a separate conversation.

**Comment by laneb** [comment]
@ninjapapa have you tried the using the toLocalIterator [method](https://stackoverflow.com/questions/21698443/spark-best-practice-for-retrieving-big-data-from-rdd-to-local-machine) mentioned in this issue? Description in Spark API doc is 

> Return an iterator that contains all of the elements in this RDD.
> 
> The iterator will consume as much memory as the largest partition in this RDD.

Seems like we could use this to implement `SmvDFHelper.smvExportCsv and skip the copy-merge optimization of `SmvDataSet.smvExportCsv`.

**Comment by ninjapapa** [comment]
No, I haven't. Sounds like it is exactly what we need here.

**Comment by laneb** [comment]
I will go ahead with that approach.

**Comment by laneb** [comment]
Done. Will open an issue for changing the name of `--publish-local`.
