### ISSUE TITLE
Rename smv-pyrun to smv-run

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#888]
As `smv-pyrun` runs all projects, including mixed and pure Scala projects, there is no need to maintain the old `smv-run`, which runs only pure Scala projects.  The current `smv-run` should be replaced with the current `smv-pyrun`, and `smv-pyrun` should print a deprecation warning.

**Comment by AliTajeldin** [comment]
The only tricky part is `smv-pyrun` requires python.  I don't think that is a major hurdle.  We just need to document that as part of the work on this ticket.

**Comment by laneb** [comment]
Installing Python is currently part of the [install guide](https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_install.md). I can update that to emphasize that Python is a requirement. The Python requirement is also enforced in the SMV installer at the moment. Should this be documented anywhere else?

**Comment by AliTajeldin** [comment]
oh yah, since `smv-install` enforces it, I think we should be ok.

**Comment by Khorkhe** [comment]
fixed
