### ISSUE TITLE
Rename --publish-local option

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#893]
Behavior of `--publish-local` is not the local filesystem equivalent of `--publish`. It is more like an export. Should change the name to something like `--export-csv`. @ninjapapa is there also need for actually publishing to the local filesystem?

**Comment by ninjapapa** [comment]
When there is a need to ship published data from one system to another, we need to do `hdfs dfs -get /data/on/hdfs`. If there is an actual `publish local` option, one can save that additional command. No more than that.

**Comment by AliTajeldin** [comment]
It is handy for things like creating local CSV files to load in database for UI.  It also helps to figure out the name of the latest file.  There could be multiple versions of the file on hdfs.  This always gets the latest.  `-export-csv` seems like a good name to distinguish from real publishing.

**Comment by Khorkhe** [comment]
done
