### ISSUE TITLE
Avoid redundant distinct operations on lists of datasets

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#914]
We have a lot of code that looks like 

```
  def allDeps: Seq[SmvDataSet] =
    (resolvedRequiresDS
      .foldLeft(Seq.empty[SmvDataSet]) { (acc, elem) =>
        elem.allDeps ++ (elem +: acc)
      })
      .distinct
```

which results in many redundant `distincts`. The order of these dependencies does not matter, and there would be no need to do any distinct if we were using a `Set` instead. Note that `Set` has a nice map operation: `Set(1, 2, 3) map (_ % 2)` results in `Set(1, 0)`.

**Comment by laneb** [comment]
Actually after writing this out I don't think this is a good solution to the problem. Need to think about this more..

**Comment by AliTajeldin** [comment]
Is this a performance issue or just ugly code? What is the core problem we are trying to solve?

**Comment by laneb** [comment]
Primarily because it's ugly. In fact, we could time this to see if it's making a difference but reading more closely I notice 2 things

- the quoted function is actually dead code
- `SmvDataSet.ancestors` is the only other instance of a recursive distinct

We do a lot of single distincts on lists of datasets but I but it's lot less ugly and there's no real performance concern there. Closing as there isn't really anything to do here.
