### ISSUE TITLE
investigate use of parquet or hive orc files for intermediate results

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#917]
Rather than write csv files (and incur the cost of conversion back and forth), investigate the use of Hive tables backed by either parquet or orc files.  Need to do a speed comparison on a real cluster and standalone machines.

**Comment by laneb** [comment]
See the new timing doc for details, but the either Parquet or ORC would be much superior to CSV. However, Spark is unable to infer the schema of an empty ORC, so if for whatever reason a module's results contain no records then there will be an error reading them back. We would probably have to dig in to the Spark API to find a workaround. Parquet does not have this problem and performs similarly, so Parquet is probably preferrable.

**Comment by laneb** [comment]
Conclusion was to use Parquet.

**Comment by jacobdr** [comment]
One more comment here -- @lane did you check to make sure that the major Hadoop distros support Parquet-backed Hive tables out of the box?

I remember running into an issue with Parquet backed tables in a Hortonworks environment where I guess a Parquet SerDe wasn't provided by default. However, it could have been an old version of Hive or HDP, but nonetheless wanted to let you know.

Jacob

**Comment by AliTajeldin** [comment]
I think the final conclusion was to use pure parquet for intermediate files rather than hive tables backed by parquet.  Spark would create the parquet files directly.

**Comment by jacobdr** [comment]
That's fine -- but reading tables from Hive directly is a requirement at some clients.

The special Spark metadata DDL is, in Spark 1.x and unsure of 2.x, unreadable by Hive and therefore consumption by external tools (and adhoc querying) breaks.

I think the point I am getting at is tangential but related to the purpose of this ticket -- SMV intermediate tables (and the final output) might want to be interrogated outside of Spark.

Jacob

**Comment by laneb** [comment]
One of the assumptions of this ticket was that we aren't supporting the inspection of intermediate (i.e. persisted) results - that is, these results (officially) are for internal purposes only. If users want to create a table that is backed by the results of the module, they should publish or export the module instead.

**Comment by jacobdr** [comment]
Makes sense. Middle stage module that needs to be read from external tools should mark as SmvOutput.

I am thrilled with the decision to move to Parquet -- I just think we need to be careful about its implications (if any) for reading directly from Hive (via CLI for example) when we create the table from the Spark side. Not to mention when creating with partitions...

On Spark 1.x, I don't think you can create an arbitrary DataFrame, call frame.write.format(Parquet).insertInto(dbfqn), and then run the query "select * limit 5 from dbfqn" from HiveCLI and have it just work out of the box. But maybe I'm wrong.

We can take this up offline next week when I'm in SD.

Jacob
