### ISSUE TITLE
does smv support jupyterhub

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#919]
does smv support [jupyterhub](https://github.com/jupyterhub/jupyterhub), or will smv support it in future?

**Comment by AliTajeldin** [comment]
Not directly.  The `smv-jupyter` command only works with basic jupyter notebook (singleton).
However, if you can get jupyter hub to work with spark shell, then it should also work with smv shell (as it is just a wrapper around spark shell).
