### ISSUE TITLE
Enable XML reading

### ISSUE THREAD

**Issue by XiaosenChen** [TresAmigosSD/SMV#936]
Currently, we handle XML at project level with below example code inside a SmvModule:

```
df = smv.SmvApp.getInstance().sqlContext.read.format('com.databricks.spark.xml')
.options(rowTag = ***, etc
.load(path)
```
This is a bit too complex, also user need to make sure the corresponding version of 'com.databricks.spark.xml' can be located. we should consider adding tools at SMV level to handle XML

**Comment by AliTajeldin** [comment]
We should consider creating an `SmvXmlFile` for reading XML files as input.  Or even a more generic `SmvSparkInput` that handles any spark code that generates a dataframe.

**Comment by laneb** [comment]
@AliTajeldin Closing as Bo has recently implemented `SmvXmlFile`
