### ISSUE TITLE
smvStrToTimestamp throws out  java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#944]
I am using smv of this version 
**https://github.com/TresAmigosSD/SMV/releases/tag/v2.1.1.0**

env:
spark-2.1.0-bin-hadoop2.6
scala 2.11.8

class fact_pdl_sample_phonebills_calls_merge_1w_smvStrToTimestamp(SmvModule, SmvOutput):
    def requiresDS(self):
        return [inputset.pdl_sample_phonebills_calls_merge_1w]

    def run(self, i):
        df = i[inputset.pdl_sample_phonebills_calls_merge_1w]
        #2016-02-06 10:51:15.0   ==>  2016-02-06
        return df.select(col("start_time").smvStrToTimestamp("yyyy-MM-dd"))

df('test.facttable.fact_pdl_sample_phonebills_calls_merge_1w_smvStrToTimestamp')

throw out

Traceback (most recent call last):
  File "/home/ml/SMV_2.1.1.0/src/main/python/smv/stacktrace_mixin.py", line 20, in catch_errs
    res = func_needing_stacktrace(*pargs, **kwargs)
  File "/home/ml/SMV_2.1.1.0/src/main/python/smv/smvdataset.py", line 247, in getDataFrame
    df = self.doRun(validator, known)
  File "/home/ml/SMV_2.1.1.0/src/main/python/smv/smvdataset.py", line 587, in doRun
    return self.run(i)
  File "/home/ml/workspaces/PDL/src/main/python/test/facttable.py", line 27, in run
    return df.smvSelectPlus(lit('2014-12-23').smvStrToTimestamp("yyyy-MM-dd"))
  File "/home/ml/SMV_2.1.1.0/src/main/python/smv/helpers.py", line 375, in method
    return getattr(helperCls(self), methodName)(*args, **kwargs)
  File "/home/ml/SMV_2.1.1.0/src/main/python/smv/helpers.py", line 1436, in smvStrToTimestamp
    jc = self._jColumnHelper.smvStrToTimestamp(fmt)
  File "/home/ml/spark-2.1.0-bin-hadoop2.6/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/ml/spark-2.1.0-bin-hadoop2.6/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/home/ml/spark-2.1.0-bin-hadoop2.6/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
    format(target_id, ".", name), value)
Py4JJavaError: An error occurred while calling o87.smvStrToTimestamp.
**: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.ScalaUDF$.apply$default$5()Lscala/Option;**
	at org.tresamigos.smv.ColumnHelper.smvStrToTimestamp(ColumnHelper.scala:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by laneb** [comment]
You are using Spark 2.1.0 with a release intended for Spark 2.1.1. I can replicate the error using Spark 2.1.0 and it is alleviated after switching to Spark 2.1.1.

**Comment by laneb** [comment]
Under [Install SMV using curl](https://github.com/TresAmigosSD/SMV/blob/v2.1.1.0/docs/user/smv_install.md#install-smv-using-curl), the given command downloads https://raw.githubusercontent.com/TresAmigosSD/SMV/master/tools/smv-install. `smv-install` on master is hardcoded to download SMV 1.5.2.12.

**Comment by jimmycheng603** [comment]
I will try  Spark 2.1.1

below maybe a bug
**pom.xml in smv_2.1.1.0.tgz**
<spark.version>2.1.0</spark.version>

`<properties>
    <scala.version>2.11.8</scala.version>
    <scala.binary.version>2.11</scala.binary.version>
    <scala.compat.version>${scala.binary.version}</scala.compat.version>
    <spark.version>2.1.0</spark.version>
    <project.build.sourceEncoding>utf-8</project.build.sourceEncoding>
  </properties>`

**Comment by jimmycheng603** [comment]
I have found out the relevant code in module org.tresamigos.smv.ColumnHelper 

```
 def smvStrToTimestamp(fmt: String) = {
    val name   = s"SmvStrToTimestamp($column,$fmt)"
    val fmtObj = new java.text.SimpleDateFormat(fmt)
    val f = (s: String) =>
      if (s == null) null
      else new Timestamp(fmtObj.parse(s).getTime())
    new Column(Alias(ScalaUDF(f, TimestampType, Seq(expr)), name)())
  }
```

I am not sure if below code will be ok
```
 def smvStrToTimestamp(fmt: String) = {
    val name   = s"SmvStrToTimestamp($column,$fmt)"
    val fmtObj = new java.text.SimpleDateFormat(fmt)
    val f = (s: String) =>
      if (s == null) null
      else fmtObj.parse(s)
    new Column(Alias(ScalaUDF(f, StringType, Seq(expr)), name)())
  }
```

 I will build the scala develop environment for unit test("test smvStrToTimestamp") in ColumnHelperTest

**Comment by ninjapapa** [comment]
@jimmycheng603 are you looking for a method which print a `TimeStamp` type to a `String`?
For your example, if the `start_time` in the original data is a `TimeStamp` type field, you can just use the Spark function to print it,
```
df.withColumn('start_time_firstday', date_format(col('start_time'), "yyyy-MM"))
```

The `smvStrToTimestamp` helper function converts a string to a `TimeStamp`. May not be the function you should use for the use case you shared.

**Comment by jimmycheng603** [comment]
tks for your advice,i will try it
