### ISSUE TITLE
Verify Spark version when starting SMV

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#945]
If the user accidentally use Spark 1.x with SMV 2.x they will get `ImportError: cannot import name SparkSession`. The meaning of this is probably quite clear by now to SMV developer but seems a little opaque for users.

**Comment by AliTajeldin** [comment]
Is there a cheap way (that is not starting a shell) to determine that?

**Comment by laneb** [comment]
We should be able to check in the `_env.sh` script (so we don't have to start a new shell) before we make the `spark-submit`.

**Comment by laneb** [comment]
#944 gives us an example of cryptic errors that can be caused by mismatched teeny versions

**Comment by AliTajeldin** [comment]
How should `_env.sh` check?  Is there a `spark-submit/spark-shell --version` that doesn't start the context or a file with the current spark version?

**Comment by laneb** [comment]
Yes, except I'm not sure it's trivial to parse.
```
$ spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.5.2
      /_/

Type --help for more information.
```

**Comment by AliTajeldin** [comment]
```
$ V=$(spark-submit --version 2>&1 | grep version | head -1 | sed -e 's/.*version //')
$ echo $V
2.1.1
```
