### ISSUE TITLE
SMV 2.1.1.0 installation instructions install SMV 1.5.2.12

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#946]
See instructions [here](https://github.com/TresAmigosSD/SMV/blob/v2.1.1.0/docs/user/smv_install.md).

**Comment by AliTajeldin** [comment]
I don't see any reference to 1.5.2.12 in the above link.

**Comment by laneb** [comment]
Under [Install SMV using curl](https://raw.githubusercontent.com/TresAmigosSD/SMV/master/tools/smv-install), the given command downloads https://raw.githubusercontent.com/TresAmigosSD/SMV/master/tools/smv-install. smv-install on master is hardcoded to download SMV 1.5.2.12.

**Comment by AliTajeldin** [comment]
Got it.

**Comment by laneb** [comment]
This is already fixed on the 2.1 branch. This will be fixed once 2.1.1.1 is released. Closing because there is no action to take.
