### ISSUE TITLE
any plan to support parameter in df function?

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#949]
now def df(name, forceRun = False, version = None):
I think it is better to def df(name, forceRun = False, params={}, version = None) or insert **kwargs

because we should run the module on different time windows, I do not want to hard code in module
is there any plan to support parameter in df function

**Comment by ninjapapa** [comment]
@jimmycheng603 not so sure why you closed this issue. Anyhow, to do multiple runs with different parameters, suggest to use command line to start smv instead of using shell.

**Comment by jimmycheng603** [comment]
I have merged it to the issue 'some advice about smv'
