### ISSUE TITLE
Add .smv_shell_all_args to project templates' gitignore

### ISSUE THREAD

**Issue by jacobdr** [TresAmigosSD/SMV#958]
SMV copies the `smv_pyshell_init.py` into my project directory. Because it does not pass any linting or type-checking, it breaks our current CI tooling. 

While I think the long-term solution is to have our bash scripts and python scripts pass common linting and type-checking tools, this is expensive and we could never anticipate what tooling any given user might have. 

I think the best fix is to make this file a dotfile, and therefore consider it more of a private implementation detail than a publicly exposed file. Most clients won't even be aware that it exists then, and most tooling should ignore it by default. 

If we do plan on making this file more of a first-class citizen in our interpreter environment setup routine, then we might want to consider at least documenting its presence and purpose somewhere, and force the user to check it into source control and handle it in her tooling.

**Comment by laneb** [comment]
The user definitely shouldn't check it into their project - and we should really get rid of it altogether. This file is generated every time `smv-pyshell` is started. It's copied over from `smv_pyshell_init.py.template` and then the SMV args for that invocation of `smv-pyshell` are pasted into the file before starting `pyspark`. I don't remember why this was originally done, but there are other ways to accomplish accessing the SMV args from the shell init script.

**Comment by ninjapapa** [comment]
No more `smv_pyshell_init.py`. However there will be a `.smv_shell_all_args` file generated in project folder. It should be removed after run, but might get left if process is killed. 

So we should add `.smv_shell_all_args` to project templates' `.gitignore`. Then this issue can be closed.
