### ISSUE TITLE
Use proper imports instead of * imports

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#962]
using `from smv import *` is EVIL that is causing quite a bit of confusing errors.  We should use namespaced imports instead (e.g. `import smv as S`).  The same applies for sql functions, these should be imported under `F` namespace.

* make `smv-init` generate a proper project without `import *` for future projects.
* update SMV docs to use proper imports (namespaces under `S` and `F`)
* remove `abc` from `__init__.py` and perhaps other global modules.
* update shell init scripts to not do `import *`

**Comment by laneb** [comment]
When you say 

> remove `abc` from `__init__.py`

do you mean remove it from the `smv` package?

**Comment by AliTajeldin** [comment]
I mean we should add a `del abc` at the end of `__init__.py` so it doesn't get propagated.  Ideally, we should never do an `import *` inside the `__init__.py` but that might be harder to resolve.

**Comment by laneb** [comment]
I see. Is it a problem for modules like `smv.smvdataset` to contain libs like `abc`? Even if not, I think it would be cleaner for the modules to delete their own imports than for the `smv` package to anticipate them.

**Comment by AliTajeldin** [comment]
That would also work.

**Comment by laneb** [comment]
I take that back, that won't work because because if we delete, e.g., `smv.smvdataset's` reference to `inspect` this will break methods that use `inspect`. Instead, we will use the [`__ALL__`]( (https://stackoverflow.com/questions/44834/can-someone-explain-all-in-python) property of Python modules to manage what gets imported into `__init__.py` and what doesn't.

**Comment by laneb** [comment]
The shell init script only does a wildcard import from `smv.smvpyshell`, so we should be okay there.
