### ISSUE TITLE
what's wrong with smv-shell on AirlineApp

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#963]
I am running the sample of AirlineApp_smv_example

when I enter smv-shell and type ls, there are no modules to be print out
```scala> ls

airlineapp.etl:

airlineapp.datamodel:

airlineapp.feature:
```

but when I enter smv-pyshell and type ls(),all modules are print out
```
>>> ls()

airlineapp.etl:
  (O) etl.dimtable.DimCustomer
  (O) etl.dimtable.DimFlightLeg
  (O) etl.dimtable.DimGeo
  (O) etl.dimtable.DimMember
  (O) etl.facttable.FactBooking
  (O) etl.facttable.FactCheckIn
  (O) etl.facttable.FactTicket
```

**why does not the command of ls in smv-shell print the modules?**

**Comment by AliTajeldin** [comment]
I believe `smv-shell` only knows about scala modules while `smv-pyshell` knows about scala and python modules.  AirlineApp you have most likely only has python modules (depending on which version of airline app you have).

**Comment by jimmycheng603** [comment]
My AirlineApp vesion has both python and scala codes. I find shell_init.scala in conf directory,when I run smv_shell, it throws out 
```
Loading conf/shell_init.scala...
<console>:40: error: object mycompany is not a member of package com
       import com.mycompany.airlineapp._
```
is it the reason why the command of ls in smv_shell can not print modules under stage?
but I find the hierarchy of scala packages is ok,how can I fix it?
```
[ml@model42 AirlineApp_smv_example]$ ls -R src/main/scala/
src/main/scala/:
com

src/main/scala/com:
mycompany

src/main/scala/com/mycompany:
airlineapp

src/main/scala/com/mycompany/airlineapp:
app  core  datamodel  etl  feature

src/main/scala/com/mycompany/airlineapp/app:
CustomerCluster.scala  input

src/main/scala/com/mycompany/airlineapp/app/input:
InputSetApp.scala
```

**Comment by jimmycheng603** [comment]
I started smv-shell with the command "smv-shell -- --driver-class-path ./src/main/scala/"
the error  "object mycompany is not a member of package com" disapperared,but
command of ls in smv-shell did not print modules yet,

**how to print modules with the command of ls**

```
scala> ls

com.mycompany.airlineapp.etl:

com.mycompany.airlineapp.datamodel:

com.mycompany.xiangdan.features:

com.mycompany.xiangdan.etl:
```

**Comment by AliTajeldin** [comment]
For mixed projects (scala + python), we recommend the use of `smv-pyshell`.

**Comment by jimmycheng603** [comment]
I have tried smv_pyshell, but it did not print modules yet. I think it must Specify some parameters about the location of scala code, if not, how can smv distinguish scala and python if both scala and python codes exist in smv project?

**Comment by AliTajeldin** [comment]
For mixed projects, SMV should distinguish Scala and Python modules.  You can look at the Scala/Python repo implementations for all the gory details.   If `smv-pyshell` is not seeing the scala modules, then there is a bug in SMV.  Just make sure your scala module code is under `src/main/scala` and you have defined your stages correctly.  Is your airline app a public repo?  Can we take a look to see what is going on?

**Comment by jimmycheng603** [comment]
I have uploaded the sample on my github repo [git@github.com:jimmycheng603/airlineapp_smv_example.git](url)

My environment:
SMV_2.1.1.1
spark-2.1.1-bin-hadoop2.6
scala-2.11.8


```
[ml@model42 AirlineApp_smv_example]$ smv-pyshell
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/

Using Python version 2.7.13 (default, Dec 20 2016 23:09:15)
SparkSession available as 'spark'.
Starting Py4j callback server on port 62516

>>> lsStage()
com.mycompany.airlineapp.etl
com.mycompany.airlineapp.datamodel
com.mycompany.xiangdan.features
com.mycompany.xiangdan.etl

>>> ls()

com.mycompany.airlineapp.etl:

com.mycompany.airlineapp.datamodel:

com.mycompany.xiangdan.features:

com.mycompany.xiangdan.etl:
>>> 
```

**Comment by laneb** [comment]
@jimmycheng603 Did you compile the project with `sbt` before running `smv-pyshell`?

**Comment by laneb** [comment]
Scala code discovery is accomplished by reflect inside of the packages that have been indicated as stages. Python code discovery is similar. No configuration is needed to specify that Python or Scala code exists.

**Comment by jimmycheng603** [comment]
I have modified the sample airlineapp_smv_example [git@github.com:jimmycheng603/airlineapp_smv_example.git](url),
but the result is the same

1)sbt compile
```
jimmy@ubuntu:~/workspace/AirlineApp_smv_example$ sbt compile
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/jimmy/workspace/AirlineApp_smv_example/project
[info] Set current project to airlineapp (in build file:/home/jimmy/workspace/AirlineApp_smv_example/)
[success] Total time: 2 s, completed Aug 30, 2017 2:29:57 AM
```

2)smv-pyshell
```
jimmy@ubuntu:~/workspace/AirlineApp_smv_example$ smv-pyshell
Using Spark at /home/jimmy/softwares/spark-2.1.1-bin-hadoop2.6
APP_JAR = /home/jimmy/workspace/SMV/tools/../target/scala-2.11/smv-2.1-SNAPSHOT-jar-with-dependencies.jar
Spark Command: python
========================================
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
Spark Command: /home/jimmy/softwares/jdk8/bin/java -cp /home/jimmy/workspace/SMV/tools/../target/scala-2.11/smv-2.1-SNAPSHOT-jar-with-dependencies.jar:/home/jimmy/softwares/spark-2.1.1-bin-hadoop2.6/conf/:/home/jimmy/softwares/spark-2.1.1-bin-hadoop2.6/jars/*:/home/jimmy/softwares/hadoop-2.6.0/etc/hadoop/ -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.extraClassPath=/home/jimmy/workspace/SMV/tools/../target/scala-2.11/smv-2.1-SNAPSHOT-jar-with-dependencies.jar --name PySparkShell --jars /home/jimmy/workspace/SMV/tools/../target/scala-2.11/smv-2.1-SNAPSHOT-jar-with-dependencies.jar, pyspark-shell
========================================
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
17/08/30 02:31:25 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/30 02:31:45 WARN metastore.ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/

Using Python version 2.7.13 (default, Dec 20 2016 23:09:15)
SparkSession available as 'spark'.
Starting Py4j callback server on port 23629
>>> ls()

com.mycompany.airlineapp.etl:

com.mycompany.airlineapp.datamodel:

com.mycompany.airlineapp.features:

com.mycompany.airlineapp.app:
```

**Comment by laneb** [comment]
I should have been more precise: you need to assemble the project with `sbt assembly`, which fails for me in your project. I am able to compile the scala files in the project with `sbt compile`, but these will be ignored when running SMV if you don't have an assembled jar in the project.

**Comment by laneb** [comment]
A bit of background: when we started supporting Python applications, all SMV applications had to be assembled (assembly creates a fat jar which includes SMV itself). This jar would get distributed by Spark at runtime. However, since pure Python projects do not have any code to compile, all they need is a fat jar of SMV. To make things easier on Python devs, we now distribute a prebuilt SMV fat jar with releases. If SMV does not find a project fat jar in the expected place, it assumes you have no Scala code and want to use the release fat jar, which does not include your Scala code.

**Comment by jimmycheng603** [comment]
thanks very much for your answer which helps me a lot(scala sample should be to be assembled to smv fat jar before smv-shell). I have also found the scala sample in run-integration-test.sh(IntegrationApp), Now everything is ok. thank you again!
