### ISSUE TITLE
line42(print ***) in  run-integration-test.sh is incompatible with python3

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#968]
My environment:
Spark 2.1.1
Python:3.5.2(Anaconda 4.2.0 (64-bit))
SMV:2.1.1.1
Scala:2.11.8

when I run unit tests in run-integration-test.sh, it throws out an error from smv_pyshell_init.py.template
line 42 print "Unable to read history, deleting history file." is incompatible with python3, maybe it is a bug.

**Comment by AliTajeldin** [comment]
Yes. That is a bug.  `print` is now a function in python 3.x.

**Comment by AliTajeldin** [comment]
Merged into master.  Will wait until master is merged into 2.1 to close.

**Comment by laneb** [comment]
Master has since been merged into 2.1.
