### ISSUE TITLE
can smv realize the methods about woe and iv in the stage of model?

### ISSUE THREAD

**Issue by jimmycheng603** [TresAmigosSD/SMV#969]
can smv realize the methods about woe and iv in the stage of model? Sometimes it it a part of logistic regression

**Comment by AliTajeldin** [comment]
@jimmycheng603 Can you elaborate further.  I'm not sure I understand your question.  Can you provide a context. Are you using `SmvModel`/`SmvModelExec`?

**Comment by ninjapapa** [comment]
@jimmycheng603 I think I understand the term WoE, what `iv` stand for?

For `WoE`, the `SmvModel` and `SmvModelExec` should be able to support. Implementation of `WoE` calculation, both create the WoE table and apply the WoE table should be provided from user defined library. A `SmvModel` could be created to call the `create_woe` function from that library, and a `SmvModelExec` can be created to call the `map_woe` function.

**Comment by jimmycheng603** [comment]
I have no idea about SmvModel and SmvModelExec. I will try them for woe. do you have any samples or code snippet about smvmodel? 
IV means Information Value,I do not find it in wiki but  an article in google [http://ucanalytics.com/blogs/information-value-and-weight-of-evidencebanking-case/](http://ucanalytics.com/blogs/information-value-and-weight-of-evidencebanking-case/), we always determine whether fields from 3rd party data provider are useful by calculating IV of them.

**Comment by ninjapapa** [comment]
Here is the document:
https://github.com/TresAmigosSD/SMV/blob/master/docs/user/smv_model.md

Need to enhance it by adding some real examples.

**Comment by jimmycheng603** [comment]
I will try it, thanks for your help
