### ISSUE TITLE
SmvGroupedData should be a user accessible class

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#970]
Current `SmvGroupedData` is defined in `smv.helpers`. User can import it with 
```
from smv.helpers import SmvGroupedData
```

Since the `helpers` module behaves more like a private module, we should actually import `SmvGroupedData` in the `__init__.py` of `smv`, so that user code can be 
```
from smv import SmvGroupedData
```

A use case of user code to import SmvGroupedData is that some library functions may want to 
handle parameters which can be either DF or SmvGroupedData. A `isinstance` call on `SmvGroupedData` might be needed.

**Comment by laneb** [comment]
The helpers module isn't really any more private than any other module, but I will make it importable from `smv` for simplicity`.
