### ISSUE TITLE
Access the current hash of an SmvModule

### ISSUE THREAD

**Issue by daStrauss** [TresAmigosSD/SMV#971]
If in addition to `runModuleByName` we had `getModuleHash`, it would be useful. The main utility is to be able to connect the final module hash with a downstream pipeline that is not based in Spark. Examples include saving as a pandas data frame and using it for training an ML model.

**Comment by laneb** [comment]
You just want a `getModuleHash` function that's attached to `SmvApp`, like `runModuleByName`? Or does it need to be available e.g. in the shell?

**Comment by AliTajeldin** [comment]
I think the use case @daStrauss described would only need a method on `smvApp`.  But for completeness sake, let's add it to shell as well.

**Comment by laneb** [comment]
Done.
