### ISSUE TITLE
OOM error if forceParserCheck and failAtParsingError are true for CSV files.

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#972]
Given a relatively small CSV file (~2GB), if `forceParserCheck` and `failAtParsingError` are true (their default value), then we get an out of memory error even when executors are given as much as 10GB memory.  The short term workaround is to define these two values to return false until this issue is resolved.  For example:
```python
class SomeFile(smv.SmvCsvFile):
    def path(self):
        return "foo.csv"

    def forceParserCheck(self):
        return False

    def failAtParsingError(self):
        return False
```

Note: the error even occurs if we set `failAtParsingError` to false and `forceParserCheck` to true (which should have created an "empty" DQM rule).

**Comment by laneb** [comment]
I am unable to replicate this issue as described, even with a ~4gb file limiting executor memory to 4g. Can you verify that this error occurs for the standard Spark 1.5.2 release?

**Comment by laneb** [comment]
I have tried with:

- Spark releases 1.5.2 and 1.5.0
- SMV releases 1.5.2.9 and 1.5.2.7
- Data including a Timestamp
- Executor memory limited to 2g
- A 3.7gb csv file
- JVM memory limited to 1g (Spark sets this for the driver by default)

I have not been able to replicate this issue and did not observe any significant memory anomalies when monitoring with `jstat`.

**Comment by laneb** [comment]
After further investigation with @AliTajeldin, we discovered the cause of the issue: the offending CSV file had millions of null characters causing parser errors. Each error was logged to file with its record contents, which were being escaped on the driver when generating the parser log for logging in JSON. Escaping the null characters from 1 byte to 7 bytes each. There were 2 logs containing these characters. The resulting magnification of the data consumed all the memory on the driver. 2 solutions:

- The CSV file needs to be fixed
- SMV should limit the record length when generating the json string

**Comment by AliTajeldin** [comment]
We should limit the record length in the log to max 10k characters or so.

**Comment by AliTajeldin** [comment]
Will keep this open until we make an official release to client.
