### ISSUE TITLE
Create SmvSqlCsvFile which supports SQL commands

### ISSUE THREAD

**Issue by cloudysail** [TresAmigosSD/SMV#979]
Like `SmvSqlModule`, we want to support sql for the input `SmvCsvFiles`.

The user code looks like this:
```
class MyInput(SmvSqlCsvFile):
    def path(self):
        return "checkin.csv"
    def tableName(self):
        return "t1"
    def tableQuery(self):
        return "select a, b from t1"
```

**Comment by laneb** [comment]
I edited your comment to remove reference to an issue in a private repo.

**Comment by AliTajeldin** [comment]
@cloudysail Let's hardcode the tablename as there is only one table for the input.
