### ISSUE TITLE
Verify that argument to Python RunParams is an SmvDataSet

### ISSUE THREAD

**Issue by laneb** [TresAmigosSD/SMV#983]
Occasionally users supply a `DataFrame` as an argument instead, causing a somewhat opaque error.

**Comment by laneb** [comment]
Is this ready for a PR?

**Comment by kmannislands** [comment]
Yes. Apologies for sloppy committing. Assuming I shouldn't squash these commits first, I think it's good to PR. Tests are passing.

**Comment by AliTajeldin** [comment]
@kmannislands go ahead and submit a PR.

**Comment by kmannislands** [comment]
Talked with Lane and had to change approaches as SmvModuleLink is outside of the class hierarchy in question. Error has been left as the same TypeError, but now we simply check for the presence of a urn attribute.

**Comment by AliTajeldin** [comment]
That should do
