### ISSUE TITLE
Improvement on smvHist function

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#988]
When input column is a numerical type, smvHist prints histogram with defaulted bin size 100.

`train_new.smvHist("binary_target")`

> Histogram of binary_target: with BIN size 100.0
> key                      count      Pct    cumCount   cumPct
> 0.0                      32561  100.00%       32561  100.00%

This behavior is not quite user friendly. If users want to do a distribution check on a column with limited numbers, they have to pick up an appropriate bin size and use smvBinHist like below, which is a little complex.

`train_new.smvBinHist(("binary_target",1))`

> Histogram of binary_target: with BIN size 1.0
> key                      count      Pct    cumCount   cumPct
> 0.0                      24720   75.92%       24720   75.92%
> 1.0                       7841   24.08%       32561  100.00%

Could we just improve the function and print all values in this column? I understand # of vales will be pretty large in some cases but users can always choose smvBinHist to limit the output.

**Comment by ninjapapa** [comment]
Need a little design here.

We can not make the histogram on a numerical field without binning too easy to trigger, especially when user does not even know what the distribution may look like. It will easily hang the system and run out of memory. 

However we could introduce a method which named clearly so that no one will use it unintentionally. `smvNumValueHist` sounds too long and still unclear. @yw-yang any suggestions?

**Comment by yw-yang** [comment]
My opinion:
1. The defaulted behavior for numerical column in `smvHist` function is confusing. User may ignore the bin size 100 unintentionally and take the wrong result. I suggest to change the behavior.
2. Introduce another method `smvNumValueHist` seems a little duplicated with `smvHist` and also a burden for user to remember another hist function.
3. The concern that too many values may hang the system will also appear in string field(e.g. do histogram on PNR or name). So is it possible we set a threshold internally, e.g. if # values is greater than 1000, method stops calculating and shows a warning instead.

**Comment by ninjapapa** [comment]
Good idea. Let's take approach 3 as a brief design and refine smvHist.

**Comment by yw-yang** [comment]
This ticket is also related to the visualization improvement in dsalib. Please refer to design below:

**Design:**
1. Add another two EDD task types: `NumericByKeyHistogram` and `NumericByFreqHistogram`
2. Change class `Hist` default bin size from 100 to 0
3. Change Edd logic for numeric types as below
```
      case _: NumericType => 
        if (histCol.binSize > 0.0) edd.BinNumericHistogram(s, histCol.binSize)
        else if (histCol.sortByFreq) edd.NumericByFreqHistogram(s)
        else edd.NumericByKeyHistogram(s)
```
4. Set an internal threshold 1000 in `Histogram` `merge` function, if buffer size is greater than 1000, throw a runtime error
