### ISSUE TITLE
Use log4j instead of console log messages in SMV.

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#989]
When running smv jobs through terminal, lots of information will be printed on console but won't be stored on server. In most cases, an external log file is pretty useful for the ease of debugging and future reference.

Could SMV store console log to one external file like smv.log automatically?

**Comment by ninjapapa** [comment]
Using UNIX tee command and pipe should be able to cover this use case:
```shell
smv-pyrun ..... 2>&1 |tee smv.log
```

As an action item, add this to the user doc.

**Comment by yw-yang** [comment]
@ninjapapa Yes, users can use "tee" command to cover this issue but making it as an automatic behavior still has additional benefits:
1. User always prefers shorter command
2. Log management should be clear with the growth of project

Shall we add "smv.logDir" as a config parameter and by default, it points to current path?

**Comment by AliTajeldin** [comment]
We should utilize log4j for output logging from within SMV.  The user can then decide how to redirect that output (console, file, logstash, etc).  Applications depending on SMV can then configure the log4j properties of SMV explicitly.

Changing title of ticket to reflect need for log4j logging.

**Comment by ninjapapa** [comment]
@AliTajeldin will that solve the problem of python side logging messages?

**Comment by AliTajeldin** [comment]
yes.  Logging should be in the SMV core with python methods exposed for python SMV code to utilize.  This way, both Scala and python code would log to the same place and with a single logger configuration.  And since we are using log4j, the same logger config can be used for both spark and SMV.

**Comment by laneb** [comment]
It would also be valuable to have debug logs available in the logs. E.g., 

* What objects are inspected when searching for SmvModules
* What module is being run and when a 'subtask' of running a module starts (dqm, metadata, persisting, etc.) 
* What metadata is generated for a module

**Comment by jacobdr** [comment]
+1

Need to ale sure we are explicit to users about how they can change the levels, and add logging to their own applications.

The Java -D options might look funny to some of them, so I feel documentation will be especially important here.

**Comment by laneb** [comment]
Also: 
* **Warn** when fail to import a stage
* **Warn** about errors suppressed by walk_packages
* **Debug** listing the `sys.path` after a `DataSetRep` is constructed

**Comment by laneb** [comment]
I've added the logs, but I'm having trouble getting the logs to be printed to the console. 
* log4j only looks for configuration in Spark's conf dir
* the rootLogger configuration doesn't get inherited by SMV's logger

These may make logging configuration difficult for users. Need to find a better way than explicitly setting SMV's logging level via the Spark log4j config.

**Comment by jacobdr** [comment]
There is a section on this in the docs
https://spark.apache.org/docs/latest/running-on-yarn.html
