### ISSUE TITLE
Error: run module with option --force-run-all

### ISSUE THREAD

**Issue by yw-yang** [TresAmigosSD/SMV#990]
I used below command to run a module in airline demo app:
`smv-pyrun -m datamodel.segmentmaster.SegmentMaster --force-run-all`

Error shows:
> Traceback (most recent call last):
>   File "/Users/yuweiyang/Desktop/SMV/SMV_2.1.1.3/tools/../src/main/python/scripts/runapp.py", line 19, in <module>
>     app.run()
>   File "/Users/yuweiyang/Desktop/SMV/SMV_2.1.1.3/src/main/python/smv/smvapp.py", line 218, in run
>     self.j_smvApp.run()
>   File "/Users/yuweiyang/Desktop/SMV/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
>   File "/Users/yuweiyang/Desktop/SMV/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
>   File "/Users/yuweiyang/Desktop/SMV/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
> py4j.protocol.Py4JJavaError: An error occurred while calling o31.run.
> : org.tresamigos.smv.SmvRuntimeException: SmvModuleLink's moduleCsvPath should never be called
> 	at org.tresamigos.smv.SmvModuleLink.moduleCsvPath(SmvDataSet.scala:842)
> 

Seems "--force-run-all" can't be used when module input is SmvModuleLink. Is it a bug that we should fix?

SMV version: 2.1.1.3

**Comment by ninjapapa** [comment]
No more an issue since SmvModuleLink is just a pass through now.
